### ISSUE TITLE
Consistent Kernel examples

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#101]
dynamo/eg4 and dynamo/eg8 currently each contain a copy of the same kernel file. It also turns out that these files are slightly different. The question is what to do about this. Suggestions so far are:

1) symlink shared kernel files
2) maintain separate kernel files for examples
3) place all example kernel files in a shared kernel directory
4) place shared kernel files in a shared directory and private kernel files locally - this would require a change in PSyclone to support multiple search directories for kernel files.

My opinion is that we might actually end up with inconsistent kernels in our examples (e.g. due to changes in science to a kernel over time) so the most general solution (4) is best. However, no one has asked for this feature so far.

Failing (4) I would personally go for (2) as it gives flexibility in names at the expense of potential redundancy in code, but I could be convinced to go for (3). I think (1) is not a good solution.

**Comment by arporter** [comment]
I agree, especially since (2) requires no work on our part. I think (4) is a nice-to-have but is low priority until we have an external use case.

**Comment by rupertford** [comment]
OK, let's go for that. Closing issue.
