### ISSUE TITLE
Add FortCL initialization options as options in the OCLTrans transformation

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1019]
Recently we added a few parameters in FortCL for initializing the OpenCL device. It will be good to expose these as transformation options in PSyclone (the infrastructure already exists for the 'end_barrier' option). 

```
cltrans.apply(schedule, options={"end_barrier": True,
                                 "enable_profiling": False,
                                 "out_of_order": False,
                                 "devices_per_node": 1})
```

**Comment by sergisiso** [comment]
Should "device_per_node" be a configuration option instead?

**Comment by sergisiso** [comment]
I made a first implementation with `OCL_DEVICES_PER_NODE` being a general configuration parameter (it doesn't seem API specific although only Gocean generates OpenCL and is the only one reading it for now). However, I am not convinced with this solution (or the OCLTrans option) because they are still dependent on executing the MPI with the exact same value of ranks per node: 

```
configuration> OCL_DEVICES_PER_NODE=X
mpirun -n N -ppn X ./application
```

this can be documented but still seems a very obvious failure point.

Another option is to get infrastructure support for a function that returns the runtime X (or even better the `get_rank_in_node()` -> mod(rank, X) ). It requires MPI-3 but it would get away without any configuration value. I can implement it for `dl_esm_inf` but it would be a infrastructure requirement if OpenCL has to be ported to other APIs. @rupertford @arporter what do you think is the best option?

**Comment by rupertford** [comment]
Presumably OCL_DEVICES_PER_NODE is actually how many devices there are per node? I know that sounds like a silly question but, assuming I am right, it seems to me that allowing a user to write -ppn X without potentially realising X should equal the number of devices per node is actually more dangerous than potentially having a mismatch. So I would say having a configuration option makes sense. Whether that is loaded by MPI3 or whether the user has to match values I'm not so sure. I guess it depends on how ubiquitous MPI3 and this functionality is. My gut feeling would be to stick with the first option and document it. One potential way to help could be to get PSyclone to output a script which had configurable parameters and the mpirun command in it, or to get PSyclone to write suggestions to stdout from the command line.

**Comment by sergisiso** [comment]
Just to be clear, the '-ppn X' is going to be used in all cases (we need to assign this much MPI processes per node), the question is if the OpenCL device id that each MPI rank has associated with it is given by `mod(get_rank(), OCL_ENV_DEVICES_PER_NODE)` or `mod(get_rank, get_runtime_process_per_node())` (with the second needing special infrastructure support).

In both cases if the ppn is higher than the actual number of devices it will fail (the OpenCL error is readable in this case).

Additionally with the first option, if the configuration and the -ppn do not match the device ids can be shifted in a weird way.

**Comment by arporter** [comment]
That sounds good. As long as we're not missing out on optimisation opportunities by not having the information when we run PSyclone?
