### ISSUE TITLE
Make Makefiles consistent

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1022]
We seem to have different make targets. ``clean`` and ``allclean`` are mostly consistent. But ``examples`` uses "transform compile notebook"; ``lib`` uses 'process'; ``tutorial/practicals/{​​​​​​​​LFRic,nemo}​​​​​​​​`` uses 'test';  and ``tutorial/LFRic/building_code`` supports ``test`` and ``compile``. My suggestion and additional question:
clean: remove all local files created during test
allclean: clean + allclean for all libraries used
test:  everything that can be tested without compilation
compile: test + compilation, requires netcdf dev package available
run: compile + execute binary (ideally should also do some test for expected outcome??)

Tasks:
- [x] Document this in dev guide
- [x] Update examples
- [x] Update lib
- [x] Update tutorials

**Comment by hiker** [comment]
I noticed that a few(?) examples don't do anything when you do a ``make compile`` (only print a message that nothing can be compiled for this example). To make it clear, I intend to change all these examples so that ``compile`` will also do ``make test``, and only then print a message that nothing can be compiled (but it wouldn't fail because of this).

**Comment by hiker** [comment]
I need some feedback - @rupertford, @arporter , @sergisiso, @TeranIvy, @andrewcoughtrie, @christophermaynard  - some of the makefiles (am currently looking at the ones in ``examples``) have a ``make all`` target. Now this appears to be the same as ``make run`` as suggested above. So I am not sure what to do. Options:
1. We leave ``make all`` in, a duplicate (but maybe better name) than ``make run`` ?
2. Instead of ``make run``, we use ``make all`` - i.e. remove the ``run`` target.
3. We remove ``make all`` and use ``make run``.
4. We modify the makefiles so that ``make all`` does the 'highest supported' target: i.e. it would do ``make test`` if we only support the transformation, ``make compile`` if we can compile, but not execute, and ``make run`` if we can execute a program.

I have to admit I can't make up my mind - I have a slight preference for 4. But then again, would we call this ``all``? Maybe ... can't decide ... decisions ...  suggestions welcome :grin:

**Comment by rupertford** [comment]
I don't know the subtleties I'm afraid but it might be worth thinking about what we are using the Makefile's for. I think we have two main cases 1) we want to check everything is working OK, either automatically or manually. 2) a user is meant to use the Makefile as part of the example/tutorial etc. For case 1) I would expect to do "make test", would expect to see that in the CI scripts and would expect that to recurse down from whatever directory it is run from. I may be wrong but I don't think `make test` necessarily implies no compilation or running so am not convinced that should be the same as "just perform the transformation". I'm guessing there could be at least a 1a) as well (i.e. more in-depth tests) that might not be done in CI as it requires infrastructure to be built? If so, that should have its own name(s). Then we have the structure of each leaf Makefile. I'm happy with separate targets for the different phases and would probably your option 4) (with the proviso about make test).

**Comment by hiker** [comment]
> I don't know the subtleties I'm afraid but it might be worth thinking about what we are using the Makefile's for. I think we have two main cases 1) we want to check everything is working OK, either automatically or manually. 2) a user is meant to use the Makefile as part of the example/tutorial etc. 

There might be a third case: use makefiles to compile PSyData wrapper.

> For case 1) I would expect to do "make test", would expect to see that in the CI scripts and would expect that to recurse down from whatever directory it is run from. 

Agreed, anything should recurse down. Same for ``make allclean`` in an example: if you use this for a PSyData example, this will then ``allclean`` the psydata-wrapper, which in turn will ``allclean`` the infrastructure library (that might result in sometimes the infrastructure library cleaned more than once, since the example likely will call ``allclean`` for the infrastructure library as well).

> I may be wrong but I don't think `make test` necessarily implies no compilation or running so am not convinced that should be the same as "just perform the transformation".

Might be easier to discuss this in the telco. I would expect that compilation (and of course running) is typically ''too expensive'', so maybe we would only trigger this before a merging or so? Maybe on one of our machines with a compile environment.

> I'm guessing there could be at least a 1a) as well (i.e. more in-depth tests) that might not be done in CI as it requires infrastructure to be built? 

Infrastructure is likely required for most (all??) compiles. Maybe except for NEMO, since this is standard Fortran. LFRic and gocean more or less always require a field object, which comes from the infrastructure library.


> If so, that should have its own name(s).

Hence my suggestion to call this ``make compile`` :grin:

> Then we have the structure of each leaf Makefile. I'm happy with separate targets for the different phases and would probably your option 4) (with the proviso about make test).

Thanks!

**Comment by hiker** [comment]
@arporter example/nemo/eg3 contains link to the aped_dl_timer library:
```
PROGRAM tra_adv
  USE dl_timer, ONLY: timer_init, timer_register, timer_start, timer_stop, timer_report
  USE iso_c_binding, ONLY: C_INT64_T
  ...
  CALL timer_init
  CALL timer_register(init_timer, label = 'Initialisation')
  CALL timer_register(step_timer, label = 'Time-stepping', num_repeats = it)
  CALL timer_start(init_timer)
```
This means that this example needs an external library in order to compile, which afaik we would want to avoid in order to allow compilation testing. I see four solutions:
1) We just remove the timer. Afaik they are not essential for this example.
2) We explicitly add the calls to the simple timing library (i.e. we hand-code the PSyData API code).
3) We use a psydata-transformation to insert our simple timing library - though not ideal since we likely do not want to make this example more complicated.
4) We replace this with some hand-coded Fortran standard calls.

My preference would of course be 1) ... KISS ... but let me know if you prefer any of the other solutions (or a 5th or 6th one :) ) I am aware that this is actually an openacc example, so compilation would not actually test the newly introduced openacc code ... but even if we have openacc, the argument about the external library stands :)

**Comment by arporter** [comment]
Yes, I vote for 1) too.

**Comment by hiker** [comment]
I checked the documentation, the DevGuide points to the wiki, and the wiki already mentions that we need to run ``make compile``. If we want to have this explicitly in the DevGuide, I'd suggest to open a new ticket for that.
