### ISSUE TITLE
[LFRic] adjacent_face array is not aware of colouring with OpenMP

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1033]
This bug was noticed in the [LFRic ticket 2415](https://code.metoffice.gov.uk/trac/lfric/ticket/2415) when running with LFRic with OpenMO and more than one thread.

Currently PSyclone generates
```
      DO colour=1,ncolour
        !$omp parallel default(shared), private(cell)
        !$omp do schedule(static)
        DO cell=1,mesh%get_last_halo_cell_per_colour(colour,1)
          call subroutine(…, adjacent_face(:,cell), …)
          …
```
whereas the correct code should be

```
      DO colour=1,ncolour
        !$omp parallel default(shared), private(cell)
        !$omp do schedule(static)
        DO cell=1,mesh%get_last_halo_cell_per_colour(colour,1)
          call subroutine(…, adjacent_face(:,cmap(colour,cell)), …)
          …
```
For now it is agreed that a small number of LFRic kernels that are implementing this feature will need to be called through PSyKAl-lite until the fix is available through a new PSyclone release.

This also raises the need for more thorough testing on LFRic side (particularly having more multi-threaded jobs in the test suite).

**Comment by rupertford** [comment]
Created branch [1033_colour_adjacent_face](https://github.com/stfc/PSyclone/tree/1033_colour_adjacent_face)
