### ISSUE TITLE
SymbolTable methods should permit specialized symbol creation

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1039]
An issue with the Symbol Table is that `name_from_tag()`, when the tag does not exist it just creates generic 'Symbol' objects. It would be more convenient to choose which kind of symbol and properties do we want.

The main problem is that each Symbol kind may be initialized with different arguments. This was also an issue in creating new symbols for a new name, in that case we split the process in 3 steps:

1) find an available name: `name = SYMBOL_TABLE.new_symbol_name(root_name="a")`
2) create the symbol: `symbol = KindSymbol(name, other_kind_specific_parameters)`
3) add into the symbol table: `SYMBOL_TABLE.add(symbol)`

I don't like this solution because:
- Its verbose.
- Same 3 steps ends up repeated in many places
- It's fragile: a statement with a symboltable side effect bewteen this statement 3 can make it fail.
- It's fragile: The user must know not to modify the name or it will break.

I propose replacing the "new_symbol_name" with a method that does the 3 steps atomically (with Python *args and **kargs expansion):

`SymbolTable.create_symbol("name", DataSymbol, INTEGER_TYPE, Symbol.DEFAULT_VISIBILITY, constant_value=3)`

(Note: this doesn´t replace the add method, users can still create and `add()` their new symbols for more complex/uncommon cases. )

Also one function returns a name while the other returns a symbol. I propose both return a symbol (we can always do .name easily when the string name is needed)

`name_from_tag(...)` -> `symbol_from_tag(...).name`

**Comment by arporter** [comment]
That sounds good to me Sergi.

**Comment by sergisiso** [comment]
Issue #720 is similar (but focuses only on the name_from_tag method).
