### ISSUE TITLE
Support coloured loops with redundant computation

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#105]
The LFRic infrastructure now supports colouring within a fields halo. This means that we can now allow the redundant computation transformation to be applied to coloured loops, as long as we obey the appropriate API.

Examples of how this API works have been developed by the LFRic team and implemented in the so-called PSyKAl-lite layer (i.e. hand written, rather than PSyclone generated, PSy-layer code). The associated Met Office SRS ticket for this is 1155 and can be viewed here https://code.metoffice.gov.uk/trac/lfric/ticket/1155

**Comment by rupertford** [comment]
For reference, the API itself was implemented in the LFRic infrastructure in the Met Office LFRic SRS ticket 458 which can be viewed here https://code.metoffice.gov.uk/trac/lfric/ticket/458

**Comment by rupertford** [comment]
Created branch redundant_colouring https://github.com/stfc/PSyclone/tree/redundant_colouring for this work

**Comment by arporter** [comment]
PR #115 has been merged to master. Closing issue.
