### ISSUE TITLE
test_loop_swap_correct taking a *long* time to run

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1069]
If I do the following on master:

    pytest --durations=5 -k test_loop_swap_correct domain/gocean/transformations/gocean1p0_transformations_test.py 
    ============================= test session starts ==============================
    platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
    rootdir: /home/Projects/PSyclone, inifile: setup.cfg
    plugins: forked-1.2.0, xdist-1.33.0, cov-2.10.0
    collected 67 items / 66 deselected / 1 selected                                

    domain/gocean/transformations/gocean1p0_transformations_test.py .        [100%]

    =========================== slowest 5 test durations ===========================
    43.47s call     src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py::test_loop_swap_correct
    0.01s setup    src/psyclone/tests/domain/gocean/transformations/gocean1p0_transformations_test.py::test_loop_swap_correct

Sergi is able to reproduce (albeit it 'only' took 17s on his machine).

**Comment by arporter** [comment]
@hiker, would you mind taking a look at this as I think you wrote the test originally? I had a quick look and see that it uses a lot of regex - perhaps that's the problem?

**Comment by hiker** [comment]
Ah, the greedy RE are causing the problem. Using non-greedy (i.e. using .*?), and removing some unnecessary .* brings the runtime down from over 24 seconds to 0.39 seconds.
