### ISSUE TITLE
Use dependency analysis for loop fusion

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1075]
Use (and if required extend) the dependency analysis to validate loop fusion. Note that this is to a certain degree a duplicate of #257, but this ticket implements one of the two potential solutions mentioned in that ticket, so I'll keep it separate. Some issues to discuss:
- Should we rely on stencil information (esp. in gocean) when reasoning about which array elements are read/written, or should we rely on the actual code.
    - The actual code might be too complicated (assume an access ``a(i,j+n)``, where n comes from a module - we won't know if n is positive or negative).
    - The stencil information might be wrong (user error).
    
  For now I would suggest that we use the actual code, but if we encounter an unknown symbol, we use the stencil information. 
- It might be useful to add a symbolic maths library (as discussed in #523, #533). My idea would be to encapsulate this in a separate class, which would have some simplified implementation that covers a large fraction of the use cases if no symbolic maths lib is available. Example:
    ````
    SymbolicMath.is_smaller("i-1", "i")
    ````
  The ``is_smaller`` method could just handle the four cases: first element is a variable or variables with +/- integer constant, and same for second element. This means:
  ```
  SymbolicMaths.is_smaller("i-1", "i+2")    # would work and return true
  SymbolicMaths.is_smaller("i+1", "i-2")    # would work and return false
  SymbolicMaths.is_smaller("1+1", "-2+i")    # might not work, return either false or raise exception
  SymbolicMaths.is_smaller("1+1+2", "i-2+1")  # will likely not work and return either false or raise exception
  ```

  But with a symbolic maths library, the last two cases might work.
  
More brainstorming to be collected in this ticket.

**Comment by hiker** [comment]
Some example sympy:
```
>>> from sympy import *
>>> i,j = symbols("i j")
>>> simplify(i<i+1)
True
>>> simplify(i+1<i)
False
>>> simplify(i+1-2<i)
True
>>> simplify(i+1<j)
i - j < -1

```

**Comment by arporter** [comment]
Can this one be closed now or do you want to keep it open for sympy-related work?

**Comment by hiker** [comment]
We should also sort out the test. E.g. domain/nemo/transformations/nemo_loop_fuse is actually covered in the test tests/psyir/transformations/loop_fusion_test, while there is no corresponding test in tests/domain/nemo/...

**Comment by hiker** [comment]
> Can this one be closed now or do you want to keep it open for sympy-related work?

I agree to close this. The fact that one file is not covered by the corresponding test file is not a problem here, and the outstanding loop fusion work is covered in #257.
