### ISSUE TITLE
New release 1.5.1

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#110]
The Met Office would like a new release to allow use of the new quadrature API.

**Comment by arporter** [comment]
Have you updated the changelog for this release? I've pulled what I think is the latest master and gitlog isn't showing me any changes related to the release...

**Comment by arporter** [comment]
I've just checked and https://github.com/stfc/PSyclone/blob/master/src/psyclone/version.py has not been updated either.

**Comment by hiker** [comment]
Any chances to also release the new fparser (and merge some of my pull requests)? Would save some work long term.

**Comment by arporter** [comment]
I've manually deployed to pypi (`python setup.py sdist upload`). I had to do this from my desktop as something in the software stack of my VM is too old and was resulting in SSL errors.
(@hiker - I have now also made a new release of fparser and need some guidance from you as to which PRs to tackle.)
