### ISSUE TITLE
parse modules containing subroutines in one function/method

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1104]
There is no `fparser2 to psyir` function/method that takes Fortran code and turns it into PSyIR. The actual functionality needed at the moment is to support a module containing subroutines so any implementation could just support this for the moment.

**Comment by rupertford** [comment]
Created branch [1104_fparser2_to_psyir](https://github.com/stfc/PSyclone/tree/1104_fparser2_to_psyir)

**Comment by arporter** [comment]
This kind of overlaps with what I was proposing to do in #737 - I was going to re-write generate_schedule so that it became generate_routine. Is that the kind of thing you had in mind? If so, I'm very happy to let you do it :-)

**Comment by rupertford** [comment]
@arporter you can review it and see :-)
