### ISSUE TITLE
Specifying PSyIR node colours

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1112]
PSyIR nodes can be given a colour so that the output of the `view()` method is more readable. At the moment a node specifies a keyword name in a `_colour_key` variable and a mapping from keywords to colours is provided in the `Node` base class.

This solution does not seem particularly nice as the base class needs to have information from all of its child classes (that want to specify a colour). It is a particular problem when the PSyIR is specialised for a domain as it makes no sense for specialised classes to add keyword names to the Node base class.

One simple solution would be to remove the idea of a keyword and simply specify the colour in the class itself (modifying `_colour_key` to `_colour`. This would then defer the choice of colour to the class itself which seems to make sense.

A (more hacky) solution would be to support generic mappings from a colour to a colour as well as the existing generic PSyIR ones in the `Node` baseclass. For example, the base class could support `"red": "red"` which would allow any domain-specific classes to override their colour explicitly, whilst keeping the same implementation as we have now.

If it is decided that the choice of colour should continue to be separated from the class (to allow the colours to be changed independently) then a more radical solution might be preferred. A mapping would need to be kept, but I think this would be better kept in configuration files (with separate mappings for domain-specific nodes). I'm not sure how that would be implemented though as I think we would need to know which domain a domain-specific node was from (so we could look in the appropriate mapping). Perhaps all domain-specific nodes would need to identify themselves as such via another variable, or they could all inherit from a particular domain-specific class as well as `Node` (i.e. support multiple inheritance)?

Any thoughts, suggestions or preferences @sergisiso and @arporter?

**Comment by sergisiso** [comment]
I like the `_colour` attribute for each class, since we already do this for the "_text_name". I don't know any case where I wanted/needed to change the colour, so I wouldn't add the complexity of making them configurable unless somebody has this specific need.

**Comment by arporter** [comment]
I agree with @sergisiso - there's no need to make this complicated: just specifying the colour directly seems fine to me. As an aside, @hiker has pointed out that most of the time "_text_name" is just `self.__class__.__name__` so we could get rid of that property too.

**Comment by rupertford** [comment]
Thanks both, I'll implement `_colour` then.

**Comment by rupertford** [comment]
Created branch [1112_simplify_node_colours](https://github.com/stfc/PSyclone/tree/1112_simplify_node_colours)
