### ISSUE TITLE
Symbol additional specialisation attributes

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1113]
PR #1063 adds basic support for a symbol specialisation method but it doesn't solve what  to do with additional required (and/or optional) attributes of the subclasses:

e.g :
```
a = Symbol("name") 
# And later we know that "name" is an INTEGER DatatSymbol (the datatype is mandatory in DataSymbols)
a.specialise(DataSymbol, datatype=INTEGER_TYPE)
```
I think this is possible with something like:
```
class Symbol:
	# Subclasses shouldn't override this constructor
	def __init__(name, args, Kawgs):
		_init_attributes(args, kwargs)
	
	def _init_attributes(visibility, interface):
		# All attributes are consumed here
		# Same code as current Symbol.__init__
	
	def specialise(symbol_class, kwargs):
		# Check symbol_class is subclass of type(self) 
		self.__class__ = symbol_class
		self._init_attributes(kwargs)

class DataSymbol():
	def _init_attributes(datatype, constant_value, kwargs):
		# Consumes datatype and constant_value, the rest are passed to parent
		super(DataSymbol)._init_attributes(kwargs)
		# Same code as current DataSymbol.__init__
```

**Comment by arporter** [comment]
Just to play devil's advocate: why not have `specialise` call the `__init__` method?

**Comment by sergisiso** [comment]
I copied this comment from the PR conversation so it can be referenced in TODOs but this was just pseudocode (the unammed arguments are also not quite figured out). I will let the person who implements it decide on the details, but I am not sure calling the "constructor" method after the object is already constructed a bit confusing (even if in Python you can do anything :))

**Comment by arporter** [comment]
Yes, I agree that it could be confusing. In fact, now that I think about it, much of the pain in understanding what fparser does is that all the magic happens in a single `__new__` method. I'm just slightly concerned that we're effectively re-implementing `__init__`.

**Comment by arporter** [comment]
I've hit a problem relating to this. In specialising a Symbol in`_find_or_create_imported_symbol` we are losing the original interface that the Symbol was created with (because we call `__init__` with the supplied options and they don't include an interface so we get the default of a LocalInterface). Basically, `_init_attributes` needs to ensure that it doesn't change an attribute if it is already set and no explicit value is given for it.
