### ISSUE TITLE
Add codecov integration with Travis

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#112]
Currently we use coveralls to automatically provide test-coverage statistics for the tests run by Travis. However, codecov provides much more useful output. We will incorporate use of codecov with Travis in this issue.

**Comment by tofu-rocketry** [comment]
If you don't mind me asking, what do you find better ("more useful") in Codecov?

**Comment by arporter** [comment]
@tofu-rocketry it provides test-coverage information on the diff between a branch and master which will hopefully make doing code reviews a lot easier.

**Comment by rupertford** [comment]
#113 is on master. Closing this issue.
