### ISSUE TITLE
Add field access details for gokernel based on stencil/access mode declaration

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1130]
ATM if a field is accessed in a gocean kernel, the variable usage analysis adds the variable with index ``[1]`` (which was done to mark that this is an array access).

When implementing better testing for loop fusion, we need additional details about the access of fields in a kernel, which we can achieve only based on the meta-data (consistency of meta-data and code is a different issue). The suggestion is to add access as follows:
- if a field ``A`` is written in a kernel, add a write-access to ``A(i,j)``. This is the basic assumption for a gokernel that there are no 'stencil writes' to a field.
- if a field ``B`` is read in a kernel, add several read access, based on the stencil information. E.g. assume the stencil is ``010,112,003``, we would then add (assuming that the first line - 010 - represents ``j-1``, if it should be ``j+1``, swap all plusses and minuses :grin:):
    - ``B(i,j-1)`` 
    - ``B(i-1,j)``
    - ``B(i,j)``
    - ``B(i+1,j)`` and ``B(i+2,j)``
    - ``B(i+1,j+1)``, ``B(i+2,j+2)`` and ``B(i+3,j+3)``
 These array accesses would represent the stencil information.

Once we have the individual accesses, we can use the same code for dependency analysis in NEMO and gocean.

@arporter, @rupertford, @sergisiso  - feedback please :) (anyone else as well, but I think you three are the people involved in gocean).

**Comment by rupertford** [comment]
Hi @hiker. Yes that logic looks right to me. I think the top row is j+1 and the bottom j-1 as we treat it as a graph with the centre being 0,0. At least, that is how I read the documentation. So please swap the j +'s and -'s as you suspected, unless @arporter and @sergisiso say I wrong. :-)

**Comment by arporter** [comment]
I think @rupertford is right about the indexing and I think @hiker's suggestion as to how to interpret the meta-data to get read/write information is good.

**Comment by hiker** [comment]
Thanks, changing from question to improvement 👍

**Comment by arporter** [comment]
#1133 is merged. Can this be closed now @hiker?

**Comment by hiker** [comment]
Thanks a lot, @arporter
