### ISSUE TITLE
GO Stencil inconsistent value

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1132]
If a GOStencil is set as ``go_pointwise``, you can still query its depth, but you will get ``[000,00,000]``. Either getting the depth of a stencil with ``go_pointwise`` should raise an exception, or (my preferred solution) this should return ``[000,010,000]``. The latter would  imho express the meaning of ``go_pointwise`` adequately (and remove if-tests for some of my dependency code). 

Am happy to fix this as part of #1130, but in case that we don't agree on the best way we have this ticket to discuss this independently. @rupertford , @arporter, @sergisiso

**Comment by sergisiso** [comment]
I also like your solution with the 1 in the middle, no special cases is better if possible.
