### ISSUE TITLE
Make LFRicBuiltIn an abstract class

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1140]
As raised in the review of the PR #1125, `class LFRicBuiltIn(BuiltIn)` (in `src/psyclone/domain/lfric/lfric_builtins.py`) should really be an abstract class. This probably means that the parent class, `BuiltIn` in `src/psyclone/psyGen.py`, should also be abstract.

**Comment by arporter** [comment]
Since I'm working on the builtins in #1237 I shall do this change there.

**Comment by arporter** [comment]
This will be complete once #1239 is merged.
