### ISSUE TITLE
Documentation of compilation

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1158]
Iva raised the following issues in my "rename directories" PR (#1072), but I want to keep that PR small, so I'll add this as a separate issue:

> A paragraph or a subsection on about how to actually compile these examples with the two compilers that we know work, Gnu and Intel, would be very useful. Currently the "default" flags in Makefiles are set for gfortran:
> 
> F90 ?= gfortran
> F90FLAGS ?= -Wall -g -fcheck=bound
> and these flags need to be either changed in the respective Makefiles or given as the command-line arguments (e.g. F90=ifort F90FLAGS="-g -check bounds" make). All of this should be explicitly written down so that a user doesn't have to dig in the Makefiles and other places to figure out how to compile and run the examples.

I might not totally agree with that - setting the compiler and flags is pretty standard, and is documented in the Makefiles.  I am also not keen on specifying compilation flags - for testing ``-g -check bounds`` might be good, but then we risk that someone copies&paste this and starts to time stuff. 

If we agree to add this to the user's guide, all examples and tutorials need to be checked to be consistent (I found at least one makefile that sets FFLAGS instead of F90FLAGS).

> 
> Please mention the compilers that we know the code works with. It would also be good to add that if the code is tested with other than the listed compilers the PSyclone developers would wlecome the feedback.

Good idea 👍 

> 
> Also, if something is changed, how is the code recompiled? What is make clean used for and what does it do?

I believe this is standard makefile behaviour, and does not really need to be documented - but if we add a compilation section, we could of course add this. Note that all used Makefile targets are documented in https://github.com/stfc/PSyclone/blob/master/doc/user_guide/examples.rst (that's a result of merging the PR to make the makefiles consistent).

**Comment by TeranIvy** [comment]
I am now reviewing the updated PR #1072 and I think the documentation there fixes this issue, so I am closing it.
