### ISSUE TITLE
Support colouring of discontinuous loops

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#116]
Loops are coloured so that each of the colours can be computed in parallel. This is required for loops where the field or fields being modified is/are continuous and the iteration space is cells (as neighbouring cells update shared dofs) - let's call this a continuous loop.

Colouring is not required for loops where the field or fields being modified is/are discontinuous - let's call this a discontinuous loop.

However, one might want to colour a discontinuous loop in order to improve parallel performance as it could allow a set of loops to be parallelized in the same way (e.g. a continuous loop, followed by a discontinuous loop, followed by a continuous loop) and potentially be loop fused.

Note, there has been no request for this functionality so it is speculation on my part.

At the moment the colour transformation will raise an exception if the user attempts to colour a discontinuous loop (or at least it will once pr #115 is on master).

For the record. a standard discontinuous loop (with no redundant computation) should end up with the following upper bound for each colour ...

{{{
DO cell = 1, mesh%get_last_edge_cell_per_colour(colour)
}}}

Thanks to Steve M. for this information.

**Comment by TeranIvy** [comment]
I am not sure this is needed at all because of the support added in PRs #115 and #128. Closing the issue for now as redundant. If somebosy thinks it needs to be reopened, please do.
