### ISSUE TITLE
[psyir] Fortran backend rejects unresolved symbols

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1160]
After the prompt by Rupert at the telco this morning I tried processing standard NEMO code with the branch I'm working on in #1147. Unfortunately doing this immediately showed me that the PSyIR backend won't allow any unresolved symbols (other than kind parameters). Since NEMO very rarely uses the `ONLY` clause on `USE` statements, pretty much any symbol that is accessed via a `USE` will immediately prevent the backend from generating code. Given that we don't want to be parsing code unnecessarily, I think this constraint should be weakened so that the backend only checks that there is at least one import that could be bringing an unresolved symbol into scope?

**Comment by arporter** [comment]
Bringing @rupertford and @sergisiso into the conversation to get their thoughts.

**Comment by arporter** [comment]
Perhaps this should be some sort of configuration option as I can imagine, e.g. if we're coming from a different language, that we would want to keep these constraints?

**Comment by sergisiso** [comment]
Unless I am missing something I agree this check can be weakened with the idea that that the PSyIR only resolves symbols lazily (if it really needs the info), but this doesn't seem to be the case here. Is it the backend that tries to resolve the symbols or something inside PSyIR along the way?

**Comment by arporter** [comment]
It's in `gen_decls()` in the backend - it performs the following check:

https://github.com/stfc/PSyclone/blob/97637bdb7c066535a8ae71412f690e030f64c6b8/src/psyclone/psyir/backend/fortran.py#L623-L631

**Comment by arporter** [comment]
Are people happy if I change this bit of code so that it checks for a wildcard import and only errors if there isn't one? I could also add a TODO to log this situation once we have logging.

**Comment by rupertford** [comment]
OK with me. We might want the ability to support additional options in the future e.g. fail, search for the symbol, or require a config file containing the symbol types.
