### ISSUE TITLE
[psyir] Add support for TINY and HUGE, TANH and more

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1161]
Fortran has the `TINY(x)` and `HUGE(y)` intrinsics which return the smallest and largest numbers that may be represented in a variable of the same type as `x` or `y`. For TINY, `x` must be real, for HUGE, `y` can be real or integer.

A quick google shows me that C++ has the `numeric_limits` class template in the `limits` header.

Conceptually I think this is quite simple so it's really just a matter of choosing the names to use for the corresponding Unary Operators in the PSyIR. We could stick with the Fortran names @sergisiso and @rupertford?

**Comment by rupertford** [comment]
I'm not one for changing names for the sake of it but I think `smallest()` and `largest()` would make more sense.

**Comment by arporter** [comment]
Simon Mueller has also found that we don't support `tanh` and other hyperbolic functions. These could be added as part of this ticket.

**Comment by arporter** [comment]
In Wavewatch 3 Simon has found:

'atan2', 'dot_product', 'floor', 'maxval', 'anint', 'alog', and 'alog10'. There is another intrinsic that is used, 'float', which is part of the GNU extension, not the Fortran standard.

**Comment by rupertford** [comment]
I need huge() and tiny() to be supported for #2105 so will start on this issue. @arporter and @sergisiso, presumably we are just planning to support the Fortran names and interfaces directly in the PSyIR as we have done for other instrinsics, rather than looking to canonicalise (unless there is redundancy)?

**Comment by rupertford** [comment]
Created branch [1161_huge_tiny](https://github.com/stfc/PSyclone/tree/1161_huge_tiny)
