### ISSUE TITLE
lists in the config file

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1163]
ConfigParser does not support lists natively, it just returns a string, so the reader has to handle it manually. At the moment there are two different formats for list in the config file, one just with spaces and one with commas. The user must keep to these different formats for the entries otherwise the code will break. I don't like this and I don't like the fact that the code developer has to handle the formatting each time.

What I suggest is that we add the following to ConfigParser when we create it ...

```
ConfigParser(converters={'list': lambda x: [i.strip() for i in x.split(',')]})
```

and then access all lists like this ...

```
section.getlist(name)
```

This would mean that all lists would have to be comma separated.

**Comment by rupertford** [comment]
@hiker, are you happy with the suggested change?

**Comment by TeranIvy** [comment]
We have a function `create_dict_from_string` in the `class APISpecificConfig` but not something similar for lists. Would this be another method in this class?

**Comment by hiker** [comment]
Good catch, I didn't use "," in the psydata prefixes. Certainly, go ahead.

**Comment by rupertford** [comment]
> We have a function `create_dict_from_string` in the `class APISpecificConfig` but nothing similar for lists. Would this be another method in this class?

Hi @TeranIvy, the approach I'm suggesting is to add a `converter`. See the additional argument to `ConfigParser` in my first comment. Adding this creates an `getlist(...)` method in that instance of ConfigParser, so we don't need to add our own explicitly.

**Comment by rupertford** [comment]
created branch [1163_config_file_list](https://github.com/stfc/PSyclone/tree/1163_config_file_list)
