### ISSUE TITLE
Bug when using a constant for a scalar kernel parameter

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#117]
When a kernel is invoked as:
```
  call invoke( bc_ssh(0, p_fld) )
```
with a constant value as the scalar parameter  (bc_ssh is unchanged from the test files):
```
  type, extends(kernel_type) :: bc_ssh
     type(arg), dimension(3) :: meta_args =        &
          (/ arg(READ,      R_SCALAR, POINTWISE),  &
             arg(READWRITE, CT,       POINTWISE),  &
             arg(READ,      GRID_MASK_T)           &
           /)
```
the code created includes:
```
REAL(KIND=wp), intent(inout) :: 0
```
In https://github.com/hiker/PSyclone/tree/constant-parameter I've created an x-failing test to show this, not sure if you want a pull request for the test itself. Easy work around of course: declare a variable zero=0.

**Comment by rupertford** [comment]
Literal scalars are supported in the dynamo0.3 api and the logic for knowing if an argument is a literal or not is in the base class - see psyGen.py, class Argument, method is_literal() so it should not be too difficult to support correctly in gocean1.0.

**Comment by hiker** [comment]
Thanks, that will help. Don't have time atm to look at it now. Glad that we don't need parser improvements for that :)
