### ISSUE TITLE
Tests fails due to config file if PSyclone is not installed

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1171]
It does not affect all tests, a simple reproducer:
```
.../psyclone/src/psyclone/tests/domain/gocean/transformations$ pytest ./globalstoargs_test.py 
============================================================================================= test session starts ==============================================================================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/joerg/work/psyclone, configfile: setup.cfg
plugins: cov-2.11.1
collected 0 items / 1 error                                                                                                                                                                                    

==================================================================================================== ERRORS ====================================================================================================
___________________________________________________________ ERROR collecting src/psyclone/tests/domain/gocean/transformations/globalstoargs_test.py ____________________________________________________________
globalstoargs_test.py:46: in <module>
    from psyclone.transformations import KernelGlobalsToArguments, \
../../../../transformations.py:57: in <module>
    from psyclone.domain.lfric import FunctionSpace
../../../../domain/lfric/__init__.py:45: in <module>
    from psyclone.domain.lfric.function_space import FunctionSpace
../../../../domain/lfric/function_space.py:45: in <module>
    class FunctionSpace(object):
../../../../domain/lfric/function_space.py:91: in FunctionSpace
    range(Config.get().api_conf("dynamo0.3").num_any_space)]
../../../../configuration.py:136: in get
    Config._instance.load()
../../../../configuration.py:231: in load
    self._config_file = Config.find_file()
../../../../configuration.py:468: in find_file
    raise ConfigurationError("{0} not found in any of {1}".
E   psyclone.configuration.ConfigurationError: "PSyclone configuration error: psyclone.cfg not found in any of ['/home/joerg/work/psyclone/src/psyclone/tests/domain/gocean/transformations/.psyclone', '/home/joerg/.local/share/psyclone', '/usr/share/psyclone']"
```
This is caused by initialising constants (either global, or class-variables) using the config file, e.g.:
```
    VALID_ANY_SPACE_NAMES = [
        "any_space_{0}".format(x+1) for x in
        range(Config.get().api_conf("dynamo0.3").num_any_space)]
```
If PSyclone is not installed (i.e. it's installed using ``pip -e``), the config file is not found in any of the paths searched. It is only found after the session fixture ``setup_psyclone_config`` in ``config_test.py`` is executed, which happens after the tests are imported.

There are a few solutions:
1) Refactor the code to initialise these constants in a constructor.
2) Create a separate (base) class containing all LFRic constants (and again they must be initialised in the constructor of the base class).
3) We add the path to the repository config file to the config search path. There is already a function (``get_repository_config_file``) we can use.
4) We initialise the config path for testing in ``conftest.py`` as code executed on importing the file (the file is imported before importing tests, only the session fixture in that file is executed later). So basically we move the code of the session fixture to initialise the config path out of the fixture - into the global name space (which means it is executed at import time).
5) We document that in case of using a ``-e`` installation you **HAVE** to set PSYCLONE_CONFIG to point to the right config file.

While I like 1) or 2) (I think it would make for a clearer initialisation of PSyclone if we got rid of code executed at import time), it is quite a bit of work (I looked at it, if you clean up function_space.py, then dynamo0p3 triggers the problem, and that file defines its constants outside of a class, i.e. global name space. So this would mean any use of any of these variables then need to be prefix with the class name ... and who knows what else is affected by that).

Options 3) and 4) both work fine, and are rather small. I don't like 4) (same issue ... executing code at import time, bad idea imho). I am not sure why we never did 3, and instead added this as a session fixture. My commit message/documentation says that this was done to make sure all tests get the right config file (e.g. if the user installs and modifies a config file, tests might fail. By explicitly setting ``PSYCLONE_CONFIG`` in the test, we make sure all tests get the right config file). Hard to say what side effects there would be (and also, in which order should we search for config files *sigh*). I also don't like 5), since it would mean that the user could easily run with the wrong config file (even worse - it would use this config file during importing, but likely once the session fixture is called, then use a different config file, depending in which order the tests are run - especially the tests that load and reload various test config files).

Happy to discuss in the telco. For now I'll be explicitly setting ``PSYCLONE_CONFIG`` to make the tests work again.

**Comment by hiker** [comment]
The outcome of the telco was that we should do a proper refactoring, introducing separate classes to store the constants (one class for each API), and initialise these constants in the construtor. There are two potential approaches:
1) This class becomes a base class for anything that needs access to a constant (so the constructor is called) - if a constant should be needed outside of a class context, you would have to create an instance of the object to access a constant.
2) we use a singleton construct.

There would be some overhead of calling the constructor in 1) over and over again, this could be reduced by storing variables in class variables like this:
```
class LFRicConstants:
   WAS_INITIALISED = FALSE
   CONST_VALUE = None
   
    def __init__(self):
        if LFRIcConstants.WAS_INITIALISED:
            return
        LFRicConstant.CONST_VALUE = config.get(bla bla bla)
```

The other question is if we want the constants to be accessed directly, or using getter/setter. I think in case of a class that only stores constants using these constants directly should be fine. These can be replaced with setter/getter if required anytime.

**Comment by hiker** [comment]
I've opened https://github.com/stfc/PSyclone/tree/1171_lfric_constants, and moved two constants across, and all seems to work fine (admittedly these constants do not need config file). The core is like this (all comments remove to keep the excerpt small):
```
class LFRicConstants(object):
    HAS_BEEN_INITIALISED = False
    def __init__(self):
        if LFRicConstants.HAS_BEEN_INITIALISED:
            return
        LFRicConstants.HAS_BEEN_INITIALISED = True
        LFRicConstants.VALID_QUADRATURE_SHAPES = \
            ["gh_quadrature_xyoz", "gh_quadrature_face", "gh_quadrature_edge"]
```

There are two ways of using this class. I have (so far) use the following way:
```
    const = LFRicConstants()
    if basis_fn["shape"] not in const.VALID_QUADRATURE_SHAPES:
```
in any function/method that needs a constant. Disadvantage is that the constructor gets called once for each function that needs an LFRic constant (though it's cheap, since it will only actually execute code the very first time). Alternative this class could become a base class, and then the constants could be accessed like this:
```
class SomeClass(LFRicConstants):
    def __init__(self):
        super(SomeClass, self).__init__()

    def some_function(self):
         self.VALID_QUADRATURE_SHAPES
```
I don't like using ``self`` there (it's pretty hard to know where these variables come from, especially if it's in a base class three level higher), and if you use ``LFRicConstants.VALID_...`` instead, then there is a risk that the constructor is not called (though that will at least immediately raise an exception, since the class constants are only defined in the constructor).

Let me know if you prefer the baseclass approach, am happy to use it (though there are some function that certainly need to create an instance of ``LFRicConstants`` to make sure the constructor has been called.

**Comment by hiker** [comment]
@rupertford, @arporter, @TeranIvy , @sergisiso @christophermaynard , @andrewcoughtrie - comments welcome :)

**Comment by arporter** [comment]
Like you, I think I prefer the first approach as it makes the source more obvious.

**Comment by hiker** [comment]
OK, I will continue this way then, glad that no one objected :)

I noticed one other problem we have: in ``dynamo0p3`` there is code like this (in the constant area, i.e. executed when you import this)
```
psyGen.VALID_INTRINSIC_TYPES = VALID_INTRINSIC_TYPES
```
This is really bad, e.g. if you execute a ``gocean`` test that imports ``transformations.py``, this in turn will import ``dynamo0p3``, so ``psyGen.VALID_SCALAR_NAMES`` (and other similar constants) are actually set to LFRic values, and I think that only works because these variables are not used in gocean, or we are lucky in the order in which we import things (gocean does not set these constants at all). 
And obviously this does not work if we initialise these constants only later.

My suggested solution would be to add a factory that creates an (API-dependent) constant object. In API-specific code (``dynamo0p3``) we use ``LFRicConstants`` directly, in generic code (``psyGen`` for example), we use the factory to get the right constant object (the factory will rely on the ``config.api``) . This obviously implies that we will need similar constant objects for other APIs.

The reason for 'hard coding' the API-specific constant object in API-specific code is to avoid side-effects - e.g. importing ``transformations.py`` with a gocean API would then trigger to import ``dynamo0p3``, and I want to make really sure that nothing in there then gets initialised with gocean constant data (likely this kind of initialisation will be completely gone and not happening anymore in the end, but better safe than sorry)

**Comment by arporter** [comment]
That all sounds sensible to me Joerg - thanks for clearing up our mess!

**Comment by rupertford** [comment]
Sorry for the delayed reply. I'm also happy with the first approach - thanks @hiker. We could potentially revisit if and when we decide to overhaul the psy-layer code generation. An API-dependent constant object also sounds good.

**Comment by hiker** [comment]
I have a first version running. A few  things are missing (esp. testing of the gocean/nemo constant objects), but before I spent any more time on it, I would like to get some feedback. One change: I use the config object to get the constant class for the current API (seems silly to introduce a factory considering that we already have the api-specific config files).

I moved a minimum set of constants from various classes (``dynamo0p3``, ``psyGen``, ``FunctionSpace``, ``LFRicArgDescriptor``, maybe more) into one ``LFRicConstants`` class, and used it as discussed above, and also removed intriguing concepts like ``dynam0p3`` setting variables in ``psyGen`` based on values in ``LFRicArgDescriptor`` when importing ``dynamo0p3``.

You can see the new ``LFRicConstants`` file [here](https://github.com/stfc/PSyclone/blob/1171_lfric_constants/src/psyclone/domain/lfric/lfric_constants.py).

My questions:
1) This class is somewhat big. It does not yet need a pylint-directive to avoid warnings about too many attributes (I've seen this in some other classes), so not the worst offender, but still. Is it too big?
2) Moving only the minimum number of constants left some constants behind, so it is very hard to know where a constant comes from.For example, ``ANY_W2_FUNCTION_SPACES`` is in ``FunctionSpace``, but ``CONTINUOUS_FUNCTION_SPACES`` is in ``LFRicConstants`` (because the latter is used to define ``VALID_FUNCTION_SPACES`` , which needs ``VALID_ANY_DISCONTINUOUS_SPACE_NAMES``, which comes from the config file, so it had to be moved). I don't like this, and did this only to see how small we can keep this object (@arporter agreed that the size and manageability might be an issue).

In hindsight, I see one alternative approach could have been to create a separate constant-object for each class, e.g. ``FunctionSpaceConstants``, ``Dynamo0p3Constants``, ... though I am not sure how the dependencies between these various constant objects would work out, i.e. if there might not be circular dependencies (requiring imports outside of toplevel). 

Feedback welcome :)

**Comment by hiker** [comment]
That is fixed  (again :) ), and the bug cannot be reproduced anymore.
