### ISSUE TITLE
Reshaping of LFRic intergrid mesh maps

### ISSUE THREAD

**Issue by tommbendall** [stfc/PSyclone#1173]
As part of LFRic ticket 2572 we are reshaping the mesh map that encodes which cells on a fine mesh are associated with which cells on a coarse mesh.

The idea is that the mesh map won't just be a list of fine cells per coarse cell, instead it will be a table whose layout matches the arrangement of the fine cells within the coarse cell.

To facilitate this any LFRic intergrid kernels would now take `ncell_f_per_c_x` and `ncell_f_per_c_y` as arguments instead of just `ncell_f_per_c`, e.g.:

```
  subroutine restrict_kernel_code(nlayers,         &
                                  cell_map,        &
                                  ncell_f_per_c_x, &
                                  ncell_f_per_c_y, &
                                  ncell_f,         &
                                  coarse,          &
                                  fine,            &
                                  undf_c,          &
                                  dofmap_c,        &
                                  ndf,             &
                                  undf_f,          &
                                  dofmap_f)
```

I think we'll need to update the following bit of Psyclone for this to be supported:
https://github.com/stfc/PSyclone/blob/9d6919083057c48c437010ba73e18aad8a32eeb6/src/psyclone/domain/lfric/kern_call_arg_list.py#L106-L109

**Comment by arporter** [comment]
Thanks @tommbendall. Can this functionality wait until after we've made the 2.0 release of PSyclone or do you need it ASAP?

**Comment by tommbendall** [comment]
I have a psy lite implementation of the existing kernels so I definitely wouldn't say it's needed ASAP!

**Comment by TeranIvy** [comment]
I think it would be good to have this for PSyclone 2.0.0 as the multigrid kernels will need to change so any time this goes on trunk we will have a non-backward compatible change. This is why I think it would be great to have it in PSyclone 2.0.0 rather than pushing it to another non-backward compatible change.

The relevant branch with the PSyKAl-lite implementation is [r27703_reshape_mesh_map](https://code.metoffice.gov.uk/trac/lfric/log/LFRic/branches/dev/thomasbendall/r27703_reshape_mesh_map) (Tom's [LFRic ticket 2572](https://code.metoffice.gov.uk/trac/lfric/ticket/2572)).

**Comment by arporter** [comment]
Looking at https://code.metoffice.gov.uk/trac/lfric/changeset?new_path=LFRic%2Fbranches%2Fdev%2Fthomasbendall%2Fr27703_reshape_mesh_map%2Fgungho&old=27922&old_path=%2FLFRic%2Ftrunk%2Fgungho the new code to be generated is:

    ncell_f_per_c_x = mmap_fine_coarse%get_ntarget_cells_per_source_x()
    ncell_f_per_c_y = mmap_fine_coarse%get_ntarget_cells_per_source_y()
    map_coarse => coarse_proxy%vspace%get_whole_dofmap()
    map_fine => fine_proxy%vspace%get_whole_dofmap()

    do cell=1,mesh_coarse%get_last_edge_cell()
      call restrict_kernel_code(nlayers,                   &
         cell_map_coarse(:,:,cell), &
         ncell_f_per_c_x,           &
         ncell_f_per_c_y,           &
         ncell_fine,                &
         ...
