### ISSUE TITLE
Cannot create Reference Guide

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1178]
When I try to ``make html`` in ``doc/reference_guide``, I get:
```
Generating example index...
finalizing index lists...
writing tag file...
Running plantuml with JAVA...
Running dot...
lookup cache used 10203/65536 hits=44693 misses=10674
finished...

Extension error:
Could not import extension autoapi.sphinx (exception: No module named 'autoapi.sphinx')
make: *** [Makefile:19: html] Error 2
```

I couldn't find much about this when googling, https://github.com/readthedocs/sphinx-autoapi/issues/69 indicates to test the following command:
```
~/work/psyclone/doc/reference_guide$ python3 -mautoapi.extension
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'autoapi.extension' found in sys.modules after import of package 'autoapi', but prior to execution of 'autoapi.extension'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
~/work/psyclone/doc/reference_guide$ which python3
/usr/bin/python3

```
So while there is a warning, I don't think that's important.

Any idea what might be wrong? I thought it was because of my two python3 installations (system and OneAPI), but I still have the same issue when I disable oneapi.

**Comment by arporter** [comment]
In a word, "no." I have the following packages installed:
    (py3) psyir$ pip list | grep autoapi
    autoapi                       2.0.1     
    (py3) psyir$ pip list | grep sphinx
    sphinx-rtd-theme              0.5.0     
    sphinxcontrib-applehelp       1.0.2     
    sphinxcontrib-bibtex          2.1.4     
    sphinxcontrib-devhelp         1.0.2     
    sphinxcontrib-htmlhelp        1.0.3     
    sphinxcontrib-jsmath          1.0.1     
    sphinxcontrib-qthelp          1.0.3     
    sphinxcontrib-serializinghtml 1.1.4

**Comment by arporter** [comment]
If you make a clean virtualenv and then do a full pip install of PSyclone (from the source) does it work then?

**Comment by hiker** [comment]
That was extremely useful, I didn't have autoapi installed, only sphinx-autoapi. Not sure if this makes any sense this way, but it's working now. THANKS!!

**Comment by hiker** [comment]
I'll reopen this to document this somewhere.
