### ISSUE TITLE
make clean in reference guide does not clean all files

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1179]
``make clean`` does not remove the unnecessary files in ``doc/reference_guide/source``. I have >180MB in there, and on machines behind a firewall I need to manually sync psyclone from a machine with outside access to the one with restricted access. Having to copy >180MB unnecessary is annoying.

Suggested solution would be to add a ``make allclean`` target (to avoid redefining Sphinx's ``clean`` target).

**Comment by arporter** [comment]
This is being done as part of #1285.
