### ISSUE TITLE
Change makefile variables from F90 to FC and F90FLAGS to FFLAGS

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1180]
As discussed on teams, I opened a ticket for that (with the option to simple close this issue if we don't want to do it). I came up with the following script so far:
```
#!/bin/bash

for i in $(find . -path ./.git -prune -false -o -type f); do
    echo $i
    sed -i 's/$(FC)/$(FC)/g; s/${F90}/$(FC)/g; s/F90=/FC=/g; s/^F90\b/FC/g; s/F90LAGS/FFLAGS/g' $i
done
```

Note that we cannot use ``s/\bF90\b/FC``, since this will also change a valid Makefile line like:
``
%.o: %.F90
``
But I believe I caught the cases so far (will have a closer look if we decide to do this). The sed command replaced:
- all ``$(FC)`` (used in makefiles, but potentially also documentation and included makefiles like ``common.mk``.
- Replace ``${F90}`` with ``$(FC)`` - sorry, I don't like mixing ``$()`` and ``${}`` in our makefile, this makes is harder to write scripts like this one, so I replace the ``{}`` with ``()`` as a start :)
- Change if we pass a variable to another makefile: ``$(MAKE) F90=$(F90)`` --> ``$(MAKE) FC=$(FC)``
- Change assignments ``FC ?= gfortran``
- Replace ``FFLAGS`` - I couldn't spot any immediate problems with this variable compared with ``F90``

It ran across all files, the one I spotted that will need manual attention is ``utilities.py``:
```
-    F90FLAGS = ""
+    FFLAGS = ""
...
-        Compile.F90FLAGS = config.getoption("--f90flags")
+        Compile.FFLAGS = config.getoption("--f90flags")
...
-        self._f90flags = Compile.F90FLAGS
+        self._f90flags = Compile.FFLAGS

The other problem of course is that we also need to convert the external repos (since we sometimes pass flags from PSyclone to dl_esm_inf etc). I would expect that a script like the one above would work.

```

**Comment by hiker** [comment]
We have one problem with implicit variables for commands like FC that always have a default value (f77 for FC), which means code like:
```
FC ?= gfortran
```
does not work (and everything gets compiled with f77 - which is a link to gfortran on my machine). This should therefore be replaced with:
```
ifeq ($(origin FC),default)   # Only trigger then the value of FC is taken from the default value, i.e. not set by user
FC = gfortran
endif
```

Now this change becomes a lot more work (need to adjust (c) years in all these files as well sigh). There are some alternatives. Instead of ``?=`` we just use:
```
FC = gfortran
```
in a Makefile. This **can** be overwritten with either:
```
make FC=ifort
```
or
```
FC=ifort make -e
```
Of course, LFRic could just call our makefiles with:
```
$(MAKE) -C (SOMEDIR) F90="$(FC)" F90FLAGS="$(FFLAGS)" some_target.
```

This would move from the "FC/FFLAGS" pattern to "F90/F90FLAGS" usage.  Might that just used to avoid the whole problem?

**Comment by hiker** [comment]
(Oh, in case that someone copies the script into psyclone and runs it ... don't ... the script will obviously modify itself, and mess up all the regular expressions :) )

**Comment by hiker** [comment]
@TeranIvy Can this ticket be closed? I believe we agreed to keep F90/F90FLAGS in PSyclone, and Met Office will just provide these variables from a top level makefile or script using something like:
```
 F90="$(FC)" F90FLAGS="$(FFLAGS)" make ....
```

**Comment by arporter** [comment]
Closing this unless @TeranIvy wants to reopen it?
