### ISSUE TITLE
[psyir] Perform tree validation prior to code generation

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1184]
In the 'old' way of doing things, the `gen_code` routines perform validation (where necessary) before generating code. This is necessary because we do not mandate the order in which Transformations are applied and therefore we can only check that the tree is correct at the point of code generation. Some (but not all) nodes have the `_pre_gen_validate()` method which performs these checks.
With the move to the use of a Visitor to generate code from the PSyIR, these checks are no longer being performed. The best way of implementing them is not yet clear. Some options:

 1. Have an entirely separate visitor that performs validation;
 2. Update the Visitor base class to call something like `_pre_gen_validate()` on each node;

Currently, I favour 2. as the checks are language independent and are specific to a particular node type.

**Comment by arporter** [comment]
Option 2. turns out to be very easy and works well. Now that I'm calling `_pre_gen_validate` from the visitor it will have to be made a 'public' method. I could just drop the leading `_` but I feel that the 'gen' could be misleading now. Do either @rupertford, @hiker or @sergisiso have any suggestions? I'm wondering about `validate_in_tree` or somesuch? (We could have just `validate` but that might get confusing given that `Transformation`s have a method with that name.)

**Comment by arporter** [comment]
A second question, should I give the `Node` base class an (empty) implementation of this new method? The visitor would then not have to check whether a node has the e.g. `validate_in_tree` method before attempting to call it.

**Comment by sergisiso** [comment]
I agree to drop `_pre_gen`. Since the node attributes itself and its direct parent and children should already be valid by the multiple node creation/children connection checks, a possible name could be `validate_global_constraints`?

Imo, the empty default implementation is nicer than a the check if the method exists.

**Comment by arporter** [comment]
Thanks Sergi, I've gone with both of your suggestions.
