### ISSUE TITLE
Re-factor PSyDataNode constructor

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1185]
In #1177 it was noted that the constructor for the PSyDataNode no longer follows the pattern that has been adopted for other PSyIR nodes (where we have a 'thin' constructor and a static 'create' method that does most of the work). It's also possible that some of what it does should be performed by the associated transformation.

**Comment by hiker** [comment]
@arporter Is this needed for the upcoming release, or can this wait till later?

**Comment by sergisiso** [comment]
This can wait, it is not a bug nor a blocker to anything else. It is just to make the interface similar to other Nodes.

**Comment by arporter** [comment]
In doing #1147 I've also realised that moving to the PSyIR backend means we're losing the current checks that there isn't going to be a name clash when we introduce a `use` for the PSyData module and associated symbols. We can fix this as part of this Issue by ensuring that we give PSyData-related symbols an appropriate tag when we create them. That way we can distinguish them from any pre-existing symbols in the code being processed.
