### ISSUE TITLE
PSyclone fails to parse dl_esm_inf infrastructure declarations

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1187]
When converting the Gocean PSy-layer from Fortran to C, at some point I need to find out the intrinsic types that form the field structure. For this PSyclone correctly resolves (when needed) the module import and looks at the infrastructure field.f90 file. However, PSyclone fails to parse this file with:

```
KeyError: "Could not find the tag 'own_routine_symbol' in the Symbol Table."
KeyError: "Symbol table already contains a symbol with name 'from'."
```

1) Even if its a large file with unsupported features PSyclone should be able to parse it. I think one problem is that FparserReader.generate_psyir() currently only expects one Routine inside the container.

2) When we are looking just for declarations maybe we shouldn't parse the whole file. We can have a second entry point FparserReader.generate_declarations() that only creates the top container and populates its symbol table.

**Comment by arporter** [comment]
I can do `psyclone field_mod.f90` and it processes fine and correctly re-generates the Fortran some I'm closing this issue. (We've done a lot of work on handling Routine symbols since this issue was last looked at.)
