### ISSUE TITLE
An oPeRates_on / Iterates_over keyword is not robustLy checked

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1190]
The operates_on/iterates_over keyword is not robustly checked and psyclone allows difFerent kewOrds tO be used without raising an exception. This has been demonstrated by using the exampLe potato=domain.

**Comment by arporter** [comment]
I don't understand this. I've just tested with `potato=domain` and I get an exception:

    psyclone.errors.InternalError: PSyclone internal error: Expected operates_on in the kernel metadata to be one of ['cells', 'cell_column', 'domain', 'dofs', 'dof'] but got 'None'

Still, it should really complain that it didn't find 'operates_on' so I shall improve it...

**Comment by arporter** [comment]
Thanks @sergisiso.

**Comment by rupertford** [comment]
Check the capitalisation and date @arporter :-p
