### ISSUE TITLE
Drop Python 3.5?

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1193]
The notebook tests are failing for Python 3.5. Possibly this is because Jupyter has dropped support for Python 3.5 (https://github.com/jupyter/notebook/pull/5962). Apparently 3.5 was EOL last September.

As discussed at https://github.com/jupyter/notebook/issues/5961#issuecomment-768662236), we could choose to pin the version of Jupyter we use but I think a better option is to drop 3.5.

**Comment by arporter** [comment]
For now, I've made the success of the Python 3.5 tests an optional requirement before merging a branch to master.

**Comment by hiker** [comment]
I'm ok with dropping 3.5 (Intel OneAPI comes with python 3.7.9, and I am using 3.8).

**Comment by sergisiso** [comment]
Even if Python 3.5 is not marked as required now, when it fails it cancels the other tests and make the whole CI not pass.

**Comment by rupertford** [comment]
If we are going to do this then it should be made clear in the documentation that it does not work. Also, what version of Python3 do the Met Office use and what version is in the LTS versions of linux? If 3.5 is still a standard version anywhere then I don't think we should drop it. I also thought that Sergi found that this problem had gone away (and I've not noticed it yet) - obviously not?

**Comment by TeranIvy** [comment]
We're using 3.6.8 in LFRic, so from our point of view it makes sense to replace 3.5 testing with 3.6.

**Comment by arporter** [comment]
Apparently 3.5 is shipped with Ubuntu 16.0.4 which (I've just learned) reaches EOL this month!

**Comment by arporter** [comment]
Suddenly this problem has gone away again! I've delved in the logs for the tests and there are differences in the dependencies that are being installed:

    < decorator-5.0.6-py3-none-any.whl
    > decorator-5.0.5-py3-none-any.whl
    < jupyter_client-6.1.12-py3-none-any.whl
    > jupyter_client-6.1.13-py3-none-any.whl
    > nest_asyncio-1.5.1-py3-none-any.whl

**Comment by arporter** [comment]
Anyway, we can close this for the time being.

**Comment by arporter** [comment]
@LonelyCat124 is getting failures again with 3.5 which is now a year past its EOL. 3.6 reaches EOL this year too. I propose we drop 3.5...

**Comment by arporter** [comment]
and @LonelyCat124 also points out that 3.10 is due in 5 days!

**Comment by LonelyCat124** [comment]
Ubunbu 18.04 LTS end their "Hardware and maintenance updates" 6/2022, and ships with Python 3.6 as their default Python version, so I've bumped 3.5 up to 3.6 in #1415 as discussed with Andy

**Comment by arporter** [comment]
Flake8 is now failing with 3.5 and I can see no reason (given the above discussion) not to switch from 3.5 to 3.6 so I'll open a PR.

**Comment by sergisiso** [comment]
We could also consider bumping 3.8 to 3.10 in GHA, so we check with the oldest and latest stable versions.

**Comment by arporter** [comment]
Yes, I'd be happy with that. Any objections from @TeranIvy, @rupertford or @hiker ?

**Comment by hiker** [comment]
OK with me.

**Comment by arporter** [comment]
Reopening as I've hit trouble with the fact that we pin the version of jsonschema in setup.py and there's a TODO there for this issue (naughty us missing that).
