### ISSUE TITLE
Make PSyIR Schedules copiable 

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1198]
Currently the schedules are not copiable (.copy() method fails). To make them copiable their _refine_copy method needs to:
- Make a deepcopy of the original schedule symbol table.
- Update all the children references to the new symbols of the copied symbol table.

The same is true for Containers. (maybe we could introduce a generic abstract class ScopingNode that has the logic for both)

**Comment by arporter** [comment]
Can this be closed now @sergisiso ?
