### ISSUE TITLE
W2any support in psyclone

### ISSUE THREAD

**Issue by thomasmelvin** [stfc/PSyclone#12]
LRFic ticket #975 https://code.metoffice.gov.uk/trac/lfric/ticket/975 implements mass matrices in the horizontal (W2h) and vertical (W2v) components of the W2 space. However a new kernel had to be created as the concept of W2any does not exist in LFRic or psyclone.

It would be useful to support the kernels written for W2any function spaces where W2any could be W2, W2v or W2h. In the psy layer these would all appear the same.

LFRic ticket #807 https://code.metoffice.gov.uk/trac/lfric/ticket/807 will implement the corresponding metadata support in LFRiic

**Comment by rupertford** [comment]
I'll take this on to get me back into PSyclone'ing.

Created branch w2any

**Comment by christophermaynard** [comment]
Hi Ru Fo, good to have you back on board. How's the ankle?

ChriMa.

Sent from my iPhone

On 24 Mar 2017, at 16:37, Rupert Ford <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll take this on to get me back into PSyclone'ing.

Created branch w2any

**Comment by rupertford** [comment]
Hi Chris, progressing I think. Staples are out on Tuesday so hopefully I'll know more then.

**Comment by rupertford** [comment]
I need some input from Tom on functionality. The question is what it means when we have more than one field specified as any_w2 in a kernel. The way PSyclone currently works is to assume that all fields specified as any_w2 are on the same space and to only dereference once for all of them. I suspect this is not what is wanted. However, it does lead on to the question of whether we know that certain fields are on the same space, even if we don't know what they are. The way this is solved for any_space is to have _1, _2 etc. We could do the same thing here and have any_w2_1, any_w2_2 etc. Alternatively we could assume that all any_w2 fields are on different spaces and therefore always deference them separately. Finally, we could ignore all this for the moment and limit kernels to only supporting one any_w2 field. What do you suggest Tom?

**Comment by rupertford** [comment]
A quick update.

It would not be possible to distinguish between one any_w2 field needing a differential basis function and another any_w2 field needing a basis_function as they would both be specified as being on any_w2 when referencing.

In the following example, we need `_1` and `_2` to distinguish

```
  type(arg_type) :: meta_args(2) = (/                                  &
       arg_type(GH_OPERATOR, GH_WRITE, ANY_W2_1, ANY_W2_1),      &
       arg_type(GH_FIELD*3,  GH_READ,  ANY_W2_2)                    &
       /)
  type(func_type) :: meta_funcs(2) = (/                                &
       func_type(ANY_W2_1, GH_DIFF_BASIS),                          &
       func_type(ANY_W2_2, GH_BASIS)                                      &
```
or we have to assume they are the same ...

```
  type(arg_type) :: meta_args(2) = (/                                  &
       arg_type(GH_OPERATOR, GH_WRITE, ANY_W2, ANY_W2),      &
       arg_type(GH_FIELD*3,  GH_READ,  ANY_W2)                    &
       /)
  type(func_type) :: meta_funcs(2) = (/                                &
       func_type(ANY_W2, GH_BASIS, GH_DIFF_BASIS)                          &
```

Therefore I think we either need to assume that all any_w2 fields are on the same (unknown) space in a kernel (which I suspect is too restrictive in general) or change to use any_w2_1, any_w2_2 etc.

**Comment by thomasmelvin** [comment]
I think for now we should restrict it so that all fields on any_w2 are on the same space (one of W2, W2v, W2h) this will cover most of the use cases I am thinking of

**Comment by rupertford** [comment]
OK. By default this will have to be assumed i.e. if the user specifies any_w2 and the fields are not on the same space then PSyclone will still generate (presumably) incorrect code as it will not know any better at pre-compile time.

We do have an outstanding issue which will add run-time checks to make sure the specified types in Kernels and actual types in arguments match which would perform the appropriate checks.

Are you alright with this for the time being or would you like a run-time check added now?

**Comment by thomasmelvin** [comment]
Yes this is fine

**Comment by rupertford** [comment]
pull request #19 has been merged to master. Closing issue.
