### ISSUE TITLE
Installation and configuration files

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#121]
Up until now there has only been one configuration file associated with PSyclone (`config.py`) and it is not something that the average user ever has to edit. As such it is just installed as part of the PSyclone package when using setuptools.

However, with the work to interface Claw and PSyclone (#114) it is now necessary to have another configuration file with details of the Claw/Omni installation. Unlike `config.py` this *will* have to be edited as part of the installation procedure. We therefore need to decide where configuration files should be installed to and then edit `setup.py` in order to achieve this. (See e.g. https://docs.python.org/2/distutils/setupscript.html#installing-additional-files for details of how this should be done.)

**Comment by arporter** [comment]
Since we treat `config.py` as part of the PSyclone package, we currently just `import` it whenever we need to. However, this approach won't work if we have configuration files that are not on our PYTHONPATH. We may need extra code to load a configuration file and make the resulting data available.

**Comment by arporter** [comment]
As @MatthewHambley is not yet a collaborator, I shall bring him into this discussion like so...

**Comment by MatthewHambley** [comment]
I'm not sure how Python normally handles these matters but I do know the expectations on a Posix system.

Normally there would be a hidden configuration file in the users home directory. Maybe a `~/.psyclone` file. If we expect multiple configuration files it could be a directory.

There might also be a site-wide "default" configuration in either `/etc/psyclone` or`'/usr/local/etc/psyclone`.

The contents of these files is largely down to the owning application. It is commonly something human readable though.

Obviously different expectations exist for Windows systems and probably MacOS and Linux systems too despite being somewhat Posixy.

**Comment by hiker** [comment]
There should also be a project specific file (e.g. $PROJECTDIR/.psyclone).

**Comment by MatthewHambley** [comment]
> There should also be a project specific file (e.g. $PROJECTDIR/.psyclone).

That's a good idea but what is `$PROJECTDIR` in this case. Do you mean "current directory"? Effectively `./.psyclone`?

**Comment by arporter** [comment]
Perhaps we should attempt to install to `/etc/psyclone/`and fall-back to `~/.psyclone/`. I've been doing a lot of googling but it's not clear to me that there's a standard way of doing this in `setup.py`. My guess would be that, before the call to `setup()`, we attempt to write to `/etc/psyclone/` and if that fails, set the directory of the `data_files` arg to `setup()` to be `$HOME/.psyclone/`. We can get $HOME using the `os` module although I'm not sure how portable this will be. (I was about to say we don't care about Windows but then remembered that Mike was building LFRic on Windows 10...)

Separately to installation, there's then the matter of locating and reading the configuration file(s) when PSyclone is run. This is simpler - we just need a list of potential locations and search them in a ~Posix-compliant order.

Finally (I think), there's the format of the configuration files. As I've already said, they are currently python modules but I don't think that's a solution for the long term. A better way of doing it might be to use `configparser` (https://docs.python.org/3/library/configparser.html).

**Comment by MatthewHambley** [comment]
I agree with @arporter. There are 3 issues to hand: Installation, Execution and Format. Furthermore what he proposes makes sense.

With regard to the user's home directory, a good solution seems to be `os.path.expanduser('~')`. The documentation claims that this is platform independent and will work on Windows too.

**Comment by arporter** [comment]
Following our re-think on how we integrate CLAW with PSyclone, it's likely that we won't need a new configuration file. (I think we can just require that Omni be on the user's PATH.) Therefore I'm closing this issue for the time being. We can always open it again if it becomes relevant.

**Comment by arporter** [comment]
It only took me 3 hours to realise that this issue *is* still relevant. As soon as we want to use Omni we hit the problem of providing it with Omni-compiled `.xmod` files of any modules that a kernel file depends upon.

**Comment by arporter** [comment]
I have the installation of a configuration file now working (although, developers please note that it does not work if you ask pip to do a 'live' install using the "-e" flag).

Next step is to decide how we make the settings from that file available within PSyclone. Currently we have `psyclone.config` which contains various static properties, e.g. `DEFAULTAPI = "dynamo0.3"`.
Since this is a Python module it is available for use throughout the code base via a simple `from psyclone import config`. I propose to replace this module by:
1. Moving its contents into `psyclone.cfg`
2. Having a *new* `config` module that is responsible for reading that config file and making the values available throughout PSyclone.

**Comment by arporter** [comment]
I'm hitting test failures again because, in one of my tests, I create a new `Config` from a different configuration file containing different settings. This `Config` is then picked up in other tests causing failures. This is because `Config` is stored in `psyclone.configuration.ConfigFactory._instance` and therefore, once created, will exist as long as `psyclone.configuration` is in scope. Given that some of my pytest code imports `psyclone.configuration`, this means that the same `Config` will exist for multiple tests.

**Comment by arporter** [comment]
My `configuration` module contains a `ConfigFactory` class object and it is this that holds the static variable `ConfigFactory._instance`. Reading around (https://docs.python.org/2.0/tut/node11.html), it seems that module scopes exist for as long as the python interpreter is running so, once `configuration` has been loaded into the interpreter, it is there for good. Given that loading `configuration` into the interpreter also creates the `ConfigFactory` class object, that too will exist for as long as the python interpreter is running.

**Comment by arporter** [comment]
I think I'm on to points 6) and 7) of my TODO list. These are more easily dealt with given the additional info provided by a PR so I shall make one now...

**Comment by rupertford** [comment]
pr #166 is now on master. Closing issue.
