### ISSUE TITLE
Outline script that will translate TL kernels to AD kernels

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1231]
An initial outline script is required for the adjoint project. This should take a TL kernel file as input, parse it with fparser2, translate it to language-level PSyIR, provide hooks/comments for translating to LFRic-specific PSyIR, provide hooks/comments for performing transformations to convert to an AD kernel and then write out the resultant transformed PSyIR to file.

**Comment by arporter** [comment]
I was thinking about this and thought that an alternative (perhaps longer term) would perhaps be to build on @hiker's kernel extraction. That way we would also have suitably-scaled input data for the kernel to use in the test.

**Comment by rupertford** [comment]
That's a good thought, particularly if we get effort to look at automating at the algorithm level as well, as it would potentially allow us to set up multi-kernel, or whole algorithm file tests. It may be that we need to run through the algorithm layer to get the context in which kernels are called in this project but for the moment I suggest we work on the assumption that we can take a TL kernel as input and produce an AD version. We can always throw away the script in the future, it is just something that we can use to demonstrate and test functionality. Does that sound reasonable @arporter?

**Comment by rupertford** [comment]
TITAN : Tangent lInear To AdjoiNt ?

**Comment by arporter** [comment]
I hate to be pedantic (OK, that's a lie) but we're taking the Adjoint of the Tangent Linear of LFRic.

**Comment by arporter** [comment]
Oh, I see what you mean - as in we're going *from* the TL *to* the Adjoint? Still, I think we want a PSy in there somewhere really...

**Comment by arporter** [comment]
> That's a good thought, particularly if we get effort to look at automating at the algorithm level as well, as it would potentially allow us to set up multi-kernel, or whole algorithm file tests. It may be that we need to run through the algorithm layer to get the context in which kernels are called in this project but for the moment I suggest we work on the assumption that we can take a TL kernel as input and produce an AD version. We can always throw away the script in the future, it is just something that we can use to demonstrate and test functionality. Does that sound reasonable @arporter?

Yes, that sounds reasonable - it shouldn't be a big script.

**Comment by arporter** [comment]
PSyAN ? Logo will be really easy....

**Comment by rupertford** [comment]
Definitely up there. If we're going with the PSy theme then how about PSyDA - let's think big!

**Comment by rupertford** [comment]
Created branch [1231_psyda_script](https://github.com/stfc/PSyclone/tree/1231_psyda_script)
