### ISSUE TITLE
adjoint assignment transformation

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1232]
An initial tl2ad transformation should be written that works for a single line of Fortran code that performs an assignment to a field array. The simple ax+by builtin code is the proposed first example. This might be easiest to implement with simple rules (dealing with each linear term independently) but could be implemented by actually creating and transposing the code matrix. This could be discussed with the Met Office to decide what is best, or perhaps both solutions could be provided in the first instance so that they can be compared.

**Comment by rupertford** [comment]
sympy looks like it might be able to represent the matrices, perform the transpose and symbolically compute the result, but I'm not sure how we would link PSyIR nodes to sympy epressions.

**Comment by arporter** [comment]
Personally, I wouldn't bother with Sympy. To use the phrase du jour, it should be trivial.

**Comment by rupertford** [comment]
I thought that would have piqued your interest :-)

**Comment by rupertford** [comment]
My current thought is to implement a transformation that takes a single PSyIR assignment, checks that the assignment conforms to any restrictions and then transform that line in-place using the rules specified in the very helpful [ECMWF presentation](https://earth.esa.int/documents/973910/2642313/AB2b.pdf). I think I will add the idea of a list of active variables as well as I don't think it would be possible to determine what to do otherwise e.g. `A(i) = B(i)*C(i)` could be valid if `B` or `C` are not active, but we need to know which is which.

**Comment by rupertford** [comment]
Created branch [1232_assignment_tl2ad_trans](https://github.com/stfc/PSyclone/tree/1232_assignment_tl2ad_trans)
