### ISSUE TITLE
make node.view() return a string

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1238]
At the moment `node.view()` prints directly to `stdout`. It would be nicer if it returned a string which could then be output as required. This has come up as I've been using logging in our adjoint script and capturing the output from `view()` in order to log it is a pain.

Does anyone think this is a bad idea? It will obviously affect any scripts that use view().

**Comment by arporter** [comment]
I'd been wondering about adding an optional file handle as argument but getting it to return a string covers that use case. While you're at it, please could you add an optional argument to disable colouring of the output? (Needed for #1220).

**Comment by rupertford** [comment]
Thanks Andy, will do. Any more thoughts/suggestions @TeranIvy, @sergisiso, @hiker?

**Comment by sergisiso** [comment]
Just that it would be good to change `node.symbol_table.view()` in the same way to make them similar to use.

**Comment by hiker** [comment]
Totally agree!

**Comment by rupertford** [comment]
Created branch [1528_modify_view](https://github.com/stfc/PSyclone/tree/1528_modify_view). This branch will address both this issue and #1528.
