### ISSUE TITLE
[psyir] fparser2 frontend currently ignores implicit statements

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1254]
To date we have always (implicitly) assumed that the Fortran we are dealing with is using `implicit none`. The fparser2 psyir frontend needs extending to check that this is the case and to abort if not.

**Comment by sergisiso** [comment]
We ignore more than the "implicit none", we ignore the whole implicit-part-stmt:

```
R506 implicit-part-stmt is implicit-stmt
                          or parameter-stmt
                          or format-stmt
                          or entry-stmt
```
for instance from:
```
program test
    real :: para
    parameter (para=2.3)

    write(*,*)  para
end program test
```
we wrongly get:
```
program test
  real :: para

  WRITE(*, *) para
end program test
```
after psycloning

**Comment by sergisiso** [comment]
Note that parameter-stmt also appears in:
```
R508 specification-construct is derived-type-def
    or enum-def
    or generic-stmt
    or interface-block
    or parameter-stmt 
    or procedure-declaration-stmt
    or other-specification-stmt
    or type-declaration-stmt
```
@arporter @rupertford maybe the issue here is that fparser gets it wrong by not being context-aware and doing the implicit-part-stmt first? Although I don't know the difference between a specification parameter-stmt and a implicit-part parameter-stmt

**Comment by arporter** [comment]
You are right @sergisiso, I've realised that we end up with an `Include_Stmt` *as a child of* `Implicit_Part` in the parse tree and that's not right. I'm not quite sure what `Implicit_Part` is supposed to match but I wouldn't have expected it to include things like `parameter` and `include`. I was going to open a new fparser issue for this.

**Comment by sergisiso** [comment]
Anyway, I added support for `parameter (val=1)` expressions in a WIP branch because it is needed for CROCO, I will do a separate issue/PR for it. We can move this later if its provided by the specification part instead.
