### ISSUE TITLE
[PSyIR] Give RoutineSymbol a datatype

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1259]
In #1255 I added code to capture Fortran `interface` definitions as `DataSymbol`s of `UnknownFortranType`. However, such `interface` blocks are actually defining (the interface to) a Routine and therefore should really be `RoutineSymbol`s of `UnknownFortranType`. Since Fortran functions (and all C routines) have return types, it is a natural extension to give the `RoutineSymbol` a `datatype` property. For Fortran subroutines this would be `None`.

**Comment by arporter** [comment]
Currently both `RoutineSymbol` and `DataSymbol` sub-class `Symbol` with `DataSymbol` adding various properties related to type (e.g. `datatype`, `is_scalar` etc.). Rather than duplicate this functionality in `RoutineSymbol` it seems sensible to introduce another base class, `TypedSymbol` that has these properties and is then sub-classed by `RoutineSymbol` and `DataSymbol`. Does that make sense to @rupertford and @sergisiso?

**Comment by rupertford** [comment]
Sorry if I am a bit slow but I'm struggling a bit here. Shouldn't the datatype of the return value of a Routine be associated with the Routine node, rather than a RoutineSymbol? In my mind a RoutineSymbol is simply a way of getting to the appropriate Routine.

**Comment by arporter** [comment]
You may be right but perhaps I should go back to the problem that I'm trying to solve: there is information about routines that must be captured from a specification part (in Fortran) that may not exist anywhere else. The main problem I have is interface blocks - essentially, these define a mapping from a single routine name (which has no corresponding implementation and thus no Routine node) to various different implementations of that routine (that do have implementations). At the moment we have no way of capturing this and ideally we wouldn't put explicit support for this into the PSyIR as I have no idea how we'd make it language independent.

**Comment by sergisiso** [comment]
Note that we also have `TypeSymbol` which also has `datatype` and the name is very close to the proposed `TypedSymbol`. In fact, maybe we can consider all Symbols to be typed and move the `datatype` attribute to the base `Symbol` class?

At the moment, the only generic Symbols (without datatype) are essentially because we don't know what it is. But these could default to  DeferedType or UnknwonType and get rid of untyped symbols. I believe this will make things easier and with less corner cases.

> For Fortran subroutines this would be None.

Or a new NoType/EmptyType/VoidType equivalent to the C 'void'?

**Comment by arporter** [comment]
> At the moment, the only generic Symbols (without datatype) are essentially because we don't know what it is. But these could 
> default to DeferedType or UnknwonType and get rid of untyped symbols. I believe this will make things easier and with less corner 
> cases.
I like that suggestion. I'll take a look.

**Comment by arporter** [comment]
What about `ContainerSymbol` - I don't think it should have a type?

**Comment by arporter** [comment]
Currently we have `ContainerSymbol`, `RoutineSymbol`, `DataSymbol` and `TypeSymbol` (https://psyclone-ref.readthedocs.io/en/latest/_static/html/classpsyclone_1_1psyir_1_1symbols_1_1symbol_1_1Symbol.html). Of these all except `ContainerSymbol` could have a type (`RoutineSymbol` currently does not). We could therefore introduce a new sub-class:

                              /--DataSymbol
             /--TypedSymbol--/--RoutineSymbol
    Symbol--/                \--TypeSymbol
             \
              \----ContainerSymbol

Although, as Sergi points out, we then have a `TypedSymbol` and a `TypeSymbol` which is not good. We could rename `TypeSymbol` to `StructureTypeSymbol` perhaps?

**Comment by sergisiso** [comment]
You are right ContainerSymbol does not have a type. I few questions that come to my mind:

- Do the RoutineSymbols that have no return type are typed? I am asking to see if we can solve both problems with the same solution (Typed hierarchy or new NoType datatype), or we really need both solutions.

- Are TypeSymbol really typed? I mean we have "datatypes" properties in both but doesn't sound exactly the same thing. TypeSymbols are an alias to a datatype while DataSymbols has a representation provided by a datatype.

- ">We could rename TypeSymbol to StructureTypeSymbol perhaps." What about `DataTypeSymbol`?

Interesting problem :)

**Comment by arporter** [comment]
Strictly speaking, Fortran subroutines have no type (if that's what you mean by your first question), however Fortran functions have a type as do all C routines. @rupertford has expressed reservations about giving RoutineSymbols a type but I think it will be useful in determining the type of the result of an expression.

As you say, a TypeSymbol is basically a name given to a StructureType so the fact that we use the `datatype` property is rather stretching the concept. Ultimately, if we really do want to add support for things like type-bound procedures (as Rupert mentioned the other day), then I think TypeSymbol is heading towards holding the name of a class and `datatype` is even less suitable.

So, possibly a `TypeSymbol` should just subclass `Symbol` and be renamed to err, something better :-) That potentially leaves us with both `RoutineSymbol` and `DataSymbol` having a datatype. I feel a design discussion coming on...

**Comment by arporter** [comment]
Bringing those suggestions together, I think we're talking about a hierarchy that looks like:

                              /--DataSymbol
             /--TypedSymbol--/--RoutineSymbol
    Symbol--/ 
            \----ContainerSymbol
            |
            \----DataTypeSymbol

so that `RoutineSymbol` has a type (which, for Fortran Subroutines would be None or NoneType or somesuch). I think that's simpler than having an entirely separate class for a RoutineSymbol without a type.

**Comment by rupertford** [comment]
The proposal looks good to me. I'm happy with `None` being a valid return value for `RoutineSymbol`.

**Comment by arporter** [comment]
I've realised that, in addition to whether a symbol has a type, there's the question of its interface and the mechanism to look up its type if it is deferred. Currently, only the DataSymbol has this functionality but it certainly applies to routines (e.g. Fortran functions) as well as to DataTypeSymbols. Basically, any symbol that can have a deferred type should probably have the mechanism to look up its actual type.

**Comment by arporter** [comment]
Although a ContainerSymbol has an interface (e.g. in Python, a module can be made available from another module), it does not have a type and therefore I don't think it needs the `resolve_deferred` method of a TypedSymbol. The fly in the ointment is then DataTypeSymbol which represents some structure type - it does make sense to have a mechanism to resolve the details of the type it represents. However, we've already agreed that the 'datatype' of a DataTypeSymbol is not the same concept as the 'datatype' of a TypedSymbol. Perhaps we need a Mixin class to share the resolution mechanism between these classes?

**Comment by arporter** [comment]
(I should add that currently DataTypeSymbol has no mechanism to resolve deferred types.)

**Comment by arporter** [comment]
RoutineSymbols do have a type now and Rupert is adding support for ensuring that it is set correctly. Therefore I'm closing this issue.
