### ISSUE TITLE
Test failure in gocean1p0_config_test.py

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1272]
If I run only this one test, I get parsing errors:
```
gocean1p0_config_test.py:359: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../configuration.py:380: in load
    self._api_conf[api] = GOceanConfig(self, self._config[api])
../configuration.py:1092: in __init__
    GOLoop.add_bounds(it_space)
../gocean1p0.py:712: in add_bounds
    six.raise_from(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = None, from_value = NoMatchError("Nonlabel_Do_Stmt: 'do i=1, 1'")

>   ???
E   psyclone.configuration.ConfigurationError: "PSyclone configuration error: Expression '1' is not a valid do loop boundary. Error message: 'Nonlabel_Do_Stmt: 'do i=1, 1''."

<string>:3: ConfigurationError
```
I can avoid this if I run certain other tests before the config test, e.g. gocean0p1_test, dependency_test, alggen_test, but not all (e.g. running f2pygen_test first does not avoid the problem).

At this stage it appears that the failure is triggered by the class ``Base`` in fparser.two.utils.py. Around line 370:
```
       elif result is None:
            # Loop over the possible sub-classes of this class and
            # check for matches
            print("Looping", Base, cls.__name__)
            for subcls in Base.subclasses.get(cls.__name__, []):
                print("Looping", subcls)
                if subcls in parent_cls:  # avoid recursion 2.
                    continue
                try:
                    obj = subcls(string, parent_cls=parent_cls)
                except NoMatchError:
                    obj = None
                if obj is not None:
                    return obj
```
In the failure case, it appears that there are no subclasses, the loop does not go into Equiv_Operand, Or_Operand, And_Operand, ...

**Comment by hiker** [comment]
In case of the failing test, ``Base.subclasses.get(cls.__name__, [])`` is empty, when it succeeds, it is ``[<class 'fparser.two.Fortran2003.Level_5_Expr'>]``. That explains why it doesn't go down the level5, equiv, or, and, ... chain

**Comment by hiker** [comment]
I've confirmed the failure on a second system.

After some debugging the reason appears to be that when I only start the `gocean1p0_config_Test`, the fparser is not initialised. Adding ``ParserFactory().create(std="f2003")`` as first line in the failing test fixes this issue.

**Comment by hiker** [comment]
To keep track of this discussion: @arporter commented on teams:

> To answer your question on the PR Joerg Henrichs I would just add a use fixtures to the offending test. We could keep the Issue itself and look to introduce the autouse setting to replace all the individual use fixtures.

After having yet another look, I have to disagree with both my original solution, and this suggestion. Reason is that if you use a config file with a custom gocean iteration space, both ``psyclone`` and ``genkernstub`` crash, because the config file in each case is read before the parser is initialised. While I agree that custom iteration spaces are rare, we need to support it. So I replaced this fix by making sure fparser is properly initialised before the `Nonlabel_Do_Stmt` is used.

**Comment by arporter** [comment]
Can this be closed now @hiker?

**Comment by arporter** [comment]
I can run the tests on gocean1p0_config_test.py without problems. Closing this issue.
