### ISSUE TITLE
Generate the current code for a DSL-level PSyIR tree without losing the DSL information

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1274]
Currently the lowering modifies the PSyIR tree in-place. This is because it was much easier to implement and before we didn't have the "copy()" operator. In theory it should be fine as lowering happens after all domain level transformations have been applied. But in practice, specifically when developing/debuging a script one may want to produce the output code at each step without losing the domain information because it has to continue applying transformations?

```
PSY = PSyFactory(API, distributed_memory=False).create(INVOKEINFO)
print(PSY.gen)
# Apply transformation 1
...
print(PSY.gen)
# Apply transformation 2
...
print(PSY.gen)
```

The script above currently would fail if any transformations require domain information (which is often the case). And worse, adding/removing the print could change the behaviour because there is an implicit lowering step when generating code that changes the tree.

So now that we have "copy" operators in most nodes maybe we can explore if it's feasible for the lowering to create a new tree.

**Comment by sergisiso** [comment]
Also several lowering methods currently use the "replace_with()" to do the in-tree modification. This adds the strange requirement that a disconnected node (with no parent) may not be able to be lowered because the replace_with will fail.

If the lowering method would return a new tree this would not be a problem.

**Comment by sergisiso** [comment]
Instead of changing the lowering implementation (which is hard for several reasons) I realized that I should update the
`print(psy.gen)`
in user scripts/tests to
`print(fortran_writer(psy.container))`
because after all we need to specify what language we want the output for language-independent PSyIR.

This already solves the problem I had because I can make `fortran_writer` to not change the contents of psy.container (the copy or a lower_to_language_level will be executed internally if needed which is nice because it means a script user doesn't need to know of their existence). And after the print statement it continues with a tree consistent with what the user was seeing before, which is much more unsurprising behaviour.

**Comment by rupertford** [comment]
I like the ability to choose the backend and the simplification of no lowering! A couple of comments/questions 1) Don't you still have the same problem from within fortran_writer i.e. having to ensure lower_to_language_level creates a new tree, otherwise you will change psy.container? 2) Might the script writer potentially want to apply transformations at the language level after lowering?

**Comment by sergisiso** [comment]
> 1) Don't you still have the same problem from within fortran_writer i.e. having to ensure lower_to_language_level creates a new tree, otherwise you will change psy.container?

I have the same problem but is a much easier solution because it has a single entry (the backend functor method), that now does: make a copy -> lower the copy -> recursively visit the lowered copy.
Changing the lowering to create a new tree looks more difficult because I would have to update all lower_to_language_level and mix the complexity of creating new nodes/copies with the already complex lowering implementations.

> 2) Might the script writer potentially want to apply transformations at the language level after lowering?

lower_to_language_level is still a public method that can be called at anytime (e.g. during the script) and will still make the modification in-place (similar to a transformation), so it still can be done. In the future I like the alternative of 2 script functions but I am still not dealing with the generator.py structure.
