### ISSUE TITLE
Use algorithm precision/types when generating PSy-layer

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1277]
In #1262 the precision/datatype information for variables in the algorithm layer was captured. This information needs to be used when generating PSy-layer arguments. At the moment the datatypes are hard coded.

**Comment by rupertford** [comment]
OK, now that #1261 is on master we are ready to start work on this issue.

Created branch [1277_lfric_mixed_precision](https://github.com/stfc/PSyclone/tree/1277_lfric_mixed_precision)

**Comment by TeranIvy** [comment]
This was closed by #1349.
