### ISSUE TITLE
Warnings from Sphinx autoapi when building reference guide

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1280]
While doing #1194 it was found that adding an `__all__` for `TransformationError` to `psyclone/psyir/transformations/transformation_error.py` caused over 130 'more than one target for cross-reference' warnings:

    Projects/PSyclone/src/psyclone/transformations.py:docstring of psyclone.transformations.KernelGlobalsToArguments.validate:: WARNING: more than one target found for cross-reference 'TransformationError': psyclone.psyir.transformations.TransformationError, psyclone.psyir.transformations.transformation_error.TransformationError

Without that `__all__` we do not get detailed documentation generated for the `TransformationError` class. This problem has been raised on the sphinx mailing list: https://groups.google.com/g/sphinx-users/c/vuW6OOb96Yo

We also get errors about duplicate documentation of classes that are themselves defined within other classes (such as psyclone.domain.lfric.kern_call_arg_list.NdfInfo).

**Comment by arporter** [comment]
The current warnings are:

 * PSyclone/src/psyclone/domain/lfric/kern_call_arg_list.py:docstring of psyclone.domain.lfric.kern_call_arg_list.NdfInfo:1: WARNING: duplicate object description of psyclone.domain.lfric.kern_call_arg_list.NdfInfo, other instance in autogenerated/psyclone.domain.lfric.kern_call_arg_list, use :noindex: for one of them
 * PSyclone/src/psyclone/domain/lfric/kern_call_arg_list.py:docstring of psyclone.domain.lfric.kern_call_arg_list.NdfInfo:1: WARNING: duplicate object description of psyclone.domain.lfric.kern_call_arg_list.NdfInfo, other instance in autogenerated/psyclone.domain.lfric, use :noindex: for one of them
 * PSyclone/src/psyclone/psyad/main.py:docstring of psyclone.psyad.main.main:1: WARNING: duplicate object description of psyclone.psyad.main, other instance in autogenerated/psyclone.psyad.main, use :noindex: for one of them
 * PSyclone/src/psyclone/psyad/main.py:docstring of psyclone.psyad.main:1: WARNING: duplicate object description of psyclone.psyad.main, other instance in autogenerated/psyclone.psyad, use :noindex: for one of them
 * PSyclone/src/psyclone/psyir/nodes/operation.py:docstring of psyclone.psyir.nodes.operation.Operator:1: WARNING: duplicate object description of psyclone.psyir.nodes.operation.Operator, other instance in autogenerated/psyclone.psyir.nodes.operation, use :noindex: for one of them
 * PSyclone/src/psyclone/psyir/nodes/operation.py:docstring of psyclone.psyir.nodes.operation.Operator:1: WARNING: duplicate object description of psyclone.psyir.nodes.operation.Operator, other instance in autogenerated/psyclone.psyir.nodes, use :noindex: for one of them
 * PSyclone/src/psyclone/psyir/symbols/datatypes.py:docstring of psyclone.psyir.symbols.datatypes.ComponentType:1: WARNING: duplicate object description of psyclone.psyir.symbols.datatypes.ComponentType, other instance in autogenerated/psyclone.psyir.symbols.datatypes, use :noindex: for one of them

In theory one can add a handler that enables documentation of certain things to be skipped by adding the following:

    def skip_util_classes(app, what, name, obj, skip, options):
        if what == "class" and "ComponentType" in name:
            skip = True
        return skip

    def setup(app):
        app.connect('autoapi-skip-member', skip_util_classes)

to the `conf.py`. However, when I do that I get an error saying that event autoapi-skip-member is unrecognised.

**Comment by arporter** [comment]
The __all__ list in __init__.py is only there to specify what from my.package import * actually imports (see https://docs.python.org/3/tutorial/modules.html). Given that that usage is frowned upon (and we don't employ it), the __all__ in __init__.py is only used by autoapi. Since this then causes errors/warnings about multiply-defined symbols I would suggest we stop adding __all__ to the __init__.py files. What do @sergisiso and @rupertford think?

**Comment by sergisiso** [comment]
But will individual member still be importable from a single module?
e.g. `from psyclone.psyir.nodes import Literal, Reference, Loop`
If that's the case, I see no issues in not adding (or removing) init's alls fields

**Comment by arporter** [comment]
Yes, I believe this won't affect that usage.

**Comment by sergisiso** [comment]
When searching for a solution to some of the refguide warnings, e.g. nametuples, what I find is the same that @arporter proposed above, e.g.:
```
import collections
def remove_namedtuple_attrib_docstring(app, what, name, obj, skip, options):
    if type(obj) is collections._tuplegetter:
        return True
    return skip

def setup(app):
    app.connect('autodoc-skip-member', remove_namedtuple_attrib_docstring)
```

Maybe "autodoc-skip-member" was not properly supported 3 years ago when you last attempted it @arporter but is worth another try?

**Comment by arporter** [comment]
> Maybe "autodoc-skip-member" was not properly supported 3 years ago when you last attempted it @arporter but is worth another try?

Yes, it's probably worth another go now. I'll take a look.

**Comment by arporter** [comment]
Thanks for that updated code Sergi. I can confirm it works but I'm not yet sure whether we can use it to avoid the 'duplicate object description' warnings. The best solution to that still appears to be to make sure we don't have a given object appear in more than one `__all__` list which in turn means that we have to remove those lists from the `__init__.py` files of the various modules.

**Comment by arporter** [comment]
I realised that although I'd updated my version of Sphinx, I hadn't done the same for `sphinx-autoapi`. I've done that now. It seems that if I convert the `namedtuple` instances into `dataclass` then all of the warnings disappear :-)

**Comment by arporter** [comment]
We still had problems with TYPE_MAP_TO_PYTHON (which is just a dict). I've moved that into the ScalarType class for now and that has solved all the warnings. I'm not sure it lives in ScalarType but that is where the `Intrinsic` enum is defined so it sort of fits.

**Comment by arporter** [comment]
It may be that we can configure the handler to exclude 'thing' if the `name` argument ends in 'thing'. (`name` is the fully-qualified name of the object). This would require that we rigidly conform to a naming convention which I don't think we do presently.
