### ISSUE TITLE
Comparing Signatures under python 2

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1283]
In #1253 I've re-written things to use Signatures and it has simplified the code. However, when run under Python 2 I get test failures.
I've discovered that if I add the following test to tests/core/signature_test.py:

    def test_signature_comparison():
        ''' Test that two Signatures can be compared for equality. '''
        assert Signature(("a", "b")) == Signature(("a", "b"))
        assert not Signature(("a", "b")) != Signature(("a", "b"))
        assert Signature(("a", "b")) != Signature(("a", "c"))
        assert not Signature(("a", "b")) == Signature(("a", "c"))

then it passes under Python 3 but not under Python 2 (the comparison always yields True in this case).

The first question is, have I understood correctly and therefore this test should pass?
If I have misunderstood and Signatures aren't supposed to allow this kind of comparison, could we extend them so that they can?

**Comment by hiker** [comment]
There is a `__eq__` function, but not much else. I assume we would also need a `__ne__` or so. But I agree, this should indeed work, thanks. I don't have python2 on my laptop, so I usually only rely on CI to do that, and ... obviously, there's no test for that.

**Comment by arporter** [comment]
#1290 has been merged and fixes this issue.
