### ISSUE TITLE
Build of UG fails with missing "tgtermes.sty" after updating Sphinx

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1285]
I recently updated my pip-installed version of Sphinx in order to try and fix some warnings. However, after having done that I was no longer able to build the 'pdflatex' target of the userguide - I got an error saying "tgtermes.sty" could not be found. To fix this I had to do `apt-get install tex-gyre`.

Please could @hiker check that this is consistent with his instructions for a minimal installation in the dev guide? If it is then I'll add it there.

**Comment by arporter** [comment]
BTW, I now have:

    Sphinx                        4.0.2     
    sphinx-rtd-theme              0.5.2     
    sphinxcontrib-applehelp       1.0.2     
    sphinxcontrib-bibtex          2.3.0     
    sphinxcontrib-devhelp         1.0.2     
    sphinxcontrib-htmlhelp        2.0.0     
    sphinxcontrib-jsmath          1.0.1     
    sphinxcontrib-qthelp          1.0.3     
    sphinxcontrib-serializinghtml 1.1.5

**Comment by hiker** [comment]
I can confirm that this happens, and that installing tex-gyre fixes it. I need to find an OpenSuse installation where I can test the behaviour (and solution) on OpenSuse. Hopefully I can do that tomorrow.

If you fix this, could you also do #1179 (should be simple adding make allclean to rm -r some directories) and #1178 (add auto-api to the list of packages)? That all seems to be closely related.

**Comment by hiker** [comment]
@arporter  I had a look at my old OpenSuse module. I couldn't update python2 p sphinx4 (I only got up to 1.8.5), but I could update all the packages to the versions you listed. I did not have to install any additional latex theme at all, tgterms.sty wass already installed, so no additional change for OpenSuse is required. It seems to be only required for ubuntu then.
