### ISSUE TITLE
[PSyData] Kernel extraction: create the driver using PSyIR

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1288]
Atmn the old-style Fortran code creation is used, since at the time PSyIR wasn't able to create modules. This should be possible now, so the following points should be implemented:
- [x] Use PSyIR to create the driver.
- [x] Find a better solution for name clashes (e.g. a property `field%whole%dx` will atm use dx as local name, which will clash with a name 'dx' used by the user. Options: use `field_whole_dx` instead of just dx.
    - Advantage: better name anyway, and it would work if we have fields with different grids at some time the features.
    - Disadvantage: we might write the required grid data several times if we have `a%whole%dx`, then `b_whole_dx` in a second kernel etc. When I tried originally, I had problems avoiding a name clash with a user variable `field_whole_dx`. This might be better once we moved to PSyIR and a symbol table(?). 
- [ ] Alternatively, we could use a simple structure that mirrors the dl_esm_inf field type (but is declared in the driver, so no external dependency). This would make the code creation easier (no need to change the config file information that creates properties).
- [ ] See if the code that creates unique NetCDF names can be improved to avoid name clashes: atm an output variable `a` and an input variable `a_post` will create a clash (both using the name `a_post` as name in the NetCDF file). Hopefully, we can avoid handling this case by using a character as a separator that is not a valid Fortran name, e.g. 'a$post' or so for the NetCDF name, and use the symbol table to create unique names as local variable names
- [x] Create code that compares the result (which is kind of a duplicate of #647 and #298)

**Comment by arporter** [comment]
#1379 is on master now. However, presumably this needs to remain open for LFRic and the other things listed in the Issue description?

**Comment by hiker** [comment]
LFRic is handled in #1392, the potential name clash in the new ticket #1408, and the only other point was just an optional alternative implementation, which as it turns out was not required when using PSyData at all. So I am closing this ticket now.
