### ISSUE TITLE
Coding style for filenames

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1289]
I think we need to have a look at our file name usage for our coding standard. I really don't like some of our long file names that are hard to read ... I can't be the only one reading 'datatypesymbol.py ' as  'datatypes-ymbol.py ', only then to backtrack and read it properly. I find this nearly impossible to parse (need fparer two in my brain)  :)

In general most of our file names follow the camel-case class name: for all capital letters in the name, we add a _ and use lower case. E.g.: `KernCallAccArgList` --> `kern_call_acc_arg_list.py`. I find this much easier to read, and much easier to find a file. It avoids these very German names ... words that just don't end :) 

Looking at the file names ... I guess I was responsible for a lot of the "_" names :blush: So I only label this as a question for now, and see if we can agree on this.

**Comment by arporter** [comment]
I believe our coding standard (or maybe pep) already specifies that we should use underscores, it's just that we're not consistent. I'm happy to work towards being consistent!

**Comment by hiker** [comment]
Gee, you are right. I could have sworn that I searched for that a while ago (this has been nagging at me in the background for some time), and didn't find it myself *sigh*. OK, I am closing this issue, and will try to rename files now and again. Sorry for this noise.
