### ISSUE TITLE
Meta data for non-pointwise GH_INC

### ISSUE THREAD

**Issue by thomasmelvin** [stfc/PSyclone#1292]
Development of https://code.metoffice.gov.uk/trac/lfric/ticket/2643 (in https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/mohamedzerroukat/r28908_positive_flux) has highlighted a new use pattern in a kernel on a W2 field: https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/mohamedzerroukat/r28908_positive_flux/gungho/source/kernel/impose_min_fluxes_kernel_mod.F90 where the code produces incorrect answers for parallel runs. Further investigations show that an extra halo update of the GH_INC field needs to be performed before the kernel is called.

I believe what is happening is that for GH_INC field psyclone assumes that the field (F) is treated in a kernel as:
F(df) = G(df) + R 
Where in particular G does not depend upon F, i.e. F is incremented pointwise and so no halo update of F is performed the kernel call, the kernel maintains the halo (dirty/clean) status

While I think impose_min_fluxes_kernel does something different
F(df) = G(F(:))
Where G now depends upon all values of F in a cell.  

Assuming we have only 2 dofs F = [Fl, Fr] and Fl is a halo dof and so is incorrect (as there was no halo update before) but Fr is an owned dof so is correct, then the kernel code is effectively computing:

Fl = Gl(Fl, Fr) 
Fr = Gr(Fl, Fr)
With Gl & Gr some functions of their arguments

Ie. Fl and Fr now depend upon Fl and Fr, but since Fl is incorrect going into the kernel, Fl & Fr are then incorrect coming out and since Fr is an owned dof it won’t be corrected by any subsequent halo update

I think the solution is to have a new metadata type for this kind of use to state that the GH_INC is non-pointwise, maybe GH_INC_ALL??

**Comment by thomasmelvin** [comment]
Code that calls the kernel: https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/mohamedzerroukat/r28908_positive_flux/gungho/source/algorithm/advection/transport_general_mod.x90

**Comment by TeranIvy** [comment]
Quote from @thomasmelvin:

_By pointwise increment I mean what what all the current kernels do, i.e._

Do k = 0,nlayers -1
  ! compute something G that might depend upon various fields, but not F
  Do df = 1, ndf_w2
    F(map_w2(df)+k) = F(map_w2(df+k)) + G
  End do
End do

_So that each dof of F only depends upon itself and other fields and the halo parity (clean/dirty) is maintained_
_Whilst this kernel does something akin to_

Do k = 0,nlayers -1
  ! compute something G that depends upon  F, e.g
  G = 0.0
 Do df = 1, ndf_w2
    G = G + F(map_w2(df+k))
  End do 
  Do df = 1, ndf_w2
    F(map_w2(df)+k) = F(map_w2(df+k)) + G
  End do
End do

_So now, e.g F(map_w2(1)+k) depends upon F(map_w2(1:6) + k) and so the halo parity is not maintained. i.e if F(map_w2(1)+k) is a dirty halo value then this will infect all other values of F in that cell (F(map_w2(1:6)+k))_

**Comment by rupertford** [comment]
This example is GH_READ followed by GH_INC is it not?. If we could treat it as that in the internal logic then we would get the required HEx before the kernel (due to the GH_READ). I agree it is a case we don't currently cater for so again agree we need to find a way of capturing this case in metadata. Personally I would prefer a concatenation of `GH_READ` and `GH_INC` to `GH_READ_INC`. Once we agree on an appropriate name, I'm happy to take this on.

**Comment by thomasmelvin** [comment]
That sounds correct, i'm happy with some concatenation, maybe `GH_READINC`  in a similar fashion to `GH_READWRITE`?

**Comment by rupertford** [comment]
It has been agreed to use `GH_READINC` as the new name. I expect support will be done in 2 steps, but it may turn out to be simpler to do in one.

- [ ] Add support for reading the new metadata
- [ ] Add support for processing the new metadata

**Comment by rupertford** [comment]
Created branch [1292_gh_readinc_metadata](https://github.com/stfc/PSyclone/tree/1292_gh_readinc_metadata)
