### ISSUE TITLE
PR 1264 re-introduces #1171

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1295]
PR 1264 changes the following line in `psyir.py`:
```
 MODULES = [
-    Module("constants_mod", ["i_def", "r_def", "l_def"])]
+    Module(LFRicConstants().UTILITIES_MOD_MAP["constants"]["module"],
+           ["i_def", "r_def", "l_def"])]

```
in dfc27653ff6c312a38ae2946781686a280d5ae4b. This causes the `LFRicConstants` object to be executed on import, causing the failures from #1171 again.

You can trigger this bug by executing:
```
~/work/psyclone/src/psyclone/tests$ pytest ./dependency_test.py 
____________________________________________________________ ERROR collecting src/psyclone/tests/dependency_test.py ____________________________________________________________
dependency_test.py:48: in <module>
    from psyclone.domain.lfric import KernCallAccArgList, KernStubArgList
../domain/lfric/__init__.py:52: in <module>
    from psyclone.domain.lfric.kernel_interface import KernelInterface
../domain/lfric/kernel_interface.py:44: in <module>
    from psyclone.domain.lfric import psyir as lfric_psyir
../domain/lfric/psyir.py:58: in <module>
    Module(LFRicConstants().UTILITIES_MOD_MAP["constants"]["module"],

```

**Comment by arporter** [comment]
I can't reproduce this @hiker. Is it still a problem for you?

**Comment by hiker** [comment]
Yes, I can't run all/some tests if I don't set PSYCLONE_CONFIG (note that I have a `pip -e` installation, which I believe is slightly different from a normal installation):
```
joerg@Joerg-Surface:~/work/psyclone/src/psyclone/tests$ pytest
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.8.10, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/joerg/work/psyclone, configfile: setup.cfg
plugins: forked-1.3.0, xdist-2.3.0, cov-2.11.1, anyio-3.5.0
collected 2131 items / 83 errors / 2048 selected                                                                                                                                 

===================================================================================== ERRORS =====================================================================================
_______________________________________________________________ ERROR collecting src/psyclone/tests/config_test.py _______________________________________________________________
config_test.py:54: in <module>
    from psyclone.domain.lfric import LFRicConstants
../domain/lfric/__init__.py:52: in <module>
    from psyclone.domain.lfric.kernel_interface import KernelInterface
../domain/lfric/kernel_interface.py:44: in <module>
    from psyclone.domain.lfric import psyir as lfric_psyir
../domain/lfric/psyir.py:58: in <module>
    Module(LFRicConstants().UTILITIES_MOD_MAP["constants"]["module"],
../domain/lfric/lfric_constants.py:66: in __init__
    api_config = Config.get().api_conf("dynamo0.3")
../configuration.py:139: in get
    Config._instance.load()
../configuration.py:233: in load
    self._config_file = Config.find_file()
../configuration.py:458: in find_file
    raise ConfigurationError("{0} not found in any of {1}".
E   psyclone.configuration.ConfigurationError: PSyclone configuration error: psyclone.cfg not found in any of ['/home/joerg/work/psyclone/src/psyclone/tests/.psyclone', '/home/joerg/.local/share/psyclone', '/usr/share/psyclone']
_____________________________________________________________ ERROR collecting src/psyclone/tests/dependency_test.py _____________________________________________________________
```
domain/lfric/psyir.py contains:
```
MODULES = [
    Module(LFRicConstants().UTILITIES_MOD_MAP["constants"]["module"],
           ["i_def", "r_def", "l_def"])]
```
I.e. this gets executed when you import psyir.py (note that there are three psyir.py files, make sure to check the right one :) ).

I believe if all this would be wrapper in a class (which would be instantiated/initialised after the import), the config file would be initialised properly and it would work.

**Comment by arporter** [comment]
I think we document somewhere that you have to install before you can run the tests. We also document the fact that doing a `-e` install does not install the config file which I agree is a pain. I'm fairly comfortable with these limitations given that only a developer is likely to be doing the `-e` installation.

What I'm less comfortable with is the fact that we can't build the documentation unless PSyclone is installed and the config file discoverable. This is causing us problems on readthedocs where I'm having trouble (#1538) working out where the config file is ending up. If I could reliably work that out then I could probably set PSYCLONE_CONFIG and all would be well (for now).

Having written that, I think I've convinced myself that the work that you suggest is worth doing to fix this :-)

**Comment by hiker** [comment]
:)  FWIW, we have added a fixture to set PSYCLONE_CONFIG, so it works reliably. It's just that using the config before (i.e. if it gets executed during an import), this is before PSYCLONE_CONFIG is set. The reason we have this fixture is that our tests always work the same, even if someone should have a different psyclone.cfg file installed (e.g. in the met office, who patches their installed config file :) )

**Comment by hiker** [comment]
I just remembered ... while testing something else ... can't remember the details now, there was a function that pytests calls very early. Maybe we can set PSYCLONE_CONFIG there?

**Comment by hiker** [comment]
```
~/work/psyclone/src/psyclone/tests$ git diff conftest.py
diff --git a/src/psyclone/tests/conftest.py b/src/psyclone/tests/conftest.py
index e54d7deec..5155b1221 100644
--- a/src/psyclone/tests/conftest.py
+++ b/src/psyclone/tests/conftest.py
@@ -51,6 +51,10 @@ from psyclone.tests.gocean1p0_build import GOcean1p0Build
 from psyclone.tests.lfric_build import LFRicBuild
 from psyclone.tests.utilities import Compile
 
+def pytest_configure(config):
+    config_file = Config.get_repository_config_file()
+    os.environ["PSYCLONE_CONFIG"] = config_file
+
 
 # fixtures defined here are available to all tests
 @pytest.fixture(scope="module", params=[False, True])
```
That works for me. I don't know about RTD. Can we add something similar to the setup there?

**Comment by hiker** [comment]
According to https://stackoverflow.com/questions/70944148/is-there-a-way-to-have-sphinx-call-a-script-or-executable-as-a-pre-build-task you can just add the above code to conf.py. 

For me locally (in a setting where I would usually get an error):
```
~/work/psyclone/doc/developer_guide$ git diff conf.py
diff --git a/doc/developer_guide/conf.py b/doc/developer_guide/conf.py
index f260346ba..e1275cf25 100644
--- a/doc/developer_guide/conf.py
+++ b/doc/developer_guide/conf.py
@@ -31,6 +31,10 @@ sys.path.insert(0, os.path.abspath('.'))
 docs_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
 sys.path.insert(0, os.path.join(docs_dir, "_ext"))
 
+from psyclone.configuration import Config
+config_file = Config.get_repository_config_file()
+os.environ["PSYCLONE_CONFIG"] = config_file
+
 # -- General configuration ----------------------------------------------------
```
And that works for me. Though ... it is a work around for bad design 😆 :rofl:
