### ISSUE TITLE
ContainerSymbols should sometimes have a LocalInterface

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1298]
Currently ContainerSymbol gives by default a FortranModuleInterface to its interface values. This expects it to be an external container that can be imported when needed. However, we don't currently account for locally declared containers (I assume we just give them the wrong Interface and never use the import function)

Also the "_reference" attribute needs to be properly populated for Local ContainerSymbols so that it points to the definition.

**Comment by arporter** [comment]
Hi @sergisiso, is this fixed now that you've updated the way interfaces are handled?

**Comment by sergisiso** [comment]
Yes. Closing the issue.
