### ISSUE TITLE
[psyir] Frontend loses functions if they are contained within a function

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1302]
storng.f90 in NEMO contains a function that itself contains two functions:

      x = t + x
      y = m( m( m(y,13_8), -17_8 ), 43_8 )
      z = 6906969069_8 * z + 1234567_8

      kiss = x + y + z

      CONTAINS

         FUNCTION s(k)
            INTEGER(KIND=i8) :: s, k
            s = ISHFT(k,-63)
         END FUNCTION s

         FUNCTION m(k, n)
            INTEGER(KIND=i8) :: m, k, n
            m =  IEOR(k, ISHFT(k, n) )
         END FUNCTION m

    END FUNCTION kiss

and we lose those functions. I'm not sure what the solution to this is since, currently, only a Container can contain Routine definitions.

**Comment by arporter** [comment]
Related to this, if I have a PROGRAM that CONTAINS a subroutine then we get a VisitorError:

    program string_concat
      implicit none

      character(len=30) :: my_string

      my_string = "andy" // " " // "porter"
      call output(my_string)

    contains

      subroutine output(var)
        character(len=30), intent(in) :: var
        write (*,*) var
      end subroutine output
  
    end program string_concat

gives:

    Visitor Error: Routine symbol 'output' does not have a GlobalInterface or LocalInterface, is not a Fortran intrinsic and there is no wildcard import which could bring it into scope. This is not supported by the Fortran back-end.

**Comment by arporter** [comment]
If I move the subroutine out of the program but keep it in the same file then we get the same error. I'd have thought the symbol would have been in the FileContainer SymbolTable?

**Comment by sergisiso** [comment]
It may be tricky to replicate the same scoping rules than the nested functions. Is this function important for the performance? Would an option for now be if a program/subroutine/function has a CONTAINS declare the parent RoutineSymbol but put the whole implementation in a CodeBlock (main and nested functions)?

**Comment by sergisiso** [comment]
> If I move the subroutine out of the program but keep it in the same file then we get the same error. I'd have thought the symbol would have been in the FileContainer SymbolTable?

This may be a separate issue, what interface does 'output' has then?

**Comment by arporter** [comment]
The code in question is a random-number generator so is probably not very significant. Unless of course leaving it on the CPU causes additional memory traffic. @deardenchris, does `storng.f90` ring any bells? What do we currently do with it?

**Comment by deardenchris** [comment]
Hi @arporter `storng.f90` isn't one that I've looked at much as it doesn't show up in nsys as an expensive or frequently called routine. We do attempt to process it with PSyclone but no OpenACC directives get introduced, just profiling regions.

**Comment by arporter** [comment]
Simon has reported that he's hit this in WW3 (where there is a SUBROUTINE contained within a SUBROUTINE).

**Comment by arporter** [comment]
Simon has also reported that we currently incorrectly add the name of a subroutine CONTAINed within another subroutine as being public in the parent module. I think this will be fixed once we address this whole issue. At the very least we should probably spot this situation and put the whole routine (and thus anything it CONTAINS) within a CodeBlock.

**Comment by arporter** [comment]
#2208 has implemented functionality to ensure that we get a CodeBlock in this situation. A discussion of whether/how we can do better is ongoing in #2205 so I'll close this one.
