### ISSUE TITLE
[psyir] Scoping of symbols in imported containers not preserved

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1305]
NEMO uses the following idiom fairly frequently:

    module my_mod
      use some_other_mod
      private
      integer :: some_internal_flag
      integer, public :: my_useful_flag
    contains
      ..
    end module my_mod

Unfortunately, the code that deals with symbol visibility (which I wrote) thinks it can do away with the `private` statement and just declares the accessibility of each symbol explicitly. This means that we end up generating:

    module my_mod
      use some_other_mod
      integer, private :: some_internal_flag
      integer, public :: my_useful_flag
    contains
      ..
    end module my_mod

This then means that any code that does a wildcard import from `my_mod` will now also import all the public symbols from `some_other_mod`. This is incorrect.

**Comment by arporter** [comment]
Related to this, we also get symbol visibility wrong sometimes if the declaration ends up being of `UnknownFortranType`.

**Comment by arporter** [comment]
One possibility is to capture the visibility of each `ContainerSymbol` so in the earlier example, the symbol for `some_other_mod` would be private. The backend could then figure out what to do.

**Comment by arporter** [comment]
Just need to add tests for new backend functionality.

**Comment by arporter** [comment]
#1255 improves the frontend so that it does now capture the visibility of symbols of `UnknownFortranType`. However, the backend generates the declaration of such symbols by simply using the text stored in `UnknownFortranType.declaration`. Therefore, for Fortran such as:

    module my_mod
      private
      integer, target :: my_var
    end module my_mod

we will capture the fact that `my_var` is `private` *but* the code generated by the Fortran backend will lose this information since it isn't an attribute of the declaration of `my_var` and we won't re-generate the `private` accessibility statement.

**Comment by arporter** [comment]
I think there are only two solutions to this problem:

 1. somehow break-down the `UnknownFortranDeclaration` into bits that we do and do not understand (c.f. CodeBlocks);
 2. capture the 'default accessibility/visibility' of symbols in a SymbolTable.

My preference is for the second option as the first one sounds complicated. What do @rupertford and @sergisiso think?

**Comment by sergisiso** [comment]
Some questions:
By `UnknownFortranDeclaration` do you mean `UnknownFortranType`? Or there is a new concept?

In option 3 what do you mean by "default visibility"? is it different than the "symbol.visibility"? Do you intent to replace the symbol one with the symbol table one? or have both?

**Comment by arporter** [comment]
Oops, it was a typo, I meant `UnknownFortranType` - fixed now.
For 3., I mean capturing the fact that there's a `private` in the module declaration which means that everything it contains that doesn't have an explicit visibility is then private. If the Fortran backend reproduced this then we would automatically get the right visibility for those symbols of `UnknownFortranType`. Admittedly this feels a bit hacky. I'm beginning to think option 2. might be better although it involves a bit of parse tree manipulation.

**Comment by sergisiso** [comment]
I like 3 more, seems that visibility shouldn't be mixed with the Types, is more a property of the scope. So adding a symbol_table property for it seems right to me.

**Comment by arporter** [comment]
Yes, I started to play with 2. and then found I needed to pass visibility into UnknownFortranType and that didn't seem like a good thing.

**Comment by arporter** [comment]
Adding a `default_visibility` property to the SymbolTable has enabled me to simplify the interface to some frontend routines and it's possible that there may be more that I can do.
