### ISSUE TITLE
[psyir] Lower bound in Fortran array declarations is not retained

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1307]
In Fortran an array's bounds can be specified within the declaration:

    integer, dimension(0:12) :: my_array

In raising to PSyIR and then lowering again, this information is lost and the resulting array is declared as:

    integer, dimension(12) :: my_array

**Comment by arporter** [comment]
We have a bit of a conceptual problem here because, at the moment, the `ArrayType` has no support for specifying the lower bound of an array (https://psyclone-ref.readthedocs.io/en/latest/autogenerated/psyclone.psyir.symbols.datatypes.html#psyclone.psyir.symbols.datatypes.ArrayType). Its constructor takes a `shape` argument which contains a list of either ints, DataNodes or one of the values of the `ArrayType.Extent` enum.

**Comment by arporter** [comment]
I think the simplest thing to do is to extend the `ArrayType` constructor to allow the `shape` list to contain `Range` nodes. It will then be up to the backend to decide whether such a type is supported. Does that sound OK to @rupertford, @sergisiso and @hiker?

**Comment by sergisiso** [comment]
I am not sure about using `Range` as the shape can not have a "step" (right?) and it would accept any PSyIR sub-expression in the start/stop, which is also probably not the case as I assume there are many limitations of what can be found in the declarations.

What about each element of the shape list be a 2-tuple of lower and upper bound?

**Comment by arporter** [comment]
Thanks Sergi. You are correct, R511 of the Fortran standard says that an explicit-shape-spec is `[lower-bound:] upper-bound` so a 2-tuple is a much better idea.

**Comment by arporter** [comment]
Does this look alright:

![image](https://user-images.githubusercontent.com/17409212/123946961-b121bf00-d997-11eb-8860-322274a91639.png)

i.e. unless the extent is 'ATTRIBUTE' or 'DEFERRED' then it now always has a lower bound and an upper bound?
