### ISSUE TITLE
Making loop boundaries for gocean1.0 more flexible

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#131]
In the gocean API it is not possible at the moment to e.g. specify a 1-iteration loop. For example:
```
self._bounds_lookup['offset_ne']['ct']['w_halo'] = \
    {'inner': {'start': '1', 'stop': '+1'},
    'outer': {'start': "2", 'stop': ""}}
```
does not create an inner loop with ```do i=1, +1```, but something like ```DO i=1,istop+1``` (and the '+' in '+1' is required, otherwise incorrect Fortran code will be created).

Besides the asymmetric handling ('start' is taken verbatim, while 'stop' puts ```istop/jstop``` in front of the string, it also does not use the minimum index that might be available in the runtime library (I vaguely seem to remember reading somewhere that there is a reason why lower bound was fixed at 1 or 2).

For my work I have replaced this mechanism to support expressions like:
```
self._bounds_lookup['offset_ne']['ct']['s_halo'] = \
            {'inner': {'start': "1", 'stop': "{stop}+1"},
             'outer': {'start': '{stop}+1', 'stop':"{stop}+1"}}
```
The expressions '{start}' and '{stop}' will be replaced with the corresponding value from the API (e.g. '{stop}' becomes 'istop' or 'jstop' (which are initialised with ```somefield%grid%simulation_domain%xstop/ystop```). So the outer loop specifies a loop with only one iteration (```do j=jstop+1, jstop+1```), and an inner loop ```do i=1, istop+1```. Patch https://github.com/hiker/PSyclone/commit/5e31dc90bfb68d8f8255399a20cf07b72671a99c (see #129) is responsible for replacing the single iteration loop with a simple assignment (though in reality I guess the compiler woudl do that automatically anyway).

Patch https://github.com/hiker/PSyclone/commit/f932a8467af3fb3a2175adbbb42176639178b5ef implements this. To be compatible with the current settings I set 'start' to be '', so constant lower bounds of 1 and 2 will be specified the same way they are atm (all tests work without any changes), but it would be easy to use the ```xstart``` of the fields.

Again, let me know if you are interested to add this patch, then I'll fix it up (and also let me know if you want to have the start values fixed at 1 or 2 as they are atm, or if you want to use 'somefield%grid%simulation_domain%xstart/ystart instead), or just close this request otherwise.

**Comment by arporter** [comment]
I'm a bit confused about why we'd want to generate a loop with only a single iteration - is that part of the work you're doing on supporting N/E/S/W-boundary-only iteration spaces? If so, my first reaction is that it would be better to generate a single loop rather than 'fix' it so that the outer loop has a single iteration. I think the value of the loop counter for that single iteration can be put in the argument list of the kernel (i.e. replace "ji" with "jstop+1" or whatever).

Having said that, I'm always open to code improvements and better consistency is always good so if there's scope to improve things then do put in a PR.

**Comment by hiker** [comment]
Yes, it is part of my N/S/W/E-boundary-only iteration spaces. 

To a certain degree I agree that only a single loop should be generated, BUT: this means making the code creation more complicated (handling this as a special case), while this way (just adding more general loops specification which could be useful elsewhere) together with the fix #129, and everything just happens automatically. Basically while the patch replaces a few lines, de-facto it only adds 4 new lines of code ... hard to beat ;) 

Actually, I think (didn't check all the cases in those functions, so it's a bit of a guess) that with this patch ```lower_bound``` and ```upper_bound``` could become one function (getBound("start" or "stop" ) - reducing the amount of code ;)

IMHO it also makes the code easier to understand since now start/lower_bound and stop/upperbound are handled identical, while atm start is taken verbatim, stop gets x_stop prepended) 

I'll have a look about creating only a single loop, but I'd guess that this is a lot more complicated (e.g. tests to see if only the inner or outer loop should be created, passing in the right index at the right position - but I'll check. At least I won't close this for now

**Comment by hiker** [comment]
Yes, it is part of my N/S/W/E-boundary-only iteration spaces. 

To a certain degree I agree that only a single loop should be generated, BUT: this means making the code creation more complicated (handling this as a special case), while this way (just adding more general loops specification which could be useful elsewhere) together with the fix #129, and everything just happens automatically. Basically while the patch replaces a few lines, de-facto it only adds 4 new lines of code ... hard to beat ;) 

Actually, I think (didn't check all the cases in those functions, so it's a bit of a guess) that with this patch ```lower_bound``` and ```upper_bound``` could become one function (getBound("start" or "stop" ) - reducing the amount of code ;)

IMHO it also makes the code easier to understand since now start/lower_bound and stop/upperbound are handled identical, while atm ```start``` is taken verbatim, ```stop``` gets ```x_stop``` prepended.

I'll have a look about creating only a single loop, but I'd guess that this is a lot more complicated (e.g. tests to see if only the inner or outer loop should be created, passing in the right index at the right position - but I'll check). At least I won't close this ticket for now, and will update it later.

**Comment by hiker** [comment]
See pull request #180.

**Comment by hiker** [comment]
#180 was merged, closing this issue.
