### ISSUE TITLE
Metadata for any discontinuous space

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#133]
#84 (PR #128) introduced two more discontinuous spaces, `w2v` and `wtheta`. This raises a question of whether we want to "group-mark" their discontinuity for common purposes, similar to `ANY_SPACE_` which assumes things to be continuous by default.
Is this something that would be useful?

**Comment by arporter** [comment]
I think @thomasmelvin has mentioned an `any_w2` space in the past. I don't know whether there is support for this in the LFRic infrastructure. I think an `ANY_DISCONTINUOUS_SPACE` would make sense but I don't have any feel for how significant an improvement this would be - i.e. what fraction of calls to kernels with arguments on `ANY_SPACE` actually could be on `ANY_DISCONTINUOUS_SPACE`?

**Comment by TeranIvy** [comment]
There is `any_w2` in the LFRic infrastructure and in PSyclone, where it is treated as continuous. Regarding `any_discontinuous`, Sam asked me whether this was available because she would like to do interpolated output from one discontinuous space to another without explicitly coding which one it is. I think she mentioned `w2v` to `wtheta` (or vice versa, I am not sure) which are both based on the vertical part of `w2`.

**Comment by rupertford** [comment]
Hi Iva, I have no hard results but I think that, in general, updating/writing to discontinuous fields is going to be more efficient than updating/writing to continuous fields. At the moment we need to assume continuous for a kernel that specifies `any_space` (unless we can statically determine what the space actually is). If there are scientifically meaningful cases where `any_space` should really be `any_d_space` then I think this would be potentially useful for performance. Similarly, if it makes scientific sense to generalise a kernel on a particular discontinuous space to all discontinuous spaces then I don't think that will affect performance.

**Comment by thomasmelvin** [comment]
Since there are computational advantages to knowing if a field is discontinuous then I think it is a good idea to have a `any_d_space` then we can take advantage of this knowledge for some general kernels such as `dg_matrix_vector`

**Comment by TeranIvy** [comment]
It seems this is now required for physics kernels to ensure they are not looping into the halos when it is known that they operate on discontinuous fields. We also need to ensure that colouring is not applied to loops over discontinuous spaces. My suggestion of the metadata for Dynamo 0.3 API is below.

`VALID_ANY_D_SPACE_NAMES = ["any_d_space_1", "any_d_space_2", ...]` (depends how many are needed),

`VALID_F.UNCTION_SPACE_NAMES` are updated with above. It would be useful to introduce a list for all discontinuous function spaces:

```
ALL_DISCONTINUOUS_FUNCTION_SPACES = DISCONTINUOUS_FUNCTION_SPACES + VALID_ANY_D_SPACE_NAMES
```
so the optimisation script specifies no colouring for them. A similar list can be introduced for continuous spaces
```
ALL_CONTINUOUS_FUNCTION_SPACES = CONTINUOUS_FUNCTION_SPACES + VALID_ANY_SPACE_NAMES
```
Ideally, function space names and any space names would be defined in the configuration file but we can leave it for another issue after the next PSyclone release to minimise disruption for Aquaplanet delivery.

**Comment by TeranIvy** [comment]
Looking into [argument_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/field/argument_mod.F90), there is also an identifier for  `ANY_SPACE_10` which we do not have in PSyclone so it would be good to add it.

**Comment by TeranIvy** [comment]
Re-assigned people because of accidentally deleting them.

**Comment by TeranIvy** [comment]
I see this hasn't moved on since the beginning of July. I'm happy to take it as originally planned.

**Comment by rupertford** [comment]
> Looking into [argument_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/field/argument_mod.F90), there is also an identifier for `ANY_SPACE_10` which we do not have in PSyclone so it would be good to add it to `VALID_ANY_SPACE_NAMES`.

I would have expected PSyclone to pick up on this and raise an exception. I'll raise an issue.

**Comment by rupertford** [comment]
> I see this hasn't moved on since the beginning of July. I'm happy to take it as originally planned.

Feel free to take it Iva, that would be great.

**Comment by TeranIvy** [comment]
After a chat with @thomasmelvin and @christophermaynard it was desided that it would be better the new metadata are more descriptive. That is, `ANY_DISCONTINUOUS_SPACE_*` instead of `ANY_D_SPACE_*`. Mike H. and Steve M. are also in agreement. I will update the changes accordingly before going through more tests. 
The relevant LFRic ticket to update metadata is [1906](https://code.metoffice.gov.uk/trac/lfric/ticket/1906). There is also an LFRic [test ticket 1903](https://code.metoffice.gov.uk/trac/lfric/ticket/1903) for validation purposes.

**Comment by rupertford** [comment]
pr #460 is now on master so closing this issue.
