### ISSUE TITLE
math_equal() problems

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1332]
`Literal` `math_equal()` fails as it is comparing with something that does not have a value. We need to add code to check whether the other instance is a Literal.

Also, `math_equal()` when checking two structure references, does not check that the members (`ArrayMember` in this case), are the same or not. Therefore `a%b(n)` and `a%c(n)` will return `True`.

**Comment by hiker** [comment]
Looking at the impact of SymPy: the test ``test_multi_add`` in ``test_assignment_trans`` fails. But reason is:
```
  b(j) = b(j) + 3 / n * a(i + 2)
```
is compared with:
```
  b(j) = b(j) + a(i + 2) * (3 / n)
```
using a string comparison, which fails. If this expression would be compared using symbolic maths, I believe it would succeed. E.g. I get:
```
.COMPARING b(j) + a(i + 2) * (3 / n) with b(j) + 3 / n * a(i + 2) --> True
```
as output when using SymPy.
So the issue appears to be that the test is too restrictive, not at all that symbolic math (or fwiw math_equal ever) was responsible for this failure. I'd suggest renaming this issue (or opening a new one)
