### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by ScottWales** [stfc/PSyclone#135]
Currently PSyclone only supports Python 2. Supporting Python 3 in addition would help future-proof the code.

**Comment by ScottWales** [comment]
I'm happy to take a look at this

**Comment by arporter** [comment]
That's brilliant = thanks Scott.

**Comment by arporter** [comment]
Hi @ScottWales, we have now changed the fparser API so that it clears the cache by default. This fixes one of the things you had to work around in this issue.
