### ISSUE TITLE
Operators in different modules 

### ISSUE THREAD

**Issue by christophermaynard** [stfc/PSyclone#1350]
To make operators in LFRic, the different inherited classes of operator now live in the own modules. Previously, in the PSylayer, the code would look like ...
`USE operator_mod, ONLY: operator_type, operator_proxy_type, &
     columnwise_operator_type, columnwise_operator_proxy_type`
Now the code should look like ...
`USE operator_mod, ONLY: operator_type, operator_proxy_type
    use columnwise_operator_mod, only: columnwise_operator_type, columnwise_operator_proxy_type`
Same goes for `r_solver_operator`
See LFRic ticket [#2765](https://code.metoffice.gov.uk/trac/lfric/ticket/2765)

**Comment by TeranIvy** [comment]
This looks like a change in [LFRicConstants.DATA_TYPE_MAP](https://github.com/stfc/PSyclone/blob/master/src/psyclone/domain/lfric/lfric_constants.py#L284) so it can probably be absorbed into #1349.

Testing in LFRic will be tricky as the trunk would need to be changed and we are already non-backward compatible with PSyclone master. I have an LFRic branch that is compatible with the PSyclone master and can be used for testing in [LFRic ticket #2738](https://code.metoffice.gov.uk/trac/lfric/ticket/2738). I would suggest merging code changes from [LFRic ticket #2765](https://code.metoffice.gov.uk/trac/lfric/ticket/2765) to this LFRic test branch.

**Comment by christophermaynard** [comment]
Hi @TeranIvy OK, thanks for this. I will look at these tickets/issues. My ticket is functional, but not finished (documentation and testing.)

**Comment by rupertford** [comment]
Created branch [1350_lfric_mixed_precision_operators](https://github.com/stfc/PSyclone/tree/1350_lfric_mixed_precision_operators) which is a branch of [1277_lfric_mixed_precision](https://github.com/stfc/PSyclone/tree/1277_lfric_mixed_precision) that is associated with PR #1349.

**Comment by TeranIvy** [comment]
We will very likely need this after all, as Mike has found the way to separate operators, see his ticket [3144](https://code.metoffice.gov.uk/trac/lfric/ticket/3144).

The main change is in `USE` statements for columnwise operators. That will be `USE columnwise_operator_mod, only: columnwise_operator_type, columnwise_operator_proxy_type` (they are separated from the `operator_mod`).

The LFRic ticket is currently in review with Chris. It would have to be commited to trunk together with the change in PSyclone (most likely new release 2.3.0).

**Comment by rupertford** [comment]
Closing this issue as Mike Hobson has said that the LFRic mixed-precision support does not (currently) need any module changes so no changes are needed in PSyclone.
