### ISSUE TITLE
Bring Jupyter tutorials up-to-date

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1371]
Although the fact that we test the tutorials means that they do at least execute, some of the accompanying text is now out of date (e.g. Calls are now represented in the PSyIR rather than being put in CodeBlocks).

**Comment by arporter** [comment]
A question for @rupertford and @sergisiso; currently, the PSyIR part of the tutorial uses the NEMO API. I'm inclined to change it so that it uses our new fortran frontend and just deals with language-level PSyIR. What do you think?

**Comment by arporter** [comment]
(e.g. see https://github.com/stfc/PSyclone/blob/master/tutorial/notebooks/psyir/psyir_example2.ipynb)

**Comment by rupertford** [comment]
> A question for @rupertford and @sergisiso; currently, the PSyIR part of the tutorial uses the NEMO API. I'm inclined to change it so that it uses our new fortran frontend and just deals with language-level PSyIR. What do you think?

Sounds reasonable to me.
