### ISSUE TITLE
Leaf/childless Directive support

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1374]
When creating `OMPTaskwaitDirective`, it appears to be a special type of directive which does not need to contain children, i.e. the directive is always just a single command:
```
!$omp taskwait
```
For now, the implementation in #1338_taskwait_directive branch throws an Error if children are provided to the directive. However #1338_childless_directive attempts to create a new type, similar to the Directive type, however it forbids any children nodes.

@arporter expected we could also use this for some ACC directives (e.g. EnterData), however I had some issues getting that to work. Tagging @sergisiso as he's working on those directives.

**Comment by sergisiso** [comment]
I like the idea. There are more issues than just the `validate_child`, for instance the abstract methods end_string() and _add_region() don't fit well at all when we have a directive which is just a leaf statement.

I looked at the new implementation at #1374, the problem there is that it would change the behavior of:
`node.walk(Directive)` or `node.walk(OMPDirective)`
and I think it makes sense to conserve the original behavior for these.
The first is easy to have by creating a generic Directive node  and 2 suclasses (with schedule or childless), the second we may have to use a Mixin class with the common OMP or ACC features if we use inheritance to separate childless vs schedule.

By the way, childless/leaf is very AST speak, do we have any alternative word to differentiate them that we would use for directives in plain source code?

**Comment by LonelyCat124** [comment]
Ok. how do you mean this should be done? We create an abstract Directive class that the two implementations in #1374 inherit from? I kept them different and inheriting from `Statement` right now as most of the functionality isn't needed in ChildlessDirective, but I don't know how that affects `node.walk`.

I think for OMP there aren't any features stored in the OMPDirective class other than `_PREFIX` that I can see? The `_get_reductions_list` is maybe not relevant for these types of "floating" directives, though its possible OMPTaskwait might eventually want it, so that could be a Mixin class, though I think that would be wanted for more/all OMPDirectives anyway, so might be mixed into that class instead of its children.

In the OpenMP manual it looks like "stand-alone directive" is the preferred term?

**Comment by sergisiso** [comment]
Yes, so:
```
            | -> StandaloneDirective
Directive <-|
            | -> RegionDirective
```

Then I am not sure if another hierarchy level or a mixin (I would say the second to avoid repeating code, but the multiple-inheritance scares me a bit :)) with OMP and ACC.

I think currently it fails because it doesn't find the appropriate visitor, which could be again because the current modification changed the generic class hierarchy,

The visitor goes up the class hierarchy until it finds a candidate visitor. The error says "'GOACCEnterDataDirective' found: method names attempted were ['goaccenterdatadirective_node', 'accenterdatadirective_node', 'accchildlessdirective_node', 'childlessdirective_node', 'statement_node', 'node_node', 'commentablemixin_node']."
So ACCDirective_node and Directive_node have not been tested now and maybe this example was using them?

**Comment by sergisiso** [comment]
What @arporter @rupertford think about these classes, naming, ...?

**Comment by arporter** [comment]
I like the names you suggested in your last comment Sergi. I too would favour a Mixin but it might be difficult to get the various constructors to play together nicely. However, as @LonelyCat124 says, maybe the constructors for the `OMPDirective` and `ACCDirective` classes could be minimal?

**Comment by LonelyCat124** [comment]
I rebased the PR to master now. I can start looking at this at some point this week or next probably.

**Comment by LonelyCat124** [comment]
Ok, so c1f21ba36 now contains something along these lines. At the moment I haven't bothered with any mixin classes. For OpenMP and OpenACC there are now two base directives, `XXXDirective` and `XXXStandaloneDirective`. For OpenMP, these classes have no shared functions outside of `node_str`, which returns OMP vs OMPStandalone.

For OpenACC, both ACCStandalone and ACC Directives share the same `validate_global_constraints`, so this could in theory be a mixin, but I'm not sure it fits to be a mixin as it calls the super class.

I'm going to put the PR up for review now as I think unless there are specific things that need to be mixin it should now be ok.
