### ISSUE TITLE
NEMO raising performance problems

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1375]
I've succeeded in making the parsing overhead look small because the transformations that raise language-level PSyIR to NEMO PSyIR can take a very long time if a routine contains a lot of code (e.g. for lbcnfd.f90 and lib_mpp.f90 in NEMO).

I've alleviated some of this in #1147 by merging two `walk()` calls into one but the situation is still not good. It's possible that adding an option to `walk()` so that it returns nodes depth first would improve things as then we could transform the deepest loops first.

**Comment by arporter** [comment]
I've created `perf_test.f90` which contains  lbc_nfd_2d, lbc_nfd_2d_ptr, lbc_nfd_2d_ext, lbc_nfd_3d, lbc_nfd_3d_ptr, lbc_nfd_4d from `lbcnfd.f90`. Profiling this:

   $ python -m cProfile -o lbcnfd_profile.out `which psyclone` -api nemo ./perf_test.f90
    $ python
    >>> import pstats
    >>> from pstats import SortKey
    >>> p = pstats.Stats('lbcnfd_profile.out')
    >>> p.sort_stats(SortKey.CUMULATIVE).print_stats(20)
    Wed Aug 18 13:50:10 2021    lbcnfd_profile.out

         265014711 function calls (225172270 primitive calls) in 91.723 seconds

    Ordered by: cumulative time
    List reduced from 3762 to 20 due to restriction <20>

    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     492/1    0.010    0.000   91.730   91.730 {built-in method builtins.exec}
        1    0.000    0.000   91.730   91.730 psyclone:3(<module>)
        1    0.000    0.000   91.577   91.577 psyclone:36(<module>)
        1    0.000    0.000   91.492   91.492 generator.py:257(main)
        1    0.000    0.000   91.475   91.475 generator.py:150(generate)
    509/85    0.018    0.000   89.871    1.057 visitor.py:145(__call__)
    2857166/1134    1.759    0.000   82.851    0.073 node.py:1332(copy)
    128173/509    6.100    0.000   82.820    0.163 scoping_node.py:69(_refine_copy)
    2857166/1134    6.696    0.000   79.687    0.070 node.py:1315(_refine_copy)
    2857166/1134    1.653    0.000   79.677    0.070 node.py:1330(<listcomp>)
    6932/1321    0.077    0.000   75.362    0.057 {built-in method builtins.eval}
    5309/85    0.019    0.000   75.357    0.887 visitor.py:194(_visit)
      342    0.001    0.000   75.297    0.220 fortran.py:986(assignment_node)
      682    0.002    0.000   75.242    0.110 fortran.py:338(gen_indices)
      145    0.001    0.000   75.200    0.519 language_writer.py:224(arrayofstructuresreference_node)
      418    0.003    0.000   75.192    0.180 fortran.py:1070(range_node)
      145    0.001    0.000   75.191    0.519 language_writer.py:183(member_node)
      824    0.004    0.000   75.166    0.091 array_mixin.py:197(_matching_access)
    84328/84308    0.012    0.000   75.164    0.001 {method 'join' of 'str' objects}
        1    0.000    0.000   50.799   50.799 psyGen.py:194(create)

**Comment by arporter** [comment]
[perf_test.txt](https://github.com/stfc/PSyclone/files/7020595/perf_test.txt)

**Comment by arporter** [comment]
[lbcnfd.txt](https://github.com/stfc/PSyclone/files/7020608/lbcnfd.txt)

**Comment by rupertford** [comment]
On my laptop the `perf_test.txt` (fortran code) example provided by @arporter takes 29s. If I remove the call to validate in the `create_nemo_kernel_trans.py` transformation apply method, the time reduces to 2s. This is expected given that I followed the profiling approach suggested by @arporter above and this method was near the top of the cumulative timings. This doesn't fix the problem but it narrows down where a large proportion of the time is taking in this particular example.

**Comment by rupertford** [comment]
The above validation time is dominated by `Assignment.is_array_range`, so we need to speed this up somehow.

**Comment by rupertford** [comment]
I think it is going to be difficult to optimise the FortranWriter visitor enough to remove this performance problem. We also want the exception to give useful information so should not remove the writer. I therefore think a reasonable solution would be to add a transformation flag (to the base class) that specifies that an exception string is required. This can default to True and only be set to False if using exceptions internally to skip the application of a transformation as the exception string is not of interest. This flag would simply be used for performance reasons.

**Comment by sergisiso** [comment]
Or use lazy evaluation:
```
if nodes:
    class LazyString:
        def __init__(self, func):
            self.func = func
        def __str__(self):
            return self.func()
    fwriter = FortranWriter()
    raise Exception(
        LazyString(lambda: "A NEMO Kernel cannot contain array assignments but found: "
            "{0}".format([fwriter(node).rstrip("\n") for node in nodes])))
```
which takes 1.2s in my laptop. (It can be a TransformationError if we remove the early str() inside TransformationError init)

Or vote for it https://bugs.python.org/issue32954

**Comment by rupertford** [comment]
Thanks @sergisiso, that is a better solution.
