### ISSUE TITLE
Disallow GH_WRITE access for continuous fields

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#138]
Although `GH_WRITE` access is officially not allowed for continuous fields in the Dynamo0.3 API there is no explicit restriction and test to reject this combination in PSyclone.
This issue will add the restriction, similar to how it is being done in #25 for `GH_READWRITE` access for continuous fields (`class DynArgDescriptor03(Descriptor):` in `dynamo0p3.py` and related tests in `dynamo0p3_test.py`).

The instances of continuous `GH_WRITE` access in PSyclone code and LFRic kernels will have to be replaced with `GH_INC`. To test for any undesirable side effects in LFRic I replaced `GH_WRITE` continuous instances (only `W0` and `W2` were found) with `GH_INC` in a working copy of the trunk. The good news is that all tests successfully complete (compilation, runs and KGOs checks). It would perhaps be good to warn LFRic developers not to add any more continuous `GH_WRITE` until the PSyclone restriction is in place - more work to remove them later :)

**Update**
It was agreed that this approach will be adopted for the user-supplied kernels that operate over `cells`. Built-ins can use `GH_WRITE` and `GH_READWRITE` on `ANY_SPACE` as they loop over DoFs (see #471).

**Comment by TeranIvy** [comment]
Closing the issue as this will be properly implemented in #471.

**Comment by TeranIvy** [comment]
Reopening as there is enough work for continuous function spaces without any_space and built-in accesses to do in one issue.

**Comment by rupertford** [comment]
I think this should stay open even though #818 is now on master. Is that right @TeranIvy?

**Comment by TeranIvy** [comment]
It can be safely closed now, @rupertford, as the rest of the field access logic for `any_space` and DoF looping is being done in isssue #471 / PR #823. I will link this issue to PR #818 as it should have been from the start, so that will close it.

**Comment by TeranIvy** [comment]
Well, linking PR didn't automatically close the issue - since you are the reviewer, @rupertford, are you happy to close it?

**Comment by rupertford** [comment]
Closed as suggested by @TeranIvy
