### ISSUE TITLE
[Tasking] Add nogroup clause by default to taskloop transformations

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1381]
This is something I'd missed from my understanding of how taskloop works in OpenMP.

It appears that by default when OpenMP finds a `taskloop` directive, it also makes a `taskgroup` around that task region. This (I think) synchronizes after the taskloop (essentially a barrier), so there's no parallelism between taskloops. We don't want this behaviour, as we're requiring PSyclone's taskwait directive to compute barrier points, and handle those automatically.

This can be avoided by using the `nogroup` clause, so I want to test adding this into PSyclone, and checking the NemoLite2D benchmark is still correct, and if so then we can push this.

My proposal here is that I add a `nogroup=True` to the constructor for the transformation, and this can be disabled by the user if they want explicit synchronization.

**Comment by rupertford** [comment]
If the default (i.e. no clause added to the directive) is a group then I would go with that as the default in the transformation as well. I would also suggest having a `nogroup` option associated with the apply method rather than the constructor as in general you might want some loops implemented as a group and some not.

**Comment by LonelyCat124** [comment]
I think having it associated with both might be better - that way you can specify a "default" choice, and use apply to set it for a specific transformation if you want something different? I'll try to implement an apply method using that idea for now.

**Comment by rupertford** [comment]
I think this is something that should be set via the optional `options` argument to the `apply` method. Setting a default value for the instance in the constructor should be fine too, but we don't have a general approach for that.
