### ISSUE TITLE
Should PSycloneError have a 'value' attribute?

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1389]
I am just curious because I see the Exception (the class that PSycloneError inherits from) does not have this attribute.
```
>>> e = Exception()
>>> dir(e)
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'with_traceback']
```
But PSycloneError has it and relies on it in the tests e.g. `"message" in str(err.value)`

It would be easy to refactor the attribute out (to make the Errors a bit more standard) but the tests would need to be updated to `"message" in str(err)`. @rupertford @arporter  Is this something worthwhile?

**Comment by rupertford** [comment]
I can't offer any justification for using a value attribute. I think I just copied some code from somewhere that did it that way. I'd be happy for it to be changed but it would affect all tests that check that exceptions are working correctly so would affect a lot of test files.
