### ISSUE TITLE
Adding PSyKE support

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#139]
PSyKE (PSy Kernel Extractor) will allow part of a PSyclone conformant code to be extracted and run separately. This is potentially useful for benchmarking and for removing/reducing the need to use the LFRic infrastructure. An earlier implementation that never made it onto master was limited to individual kernels. In this implementation we will allow any nodes within an invoke to be specified.

In the first instance we will add a new Node class called Extract and an associated transformation called ExtractTrans which adds an instance of this Node class to a schedule. For example ...

```
schedule
    loop ...
        kernel ...
    extract
        loop ...
            builtin ...
        halo exchange ...
       loop ...
           kernel ...
           kernel ...
```

This extract class should simply add a comment `! extract start` and `! extract end` at appropriate locations to start off with. All tests and examples should run as before - note some errors may be found due to code assuming parenthood rules e.g. it may be assumed that a loop is always a child of a schedule. This code should be added as base classes so it works for both dynamo0p3 and gocean1p0. 

It is not unreasonable to limit the extract to being added after all optimising transformations have been completed if that helps i.e. if extract gets in the way of optimising transformations and causes them to fail then disallowing it when optimising transformations are being applied is OK.

**Comment by TeranIvy** [comment]
It seems that at least the first part of work will only deal with LFRic kernels as more information needs to be gathered about how complicated is to extract LFRic infrastructure for larger code units. Parent classes Extract and ExtractTrans will be restricted to LFRic kernels in Dynamo0.3 API . Much of the functionality added in #7 can be reused here.

**Comment by arporter** [comment]
My understanding was that we would exclude halo swaps, not that we would restrict it to a single kernel. I think we want to make this as general as we can, within the restrictions of avoiding infrastructure calls in the extracted region.

**Comment by TeranIvy** [comment]
Yep, I forgot, you're right. I'll see from the practical point of view how much I can get out without having to include too much of infrastructure in. I'm afraid I'll hit the infrastructure issue pretty soon, though.

**Comment by arporter** [comment]
You might but do remember that you can instruct PSyclone not to generate MPI-parallel code so that should get you a lot further...

**Comment by TeranIvy** [comment]
I just realised I deleted uncommitted changes when refreshing my local PSyclone repository with the new `Extract` and `ExtractTrans` classes! D'oh!!! 
And now do it all again...

**Comment by arporter** [comment]
#218 is merged. Closing issue.
