### ISSUE TITLE
remove f2pygen and use the fgenerator package instead

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#14]
The f2pygen.py code has been placed in its own GitHub repository and is now being maintained there. It is now called fgenerator. We will therefore remove f2pygen.py, any tests and change documentation appropriately so that it can now use fgenerator.

**Comment by arporter** [comment]
This issue has now been superseded by our move to PSyIR - code is (or will be) generated using an appropriate backend so this ticket can be closed.
