### ISSUE TITLE
Create schedule based on XCodeML/F IR

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#141]
We have agreed to use CLAW when applying PSyclone to pre-existing code (i.e. where we don't generate PSy-layer code from scratch). Initial support for using CLAW from transformations has been added in #114.

If we are to continue working in Python then we must use Jython to pass the XCodeML IR stored as Java objects from CLAW to PSyclone. We can then build the Schedule view on top of the IR. This would give an architecture something like:

![clawfornemo](https://user-images.githubusercontent.com/17409212/37041116-4fabb51e-2153-11e8-8010-bd921a2e4fdc.png)

**Comment by arporter** [comment]
I've extended psyclone to launch CLAW. I'm using the existing mechanism (introduced in #114) for launching a Python script from CLAW in order to pass the AST back into PSyclone.

**Comment by arporter** [comment]
Next step is to begin thinking about how to go from the OMNI IR to a PSyclone Schedule.

**Comment by arporter** [comment]
If we change our approach so that we use the XCodeML IR instead of the AST stored as Java objects then things are simpler. Transformations are now 'applied' to the Schedule by the insertion of CLAW directives in the underlying XCodeML IR:
![clawfornemo2](https://user-images.githubusercontent.com/17409212/37784865-ad355844-2df0-11e8-961c-992307ce3302.png)
The heart of this approach still boils down to generating a Schedule view of the XCodeML IR.

**Comment by arporter** [comment]
![scheduleview](https://user-images.githubusercontent.com/17409212/37787160-3ce7dee4-2df6-11e8-8031-e5ecc4776a40.png)

I think the most difficult part of this will be providing the user with a view of the transformed Schedule when it is not yet actually transformed (just marked with CLAW directives).

**Comment by arporter** [comment]
Although it is natural to think of passing a `Schedule` constructor an XML DOM (containing XCodeML) and letting it recurse down and create its children, we know from experience that such an approach makes unit-testing of the resulting code difficult. I think it is therefore better to have a separate piece of code which walks through the DOM and populates the Schedule with what it finds. The constructor of each element in the Schedule would then take its parent node and a DOM node.

**Comment by rupertford** [comment]
I'm not convinced a separate piece of code (a factory?) would be nicer than recursion within the schedule objects.

I think we could avoid the unit testing issue by allowing each object to be created independently or as part of a hierarchy via an additional argument (e.g. recurse=True/False), or perhaps via a separate create method.

There are potential benefits to have a distributed (recursive) creation of a schedule. It allows the knowledge of valid children and parents to be kept with the appropriate classes and avoids the need for a separate builder (factory) class.

**Comment by arporter** [comment]
I can apply a generic transformation such as `OMPParallelLoopTrans` to the `Schedule`. However, this currently does not affect the underlying DOM. Ultimately, `Schedule.gen_code()` should return the modified DOM.

**Comment by arporter** [comment]
For the existing APIs we have a `PSy` object which contains one or more `Invoke`s, each of which has a `Schedule`. The `gen_code()` method of the `Schedule` takes a `parent` object of type `SubroutineGen` for the PSy-layer subroutine being created for the particular `Invoke`. I can either mimic this by creating a `PSy` object (with a single `Invoke`) from the XCodeML or, alternatively, drop those concepts when using XCodeML IR. 

On reflection, I don't think that dropping those concepts entirely is possible since I need something to hold the state of the subroutine (declarations etc?) that contains the Fortran for which I'm generating a `Schedule`.

**Comment by arporter** [comment]
In fact, if we have a source file or module that contains more than one routine then we will effectively have more than one `Invoke`.

**Comment by arporter** [comment]
It seems I'd already come to this conclusion in my previous (fparser2-based) implementation so I've copied over what I did there and adapted it.

Now comes the important bit - generating the XML for a modified `Schedule`. This feels quite different to what we do in `gen_code` (where we build-up a tree of f2pygen objects) since we are modifying an existing AST (the XML DOM). Therefore, I've elected to go for adding `gen_xml()` methods to my objects. So far these don't do anything. However, for e.g. `OMPParallelDoDirective` we need to modify the DOM to add-in the necessary CLAW directive. The question is, what is the CLAW directive and how do we specify e.g. thread-private variables? In fact, how do we even identify such variables? In my previous implementation I used Habakkuk to analyse the 'kernel' code but I don't currently have code to do that for the XML IR. I could fall back to assuming that it's just the loop variable that is private and have everything else as shared?

**Comment by arporter** [comment]
I can now add an element immediately before any loops that have OMPParallelDo applied to them. It isn't particularly clean - I probably need to store pointers into the DOM when I create the `Node` in the first place. At the minute I look at the first child (which is a Loop), get its `_xml_node` and then get its `parentNode`.

**Comment by arporter** [comment]
I've updated the example to use the OMNI backend to generate Fortran as the end product. I've also altered the script to transform all loops over levels. However, the directives are not being generated for those loops that are not at the top level.

**Comment by arporter** [comment]
We can easily extract loop limits if they are single variables or integer values. Life gets more complicated if they are expressions (e.g. "jpk+1").

**Comment by arporter** [comment]
Parking this Issue as we've swapped back to use fparser2 (#27).
