### ISSUE TITLE
[PSyIR] Fortran declarations with assignments should store the RHS in a initial_value property

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1419]
Simon is finding lots of bugs. For the following code:

    PROGRAM x
      INTEGER :: y=MAX(1,2,3)
      DO y=1,2
      END DO
    END PROGRAM x

`y` ends up being of `UnknownFortranType` (because of the un-supported initialisation) but then we fail with:
"Generation Error: variable property in Loop class should be a ScalarType but found 'UnknownFortranType'."

(Congratulations to us on a good error message I think :-) ).

In this situation we have a choice - either permit loop variables to be of UnknownFortranType or, take this opportunity to infer that it must actually be an integer and update the Symbol accordingly.

**Comment by arporter** [comment]
If we were to update the Symbol then we would no longer get the correct declaration (as that's stored as part of the UnknownFortranType). I think the only option is therefore to permit loop variables to be of UnknownFortranType.

**Comment by sergisiso** [comment]
Another idea is for the fparser2 frontend to split this statements to the declaration and the initialisation, so it becomes:
```
INTEGER :: y
y=MAX(1,2,3)
```

**Comment by arporter** [comment]
After a discussion in the office we have decided to add support for the situation Sergi gives above. `DataSymbol` has the `constant_value` property which is used for symbols with values that are fixed at compile time ('parameters' in Fortran). I propose to add an `initial_value` property which will be analogous but applicable to variables. The backend will be responsible for generating suitable assignments to variables which have this `initial_value` property set.

**Comment by arporter** [comment]
We also discussed moving to a canonical form where we would automatically add an Assignment into an associated Schedule when a symbol is given an initial value. However, Fortran allows intialisation of module variables (and other languages have similar features) and in that case there would be no Schedule to which to add a suitable Assignment.

**Comment by arporter** [comment]
Rather than add an analogous `intial_value` property (which pretty much exactly duplicates `constant_value`), I think it would be more natural to rename the existing `constant_value` property to `initial_value` and then separately capture whether the Symbol represents a compile-time constant.

**Comment by arporter** [comment]
Related to this issue (which I appear to have forgotten about), in reviewing #1850 Sergi suggested (https://github.com/stfc/PSyclone/pull/1850#discussion_r971069118)  that we should change the way we store an UnknownType so that the stored text does *not* include the variable name. That could be part of this work.

**Comment by sergisiso** [comment]
> Related to this issue (which I appear to have forgotten about), in reviewing https://github.com/stfc/PSyclone/pull/1850 Sergi suggested (https://github.com/stfc/PSyclone/pull/1850#discussion_r971069118) that we should change the way we store an UnknownType so that the stored text does not include the variable name. That could be part of this work.

This can be done separately in #2137, as it is needed for other things and the solution is clearer than the whole rhs initial value problem.

**Comment by sergisiso** [comment]
Ah!, maybe not, because we currently keep the initialisation value as part of the UnknownFortranType and we would lose it by just storing the declaration part.
The initialistion part has to be fixed first.

**Comment by sergisiso** [comment]
Ok, I changed the name to make it clear. @arporter Are pointer initial values (=> assignment) considered in this PR?

**Comment by arporter** [comment]
> Are pointer initial values (=> assignment) considered in this PR?

Probably not - they will still be UnknownFortranType I think.
