### ISSUE TITLE
Blocking Loop Transformation

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1423]
With #1415 now being implemented, the next step for the task-based project is to create explicit `Task` transformations with `depend` clauses.

Since we probably (for performance) want to have multiple tasks per loop, we need to have some way to transform loops to be better compatible to task. The currently implemented `taskloop` strategy looks like:
```
!$omp taskloop grainsize(32) nogroup
do i=1, 300
  a[i] = n
end do
!$omp end taskloop
```
what is likely happening in the compiler ends up probably being a blocking loop transformation on the outermost loop:
```
do outer_loop=1, 300, 32
  !$omp task firstprivate(outer_loop)
  upper_bound = min(outer_loop+32, 300)
  do i = outer_loop, upper_bound
    a[i] = n
  end do
  !$omp end task
end do
```

I think this is not so hard to do in PSyclone for the most part, though the exact minutiae I'm not so clear on.
We have some `Loop` object (called `loop` lets say), which has 4 children: `start`, `stop`, `step`, and a `Schedule`.

(Here we skip a bunch of me learning how things work)

I have a minicode that demonstrates the behaviour for a simple loop (in a test because that was easiest):
```
def test_omptaskwait_validate_no_taskloop(fortran_reader, fortran_writer):
    '''Test the validate method of the OMPTaskwaitTrans fails when supplied
    a parallel region containing no taskloops'''
    code = '''
    subroutine sub()
        integer :: ji, jj, n
        integer, dimension(10, 10) :: t
        integer, dimension(10, 10) :: s
        do jj = 1, n
            do ji = 1, 10
                s(ji, jj) = t(ji, jj)
            end do
        end do
    end subroutine sub
    '''
    psyir = fortran_reader.psyir_from_source(code)

    # Pull out our loop
    loop = psyir.children[0].children[0]

    # Create (or find) the symbols we need
    end_loop = loop.variable.find_symbol_table(psyir.children[0]).symbol_from_tag("inner_blocking_loop_end_tag", symbol_type=DataSymbol, datatype = loop.variable.datatype)
    start_outer_loop = loop.variable.find_symbol_table(psyir.children[0]).symbol_from_tag("outer_blocking_loop_variable", symbol_type=DataSymbol, datatype=loop.variable.datatype)
    inner_loop_start = loop.variable.find_symbol_table(psyir.children[0]).symbol_from_tag("inner_blocking_loop_start_tag", symbol_type=DataSymbol, datatype = loop.variable.datatype)
    # Find the loop's parent and the start/end indices
    loop_parent = loop.parent
    c0 = loop.children[0]
    c1 = loop.children[1]
    # Remove the loop from its parent
    loop.detach()
    # Create the end bound for the inner loop as MIN(outer_blocking_loop_variable+32, n)
    inner_loop_end_sym = Literal(end_loop.name, end_loop.datatype)
    x = BinaryOperation.create(BinaryOperation.Operator.ADD, Literal(start_outer_loop.name, start_outer_loop.datatype), Literal("32", loop.variable.datatype))
    y = BinaryOperation.create(BinaryOperation.Operator.MIN, x, Literal(c1.symbol.name, c1.symbol.datatype))
    inner_loop_end = Assignment.create(Literal(end_loop.name, end_loop.datatype), y)

    # Replace the start and end bounds of the original loop with the new bounds
    c0.replace_with(Literal(inner_loop_start.name, inner_loop_start.datatype))
    c1.replace_with(Literal(end_loop.name, end_loop.datatype))
    # Create the outer loop over blocks, containing two children
    outerloop = Loop.create(start_outer_loop, c0,  c1, Literal("32", loop.variable.datatype), [inner_loop_end, loop])
    # Add the loop to the parent schedule - here i'm just adding it at position 0 but it probably should be where the original loop was
    loop_parent.addchild(outerloop, 0)
    print(fortran_writer(psyir))
    assert(False)
```

The output from this program is what I expect:
```
subroutine sub()
  integer :: ji
  integer :: jj
  integer :: n
  integer, dimension(10,10) :: t
  integer, dimension(10,10) :: s
  integer :: inner_blocking_loop_end_tag
  integer :: outer_blocking_loop_variable
  integer :: inner_blocking_loop_start_tag

  do outer_blocking_loop_variable = 1, n, 32
    inner_blocking_loop_end_tag = MIN(outer_blocking_loop_variable + 32, n)
    do jj = inner_blocking_loop_start_tag, inner_blocking_loop_end_tag, 1
      do ji = 1, 10, 1
        s(ji,jj) = t(ji,jj)
      enddo
    enddo
  enddo

end subroutine sub
```

There are quite a few things that I do in my mini code that probably don't work in general:
1. Loop start, end and step variables don't have to be written as `i=1, n`, but can be more complex expressions. This means the MIN operation becomes more complex to construct (as its not just literals or constants, but could be general expressions). Maybe one can just do `.copy()` to setup these things?
2. If a step variable is not a constant, this is even more complicated, as there are then 3 cases that must be handled in the child nodes.
  a. Positive case
  b. Negative case
  c. Zero case (error, can't block a loop with no end known)
3. Probably we need to check the loop variable is not written to by the expressions inside the loop (is that allowed in Fortran?).
4. Probably many more things I'm unclear on

 @rupertford is this something you have time to look at or should I do this next month at some point? We probably should discuss this in more detail so I don't miss things if me and know how best to use the various pieces.

**Comment by arporter** [comment]
You can't do (3) in Fortran. However, the PSyIR is language agnostic and therefore we probably would need to check for this.

**Comment by LonelyCat124** [comment]
Yeah - I assume the same is true for the step and loop_end variables as well.

**Comment by sergisiso** [comment]
Fortran loops take the loop bounds values at the commencement of the loop, so you can write into the symbols that you used for loop_end and step without it being a dependency or altering the trip count.

This is different semantics than C where a for is just syntactic sugar for a while loop with index increases but I in PSyIR we just have to consider the loops being semantically equivalent to Fortran and deal with the differences in the C backend (by creating some temporal assignment before the loops, I was aware of this but it was not done in the OpenCL work because there are no Loops inside the kernel but I see  a loop_node visitor has made it inside inside the c.py backend and it doesn't consider this!)

**Comment by rupertford** [comment]
I doubt I'll have time to look I'm afraid, but I'd be happy to discuss if you do. You can certainly constrain what you implement which is what Fortran does in the language anyway. Blocking is certainly something that would be great to be able to do in general. The simple act of creating two loops from one and moving the content around appropriately is done in the colouring transformation so that might be a good place to look for something similar that has passed code review.

**Comment by LonelyCat124** [comment]
From discussing with Sergi the `ColourTrans`  seems to have API-specific parts to it (for example even the call `colours_loop = node.__class__(parent=node_parent, loop_type="colours")` doesn't work for a generic `Loop` object). I'm not sure if that transformation's docstring should be updated to specify what loop objects it does work for, as this code would fail:
```
    code = '''
        subroutine sub()
        integer :: ji, jj, n
        integer, dimension(10, 10) :: t
        integer, dimension(10, 10) :: s
        do jj = 1, n
            do ji = 1, 10
                s(ji, jj) = t(ji, jj)
            end do
        end do
    end subroutine sub
    '''
    psyir = fortran_reader.psyir_from_source(code)
    ctrans = ColourTrans()                                                                                                                                                     
    ctrans.apply(psyir.children[0].children[0])
```

I can make a separate issue for that if this is something that should be changed.

**Comment by rupertford** [comment]
OK, if it is not useful then feel free to write it your own way. It was written for LFRic way back when so was probably a bad suggestion.

**Comment by LonelyCat124** [comment]
What do people think about having a separate "BlockedLoop" class in PSyIR? There could be transformations (such as task) which probably should only be applied to blocked loops. I'm a bit confused about the `Loop` class and subclasses - would it be sufficient to do something like:
```
class BlockedLoop(Loop):
    def __init__(self, parent=None, vairable=None, valid_loop_types=None, annotations=None):
        super(BlockedLoop, self).__init__(self, parent=parent, annotations=annotations, valid_loop_types=valid_loop_types
        if "blocked" not in self._valid_loop_types:
            self._valid_loop_types.append("blocked")
        self._loop_type = "blocked"
```

**Comment by arporter** [comment]
Where `BlockedLoop` would be the new  loop over blocks created when blocking a `Loop`? I think that makes sense.

**Comment by sergisiso** [comment]
Would the BockedLoop node represent the 2 Loops (blocks and individual elements) or is just a regular loop with the "blocked" as loop_type and the logic around it, but still have the other loop inside? 

(Also note that I think a separation between a basic canonical loop and a PSyLayer Loop with all the loop_type and bounds is due)

**Comment by LonelyCat124** [comment]
I implemented as just a regular loop with "blocked" as loop_type.

**Comment by sergisiso** [comment]
Can the 'loop_type' be a constructor argument of the generic Loop instead of creating a new class, or is there other things to consider later on that would benefit for being a different class?

(I noticed that OpenMP 5 has introduced a "tile" clause, is this something that can be used in your use case and is it supported by compilers..)

**Comment by LonelyCat124** [comment]
I'm not using the constructor of the generic class (and it doesn't support it I think at the moment), but instead the `Loop.create()` functionality. I could just do `loop_type = X` but I couldn't see how to change `_valid_loop_types` so I wouldn't be able to add it.
I didn't want to edit the base class for now because I don't know how it might affect other code. Perhaps it needs to be a separate issue to refactor the `Loop` class?

I could potentially use `tile` maybe, I've not looked at it before. If we want to have DSL-specific restrictions though it might be better to not use it. I'll test it next time I'm working on PSyclone perhaps.

**Comment by sergisiso** [comment]
For GOcean you can add new loop_types in the VALID_LOOP_TYPES field of `src/psyclone/domain/gocean/gocean_constants.py` but I also don't know if it might affect other code.

There is an issue to refactor the Loop class in #1393 where you can list new requirements/improvements there. In this case I would say to not have the valid_loop_type as a constructor argument if the valid types are already taken from the APIConstants, as it just makes things confusing regarding where it comes from.
