### ISSUE TITLE
psyad does not changes intents of variables

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1429]
The iintents of active variables may differ from the TL and its adjoint. For example, something that is only read (intent in) in the tangent linear might be read and written in its adjoint (intent inout). psyad does not currently deal with this. The example has had to be changed as a result of this problem in order to allow it to compile.

**Comment by arporter** [comment]
I was thinking that the simplest thing to do was to change the Access of any active variables to be inout. However, given that we've hit problems before where the compiler gets upset if a variable is used as an argument without any intent further up the stack, I'm thinking that it might be better to use the DependenceAnalysis to determine what the Access should be. What do you think @rupertford?

**Comment by rupertford** [comment]
I don't like making them all inout, we might as well not provide any intent information at all in that case - which is a fallback option. We could require the TL code to provide intent which would be reasonable for LFRic but probably not for code in general. Again in LFRic we could look at the metadata - but that is more of a consistency check with the intent.

How about, for LFRic we require intent's to be specified (with a config setting). For more general code we look for intent, we then try data dependence analysis if intent is not specified and we fall back to providing no intent information if dependence analysis does not work (with a warning message added)?

**Comment by arporter** [comment]
This is for the adjoint kernel so I'm not sure whether having the intents for the TL kernel actually helps us?

**Comment by rupertford** [comment]
I was thinking that we can determine the Adjoint intents from the TL intents, but you are right, it also depends on the structure of the assignment statements in the adjoint, so this is not possible.

**Comment by rupertford** [comment]
So, I agree that the simplest thing to do is to use the dependence analysis. We could keep track of accesses as we generate the adjoint code but that complicates things.
