### ISSUE TITLE
GOcean API expects kernel meta-data to use READ/WRITE keywords

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#144]
For some reason we dropped the "GH_" prefix on the names used to identify different types of argument access for GOcean kernels. Unfortunately this means they clash with Fortran reserved names (because our kernel meta-data is itself Fortran). This is Bad. Not only that, and more immediately, it causes the Omni compiler to seg. fault when parsing kernel code.

I propose we put back the prefix. In fact, I already have a ticket (https://github.com/stfc/dl_esm_inf/issues/3) to do this for `dl_esm_inf` where I'm using "GO_" as a prefix. We need to update PSyclone to use that too.

**Comment by arporter** [comment]
@hiker - I've brought you in to this Issue to check that I'm OK to go ahead and make this change? If it's going to cause you a lot of hassle I can hold off.

**Comment by hiker** [comment]
Go ahead, no need to wait for me.

**Comment by arporter** [comment]
Closing as a duplicate of #198.
