### ISSUE TITLE
the big picture

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#145]
It would be useful to capture existing and future developments in PSyclone so people can see what's been done and what could be looked at. A concept graph or mindmap view would probably make most sense.

**Comment by rupertford** [comment]
Created bigpicture branch

**Comment by rupertford** [comment]
Created and added a mindmap outlining the big picture as I see it.
The mindmap is created in Linux using vym (view your mind). I chose this as it is a freely available Linux tool.

**Comment by rupertford** [comment]
The Met Office use freemind version 0.9.0 (as kindly confirmed by @TeranIvy). This has advantages over vym, which is what we are currently using. Therefore we will migrate. This requires a file format change. There is a conversion tool https://sourceforge.net/projects/vym2fm/ and a separate xslt script here http://freemind.sourceforge.net/wiki/index.php/Import_and_export. I will try to convert automatically.

**Comment by arporter** [comment]
Closing this issue has the branch was merged a while ago.
