### ISSUE TITLE
Re-write Kernel meta-data when creating adjoint of Kernel

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1453]
Currently the Fortran produced by PSyAD does not have any meta-data associated with it - it is left to the user to copy over that from the tangent-linear kernel and modify it appropriately.

Given that the existing meta-data support in PSyclone relies upon fparser1, we plan to produce new, standalone functionality that uses fparser2 to read kernel meta-data, store it in some suitable structure and then allow it to be serialised again.

**Comment by rupertford** [comment]
Metadata is output in the adjoint code, it is just unchanged from the metadata in the tl code and is therefore incorrect. The descriptions of the kernel arguments needs to be modified (probably just their use i.e. gh_read etc.) and the pointer to the kernel subroutine also needs to be changed to reflect the new subroutine name.

**Comment by arporter** [comment]
I've started on a skeleton of a class that will take a parse tree and extract meta-data information from it.

**Comment by arporter** [comment]
Just a note to say that the current metadata parser requires that we know the name of the kernel beforehand. It would be better if it just found the name of the kernel itself (I've added a TODO for this in my algorithm-generation code in #1620).
