### ISSUE TITLE
Bug in the ArrayRange2Loop transformation

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1487]
The ` NemoAllArrayRange2LoopTrans()` converts:
`pah1(:,:,jk) = pahs1(:,:) * (  zratio + zc * ( 1._wp + TANH( - ( gdept_0(:,:,jk) - zh ) * zw) )  )`

to
```
do jj = 1, jpj, 1
  do ji = 1, jpi, 1
    pah1(ji,jj,jk) = pahs1(ji,jj) * (zratio + zc * (1._wp + TANH(- (gdept_0(:, :, jk) - zh) * zw)))
   enddo
enddo
```
note that gdept_0 still has the array notation

**Comment by arporter** [comment]
This one might be hard to fix as it depends on the definition of the function being called (TANH in this case). Presumably TANH has the ELEMENTAL attribute?

**Comment by rupertford** [comment]
Yes, I guess the transformation thinks it is an array slice. The transformation only special cases matmul so I'm not sure why this is.

**Comment by sergisiso** [comment]
This transformation also fails with an "InternalError:  The number of ranges in the arrays within this assignment are not equal. This is invalid PSyIR and should never happen." in:
` htr_ove(:,1) = SUM( v_msf(:,:,1)*tn_jk(:,:,1) ,2 )`

so as @arporter suggested it may have issues with the intrinsic functions as the similar:
`sn_jk(:,:,1) = ptr_sjk( zts(:,:,:,jp_sal) ) * r1_sjk(:,:,1)`
and
` v_msf(:,:,1) = ptr_sjk( zvn(:,:,:) )`
in the same code are done alright.

**Comment by sergisiso** [comment]
This may be a different issue of the same transformation but it also has a SUM involved:

This code
```
DO jj = 1, jpj
  DO ji = 1, jpi
    IF( MOD(mig(ji), 3) == 1 .AND. MOD(mjg(jj), 3) == 1 ) THEN   ! bottom left corber of a 3x3 box
      ji2 = MIN(mig(ji)+2, jpiglo) - nimpp + 1                  ! right position of the box
      jj2 = MIN(mjg(jj)+2, jpjglo) - njmpp + 1                  ! upper position of the box
      IF( ji2 <= jpi .AND. jj2 <= jpj ) THEN                    ! the box is fully included in the local mpi domain
        p2d(ji:ji2,jj:jj2) = SUM(p2d(ji:ji2,jj:jj2))
      ENDIF
    ENDIF
  END DO                                                                                                                                                                                          END DO
```
becomes:
```
do jj = 1, jpj, 1
  do ji = 1, jpi, 1
  if (MOD(mig(ji), 3) == 1 .AND. MOD(mjg(jj), 3) == 1) then
    ji2 = MIN(mig(ji) + 2, jpiglo) - nimpp + 1
    jj2 = MIN(mjg(jj) + 2, jpjglo) - njmpp + 1
    if (ji2 <= jpi .AND. jj2 <= jpj) then
      do jj = jj, jj2, 1
        do ji = ji, ji2, 1
          p2d(ji,jj) = SUM(p2d(ji,jj))
        enddo
      enddo
    end if
   end if
  enddo
enddo
```
And the inner loops have the same indexing symbols that the outer ones and does not compile:
```
NVFORTRAN-W-0115-Assignment to DO variable jj in loop (lib_fortran.f90: 363)
NVFORTRAN-W-0115-Assignment to DO variable ji in loop (lib_fortran.f90: 364)
NVFORTRAN-S-0074-Illegal number or type of arguments to sum - keyword argument array  (lib_fortran.f90: 365
```

**Comment by sergisiso** [comment]
Also:
```
z_abflux(:,:) = z_abflux(:,:) + p_hflux_bkginc
```
becomes:
```
do jj = 1, jpj, 1
   do ji = 1, jpi, 1
     z_abflux(ji,jj) = z_abflux(ji,jj) + p_hflux_bkginc                                                                                                                                              
  enddo
enddo
```
but p_hflux_bkginc is a 2d array defined as  `REAL(KIND = wp), DIMENSION(jpi, jpj), OPTIONAL, INTENT(IN) :: p_hflux_bkginc` (a UnknownFortranType for PSyIR?). Maybe we should refuse to do it if there is a UnknownFortranType?

**Comment by sergisiso** [comment]
And it also have some issues around derived types acessors:
```ptsd(:,:,:,jp_tem) = sf_tsd(jp_tem)%fnow(:,:,:)```
becomes:
```
do jk = 1, jpk, 1
  do jj = 1, jpj, 1
    do ji = 1, jpi, 1
      ptsd(ji,jj,jk,jp_tem) = sf_tsd(jp_tem)%fnow(:,:,:)
    enddo
  enddo
enddo
```

**Comment by rupertford** [comment]
This is like re-living the Manchester United Liverpool game :-p
