### ISSUE TITLE
[PSyAD] Test harness needs to initialise dof map arrays correctly

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1496]
Currently the PSyAD test harness initialises every kernel argument using pseudo-random numbers. However, LFRic kernels that iterate over cells are passed a dofmap array. This will need initialising with correct index data rather than random numbers.

**Comment by arporter** [comment]
As suggested by Joerg and Iva, I've taken a look at `examples/lfric/eg17` which contains a fully executable LFRic example. The problem I've got is that PSyAD is (deliberately) ignorant of the LFRic API at the moment - it deals with Fortran subroutines and does not therefore know that their arguments are fields and dofmaps etc. etc. Further, although I could (manually at the moment) construct appropriate fields following eg17, I would then need to pull out the raw data to call the subroutine at which point I would need a proxy. This is obviously what we already do when constructing the PSy layer. So long as it is only ever LFRic Algorithm-layer variables that are 'active' then the solution to this feels as though we should be constructing the test harness using `invokes` and then running PSyclone on it to generate executable code.

**Comment by arporter** [comment]
Alternatively, to avoid developing an LFRic-specific test harness implementation, we wait unti kernel extraction/driver creation is fully working and use that to generate a test harness (since it will work with raw arrays etc.).

**Comment by arporter** [comment]
The test harness for a generic subroutine does:

    ! Assign random data to inputs and keep copies
    ! CALL random_number(field1)
    ascalar_input = ascalar
    field1_input = field1
    field2_input = field2
    ! Call the tangent-linear kernel
    call testkern_code(ascalar, field1, field2, npts)
    ! Compute the inner product of the results of the tangent-linear kernel
    inner1 = 0.0
    inner1 = inner1 + ascalar * ascalar
    inner1 = inner1 + DOT_PRODUCT(field1, field1)
    inner1 = inner1 + DOT_PRODUCT(field2, field2)
    ! Call the adjoint of the kernel
    call testkern_code_adj(ascalar, field1, field2, npts)
    ! Compute inner product of results of adjoint kernel with the original inputs to the tangent-linear kernel
    inner2 = 0.0
    inner2 = inner2 + ascalar * ascalar_input
    inner2 = inner2 + DOT_PRODUCT(field1, field1_input)
    inner2 = inner2 + DOT_PRODUCT(field2, field2_input)
    ! Test the inner-product values for equality, allowing for the precision of the active variables
    MachineTol = SPACING(MAX(ABS(inner1), ABS(inner2)))
    relative_diff = ABS(inner1 - inner2) / MachineTol
    if (relative_diff < overall_tolerance) then

**Comment by arporter** [comment]
As an invoke, this might be:

    call random_number(ascalar)
    ascalar_input = ascalar
    call invoke( setval_random(field1), &
                 setval_random(field2), &
                 setval_X(field1_input, field1), &
                 setval_X(field2_input, field1), &
                 ! Call the tangent-linear kernel
                 tl_testkern_type(ascalar, field1, field2), &
                 X_innerproduct_X(rinner1, field1), &
                 X_innerproduct_X(rinner2, field2) )
    inner1 = ascalar*ascalar + rinner1 + rinner2
    call invoke( adj_testkern_type(ascalar, field1, field2), &
                 X_innerproduct_Y(rinner1, field1_input, field1), &
                 X_innerproduct_Y(rinner2, field2_input, field2) )
    inner2 = ascalar_input*ascalar + rinner1 + rinner2
    ! Code to compare inner-product values remains as before...

**Comment by rupertford** [comment]
Ooh, using PSyclone builtins as part of the harness. That is great.

**Comment by arporter** [comment]
> Ooh, using PSyclone builtins as part of the harness. That is great.

"I love it when a plan comes together" :-)

**Comment by arporter** [comment]
It turns out that the `quadrature` modules in our LFRic test infrastructure aren't being compiled.

**Comment by arporter** [comment]
I now have the code generation for this 'working' (on `1555_alg_gen`) but the code itself seg. faults in the function-space module. Possibly the examples in eg17 don't use builtins?

**Comment by arporter** [comment]
It turned out to be quite simple - I wasn't initialising the field objects that were copies of the original kernel arguments. Code now runs successfully but the test fails.

**Comment by arporter** [comment]
This is working now (modulo bugs in the PSyAD transformation itself). I need to bring the functionality from my standalone `module_gen.py` script and put it into PSyAD as a function to generate a test for an LFRic kernel. There's then a bit of a naming question: the test-harness generation code currently in PSyAD works for generic code so I'm not sure what to call it. Do you have any ideas @rupertford?
