### ISSUE TITLE
Reference cell information in kernels

### ISSUE THREAD

**Issue by thomasmelvin** [stfc/PSyclone#150]
Some gungho kernels need information from the reference element. This used to be handled by using the reference element module and so now psy layer infrastructure calls were required. However since the refernce element is now an object belonging to the mesh the information is extracted from the mesh in the psy layer and passed to the kernel. PSyclone needs to support the relevant kernel metadata and psy layer infrastructure calls. As an example `sample_poly_adv_kernel_mod` requires an array of face normal vectors. The metadata is uses is:
    `type(mesh_data_type) :: meta_init(1) = (/             &`
     `mesh_data_type( reference_element_out_face_normal ) &`
     `/)`
and the psykal-lite code is:
`  mesh => flux%get_mesh()`
`  reference_element => mesh%get_reference_element()`
`  call reference_element%get_normals_to_out_faces( out_face_normal )`

This is similar to the information required by #18 and maybe covered by #59

**Comment by arporter** [comment]
There is an alternative way to alter the meta-data and that is to follow what we do in the GOcean API when mesh properties are required:

    type(arg), dimension(4) :: meta_args =     &
          (/ arg(WRITE, CU, POINTWISE),        &
             arg(READ,  CU, POINTWISE),        & 
             arg(READ,  CF, POINTWISE),        &
             arg(READ,  GRID_DY_CONST)         &
           /)

i.e. we just have a set of names that we recognise for kernel arguments (`GRID_DY_CONST` in the above example) and PSyclone provides them to the kernel. This has the advantage that it doesn't involve us adding a further section to the kernel meta-data (the `meta_init` in your example).

**Comment by thomasmelvin** [comment]
I am happy with that suggestion, it would be good to treat mesh information the same way between the GOcean and Gungho API. This will of course require a change in lfric metadata to match this format

**Comment by arporter** [comment]
So, I'm tracking back from #193 and think I might need to do this one first. Is that right @thomasmelvin? Following on from the above, I propose extending the meta-data so that it might look like:

     type(arg_type), dimension(6) :: meta_args =    &
          (/ arg_type(gh_real, gh_read),     &
             arg_type(gh_field,gh_write,w1), &
             arg_type(gh_field,gh_read, w2), &
             arg_type(gh_field,gh_read, w2), &
             arg_type(gh_field,gh_read, w3),  &
             arg_type(reference_element_out_face_normal) &
           /)

Is that OK?

**Comment by thomasmelvin** [comment]
That looks correct,

Im not sure you have to do this before #193 but we do need them both so it is up to you how to do them.

**Comment by arporter** [comment]
@thomasmelvin: do you have a list of the names of the quantities that a kernel might require from the reference element?

**Comment by arporter** [comment]
I have the meta-data parsing sorted-out now. However, I've broken a few other tests in the process because the text and type of some error conditions have been changed. (I've taken the opportunity to use the new `InternalError` class where appropriate.)

**Comment by arporter** [comment]
Hi @thomasmelvin, hope you had a good break. Just a reminder that I need the list of recognised mesh properties so that I can get on with this ticket.

**Comment by TeranIvy** [comment]
Hi @arporter and @thomasmelvin! I am just revisiting the list of PSyKAl-lite subroutines so I can provide this information here. Tom, please update/correct it if required.

Relevant [psykal_lite_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/psy/psykal_lite_mod.F90) routines are listed below.

- `invoke_rtheta_bd_kernel`
- `invoke_ru_bd_kernel`
- `invoke_exner_gradient_bd_kernel`
- `invoke_weighted_div_bd_kernel_type`
- `invoke_weighted_proj_2theta_bd_kernel_type`
- `invoke_weighted_proj_theta2_bd_kernel_type`

All of them use [reference element information](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/mesh/reference_element_mod.F90) and refer to LFRic tickets [793](https://code.metoffice.gov.uk/trac/lfric/ticket/793) and [986](https://code.metoffice.gov.uk/trac/lfric/ticket/986), as well as PSyclone issue #18.

**Comment by TeranIvy** [comment]
Two more subroutines in [psykal_lite_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/psy/psykal_lite_mod.F90) that use reference element information are
- `invoke_sample_poly_flux`
- `invoke_sample_poly_adv`

These two do not explicitly refer to #18. They do refer to #127 (generate correct limits for coloured loops) which was closed due to work in #115, #84 and #25.

**Comment by arporter** [comment]
This is great @TeranIvy - thanks very much for taking this on.

**Comment by thomasmelvin** [comment]
Thanks Iva, that looks to have it covered, sorry for not getting it done earlier Andy.

**Comment by TeranIvy** [comment]
Hi @arporter! I am going through the relevant PSyKAl-lite subroutines and things are a bit more complicated than just using reference element information, as quite a few of them use face quadrature as well (#193). It will take me a couple of days to collate PSyKAl code, relevant metadata and where quantities are picked up from. I will then send the information to both @thomasmelvin and you so you decide about order of what needs to be done when.

**Comment by arporter** [comment]
Ooh, that does sound complicated. From what @thomasmelvin said previously, I think I can either do this one or #193 but since I've started this one I'll do this first :-)

**Comment by arporter** [comment]
After our telco today we've agreed to adopt Tom's suggested meta-data (i.e. add support for a `mesh_data_type`). @TeranIvy has kindly agreed to provide us with a list of names of properties that we will recognise.

**Comment by arporter** [comment]
Do we really want to call the new meta-data element "meta_init"? I ask because the meta-data describing arguments is "meta_args", that for basis/diff-basis functions is "meta_funcs". Is "meta_init" meaningful or would something like "meta_refcell" or some such be better?

**Comment by arporter** [comment]
Looking at https://code.metoffice.gov.uk/trac/lfric/ticket/986, it seems that there are only three reference-cell properties that we need to support: adjacent_face, normal_to_face and out_face_normal. Is that correct @thomasmelvin and @TeranIvy? Please could you provide me with a brief text description of what each of these is.

**Comment by arporter** [comment]
Actually, don't worry about the text descriptions - I can get that from the kernel documentation in the code.

**Comment by TeranIvy** [comment]
Merged #360 with the metadata design and rules. Will this issue be kept as the umbrella issue for the overall work (more PRs), @arporter?

**Comment by arporter** [comment]
Yes, I'll keep this Issue open - thanks @TeranIvy .

**Comment by arporter** [comment]
`DynKernMetaData` needs extending to hold which properties of the Reference Element are required (if any).

**Comment by arporter** [comment]
Support for parsing the meta-data is now on master so I'll move on to adding the code-generation support.

**Comment by arporter** [comment]
@TeranIvy is the reference-element meta-data on LFRic trunk? I've just updated my copy and can see that infrastructure/source/field/argument_mod.F90 defines `reference_element_number_horizontal_faces`, `reference_element_normal_to_face` and `reference_element_out_face_normal` but not `reference_element_data_type`.

**Comment by arporter** [comment]
@TeranIvy could you point me to an LFRic branch (if there is one) that has the updated Reference Element so I can see which methods to call in order to pull out the various normals that are needed.

**Comment by arporter** [comment]
This is now waiting on the implementation of the corresponding functionality in the LFRic infrastructure. However, I can get on with generating the necessary arguments in the kernel calls.

**Comment by arporter** [comment]
I have the code generation basically working now. It's awaiting final confirmation of the precise form of the LFRic API to target and then I'll need to get the compilation tests working. While doing this I realised that each member of an `Enum` has a name by which it can be accessed and that allows me to do away with the dictionary of meta-data names.

**Comment by TeranIvy** [comment]
Merged
- PR #360 (document rules),
- PR #535 (parsing metadata),
- PR #605 (code generation),
for reference element information so I am very happy to close this issue as completed :-)
