### ISSUE TITLE
Planning new release 1.6.0(?)

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#151]
The Met Office would like access to the latest functionality on master plus a couple of PRs which are currently in review. Looking at the changelog, I think that there are enough big changes to merit bumping to 1.6.0. 

I tried to summarise the current situation below. Please edit as appropriate.

Dynamo0.3 and GOcean1.0 API related additions to master:
- Fix errors in Fortran test files revealed by update to fparser 0.0.6.
- Dynamo0.3: Support integer, read-only, built-in scalar kernels plus raising a field to an integer power.
- Dynamo0.3: Support for coloured loops when performing redundant computation.
- Dynamo0.3: Make `w2v` and `wtheta` discontinuous function spaces
- GOcean1.0: Bug fix for passing kernel arguments by value.
- GOcean1.0: Support for a swap-loop transform.

Dynamo0.3 required functionality (currently in review)
- ~~PR #136: Inter-grid kernels.~~
- ~~PR #149: RW access for discontinuous quantities.~~
- ~~PR #120: Implement CLAW interface (?)~~

GOcean1.0 required functionality (currently in review)
- ~~PR #143: DAG generation fix (?)~~

fparser 
- New release 0.0.7 - required because fparser1 API has changed.
- Ideally, PRs https://github.com/stfc/fparser/pull/78 (wipe cache by default) and https://github.com/stfc/fparser/pull/71 (support comments in fparser2) should be reviewed and merged before we make a new release. Since 71 only affects fparser2 and is a bigger change we could hold off on this.

**Comment by arporter** [comment]
The interface to fparser has changed slightly. #154 will update PSyclone to match. Until this is done, master of PSyclone will not work  with master of fparser.

**Comment by arporter** [comment]
#143 is now on master and we've had a re-think about CLAW and dropped #120 as a result.

**Comment by arporter** [comment]
re. an fparser release, https://github.com/stfc/fparser/pull/78 and https://github.com/stfc/fparser/pull/71 are outstanding and I'd like them merged before we make a new release. In order to share the load I've requested @TeranIvy to review 78 :-)

**Comment by arporter** [comment]
I've released fparser 0.0.7 (licensed to parse). Next step is to finish #154.

**Comment by TeranIvy** [comment]
Licensed to parse :laughing:

**Comment by arporter** [comment]
:-) No, #166 is not required for this release. It will be required for CLAW/Omni integration but that's something for the future.

**Comment by arporter** [comment]
1.6.0 has been released. pypi and readthedocs have updated automatically.
I've emailed the lfric list.
