### ISSUE TITLE
SymPy and pre-defined functions

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1523]
While trying to fix #753 with
```
$ git diff domain/common/algorithm/psyir.py
diff --git a/src/psyclone/domain/common/algorithm/psyir.py b/src/psyclone/domain/common/algorithm/psyir.py
index 395b45196..38197c287 100644
--- a/src/psyclone/domain/common/algorithm/psyir.py
+++ b/src/psyclone/domain/common/algorithm/psyir.py
@@ -39,6 +39,7 @@
 '''
 from __future__ import absolute_import
 
+from psyclone.core import SymbolicMaths
 from psyclone.psyir.nodes import Call, Reference, DataNode, Literal, \
     ArrayReference
 from psyclone.psyir.symbols import DataTypeSymbol, ContainerSymbol, \
@@ -175,6 +176,7 @@ class AlgorithmInvokeCall(Call):
 
         arguments = []
         arguments_str = []
+        sym_maths = SymbolicMaths.get()
         for kern in self.children:
             for arg in kern.children:
                 if isinstance(arg, Literal):
@@ -183,7 +185,10 @@ class AlgorithmInvokeCall(Call):
                 elif isinstance(arg, (Reference, ArrayReference)):
                     # TODO #753 use a better check for equivalence
                     # (symbolic maths)
-                    if str(arg).lower() not in arguments_str:
+                    for existing_arg in arguments:
+                        if sym_maths.equal(arg, existing_arg):
+                            break
+                    else:
                         arguments_str.append(str(arg).lower())
                         arguments.append(arg.copy())
                 else:
```
I realised that the corresponding test in 'tests/domain/common/algorithm/alg_psyir_test.py` still fails. Reason appears to be that this test uses:
```
        "  call invoke(kern(field(i+1), field(1+i)))\n"
```
and `field` is a SymPy python functions, so parsing (which uses `eval`) fails. Changing the name from `field` to something else fixes the issue.

We need to find a way to disable that using a variable that clashes with a SymPy Python function causes this kind of failures :(

**Comment by hiker** [comment]
Solution seems to be to define a local dictionary, that maps all symbols in the expression to a (new) SymPy symbol. The following code hard-codes field, but shows how to fix the failure:
```
        field_symbol = symbols('field')
        str_exp1 = parse_expr(self._writer(exp1), local_dict = {'field': field_symbol} )
```
It should be easily possible to get all symbols in an expression, define then as symbols. 

Interestingly, that might also be an easy way to fix 'known functions' like max: define a dictionary entry that maps MAX to the sympy function Max.

**Comment by hiker** [comment]
Note that in case of derived type, we need to define all components used as symbols, e.g: `a%b` is mapped to `MOD(a, b)`, so `a` and `b` needs to be symbols.

**Comment by hiker** [comment]
In order to avoid further issues (e.g. ``a%b(b)``), my suggested solution:
1) An access like ``a(i)%b(j)%c%d(k)`` is converted to the sympy expression ``a_b_c_d(i,j,k)``. We declare ``a_b_c_d`` as a function (which means sympy will compare the indices, which is exactly what we want). 
2) We use a symbol table in case that ``a_b_c_d`` is an existing variable used in the expression.

Seeing #1537, the following extension of this should work:

3) We change  ``a(i)%b(j)%c%d(k)`` to be ``a_b_c_d(i,i,j,j,k,k)``. An array expression(``a(:)``) would be converted to ``a(-inf,+inf)`` (well, infinity is called ``zoo`` in sympy .... `00` as ininity I guess). As far as I can see this should cover all possible use cases (e.g. ``a(i:) == a(i)`` --> ``a(i, +inf) == a(i,i)``, which evaluates to false, as we would expect. And ``a(i:i) == a(i)`` with this logic, which I believe might be what we want (?? I think ``a(i:i)`` is an array with 1 element, not a scalar ... not entirely sure what we want in this case tbh).

**Comment by rupertford** [comment]
This is probably of no help, but to avoid the problem @arporter was talking about (although he suggested it be checked before flattening), could the indices be preceded by the variable name? i.e. `a(i)%b(j)%c%d(k)` => `a_b_c_d(a_i,b_j,d_k)`

**Comment by rupertford** [comment]
Although I guess that does not fix all potential cases as you could potentially have `a%a(:)` and a(:)%a`. You would need to carry the depth of the index access with the index instead i.e. `a(i)%b(j)%c%d(k)` => `a_b_c_d(i_1,j_2,k_4)`.

**Comment by hiker** [comment]
> This is probably of no help, but to avoid the problem @arporter was talking about (although he suggested it be checked before flattening), could the indices be preceded by the variable name? i.e. `a(i)%b(j)%c%d(k)` => `a_b_c_d(a_i,b_j,d_k)`

No, since e.g. in case if ``a(i)%b(i+1)`` we would get ``a_b(i_a, i_b+1)`` - which means we don't know that ``i_a`` is the same as ``i+b``.

**Comment by hiker** [comment]
> Although I guess that does not fix all potential cases as you could potentially have `a%a(:)` and `a(:)%a`. You would need to carry the depth of the index access with the index instead i.e. `a(i)%b(j)%c%d(k)` => `a_b_c_d(i_1,j_2,k_4)`.

I think it is the same issue as above - if ``i`` is used as index in different members, we don't know that ``i_1`` and (e.g.) ``i_2`` are the same. I admit I am not sure how important that is, it might not matter for our tests??? But I don't like restricting what we can deduce from the information we have.

Otherwise, I would need to try to see if this is actually accepted in Fortran (i.e. that if 'a' is an array of a structure, if this kind of array expression is allowed - after all the code is from the same subroutine (I think we can assume that, otherwise you know nothing ... even ``a`` might not be ``a`` otherwise). , so ``a%a(:)`` would be an array expression for the outer ``a``.

If it is allowed, the sympy writer knows that the first (outer) ``a`` is an array, so it could rewrite this as ``a(:)%a(:)``, which then becomes ``a_a(-inf,inf, -inf, inf)`` in both cases, which would work as expected.

It would be indistinguishable from ``a%a(:,:)``, but again this would be invalid Fortran as far as I can see - the same variable used as a 1d- and 2d-array.

Worst case, we can just declare all member names as functions - which needs a bit of careful symbol table management. Think of ``a%b`` and ``c%b`` - both would need a (different) 'function' b to be declared, but I think the symbol table could manage this if we use ``a_b`` and ``c_b`` as tags to create unique names. Though we would still need to 'double' the indices to handle array expressions (``a%b(i)`` becomes ``MOD(a, b(i,i))``, so we can compare with ``a%b(:)``, which would become ``MOD(a, b(-inf,inf))``.

I have the feeling that both ways would actually work  - with the latter approach a bit closer to the original Fortran.

It would be good to know what other edge cases might exist :)

**Comment by hiker** [comment]
I checked, `a%b(1)` is valid (if the `a` and `b` are arrays), as is `a(%b(1)), but not `a%b`. (or `a(:)%b(:)` etc) 

gfortran: Two or more part references with nonzero rank must not be specified at

intel: A component cannot be an array if the encompassing structure is an array.

So Rupert's case `a%a(:)` and `a(:)%a` cannot happen, since `a` and `a%a` would both be arrays.
