### ISSUE TITLE
Options to reduce indentation and remove colours in view() method

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1528]
The doc strings for two transformations are longer than 80 chars and therefore pycodestyle complains. The reason the are longer is that they provide the expected output from the view() method in an example which both shows how this works to users but can also be tested by doctest.

A simple solution would be to tell the view() method to reduce the indentation from 4 spaces to 3. However, this is currently not an option. The doctest also fails because the output is marked up with colours. Having the option to remove that as well would be useful.

**Comment by sergisiso** [comment]
To remove the colors when the output is not a terminal (e.g. output file, doctest) we can also use `from sys import stdout; if stdout.isatty():` when importing or using termcolor.

**Comment by rupertford** [comment]
Created branch [1528_modify_view](https://github.com/stfc/PSyclone/tree/1528_modify_view)

**Comment by rupertford** [comment]
Closing #1238 as it makes sense to capture and fix this here as well. This issue suggests returning a string from the view() method rather than writing it to stdout.

**Comment by rupertford** [comment]
This branch will also address issue #1238
