### ISSUE TITLE
Generalised support for applying transformations to as large a region as possible.

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1532]
From discussion in PSycloneBench, there is a common pattern (across multiple parallelisation schemes) to apply a transformation to as large a region as possible, e.g. to cover as many nodes as possible with a OMP Parallel region without breaking correctness.

Examples of this are at https://github.com/stfc/PSyclone/blob/b1d9c0107057af563a782aeb8f8becbe9906627d/examples/nemo/scripts/kernels_trans.py#L456-L499 or https://github.com/stfc/PSycloneBench/blob/009a223805e12ccd6311a7f881ff47581f1f48bd/benchmarks/nemo/nemolite2d/psykal/psyclone_scripts/omp_task_transform.py#L41-L68

I think the idea would be something like:
```
def apply_to_largest_regions(transformation, valid_types, region):
'''
    :param transformation: The transformation to apply to subregions.
    :param valid_types: List of types of node that the transformation is allowed to be applied to.
    :param region: The region to apply to (List of nodes).
'''
    # TODO Implement
    pass
```

My understanding would be the function loops over the elements of `region`, and find each top-level group of nodes to apply `transformation` over. Nodes would be valid to apply the transformation to if `isinstance(child, valid_types)`.

@arporter Anything I missed here?

**Comment by arporter** [comment]
`Node` now has the `get_sibling_lists` method:
![image](https://github.com/stfc/PSyclone/assets/17409212/5dbcdbcb-5d28-4cd6-bafa-7691d02cef72)
which I think covers the functionality discussed here. Are you OK if we close this @LonelyCat124 ?

**Comment by LonelyCat124** [comment]
Yes I think that looks like it would be sufficient for this.
