### ISSUE TITLE
Sympy comparison fails if array notation is used

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1537]
The PSyIR supports array slicing using ':' notation. However, this is causing test failures in #1526 because Sympy doesn't understand it:

    psyad/transformations/test_assignment_trans.py:574: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    psyad/transformations/test_assignment_trans.py:105: in check_adjoint
        trans.apply(assignment)
    ../psyad/transformations/assignment_trans.py:94: in apply
        if sym_maths.equal(ref, node.lhs):
    ../core/symbolic_maths.py:111: in equal
        str_exp1 = parse_expr(self._writer(exp1))
    /home/kbc59144/.python_envs/py3/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py:1026: in parse_expr
        raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
    /home/kbc59144/.python_envs/py3/lib/python3.8/site-packages/sympy/parsing/sympy_parser.py:1017: in parse_expr
        rv = eval_expr(code, local_dict, global_dict)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    code = "Function ('a' )(Integer (2 ):Integer (3 ))", local_dict = {}
    global_dict = {'Abs': Abs, 'AccumBounds': <class 'sympy.calculus.util.AccumulationBounds'>, 'Add': <class 'sympy.core.add.Add'>, 'Adjoint': <class 'sympy.matrices.expressions.adjoint.Adjoint'>, ...}

This problem occurs in psyad/transformations/assignment_trans.py when checking whether a reference on the RHS matches that on the LHS of an assignment (in order to identify whether it is performing an increment).

**Comment by arporter** [comment]
I've implemented a workaround in #1526 for now (with a TODO to this issue). Possibly a slightly better version of what I've done could be included in the `equal()` method.

**Comment by sergisiso** [comment]
This is also a problem in one nemo file that has the expression: `p2d(ji:ji2,jj:jj2)`
This is checked for dependencies when trying to add OpenMP and fails with:
```
      File "/home/ssiso/workspace/stfc/PSyclone/src/psyclone/psyir/backend/sympy_writer.py", line 173, in <listcomp>
    return [parse_expr(expr, type_map) for expr in expression_str_list]
      File "/home/ssiso/.virtualenv/psy3/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 1026, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
      File "/home/ssiso/.virtualenv/psy3/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 1017, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
      File "/home/ssiso/.virtualenv/psy3/lib/python3.6/site-packages/sympy/parsing/sympy_parser.py", line 912, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
      File "<string>", line 1
        jj :jj2
           ^
    SyntaxError: invalid syntax
```

**Comment by hiker** [comment]
I believe I have written it somewhere ... apparently not in this ticket :) My suggestion is to 'double' the array indices when we create the sympy expression:
``` 
a(i) --> a(i,i)
b(i,j,k) --> b(i,i,j,j,k,k)
a(i:j) --> a(i,j)
a(:i) --> a(-inf,j)
a(:) --> a(-inf:+inf)
```
This way it all becomes comparable with sympy - except of course that the usage of 'infinity' might give false results. It does work for `a(:i) == a(:2*i-i)` (--> `a(-inf, i) == a(-inf, 2*i-i)`), but it would fail in cases like: `a(1:n) == a(:n)`  (--> `a(1,n) == a(-inf,n)`). 

I am not sure what the best solution for this is - in general, PSyclone might not know the loop bounds, but the application might. If we know lower/upper values, we can of course use them,

Any better ideas? And how urgent is this?
