### ISSUE TITLE
RTD UG build failing to include autodoc documentation for transformations

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1538]
Comparing a local build of the UG with that on RTD, it is clear that the documentation for a lot of the transformations is missing. On looking at the logs I see:

    psyclone.configuration.ConfigurationError: PSyclone configuration error: psyclone.cfg not found in any of ['/home/docs/checkouts/readthedocs.org/user_builds/psyclone/checkouts/latest/doc/user_guide/.psyclone', '/home/docs/checkouts/readthedocs.org/user_builds/psyclone/envs/latest/share/psyclone', '/home/docs/.local/share/psyclone']

    WARNING: autodoc: failed to import class 'lfric.transformations.LFRicExtractTrans' from module 'psyclone.domain'; the following exception was raised:
    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/psyclone/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
      File "/home/docs/checkouts/readthedocs.org/user_builds/psyclone/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

**Comment by arporter** [comment]
RTD installs the package inside a virtualenv using `setup.py install` (according to the 'advanced settings' page). This *should* install the configuration file too but it clearly isn't being put in a standard location.

**Comment by arporter** [comment]
The installation log on RTD says:

    installing package data to build/bdist.linux-x86_64/egg
    running install_data
    creating build/bdist.linux-x86_64/egg/share
    creating build/bdist.linux-x86_64/egg/share/psyclone
    copying config/psyclone.cfg -> build/bdist.linux-x86_64/egg/share/psyclone

**Comment by hiker** [comment]
I wonder if this is related to #1295 - previously I've fixed up PSyclone (by the introduction of a constant object for each API) to not need PSYCLONE_CONFIG to be defined anymore, but someone added global constants or functions, which access the config object at import time (instead of at run time), which might cause this problem.

**Comment by arporter** [comment]
In helping @nmnobre with this, I was unable to find any documentation anywhere describing how we configure RTD. There should be a section in the Developer Guide about this.
