### ISSUE TITLE
Interface to set options in latest fparser has changed

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#154]
The latest fparser has changed/removed the `FortranStringReader.set_mode()` routine and we use this in various places in PSyclone. 
The module structure of fparser has also been changed in order to try and split versions 1 and 2 of the parser.
We therefore need to bring PSyclone up-to-date...

**Comment by arporter** [comment]
Am doing the work for this on the `fparser_set_mode` branch.

**Comment by rupertford** [comment]
PR #163 has been merged to master. Closing this issue.
