### ISSUE TITLE
Compilation if no GPU support is available

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1549]
At this stage ``examples/gocean/eg2`` fails compilation test if no GPU support is available on the system. I suggest we introduce a new makefile target, either:

1. `make compileall` (which will do CPU and GPU compilation), and `make compile` will only do CPU tests.
2. `make compilegpu`, which will only do GPU tests, and `make compile` will only to CPU tests.
3. `make comilegpu` and `make compilecpu`
4. Add `make compilecpu` to only compile CPU, and leave `make compile` to compile CPU and GPU

Or any other combination or name really :)

**Comment by arporter** [comment]
I'm puzzled - this has always worked for me and it still works for me on my laptop this morning (which doesn't have a GPU). In what way does it fail?

**Comment by hiker** [comment]
I still have the error on my terminal:
```
joerg@Joerg-Surface:~/work/psyclone/examples/gocean/eg2$ make compile
make inc_field_mod.o inc_field_0_mod.o
make[1]: Entering directory '/home/joerg/work/psyclone/examples/gocean/eg2'
make[1]: 'inc_field_mod.o' is up to date.
make[1]: 'inc_field_0_mod.o' is up to date.
make[1]: Leaving directory '/home/joerg/work/psyclone/examples/gocean/eg2'
gfortran  inc_field_*mod.o psy.o alg_gen.o ../../../external/dl_esm_inf/finite_difference/src/lib_fd.a -o single.exe
/usr/bin/ld: /tmp/ccaav0QV.crtoffloadtable.o:(.rodata+0x0): undefined reference to `__offload_func_table'
/usr/bin/ld: /tmp/ccaav0QV.crtoffloadtable.o:(.rodata+0x8): undefined reference to `__offload_funcs_end'
/usr/bin/ld: /tmp/ccaav0QV.crtoffloadtable.o:(.rodata+0x10): undefined reference to `__offload_var_table'
/usr/bin/ld: /tmp/ccaav0QV.crtoffloadtable.o:(.rodata+0x18): undefined reference to `__offload_vars_end'
/usr/bin/ld: /tmp/cc5RYbQW.target.o: in function `init':
cc8NqdY1.c:(.text+0x21): undefined reference to `GOMP_offload_register_ver'
/usr/bin/ld: /tmp/cc5RYbQW.target.o: in function `fini':
cc8NqdY1.c:(.text+0x49): undefined reference to `GOMP_offload_unregister_ver'
collect2: error: ld returned 1 exit status
make: *** [Makefile:99: single.exe] Error 1
```
I assumed this would indicate a GPU issue. So I did a 'make allclean' ... and then it worked. Now I thought I had inconsistent compilations of dl_esm_inf or so, but interestingly 'make allclean' in eg2 does not clean dl_esm_inf (which I think is a bug :) ). Since then I have done various cleans, and whatever mixture of ifort/gfortran I use, I could not reproduce this anymore (I can recreate various compilation issues related to not being able to read a .mod file).

I am closing this as invalid.
