### ISSUE TITLE
Add support for obtaining XCodeML IR of kernel code

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#155]
This issue has come out of #114 where we were going to get PSyclone to drive CLAW directly.
We have now decided that a better solution (in terms of simplicity, dependencies and need to modify CLAW) is to get PSyclone to insert CLAW directives into a kernel. CLAW can then be run (independently) in order to transform the kernel.

Since CLAW works with the XCodeML representation of Fortran we have decided that PSyclone too will use this representation when modifying kernels. This will require that we run the Omni frontend on the Fortran kernel. In this issue we will implement support for this.

**Comment by arporter** [comment]
Currently, a PSyclone transformation script that applies OpenMP to a loop might look something like:

    PSY = PSyFactory(API).create(INVOKEINFO)
    SCHEDULE = PSY.invokes.get('invoke_0').schedule

    TRANS_INFO = TransInfo()
    OMP_TRANS = TRANS_INFO.get_trans_name('GOceanOMPParallelLoopTrans')
    OL_SCHEDULE, _ = OMP_TRANS.apply(SCHEDULE.children[0])

If this script was instead applying OpenACC, then we would need to transform the kernel within the loop by, at minimum, adding a `!$acc routine` directive to it. A script to do this might then look like:

    kern = SCHEDULE.children[0].children[0]
    kern_ast = kern.toXCodeML()
    ACC_ROUTINE_TRANS = TRANS_INFO.get_trans_name('AccRoutineTrans')
    new_ast = ACC_ROUTINE_TRANS.apply(kern_ast)

**Comment by rupertford** [comment]
Here are some thoughts ...

We could keep Kernel transformations separate from PSy transformations so that it is clear what each operated on. I think this makes sense from a Python package point of view and perhaps for discovery as well, although it is then unclear what to do with combined transformations (assuming we end up supporting such things).

We could hide the fact that we are translating to a different representation by getting the transformation to do it. This is nicer from the programming perspective, however, it would mean having to translate to and from XCodeML each time there was a transformation so I prefer the explicit solution that you propose.

We could hide the fact that we are using XCodeML, simply by calling the method something else. I'm happy to be explicit.

I presume there would also be a kern.fromXCodeML(new_ast) translation.

I think we should have Kernels marked when they have been modified (when the above fromXCodeML() method is called). This would allow PSyclone to output any modified kernels after the transformation script has run.

**Comment by arporter** [comment]
Here, the `kern_ast` object will be an XML DOM or perhaps the XML `Node` containing the body of the kernel routine. In this approach the `toXCodeML()` kernel method will need to write the kernel Fortran code to file, run Omni on it and then parse it using an XML parser (e.g. `xml.dom.minidom`).
Although we can mandate that Omni be on a user's PATH we will still need to specify the search path for any module files `use`d by the kernel. This is because Omni does a full compilation pass and therefore must be able to find Omni-compiled `.xmod` files for any modules that the kernel depends upon (either directly or indirectly). This search path will doubtless be API dependent and is something a user will have to configure when PSyclone is installed. As such we will require a 'proper' configuration file - this is the subject of #121.

**Comment by arporter** [comment]
Yes, we will have to mark kernels that have been transformed. We could do this within any kernel transformation `apply()` method. 

What do we do once a kernel has been transformed? We can either:

1. Output the (transformed) XCodeML to file ready for CLAW to be run on it
2. Generate Fortran from the XCodeML using OMNI and let the build system run CLAW on it.

The conversion back to Fortran could be done automatically (for all kernels flagged as transformed) at code-generation time. There are issues around what we call the new kernels, where we put them, and how to instruct the build system to run CLAW on them.

**Comment by arporter** [comment]
Currently PSyclone allows the user to specify the output names for both the PSy routine and the transformed Algorithm. The user is also able to supply the name of the transformation script to apply.
Do we need to add an option to specify the location to which to write modified kernels?

In #114 we concluded that we needed to re-name transformed kernels and update the PSy layer to match. Now that we're transforming the PSy-layer and the kernels from the same place, this becomes a lot nicer - any kernel transformation can look at the ancestors of the target kernel to find the `Invoke` to modify.

**Comment by arporter** [comment]
Thinking some more about this, I feel that since we're doing OO, a kernel object should stay a kernel object - its internal representation should be, err, internal. For instance, in the example above, the `ACC_ROUTINE_TRANS.apply()` could check whether we already have the XCodeML for the kernel. If we don't it could be generated and stored within the kernel object. At Fortran-generation time, we would check to see whether the kernel has an XCodeML representation and, if it has, use that to generate a new kernel.

That will be OK for simple transformations but what about for those that manipulate the AST of the kernel (i.e. where the PSyclone user is scripting the transformation)? I think for this we would simply have a getter method, e.g. `Kern.ast` or `Kern.XCodeML` that returned the AST for direct manipulation.

**Comment by arporter** [comment]
Since Omni does a full compilation pass, it expects to be able to resolve dependencies that are declared in other modules and imported via a `use` statement. This then means that we have to have Omni-compiled `.xmod` files for all modules upon which we have a dependence. However, if we exclude the kernel meta-data from the GOcean kernel sources then we have almost no `use` statements to worry about. I say "almost" because the kernels do use a kind parameter for the `real` arguments.

**Comment by arporter** [comment]
Since it is effectively impossible to have kernels that don't `use` modules, I've added the path to such modules to the configuration file. We then run the Omni frontend on any files in that location before running Omni on the kernel code.

**Comment by arporter** [comment]
Given the additional dependencies (Omni+...) that this approach brings, I'm pausing development on this issue. We will initially implement kernel transformations using the fparser2 AST.
