### ISSUE TITLE
Fortan backend containers that are imported as wildcard import and as named imports

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1550]
In the Fortran backend there is this consideration: "If this symbol has both a wildcard import and explicit imports then two use statements are generated.". This was done to regenerate cases like:

```
use a_mod
use a_mod, only: symbol1
```

However, we now we can resolve wildcard imports, which populates the symbol table with all external symbols with an ImportInterface. And therefore we end up with all the symbols listed in the second statement even though they were not in the original source file. This new lists can be *very* long.

Is recreating the same import as the original important here? I could delete the second one if the container is already a wildcard import because the symbols already exist. But if it is important I can add a new attribute/flag to the imported symbols ImportInterface that clarifies if it was there in the original file or not.  @arporter @rupertford What do you think is best to do here?

**Comment by arporter** [comment]
I can't remember the reasoning behind this. Maybe it was so we didn't lose the fact that `symbol1` comes from `a_mod` while retaining the wildcard import needed for correctness? (Perhaps due to a limitation in our implementation back then.) Can you remember @rupertford?

**Comment by sergisiso** [comment]
The comment in the visitor implied that it was to regenerate the same code as it was parsed, but since we now import into the scope the imported symbols, it is not true anymore that the regenerated statements are the same as the parsed ones.

I was hopping there was no correctness issue, but let me know if you remember otherwise.

I am using this with NEMO to generate similar to the original code (regarding use statements).
