### ISSUE TITLE
Create Algorithm Layer for a Kernel

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1555]
Given a kernel (e.g. LFRic) and its associated metadata it should, in principle, be possible to generate a suitable algorithm layer that calls it. This issue is to investigate how hard or easy this is.

**Comment by arporter** [comment]
I've created a new `lfric/eg19` for this and have something that generates an algorithm layer, runs PSyclone, compiles the result and executes it. All I can really say is that it runs - I haven't attempted to give the fields or scalars any actual values.

Although I could create the full PSyIR for the algorithm layer (with judicious use of CodeBlocks), for now I've gone with the much quicker 'template' approach and just insert suitable strings into a template based on Joerg's `lfric/eg17`.

**Comment by arporter** [comment]
So, I need a kernel (probably) that initialises fields with random data and then I need to work out whether I can write the adjoint test harness in terms of invokes.

**Comment by arporter** [comment]
To do the kernel arguments properly I need a sub-class of `domain.lfric.KernCallArglist`.

**Comment by arporter** [comment]
`KernCallArgList` requires a `DynKern` object, which (copying what the kernel-stub generator does) I can create using its `load_meta` method.

**Comment by arporter** [comment]
I now have a complete example working. It uses PSyIR throughout although we have to use quite a few codeblocks for the infrastructure set-up. For now I initialise everything to zero (using setval_c for fields). Kernel arguments are currently restricted to scalars and fields.

@TeranIvy has kindly offered to investigate whether there's already an LFRic kernel for initialising fields with random data.

**Comment by arporter** [comment]
We have to decide how we're going to provide this functionality to a user. (At the moment it's just a python script in an LFRic example directory.) Related to this, what I have so far is LFRic specific but there's no reason why we can't generalise it to GOcean too.
I think the question is, should we make it an option of the `psyclone` command, e.g. `psyclone -api dynamo0.3 --alg-gen my_kernel.f90` or should we follow what we did for the kernel-stub generator and have a separate driver script? Personally, I prefer the former option but what do @rupertford, @TeranIvy, @sergisiso and @hiker think?

**Comment by rupertford** [comment]
Given that psyclone operates on algorithm files and this operates on kernel files I would lean towards keeping them separate. Otherwise we could end up with a big single interface where many options are context sensitive.

However, I also don't like the fact the kernel-stub generator script has a specific name and prefer your option of `<generic-name> -api dynamo0.3 --alg-gen my_kernel.f90` which could also potentially include a `--stub-gen my_kernel.f90` option and also a kernel script option `-s ./kern.py` to support optimisation of the kernel. If this was agreed then the question would be what to use for `<generic-name>`. Perhaps `psyclone-kern`?

**Comment by arporter** [comment]
The only thing remaining for the tl_hydrostatic_kernel (in examples/psyad/eg2) is support for passing a quadrature object from the algorithm code.

**Comment by arporter** [comment]
Iva has suggested looking at lfric/eg9 so I shall follow what's done there:

    use quadrature_xyoz_mod,            only: quadrature_xyoz_type
    use quadrature_rule_gaussian_mod,   only: quadrature_rule_gaussian_type
    ...
    type(quadrature_xyoz_type)          :: qr
    type(quadrature_rule_gaussian_type) :: quadrature_rule
    type(quadrature_face_type)          :: qrf
    ...
        ! Use project u.grad(theta) into the theta function space

Of course, all we know for sure is that this code compiles - it isn't ever actually run as part of the PSyclone examples.
        qr = quadrature_xyoz_type(element_order+3, quadrature_rule)
        ! Quadrature rule on lateral faces only
        qrf = quadrature_face_type(nqp_exact, .true., .false., &
                                   reference_element, quadrature_rule)

**Comment by arporter** [comment]
The example with quadrature now builds and runs. I still need to factor-out the functionality relating to identifying the function spaces required by a kernel from that needed to initialise function space and field objects.

**Comment by arporter** [comment]
I've created a new branch `1555_add_coords_lfric_infrastructure` as a place to keep my progress towards extending our cut-down version of the LFRic infrastructure with coordinate information. It's not clear to me that this is the right thing to do as it's quite a lot of work and there are two other alternatives:

 1. Generate code that can be cut-n-pasted into a 'proper' LFRic mini-app that can be built with the full LFRic infrastructure;
 2. Add an LFRic transformation that adds a call to the adjoint form of a kernel immediately after an existing call to a TL kernel.

We need to discuss what the best approach is with the MO.
