### ISSUE TITLE
psyad does not support a variable named field

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1560]

**Comment by hiker** [comment]
Is this related to SymPy? My current branch #1523 (reviewed already) should fix the limitation of using certain reserved names in SymPy.

**Comment by rupertford** [comment]
Yes, that would make sense :-) I'll check when the branch gets on to master and then close this issue. I'll hold off closing now just in case it is something else, but I can't imagine what. Thanks for the info. I should probably pay closer attention at the telcos as I now remember you talking about the variable name 'field' causing problems.

**Comment by arporter** [comment]
Joerg's branch is now on master so could you re-check this @rupertford?

**Comment by rupertford** [comment]
This problem was found when trying to transform LFRic's `enforce_bc_kernel` (although I don't think it is actually necessary to do this as I think it is self adjoint).

I can confirm that this problem has now been fixed so am closing this issue.
