### ISSUE TITLE
[fparser2-FE] Visibility of symbols imported from other modules is lost

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1567]
The various type definitions imported via USE statements in the following code:

    MODULE jb_def
     USE bge_ctl_def, ONLY :  fbge_ctl_typ             !: Control parameters for background error covariance
     USE bge_def, ONLY :  fbge_typ                 !: Background error covariance data structure
     USE ens_ctl_def, ONLY : fens_ctl_typ             !: Control parameters for ensemble estimation
     USE ens_typ, ONLY :  fens_typ                 !: Ensemble estimation data structure
     USE eof_ctl_def, ONLY :  feof_ctl_typ             !: Control parameters for EOFs
     USE eof_typ, ONLY :  feof_typ                 !: EOF data structure
     USE bal_ctl_def, ONLY :  fbal_ctl_typ             !: Balance operator control
     USE bal_typ, ONLY :  fbal_typ                 !: Balance operator data structure
     USE control_vectors, ONLY :  ctlvec
     USE variables, ONLY :  fvariables_typ            !: Control vector variables

     IMPLICIT NONE

     !! * Routine accessibility
     PRIVATE

     PUBLIC  fjb_typ                  !: Jb data structure

     PUBLIC  fbge_ctl_typ,  fbge_typ, fens_ctl_typ, fens_typ, fbal_ctl_typ, fbal_typ

     TYPE fjb_typ

        TYPE(fbge_ctl_typ)   ::  fbge_ctl             !: Control parameters for background error covariance
        TYPE(fbge_typ    )   ::  fbge                 !: Background error covariance data structure
        TYPE(fens_ctl_typ)   ::  fens_ctl             !: Control parameters for ensemble estimation
        TYPE(fens_typ    )   ::  fens                 !: Ensemble estimation data structure
        TYPE(feof_ctl_typ)   ::  feof_ctl             !: Control parameters for EOFs
        TYPE(feof_typ    )   ::  feof                 !: EOF data structure
        TYPE(fbal_ctl_typ)   ::  fbal_ctl             !: Balance operator control
        TYPE(fbal_typ)       ::  fbal                 !: Balance operator data structure
        TYPE(fvariables_typ) ::  fbkg_vars
        TYPE(fvariables_typ) :: fbge_vars

        TYPE(ctlvec), POINTER :: x_bkg               !: Background control vector

     END TYPE fjb_typ

    END MODULE jb_def

should be public but when we re-generate the code we lose this information. Possibly this is because there are two `PUBLIC` statements and we only spot the first?

**Comment by arporter** [comment]
I've added a new test and found that multiple access statements are in fact handled correctly.

**Comment by arporter** [comment]
Perhaps it's a bug in the backend?

**Comment by arporter** [comment]
Yep, the backend only generates access statements for RoutineSymbols. We need to do it for symbols with an ImportInterface too. However, it also seems the frontend isn't setting the visibility of imported symbols correctly (e.g. when a module has a default visibility of private). I've a feeling @sergisiso has a fix for this in the works?

**Comment by sergisiso** [comment]
@arporter I am afraid everything I had is already on master. What I was doing is dealing with visibilities inside the "external module".

**Comment by arporter** [comment]
Ah, that explains it then :-)

**Comment by arporter** [comment]
There was a small bug in the frontend - we didn't preserve a symbol's visibillity when 'promoting' a Symbol to be a DataTypeSymbol. I need to add a test for this now.

**Comment by arporter** [comment]
Victoria (Smart) has been tripped up by this again - this time we are losing accessibility statements for Symbols if they are not referred to anywhere apart from the declaration spec. of the module (e.g. nv_ctl_opn in lib_mpp.F90 of NEMOVAR).
