### ISSUE TITLE
PSyclone generates empty continuation lines in output Fortran

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1575]
Simon has reported:
 
PSyclone can generate very long Fortran source-code lines, for example through indentation of the nested if-then-else constructs that result from if constructs with many "else if" sections in the original source code, so that limiting the length of generated source-code lines is often necessary. The option "-l output" of the 'psyclone' command that provides this, however, produces empty continuation lines if the indentation is 132 characters or more, which turn out to be rejected by at least one compiler. Therefore, I'd like to suggest to filter out empty continuation lines when "-l output" is in use.

Assigning to @rupertford as he wrote the line-length limiter :-)

**Comment by arporter** [comment]
Closing now #2250 is on master.

**Comment by LonelyCat124** [comment]
I think i misread this isssue and i'm not sure if #2250 does fix this. @arporter do we have an example we can test this on?

**Comment by arporter** [comment]
I reckon it will have fixed it but I'll ask Simon which file it was that he saw this with.

**Comment by arporter** [comment]
I've generated an artifical example (thanks to Simon's suggestion):
[big_indent.f90.txt](https://github.com/stfc/PSyclone/files/12343002/big_indent.f90.txt)
and this fails:

    (psyclone310) me@laptop code_fragments$ psyclone -api nemo -l output big_indent.f90 
    Traceback (most recent call last):
    File "/home/me/.pyenv/versions/psyclone310/bin/psyclone", line 42, in <module>
    main(sys.argv[1:])
    File "/home/me/Projects/PSyclone/src/psyclone/generator.py", line 575, in main
    psy_str = fll.process(str(psy))
    File "/home/me/Projects/PSyclone/src/psyclone/line_length.py", line 134, in process
    break_point = find_break_point(
    File "/home/me/Projects/PSyclone/src/psyclone/line_length.py", line 73, in find_break_point
    raise InternalError(
    psyclone.errors.InternalError: PSyclone internal error: Error in find_break_point. No suitable break point found for line '                                                                                                                            
    WRITE(*' and keys '[' ', ',', '=', '+', ')']'

**Comment by LonelyCat124** [comment]
I'm not sure what would be an appropriate way to avoid this issue, we can just disable indentation for these lines (or unindent them a bit?) but I'm not sure how to do that.

**Comment by arporter** [comment]
I think we need to add something at L133 of line_length.py that checks the position of the first non-whitespace character. If this is greater than max line length then we just `lstrip` it.

**Comment by LonelyCat124** [comment]
I wasn't sure if that would be sufficient, since the key_list for a `statement` will only find a ",", ", " or " " to break on you could have a case where a variable name of 30 characters starts at position 110 and PSyclone would fail to break it too i think. Perhaps search for the first index of a `key_list` member and if that is over 132 then lstrip it?

**Comment by arporter** [comment]
Oh yes, that sounds better.
