### ISSUE TITLE
[PSyIR] [Suggestion] Clause class

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1585]
Looking again at #1551 and the future validation I need to do, and Andy's comments about #310 I think it might be helpful to have a clause class. Particularly for the future validation, being able to easily compare clauses would be important, as the alternative is simply to have to look through generated strings which sounds like a bad plan.

For straightforward clauses (e.g. `nowait` etc.) these would be relatively simple. For other clauses, they might need children, as the private_clause example below may show.

```
@six.add_metaclass(abc.ABCMeta)
def clause(Node):
  _children_valid_format = None
  _clause_text = ""
  def __init__(self, ast=None, children=None, parent=None, annotations=None):
    pass

  #function to convert to string - couldn't find the real name.
  def to_code_str(self)
    children_strings = []
    for child in children:
        children_strings.append(child.to_code_str()) #Use correct function name
   child_strings = ""
    if children_strings != []:
        child_strings = "(" + ", ".join(children_strings) + ")"
    return self._clause_text + child_strings

# Maybe also equality/compare functions which can be overriden.


def nowait_clause(clause):
  _children_valid_format = None
  _clause_text = "nowait"
   def __init__(self, children=None):
      super().__init__(children=children)

def private_clause(clause):
  _children_valid_format = "[Reference+]" (not sure of this syntax)
  _clause_text = "private"
  def __init__(self, children=None):
    # Children can't be None, not sure if I need to validate that here or if super does it.
    super().__init__(children=children)
```

I think we'd need another type (similar) to `schedule` for lists of clause's (e.g. `clause_list` maybe) to contain clauses for those classes who should have clauses (e.g. OpenMP nodes, OpenACC nodes etc.), which would be added as an extra child to those directives.

Does this sounds like a reasonable solution to this problem? @arporter @rupertford @sergisiso 

EdiT: I can probably start having a look at this this week if it seems reasonable.

**Comment by arporter** [comment]
That sounds pretty good to me. As you say, having a list of clauses does complicate things a bit but hopefully not too much. `Directive` nodes already have the `dir_body` property which gives back the `Schedule`. It could be that `Clause` nodes could just be all children of the `Directive` (as is done for the start, stop and step properties of a Loop) after the `Schedule` but that feels like it could get difficult. I'll be guided by @sergisiso here...

**Comment by sergisiso** [comment]
In principle I agree. As @arporter suggested, clauses could go after the Schedule, as Schedule is the only mandatory child. I think the `def to_code_str(self)` wouldn't be needed then because the backend visitors are in charge of coming up with the string representation.

What we have to think about is what happens with references that are children of a clause. Would the dependency analysis consider the whole directive is the dependency even if the real dependency is down below the directive schedule. Would a `node.walk(reference)` return all of them and we will need extra logic in all the walks to differentiate them with expression references? Or is this a good thing?

**Comment by LonelyCat124** [comment]
Are there instances where any `Reference`s that are children of a clause are not already going to be accessed in the parent's `Schedule` anyway?
I guess maybe for example in a `depend` clause, there may be a "custom" `ArrayReference` `array(index1:index1+32)` which wouldn't appear in the code as such, but I think that shouldn't affect the dependency analysis (the array is still being accessed the same)?
Would we need to do something to determine the read/write-ness of these in the dependency analysis? Since they don't appear in Statement lhs/rhs but are just "floating"?

I think the node.walk(reference) returning them all seems a bit worrying to me, but I again don't know how much code would be affected.

The only alternative I can think of (which is maybe less elegant) is to add a _clause_list member to the `Node` class (or `Directive` subclass since we're not expecting most `Node` subclasses to ), but I'm not sure if that fits well with PSyIR's design?

**Comment by LonelyCat124** [comment]
Is it worth having a quick meeting to discuss this and decide a way to go?
