### ISSUE TITLE
Compute annexed dofs

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#159]
When iterating over dofs, only owned dofs are computed. This decision makes sense as computing annexed dofs is not required for correctness, it is an optimization.

However, when iterating over cells, annexed dofs are always computed correctly, due to redundant computation being performed (which one could argue is an optimization, but it has been decided to implement the computation this way by default). For clarity it should be pointed out that redundant computation is performed when iterating over cells and modifying a continuous field; it just so happens that only continuous fields have annexed dofs.

In #77 it was observed that a simple way to (potentially) improve performance by reducing the number of halo exchanges would be to compute annexed dofs by default when iterating over dofs. This would not require any additional halo exchanges and would remove halo exchanges where a continuous field is written to (over dofs) and then read in a loop modifying a discontinuous field (as the annexed values must be correct but not the halo values).

**Comment by rupertford** [comment]
created annexed_dofs branch

**Comment by arporter** [comment]
#165 has been merged to master. Closing Issue.
