### ISSUE TITLE
Update built-ins support

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#16]
Iva's work in Ticket 907 on the SRS has revealed a lot of cases where would-be built-ins are called with
one or more duplicated arguments, e.g.:

    call invoke( axpby(a, fld1, b, fld1, fld3) )

Currently PSyclone rejects such kernel calls because they break Fortran rules on argument aliasing.
Tom has suggested that PSyclone automatically identify such cases and 'call' an alternative, suitably specialised implementation of the built-in. This then prevents the need for a proliferation of built-ins according to the various ways in which their arguments may or may not be duplicated.

We will investigate, and if possible, implement this functionality in this Issue. Although I'm 'assigning' this to both Iva and Rupert, that is really FYI as I propose to do it. (Unless anyone else feels keen :-)

**Comment by TeranIvy** [comment]
I would also like to get involved if possible so I can contribute more in the future. Please let me know can I help and how. I am currently working on identifying common categories of built-ins (in the LFRic ticket #907) so hopefully this can help in defining a set of rules for each category rather than an individual case.

**Comment by rupertford** [comment]
Looking at Iva's work so far in ticket 907 on SRS I don't think we need to implement what this ticket says. 

Unless I have misunderstood it looks like we need to add PSyclone builtin support for self_inner_product() and inc_multiply_field() to cover all existing uses of built-ins.

So we should do that.

I don't buy this proliferation of code argument, or requirement to copy fields. When an argument is passed in more than once to a built-in then the operation it is doing is different to when different arguments are passed in.

In most cases it is about incrementing something, so the argument should be passed in once as an inout. This is why we have added inc_ equivalents to existing built-ins.

If the same argument is passed in more than once and it is used as a read-only field then I would argue that you are calling the wrong routine as you will be computing something inefficiently.

A simple example ` x = ay + by` should be `c=a+b; x=cy`

OK, tin hat on.

**Comment by TeranIvy** [comment]
I think there is already some proliferation of code in there. For instance, operations
`z = ax + y` and  `z = ax - y` (a,b -scalars, x,y - vectors) are really special cases of `z = ax + by` (similar for inc_ equivalents). I was wondering can we build a category rule which can cover several of individual cases like this. For instance,
`invoke_add_scaled_fields(scalar1,field1,scalar2,field2,add_or_sub)`
where 'addorsub' is interpreted as `+` or ` -`, respectively, and if one or both of scalars are interpreted (that is, explicitly written in the call) as `1` the multiplication is omitted. Would that create much more work that adding more case-to-case built-ins?

**Comment by arporter** [comment]
We already have something close to that functionality - if a scalar argument to a built-in is passed by value (e.g. "-1.0") then that value is inserted directly into the generated code. e.g. the following invoke:

    call invoke( axpby(1.0, z, -1.0, p, res)) )

produces code like:

    DO df=1,res_proxy%vspace%get_last_dof_owned()
          res_proxy%data(df) = 1.0*z_proxy%data(df) + -1.0*p_proxy%data(df)
    END DO 

The Intel compiler is happy with that. gfortran produces a warning (`Warning: Extension: Unary operator following arithmetic operator (use parentheses)`).

I agree with Rupert that it seems we need only implement two more built-ins to support the functionality currently implemented in psykal-lite. Do you agree Iva? That said, we do want to avoid making the Algorithm layer 'clunky' by forcing scientists to bend existing built-ins to fit.

**Comment by rupertford** [comment]
We could easily recognise the use of 1.0 and -1.0 as literals and then generate code that didn't include the values (so *1.0 should not be done and *-1.0 is the same as -). So in Andy's example above we would end up with
'''
DO df=1,res_proxy%vspace%get_last_dof_owned()
      res_proxy%data(df) = z_proxy%data(df) - p_proxy%data(df)
END DO
'''
However, I suspect compilers are clever enough to notice this in any case.

I do have a worry about the loose use of terms axpy and axpby which are well defined (y = ax+y and y=ax+by respectively). We use them to mean something different.

**Comment by TeranIvy** [comment]
I think that implementing the two above mentioned built-ins is a good idea for now, especially as developers are used to them. Perhaps we can review this after we see how the changes work when merged onto the trunk and if the need arises for more built-ins which would then be handled more easily with categories and not special cases. There is one more built-in which is not covered, though: invoke_axmy (z = ax - y).
Regarding naming built-ins, perhaps we can use a generic term (e.g. "_self_" or "_inc_") for all built-ins that return a modified input field instead of a new one?

**Comment by arporter** [comment]
> I think that implementing the two above mentioned built-ins is a good
> idea for now, especially as developers are used to them. Perhaps we can
> review this after we see how the changes work when merged onto the trunk
> and if the need arises for more built-ins which would then be handled
> more easily with categories and not special cases. There is one more
> built-in which is not covered, though: invoke_axmy (z = ax - y).
> Regarding naming built-ins, perhaps we can use a generic term (e.g.
> "/self/" or "/inc/") for all built-ins that return a modified input
> field instead of a new one?
>
Sounds like a plan. We could just do axmy using the axpby with b = 
"-1.0" but
axmy seems nicer and it's not a big deal to implement (especially if 
you're doing it and not me :-)

God bless,

Andy.

**Comment by TeranIvy** [comment]
Right,  shall I do all three then or just "axmy"? I'm happy to give a go to all three, as long as I can ask you guys when I get stuck. Realistically I'll be able to fully commit to it from Monday as I've got training until Friday afternoon. If everyone's ok with that, I'll dive in to Psyclone on Monday :-)

**Comment by rupertford** [comment]
Monday sounds good to me. Step 1 - change the title of the issue :-)

**Comment by TeranIvy** [comment]
I changed the name to a more appropriate one. The branch I am doing the work on is already called BuiltIns_AliasArg, unfortunately, so I will look into changing that as well. I will add the link to LFRic wiki with PSyclone built-ins discussion when I put it together.

**Comment by rupertford** [comment]
I wouldn't worry about the branch name Iva, you'll remove the branch after use in any case.

**Comment by TeranIvy** [comment]
I finished adding required built-ins support for Dynamo. There are a few inconsistencies in the code, which could be edited or changed in a separate issue: 
- Built-ins `single_invoke` names in `src/tests/test_files/dynamo0p3/` end in both `_builtin.f90` and `_invoke.f90`. I inherited the naming convention from the subcategory I created a new built-in from. It would be good to unify the approach in the future.
- Built-ins `single_invoke` .f90 names in `src/tests/test_files/dynamo0p3/` have different copyright statements. Is the Met Office copyright still appropriate here? Also, would it be useful to update the descriptions in the files?
- Built-ins categorisation and subcategorisation in `src/tests/dynamo0p3_builtins_test.py` - is it going to be reviewed?
- Built-ins variable names in class constructors in `src/dynamo0p3_builtins.py` are not uniform. E.g. there are `invar_name1`, `fld_name`, etc. It would be good to unify the approach in the future.
- If we are going to rename built-ins, the change will affect the examples as well, e.g. `example solver_mod.x90` in `examples/dynamo/eg3`.

**Comment by rupertford** [comment]
- We have not worried about names of test files so far. We could have some conventions but it's not high on my priority list :-).
- The new copyright agreement has not yet been completed so we need to keep the old copyright for code developed whilst that copyright was in force. New and modified files should have the new copyright in them (although I've been lax with modified files). I'm not sure what should be done with copyright and code contributed by you - I'll have to take advice. I'm not sure what you mean by updating descriptions - do you mean copyright information? If so, I've hopefully already answered.
- All modified code is reviewed. I'm not sure what you mean by (sub-)categorization.
- Agreed about using uniform names.
- Yes, to pass review all examples should run. So any renaming would require changes to the examples.

**Comment by rupertford** [comment]
Pull request #29 has been merged to master. Closing this issue.
