### ISSUE TITLE
Allow GH_READWRITE/WRITE access for continuous function spaces

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1604]
There are instances in LFRic Physics schemes where halo exchanges are not required despite a field being on a continuous function space. E.g. winds are in `W2` space, however the way certain Physics schemes are computed means there does not need to be communication between different MPI processes to update the halos for continuous quantities.  `W2` is then more about marking the placement of DoFs (data points) for values than the continuity in the horizontal.

Currently PSyclone does not allow  `GH_READWRITE` and `GH_WRITE` accesses for continouous fields for correctness. After some discussions, we agreed that we will allow `GH_READWRITE` and `GH_WRITE` access for continouous fields for cases like these. It is then up to the developers who wish to use this feature to ensure that they will get correct results without halo exchanges.

**Comment by arporter** [comment]
We already have an issue for this @TeranIvy (and I've started work there).

**Comment by TeranIvy** [comment]
Thanks @arporter! Could you please refer it here so I can pass it to Ian?

**Comment by TeranIvy** [comment]
Ok, I see it is #1542. I'll add the mention of GH_READWRITE there.
