### ISSUE TITLE
Issue bringing fparser dependency to master

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1612]
@rupertford @arporter When the fparser dependency is brought to master many tests fail in the generate/get_invoke call. For instance in src/psyclone/tests/alggen_test.py

```
    def test_single_function_invoke():
        ''' single kernel specified in an invoke call'''
        alg, _ = generate(os.path.join(BASE_PATH, "1_single_invoke.f90"), api="dynamo0.3")
```
Fails with:
```
>           table.add_use_symbols(str(result[2]), only_list)
E           AttributeError: 'NoneType' object has no attribute 'add_use_symbols'
```

**Comment by arporter** [comment]
Ah. I'll take a look - thanks for reporting this Sergi.

**Comment by arporter** [comment]
I've created https://github.com/stfc/fparser/issues/310 for this. It's not a biggie.
