### ISSUE TITLE
MD Link checker uses 'stable' docs rather than 'latest'

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1626]
Probably it should always use 'latest'? e.g. at the moment it is reporting dead links because what was `psyclone_command` has become `psyclone_kern` but this isn't in a release of PSyclone yet.

**Comment by nmnobre** [comment]
No, the current behaviour is the correct one. The solution is rather to change the Github action to either:
- ignore these links,
- replace them with latest but just for the check,
- run only on new releases.
