### ISSUE TITLE
Extend PSyIR SUM intrinsic to support optional dim and mask options.

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1630]
Fortran supports optional dim and mask options in the SUM intrinsic. These are used by NEMO and currently result in PSyIR Codeblocks as currently the PSyIR SUM intrinsic only supports a single argument. Eventually this form of SUM will be transformed into equivalent code, but the first step is for PSyIR to understand it.

**Comment by rupertford** [comment]
It has been agreed that the best way to support SUM's with optional dim and or mask arguments is to support them directly in the PSyIR as this is the simplest way forward. The alternative solution of transforming from Fortran to a canonical PSyIR form would be more effort with no particular benefit.

**Comment by rupertford** [comment]
Created branch [1630_sum_optional_args](https://github.com/stfc/PSyclone/tree/1630_sum_optional_args).

**Comment by deardenchris** [comment]
In the SI3 code there are lots of uses of the SUM intrinsic with the 'dim' argument. I had previously put these within a kernels region manually but I have recently noticed that this causes page faults with managed memory, so I've had to do a little refactoring to prevent any data movements. For example:
 
 `at_i(:,:) = SUM(a_i(:,:,:), dim = 3) ! CDe causes page faults as is`

Instead I now do:

```
do jj = 1, jpj, 1
  do ji = 1, jpi, 1
      at_i(ji,jj) = SUM(a_i(ji,jj,1:jpl))
  enddo
enddo
```

Just thought I'd raise this in case the refactoring can be handled by PSyclone during processing.

**Comment by rupertford** [comment]
There is already PSyIR support for the sum intrinsic with up to 3 arguments in PSyIR. However, it does not distinguish between different types of optional arguments so, as it stands, we might have to look at the types of argument to determine which optional argument we have.

For example, if we had the following two sums ... `sum(array, dim=2)` and `sum(array, mask=mod(array,2) == 0)` the PSyIR would not distinguish between the two (they would both be binary operations with the sum operator).

The proposed solution is to keep the name of the optional argument in PSyIR `Call` nodes. This could be done in a couple of ways but in discussion with @sergisiso we agreed to add an additional list to a `Call` node that has `None` for a positional argument and a name for an optional/named argument. The advantage of this approach is that it would have minimal effect on the existing PSyIR hierarchy.
