### ISSUE TITLE
Reference equality check

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1635]
So for #1551 it would be very helpful if I can do `if reference in ListOfReferences` - but since References are unique, the default equality check (where it would check `ref1 is ref2`) will not work.

My proposed solution to this would be to override the `__eq__` function in Reference as follows:
```
def __eq__(self, other):
    eq = type(self) == type(other)
    eq = eq and (self.symbol == other.symbol)
    return eq
```

Most of the test suite doesn't seem fussed about this change, however there are a few failing tests and I can't understand why this change affects them.

The first is:
psyclone/tests/psyir/nodes/reference_test.py::test_reference_accesses_bounds

These tests both fail with the final assert, as `str_var_access_info` returns `''` both times. I'm assuming something in VariablesAccessInfo is perhaps relying on this check instead? @hiker @rupertford do either of you know what might cause this test to fail?

The other failing tests are in `psyclone/tests/psyir/transformations/hoist_trans_test.py::test_validate_dependencies_read_or_write_before`

This one seems pretty clearly to occur due to the `is_accessed_before` check in `SingleVariableAccessInfo`. This is fixed by changing:
`if access.node == reference:` to `if access.node is reference:` - and the latter is presumably the intention anyway. If I change all instances of `== reference` to ` is reference` in that file, then no additional tests fail (and I assume this is the intended behaviour throughout that functionality).

**Comment by LonelyCat124** [comment]
Ok - it actually breaks one other test, which is another weirder one.
It breaks: ` `

The `t%internal%ystop` and `xstop` accesses break, and are both `ystart`/`xstart` instead in the DO lines of the code.

I don't know which of the calls are messing up this code, so I will commend things out until it works again...

**Comment by LonelyCat124** [comment]
I'm going to separate this from my current branch and create a development branch for easier discussion, which I will link up here.

**Comment by LonelyCat124** [comment]
The failing test is super confusing to me.

It seems to be something to do with GOLoop/Loop/gen_code. 
In GOLoop.create I print:
```
print("MADE A GOLOOP: ", node.upper_bound())
```
which gives me what I think is expected:
```
MADE A GOLOOP:  StructureReference[name:'t']
StructureMember[name:'internal']
Member[name:'ystop']
```
for example (the key thing here being that the member being accessed is `ystop`).

When I run the test however, output for this loop is:
```
DO j=t%internal%ystart,t%internal%ystart
```

Inside Loop.gen_code() this is still correct, with `print(self.stop_expr)` still printing a `ystop` access.

This seems actually is maybe a bug in fortran writer call, as this:
```
            print("Loop1:", self.stop_expr)
            print("Loop2:", fwriter(self.stop_expr))
```
results in:
```
Loop1: StructureReference[name:'t']
StructureMember[name:'internal']
Member[name:'ystop']
Loop2: t%internal%ystart
```

with `ystop` having become `ystart` for no discernable reason...

**Comment by sergisiso** [comment]
I do agree that having `__eq__` implemented good be good. To have Arrays implemented generically we need to check if the number of children are the same in both nodes and that each child is equal to the child in the same position. But since we can have many things as children: operations, calls, literals, ... This means we need `__eq__` in every node.

Again, I do think we would benefit to have `__eq__` everywhere but when this was proposed before there were some ambiguities that we could not agree on.
1) was if order matter e.g. "a + b == b + a". This was very helpful for the dependency analysis. I think this is not a big problem anymore because we now have the symbolic_math.equals to deal with this comparisons.
2) Literals precision e.g. "1.0 == 1?" Again we can go for exact matches and let the symbolic math as an option then the equals is not enough. What if both are real 1.0 but with a different precision type?

Anyway, what do @arporter, @rupertford, @hiker think? Would it be fine to have a strict equals operator now that the we have symbolic_math?

**Comment by sergisiso** [comment]
Btw, this is the long term view. If people agree in having `__eq__` a first PR that only cover References and fails(?) or returns True if it is an ArrayMixin is also fine.

**Comment by LonelyCat124** [comment]
I added an `__eq__` function into the ArrayMixin that just does the default behaviour, i.e.:
```
def __eq__(self, other):
    return self is other
```
I also fixed some issues in `StructureReference` that occurs in one test, where the `.member` element is not yet defined during the test (?) so an error is thrown when attempting to access it. The StructureReference now also reverts to `self is other` if .member access throws an exception.

**Comment by LonelyCat124** [comment]
Ok, so I dug a bit more and there's an additional complication (which is why the test is failing).

The test fails due to this check returning True when it should return False:
```
self.parent.children.index(self) == 0
```

This happens, because self.parent.children contains 2 References to the same DataSymbol. 
Python index searches for the index of the first object in the specified array which is `==` the specified object, which in this case returns `0` instead of `1`, as they are equal under the `__eq__` expression.

I am not clear what a good solution to this issue is. I could override `ChildrenList.index` to instead be:
```
def index(self, obj, start=0, end=None):
    if end is None:
        end = len(self) +1
    for i in range(start, end):
        if self[i] is obj:
            return i
    raise ValueError( f"{obj} not in ChildrenList")
```

I do have concerns that starting to do this is beginning to fix a problem that is also the reason the equality check was added, so it seems bad.

I'm somewhat surprised nothing else in the code/test suite falls over because of this.

I can also rewrite the `reference_access` member of `Reference` to explicitly find the object in the ChildrenList instead, which is probably better, but I still have some reservations about this issue and its implementation.

**Comment by sergisiso** [comment]
I am against changing the index implementation as it slightly alters its semantics and the list.index API: "Return zero-based index in the list of the first item whose value is equal to x."

Would changing the expression to `self.parent.children[0] is self` work? (which is also more efficient because we don't need a linear search)

**Comment by LonelyCat124** [comment]
Yes thats basically what I did (but as a seperate if statement for some reason). I'll switch it to the same if statement and hopefully tests now pass (though weirdly the tests failed the first time they ran on github? But seem ok now)

**Comment by LonelyCat124** [comment]
I guess one thing we need to either note ourselves or in the developer documentation somewhere probably is how the behaviour of Reference (and its subclasses) means these needs to be used, i.e. it becomes important to correctly distinguish between the `is`a and `==` operators.

I've not yet added this in the PR, I'll have a look this afternoon  if i can - else tomorrow am.
