### ISSUE TITLE
Infrastructure support for r_solver

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1638]
We would like to check that the code that PSyclone generates for operators with r_solver precision is correct. However, at the moment this is not in LFRic trunk so can't be copied to our local lfric infrastructure, so we can't do any compilation checks. The offending symbols are `r_solver_operator_type` and `r_solver_operator_proxy_type`.

**Comment by TeranIvy** [comment]
The support for `r_solver_field` is on LFRic trunk. @rupertford, I am happy to provide the files since you have issues with access to MOSRS.

**Comment by TeranIvy** [comment]
I have decided to wait a bit as all operator types are now in the same module on trunk, and Mike has a ticket in review with Chris to separate them (https://code.metoffice.gov.uk/trac/lfric/ticket/3144). I will attach the modules once the ticket makes to trunk.

**Comment by TeranIvy** [comment]
Closing this as the support is added in #1810
