### ISSUE TITLE
matrix matrix matmul to code transformation not supported

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1643]
The matmul to code transformation only supports matrix vector. It needs to be extended to matrix matrix.

**Comment by arporter** [comment]
I'm doing this as part of #1644.

**Comment by rupertford** [comment]
@arporter, even though this is trivial, it would be good to get it onto master as it allows us to check that we can generate another kernel after performing some manual code tweaks, and we need to get them all done in a month somehow. Would that be OK?

**Comment by arporter** [comment]
Yes, that's OK with me. I'll break out my fix and add an appropriate test for it.

**Comment by arporter** [comment]
I'm doing this on `1644_matmul_trans_bug`.
