### ISSUE TITLE
matmul2code transformation is failing

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1644]
From `tl_vorticity_advection_kernel_mod.F90`, after manually making matmul the only thing on the rhs of an assignment in two cases ...

```
        ...
        matmul1 = matmul( jac, ls_vorticity_at_quad )
        j_ls_vorticity(:) = wqp_h(qp1) * wqp_v(qp2) *     &
                            matmul1(:)

        matmul2 = matmul( jac, vorticity_at_quad )
        j_vorticity(:) = wqp_h(qp1) * wqp_v(qp2) *        &
                         matmul2(:)
        ...
```

we get the following error matmul2code transformation error ...

```
psyclone.errors.GenerationError: Generation Error: Item 'Literal' can't be added as child of 'Loop' because it is not an orphan. It already has a 'Loop' as a parent.   
```

**Comment by arporter** [comment]
The code in question is:

    real(kind=r_def), dimension(3,3)      :: jac, jac_inv
    real(kind=r_def), dimension(3)        :: vorticity_at_quad, u_at_quad,       &
                                             ls_vorticity_at_quad, u_ls_at_quad, &
                                             j_vorticity, j_ls_vorticity,        &
                                             vorticity_term

        j_ls_vorticity = wqp_h(qp1) * wqp_v(qp2) *             &
                         matmul( jac, ls_vorticity_at_quad )

        j_vorticity = wqp_h(qp1) * wqp_v(qp2) *        &
                      matmul( jac, vorticity_at_quad )

**Comment by arporter** [comment]
I've constructed a test case for this:

        "  real, dimension(3,3) :: jac, jac_inv\n"
        "  real, dimension(3)   :: vorticity_at_quad, u_at_quad,       &\n"
        "                          ls_vorticity_at_quad, u_ls_at_quad, &\n"
        "                          j_vorticity, j_ls_vorticity,        &\n"
        "                          vorticity_term, matmul1, matmul2\n"
        "  integer :: qp1, qp2\n"
        "  matmul1 = matmul( jac, ls_vorticity_at_quad )\n"
        "  j_ls_vorticity(:) = wqp_h(qp1) * wqp_v(qp2) * matmul1(:)\n"
        "  matmul2 = matmul( jac, vorticity_at_quad )\n"
        "  j_vorticity(:) = wqp_h(qp1) * wqp_v(qp2) * matmul2(:)\n"

and it works:

    do i = 1, 3, 1
      matmul1(i) = 0.0
      do j = 1, 3, 1
        matmul1(i) = matmul1(i) + jac(i,j) * ls_vorticity_at_quad(j)
      enddo
    enddo

Did you declare `matmul1` with the correct rank @rupertford?

**Comment by arporter** [comment]
I ask because I didn't at first and then I got an error:

         psyclone.errors.GenerationError: Generation Error: the symbol 'matmul1' should have the same number of dimensions as indices (provided in the 'indices' argument). Expecting '1' but found '2'.

**Comment by arporter** [comment]
Chatting to Rupert, I need to repeat for the whole kernel that's causing the problem. It may be that the error is coming from one of the other transformations.

**Comment by arporter** [comment]
I've taken the whole kernel and modified it to get around the immediate limitations. When I run psyad as a whole  on it I get:

    psyclone.psyir.transformations.transformation_error.TransformationError: Transformation Error: Expected 2nd child of a MATMUL BinaryOperation to have 1 dimension, but found '2'.

This originates from:

        transp = transpose(jac_inv)
        jac = matmul(jac_inv,transp) !ose(jac_inv))

and, on digging, it seems that the transformation assumes that the second argument to `matmul` must be a rank-1 vector whereas in fact the Fortran standard says it can also be a rank-2 array (see e.g. https://gcc.gnu.org/onlinedocs/gfortran/MATMUL.html).

**Comment by rupertford** [comment]
That's a separate issue, see #1643 :-)
`tl_kinetic_energy_gradient_kernel_type` would be simpler to look at as it only has two outstanding issues whereas `vorticity` has many (see the list in the teams document).

**Comment by arporter** [comment]
The fix for the original error that gave rise to this issue is trivial (just a missing `.copy()` when generating loop bounds from literals). However, on the way I've started doing #1643 so I shall keep going and do that too.
