### ISSUE TITLE
Expand equality operator to all PSyIR nodes

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1649]
#1636 starts implementing the equality operator (`__eq__`) for PSyIR nodes (mostly `Reference`, `StructureReference`, `Member` and `StructureMember`), such that two nodes that could be described as equal (e.g. two `Reference`s to the same symbol).

#1551 also implements this for a subset of the OpenMP Clauses (e.g. to check if two private clauses are == if they contain an equal set of References in the same order).

The advantage of this is likely to be more apparent in transformations which make heavy use of data-usage, and for clauses, enabling compairsons such as `if Node in ListOfNodes:`.

One thing I found even for the first PR is that in certain places PSyclone currently uses code such as `if self == thing` to check if it has found the instance of `self` when searching through the code (for example for finding the global index of a node), which when equality operators that are not the default `return a is b` can return false postives, and break code, so extra caution is required when implementing this functionality to ensure these `==` checks are replaced with the appropriate `is` checks instead.

**Comment by LonelyCat124** [comment]
I spoke to Sergi about this and we decided the best place to start would be to implement `__eq__` for Node and see what happens. The basic idea is to check:
1. Is type(self) is type(other)
2. Are the children == (and do they have the same number of Children).

I implemented this branch off ofthe branch for #1636 to have a first look, and a lot of tests are failing, I will begin to narrow this down a little tongiht and mostly tomorrow and see where I get to.

**Comment by LonelyCat124** [comment]
Ok, so the first issue I've come across is that in some places of the code, the `ChildrenList.index` assumption is that it finds the specific node, i.e. the code in a lot of places is assuming `ChildrenList.index` uses `is` as opposed to `==`. However this is not true.

I will try to fix this in a few places by manually checking for is, I will not override `index` as that should be used as described by `List`.

**Comment by LonelyCat124** [comment]
I fixed that bug, but there are many more. One that I will dive into tomorrow now as I'm tired, is that all the tests involving halos are failing at:
```
        if not read_dependencies:
            raise InternalError(
>               "Internal logic error. There should be at least one read "
                "dependence for a halo exchange.")
```

Test I'm trying is `psyclone/tests/psyir/transformations/profile_test.py::test_region`

**Comment by LonelyCat124** [comment]
This bug was (again) caused by code using `.index` to find the index of a specific instance.

**Comment by LonelyCat124** [comment]
Files with failing tests (not exhaustive list):
```
psyclone/tests/alggen_test.py -- Hard to solve
psyclone/tests/psyir/transformations/profile_test.py -- Hard to solve
psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py -- A LOT of fails
psyclone/tests/domain/lfric/lfric_stencil_test.py
psyclone/tests/domain/lfric/lfric_loop_test.py
psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
psyclone/tests/domain/lfric/lfric_domain_kernels_test.py
psyclone/tests/domain/lfric/lfric_field_codegen_test.py
psyclone/tests/psyir/transformations/omp_task_transformations_test.py
psyclone/tests/psyir/transformations/kernel_transformation_test.py
psyclone/tests/psyir/transformations/profile_test.py
psyclone/tests/psyGen_test.py
psyclone/tests/dynamo0p3_test.py
psyclone/tests/dynkern_test.py
psyclone/tests/dynamo0p3_multigrid_test.py
psyclone/tests/dynamo0p3_haloex_test.py
```

alggen_test fails on at least `test_multi_function_invoke` (dynamo0.3)
profile_test fails on at least `test_multi_prefix_profile` (dynamo0.3)  


Working tests (full directories only):
```
psyclone/tests/domain/gocean
psyclone/tests/psyir/nodes
psyclone/tests/psyir/backend
psyclone/tests/psyir/frontend
psyclone/tests/psyir/symbols
psyclone/tests/psyir/tools
psyclone/tests/psyad/
psyclone/tests/parse/
psyclone/tests/nemo
psyclone/tests/core
```

I want to implement `__eq__` for all the <LeafNode> but I'm going to try to look through these tests and see if they all use dynamo0.3 or not. It looks a lot like many of them do :(

**Comment by LonelyCat124** [comment]
I removed almost all the `children.remove` and a lot of failing tests no longer fail. I'll continue the hunt on Monday

**Comment by LonelyCat124** [comment]
@arporter apologies to tag you here but git blame has your name (and of course there's no rush to reply)

I'm getting an error at `dynamo0p3.py`, `TypeError: unhashable type: 'DynKern'`
I don't quite understand what is going on here, is a dynkern being used as as a dict member? I can fix it by defining the `__hash__` function on DynKern but I'm a little out of my depth doing that :s

**Comment by LonelyCat124** [comment]
Googling suggests that when defining __eq__ we should also define __hash__ such that hashes are equal if the objects are equal.

This gives me two new questions (@sergisiso what do you think here?):
1. Should two statements ever be equal (unless the same object). I'm not sure what it would mean for two Statements to be equal as I don't quite understand their role.
2. How can I create unique hashes if they're only equal if `a is b`. I could do id(obj) perhaps

**Comment by LonelyCat124** [comment]
I added a basic implementation of __hash__ to node for now. It will need overriding anywhere where we define __eq__.

N.B __hash__ can just return True as the only requirement is that if `a == b` then `a.hash() == b.hash()` and if the hash is as expensive as computing equals I'm not sure how big the performance gain would be.

**Comment by LonelyCat124** [comment]
Note for me: DynLoop (slash Loops in general) being equal are causing tests to fail now when they probably shouldn't be equal, however I think in the case I'm looking at they are equal because of the "Kern call" they contain having no children and thus always being equal - the leafnode issue I assume
In this case it's a DynKern - I think perhaps Kern objects should not be equal outside of `is`? But I'm not sure what they represent quite so someone else would be better placed to tell me

**Comment by arporter** [comment]
A `Kern` represents a call to a user-supplied kernel. Therefore if it has the same name and the same arguments as another one then I would claim they are 'equal'.

**Comment by sergisiso** [comment]
I would not change the hash behavior since our nodes are not immutable so they are not appropriate for hashes (the datastructure could be inconsistent after a change). I would leave the default behavior (without overriding `__hash__`) which is that its hash is its id (which is the only immutable thing during the lifetime of an object). Am I missing something?

**Comment by LonelyCat124** [comment]
> I would not change the hash behavior since our nodes are not immutable so they are not appropriate for hashes (the datastructure could be inconsistent after a change). I would leave the default behavior (without overriding `__hash__`) which is that its hash is its id (which is the only immutable thing during the lifetime of an object). Am I missing something?

Yes, so if we override `__eq__` then you're also meant to override `__hash__` if you want them to be hashable objects (the default is no longer valid), and that if two objects are equal, their hash must also be equal.
It looks like PsyClone occasionally uses dict with these objects as keys, so those tests were failing because `dict[object]` was not allowed.

**Comment by sergisiso** [comment]
See the response on #1636 . Can you also port this hash updates into there? I think I need to see the implementation and the impact together in order to discuss it better.

**Comment by LonelyCat124** [comment]
Yes. I think a cheap immutable hash function (which is maybe the best starting point) is just `return type(self)`

**Comment by LonelyCat124** [comment]
I'll put something into 1636 on Monday along with the other comments, though probably after that we should close #1636 and make a PR for this branch instead?
