### ISSUE TITLE
Runtime Initialisation checks

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1665]
We are just debugging a crash in LFRic, which might have been caused by a missing initialisation of a field. I think we could support debugging this kind of issues in three ways (with different advantages/disadvantages, and we might even support all three):

1. Add a flag 'is_initialised' to each field (which is initialised to false, unless override_data is provided). If a field is then passed to a kernel where it is written, set this flag to true. If this field is passed to a kernel where it is read, but has not been initialised, print a warning. Advantage: very fast, no need for manual transformations, just adding this to the runtime checks. Disadvantage: it would not detect if a field is declared to be written, but it is not actually written in the kernel
1.  Use PSyData to compute a checksum before a kernel where a field is written, and compare after the kernel. Slower, but it would detect if a kernel is not written. Problem might be if the kernel is written, but with the same values (having a flag as in 1 above would help here).
1.  Use PSyData, but keep a copy of each  field. Slower, but would even allow us to specifically say which values are not initialised.

I think ideally we should support both (and maybe just two different runtime libraries, so you can decide at link time if you want the checksum version, or the copy-field version). Or put both option in one psydata library, and select via environment variable.

Other approaches are possible, too - e.g. runtime-check would initialise a field that has not been initialised (needs a flag in field) as above with NANs, then let NANs trigger an exception.

**Comment by rupertford** [comment]
Given that the LFRic infrastructure creates all fields, initialising data to NAN's on creation could be done there, rather than it being a PSyclone thing?

**Comment by hiker** [comment]
One argument for doing this with psyclone: as far as I can tell I cannot trigger an exception when **using** a NAN with gfortran, only when the result with valid input parameter is NAN. I.e.:
```
   a=1
   sqrt(a-2)
```
will trigger an exception (using `-ffpe-trap=invalid`), and similarly `1/(a-1)` needs `-ffpe-trap=zero` etc.

But if I initiualise a with NAN, the code will happily continue producing NANs, without any exception:
```
   use, intrinsic :: ieee_arithmetic, only : ieee_value,  &
                     ieee_quiet_nan, ieee_signaling_nan
    implicit none
    real :: a,b
    b = ieee_value(1.0, ieee_signaling_nan)
    !b = 1
    a = 1/(b -1)
    print *,a
```
This will happily print NAN with any options that I tried. 

With the intel compiler using a NAN will trigger an exception (using `-fpe0`).

**Comment by hiker** [comment]
It might also be useful for values that have no NAN (integer fields ... not sure if there will be logical fields??)

**Comment by rupertford** [comment]
Good points @hiker, and given the discussion at the telco today it sounds like it would be a useful addition to PSyclone.

**Comment by hiker** [comment]
I re-tested this. It turns out, the gnu compilers version 9.2.1, 10.3, and 11.1.0 have this bug. Older (8.5) and newer (11.4.0, 12.2.0, 13.2.0, 14.1.0) all work fine.
I am closing this ticket. The NAN testing might not be really required anymore (assuming that cray and nvidia do it properly??), but I've opened #2690 to extend the testing to allow to check that variables have values in a certain range.
