### ISSUE TITLE
[LFRic] Infrastructure library needs updating

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1667]
While looking at #450 I tried making `lfric/eg14` compilable and ran into many problems because the LFRic infrastructure has changed quite a lot. I made a start on fixing these but then wondered whether @hiker might be better placed to look at this as he got it working before?
There are many new files added (including field_vector_mod which is processed with PSyclone).

**Comment by arporter** [comment]
Pushed my changes so far to branch `1667_lfric_lib_update`.

**Comment by hiker** [comment]
I can try - but a first question: do we need all these new files? Or just the ones that are required for eg14?

**Comment by arporter** [comment]
It cascaded: I added each as it was required and ended up with the branch as you see it. I'm wondering whether it may be better to 'start from scratch' and bring the current, whole infrastructure over and then modify it in a similar way to what you did before? I also don't know how much progress has been made with the current infrastructure in moving it towards being a standalone library. @TeranIvy or @andrewcoughtrie may be able to comment on this.

**Comment by hiker** [comment]
> It cascaded: I added each as it was required and ended up with the branch as you see it.

IIRC that was how I started, and ended up with too much :) I then tried to get the minimum for a running example.

> I'm wondering whether it may be better to 'start from scratch' and bring the current, whole infrastructure over and then modify it in a similar way to what you did before? I also don't know how much progress has been made with the current infrastructure in moving it towards being a standalone library. @TeranIvy or @andrewcoughtrie may be able to comment on this.

OK, I'll wait for a discussion on Monday. My feeling is that turning infrastructure into a stand-alone library is not exactly a UKMO priority (esp. considering the potential MPI hassle :( ). If UKMO is finished with their work on the infrastructure lib, maybe we can try a refactoring that works.

**Comment by hiker** [comment]
I've made some progress, but then realised that the example in eg14 relies on other modules, none of which is part of the infrastructure library. E.g.:
```
  use runtime_constants_mod,           only: get_mass_matrix,     &
                                             get_div,             &
                                             w0_id, w3_id,        &
                                             w3inv_id, wt_id
  use timestepping_config_mod,         only: dt
  use gravity_wave_constants_config_mod, only: cs_square,                       &
                                               b_space,                         &
                                               gravity_wave_constants_b_space_w0, &
                                               gravity_wave_constants_b_space_w3, &
                                               gravity_wave_constants_b_space_wtheta
```
Also, this example seems outdated (`get_mass_matix` is now in `fem_constants`).

@arporter, how do you want to continue? Updating the example? Or adding (empty) interface declaration so we can compile (but not not link)? Adding the files to the code subdirectory (which might trigger a lot more dependency issues)? Or modifying the existing (or the new) file to remove unnecessary code (i.e. leaving variables uninitialised to remove dependencies)?

**Comment by arporter** [comment]
Thanks @hiker. It seems that eg14 is only there as an OpenACC example so the code itself doesn't matter. I wonder whether I'd be better off adding OpenACC functionality to eg17 which we can compile and run?

**Comment by hiker** [comment]
I can try to add openacc (well, make a new example that will be doing openacc, I don't like having too many makefile targets, which can result in inconsistent builds). That would certainly require a lot less infrastructure :)
I would especially need to check if I can reproduce #450, correct? I need to check if my examples actually work with DM.

**Comment by arporter** [comment]
> I would especially need to check if I can reproduce https://github.com/stfc/PSyclone/issues/450, correct? I need to check if my examples actually work with DM.

Yes. I think they at least need to compile. I have to admit I hadn't thought through the implications of trying to run a DM example.

**Comment by hiker** [comment]
Now that was extremely painless:
```
      !$acc parallel default(present)
      !$acc loop independent
      DO cell=loop0_start,loop0_stop
        !
        CALL testkern_w0_code(nlayers, field1_proxy%data, field2_proxy%data, ndf_w0, undf_w0, map_w0(:,cell))
      END DO
      !
      ! Set halos dirty/clean for fields modified in the above loop
      !
      CALL field1_proxy%set_dirty()
      !
      !$acc end parallel
```
I assume this is the right problem? It compiles without openacc. If I enable openacc, I get:
```
gfortran -fopenacc -I../../../../src/psyclone/tests/test_files/dynamo0p3/infrastructure -I../../../../lib/extract/netcdf/lfric -c main_psy.f90
main_psy.f90:36:47:

   36 | !$acc& copyin(nlayers,field1_proxy,field1_proxy%data,0.0_r_def,ndf_aspc1_field1,undf_aspc1_field1,map_aspc1_field1,field2_proxy, &
      |                                               1
Error: Syntax error in OpenMP variable list at (1)
main_psy.f90:106:63:

  106 |       !$acc enter data copyin(nlayers,field1_proxy,field1_proxy%data,field2_proxy,field2_proxy%data,ndf_w0,undf_w0,map_w0)
      |                                                               1
Error: Syntax error in OpenMP variable list at (1)
```
Though notice that my gfortran openacc setup is of limited functionality.

**Comment by hiker** [comment]
I've pushed my example to https://github.com/stfc/PSyclone/tree/1667_add_openacc_compilation/examples/lfric/eg17/full_example_openacc
@arporter, if this is good enough, I am happy to update the documentation and start a PR (or let me know if you want me to move the code from `eg17/full_example_openacc` to `eg14`.

**Comment by arporter** [comment]
That's great - thanks Joerg :-) I think move it to eg14.

**Comment by hiker** [comment]
OK, will finish it tomorrow.

**Comment by arporter** [comment]
#1667 is now on and although it doesn't update the infrastructure, it does fix the reason I was trying to do that in the first place so this can be closed.
