### ISSUE TITLE
[PSyAD] Test harness incorrect if supplied routine is a Function

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1681]
All our tests and examples have the target routine as a subroutine. If it is a Function, the test harness still uses `call` and it shouldn't.

**Comment by arporter** [comment]
In fact, PSyAD doesn't generate correct call for a function at this point. As a first step we should raise a NotImplementedError. A second step would be to support it and create a subroutine from it.

**Comment by rupertford** [comment]
It has been agreed to raise an exception if a function is found and not try to convert it into a subroutine.

**Comment by rupertford** [comment]
Created branch [1681_psyad_function](https://github.com/stfc/PSyclone/tree/1681_psyad_function)
