### ISSUE TITLE
[Frontend] PR #1670 breaks the ability to process NEMO code

### ISSUE THREAD

**Issue by nmnobre** [stfc/PSyclone#1688]
Merged PR #1670, which simplifies the symbol tables of the nodes in the PsyIR, breaks the ability to process NEMO code. I suspect (but @sergisiso can probably correct me here) that this is due to existing bugs/inconsistencies that are simply resurfacing rather than the introduction of new bugs.

- [ ] Routines, such as Fortran functions, with symbol `RoutineSymbol<DeferredType>` lose tag `own_routine_symbol`. It appears that these routines initially get the tag associated with symbol `RoutineSymbol<NoType>` but later lose it when this is converted to a specific return type, e.g. `DataSymbol<Scalar<INTEGER, UNDEFINED>, Local>`. NEMO file `domvvl.f90` contains function `dom_vvl_alloc()` which triggers the behaviour when the PSyIR is generated.

- [ ] The letter case of the symbols added to the tables is inconsistent complicating string comparisons. I suggest storing them in their original case for symbols from case-sensitive languages and in lowercase for case-insensitive languages such as Fortran.

- [ ] Fortran USE statements broken into (at least) one continuation line using an ampersand are wrongly parsed/interpreted leading to errors due to unrecognised entities which PSyclone wrongly says are never imported. This happens when processing both `julian.f90` and `obs_conv.f90`. These files/modules can be skipped with no performance penalty since, even before merging PR#1670, no optimisation was being successfully applied.

- [ ] For some reason, when processing `obs_read_surf.f90`, PSyclone tries to swap a symbol in a nonexistent table. This file/module can also be skipped with no performance penalty since it is marked for profiling only.

**Comment by sergisiso** [comment]
Can you check if #1692 fixes things. It did for me.
