### ISSUE TITLE
[LFRic] Incorrect stencil depth list for discontinuous stencil readers followed by discontinuous writers

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1689]
When we have a kernel that has discontinuous stencil readers is followed by a kernel that has discontinuous writers in a single invoke, PSyclone generates incorrect code for stencil depth list string. E.g. as reported from [LFRic/branches/dev/ianboutle/r34895_bl_exp_split@35124](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/ianboutle/r34895_bl_exp_split?rev=35124) ([LFRic ticket 3205](https://code.metoffice.gov.uk/trac/lfric/ticket/3205)):
```
algorithm/bl_exp_alg_mod_psy.f90(493): error #6642: There are null arguments in an intrinsic function reference.   [MAX]
      IF (u_in_w3_proxy%is_dirty(depth=max(stencil_depth,))) THEN
---------------------------------------^
algorithm/bl_exp_alg_mod_psy.f90(494): error #6642: There are null arguments in an intrinsic function reference.   [MAX]
        CALL u_in_w3_proxy%halo_exchange(depth=max(stencil_depth,))
-----------------------------------------------^
algorithm/bl_exp_alg_mod_psy.f90(497): error #6642: There are null arguments in an intrinsic function reference.   [MAX]
      IF (v_in_w3_proxy%is_dirty(depth=max(stencil_depth,))) THEN
---------------------------------------^
algorithm/bl_exp_alg_mod_psy.f90(498): error #6642: There are null arguments in an intrinsic function reference.   [MAX]
        CALL v_in_w3_proxy%halo_exchange(depth=max(stencil_depth,))
-----------------------------------------------^
algorithm/bl_exp_alg_mod_psy.f90(501): error #6642: There are null arguments in an intrinsic function reference.   [MAX]
      IF (tile_fraction_proxy%is_dirty(depth=max(stencil_depth,))) THEN
---------------------------------------------^
algorithm/bl_exp_alg_mod_psy.f90(502): error #6642: There are null arguments in an intrinsic function reference.   [MAX]
        CALL tile_fraction_proxy%halo_exchange(depth=max(stencil_depth,))
```

Closer inspection into the `dynamo0p3.py` function [`def _compute_halo_depth`](https://github.com/stfc/PSyclone/blob/ffd115beb3990679bff78e390f9909353ba073b0/src/psyclone/dynamo0p3.py#L5950) reveals that the problem lies in this check
```
        if len(depth_info_list) == 1:
            return str(depth_info_list[0])
```
because call to [`_compute_halo_read_depth_info`](https://github.com/stfc/PSyclone/blob/ffd115beb3990679bff78e390f9909353ba073b0/src/psyclone/dynamo0p3.py#L5961) may return an **empty string** which is **still counted as a list element**.

A print-out of `depth_info_list` and `depth_str_list` for a combination of two test-file kernels
```
 call invoke(                                                       &
       testkern_different_any_dscnt_space_stencil_type(f1,          &
                                                       f2, extent,  &
                                                       f4, extent), &
       testkern_w3_type(a, f1, f2, f3, f4)                          &
       )
``` 
returns something like 
```
depth_info_list:  [<psyclone.dynamo0p3.HaloDepth object at 0x7fe4d23fc710>, <psyclone.dynamo0p3.HaloDepth object at 0x7fe4d23fcf60>]
depth_str_list:  ['extent', '1']
depth_info_list:  [<psyclone.dynamo0p3.HaloDepth object at 0x7fe4d2272940>, <psyclone.dynamo0p3.HaloDepth object at 0x7fe4d2272400>]
depth_str_list:  ['extent', '']
```

Interestingly, this problem doesn't appear when
- The kernel with discontinuous stencil access is placed after a kernel with discontinuous writers in a single invoke;
- The kernel with discontinuous stencil access and kernel with discontinuous writers are in different invokes;
-  One or both kernels have continuous stencil access or/and readers.

A simple fix is to first create `depth_str_list` from `depth_info_list`, filter it for empty entries and then check the length of `depth_str_list`.

**Comment by rupertford** [comment]
It has been agreed that I will take a look at this to see if there is anything fundamentally wrong with the internal halo exchange logic.

Created branch: https://github.com/stfc/PSyclone/tree/1689_halo_exchange_bug

**Comment by rupertford** [comment]
The underlying issue is that a `HaloDepth` object that has 0 as its depth (i.e. there is no halo access) was returning an empty string rather than 0 due to the use of an `if x` rather than `if x is not None`. Once this is fixed we get `max(stencil_depth, 0)`. The 0 can be removed when simplifying the number of `HaloDepth` objects in `_create_depth_list` so we end up getting `max(stencil_depth)`.

**Comment by rupertford** [comment]
Before creating a PR I want to double check whether we should actually be creating a `HaloDepth` object  with depth 0 in the first place.

**Comment by rupertford** [comment]
In theory there should not be a data dependence between something that modifies the halo and something that reads non-halo data. This should be picked up in the `overlaps` part of the data dependence analysis. However, at the moment the dependence analysis does not support field subsets so it is expected behaviour for a `HaloDepth` object with depth 0 to be created.
