### ISSUE TITLE
Invalid openacc created for LFRic builtins

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1694]
Example lfric/eg14 shows the problem. What I saw yesterday on a machine with nvidia compiler  for:
```
    call invoke( name = 'Initialise fields',        &
                 setval_c( field1,     0.0_r_def ), &
                 setval_c( field2,     1.0_r_def )  &
                 )
```
was:
```
!$acc& copyin(nlayers,field1_proxy,field1_proxy%data,0.0_r_def,ndf_aspc1_field1,undf_aspc1_field1,map_aspc1_field1,field2_proxy, &
!$acc& field2_proxy%data,1.0_r_def,ndf_aspc1_field2,undf_aspc1_field2,map_aspc1_field2)
      !
      !$acc parallel default(present)
      !$acc loop independent
      DO df=loop0_start,loop0_stop
        field1_proxy%data(df) = 0.0_r_def
      END DO
```
Neither `nlayers`, nor any `(u)def*` values are defined at all (and iirc there were even more variables listed that do not exist).

I just tried to run this again on my machine (no nvfortran, but that shouldn't matter for the psy layer), and now I am getting:
```
!$acc enter data  &
!$acc& copyin(0.0_r_def,1.0_r_def,field1_proxy,field1_proxy%data,field2_proxy,field2_proxy%data,map_aspc1_field1,map_aspc1_field2, &
!$acc& ndf_aspc1_field1,ndf_aspc1_field2,nlayers,undf_aspc1_field1,undf_aspc1_field2)
      !
      !$acc parallel default(present)
      !$acc loop independent
      DO df=loop0_start,loop0_stop
        field1_proxy%data(df) = 0.0_r_def
      END DO
```
Now there is also a '0' and '1' in the copy-in, and while I am not an openacc expert, that just looks wrong :)

edited to fix the example number.

**Comment by arporter** [comment]
This seems to have been fixed by #1669 and #1724. I've just generated, built and run lfric/eg14 on GPU on Isambard and all is well.
