### ISSUE TITLE
Allow function spaces to know what cell to loop to

### ISSUE THREAD

**Issue by thomasmelvin** [stfc/PSyclone#17]
Currently psyclone (and psykalite) obtains the horizontal looping limit from the mesh depending on if the field being written to is continuous (or unknown) or discontinuous

If the field is continuous or unknown (such as for general kernels) then `mesh%get_last_halo_cell(1)` is used
If the field is discontinuous then `mesh%get_last_edge_cell()` is used

Its proposed to put this information into the function spaces so that psyclone just needs to generate
`
do cell = 1,ouput_field%vspace%get_last_cell()
...
end do
`

where `vspace%get_last_cell()` contains either `mesh%get_last_halo_cell(1)` or `mesh%get_last_edge_cell()`

The corresponding lfric ticket is 
https://code.metoffice.gov.uk/trac/lfric/ticket/985#ticket

**Comment by thomasmelvin** [comment]
I think so, (in out current method) every invoke would have: 
`do cell = 1,mesh%get_last_edge_cell() 
... 
end do`
which is the internal cell loop, and then some (continuous spaces) would also have an extra
`do cell = mesh%get_last_edge_cell() + 1,mesh%get_last_halo_cell(1)
... 
end do`

**Comment by rupertford** [comment]
Hi Tom,

I am not sure about the logic for this change, could you kindly explain.

From PSyclone's perspective we will still need to know about actual loop bounds to be able to perform or disallow loop fusion (via a PSyclone transformation).

Also, as Andy says, we will still need to make use of and know about "inner" and "outer" halos when performing loop splitting (via a PSyclone transformation) to allow overlap of comms and compute and the values will depend on stencil sizes as well as continuity.

We will also need to know about "outer" halos if we are able to perform redundant computation (via a PSyclone transformation) to avoid communication.

In all of the above cases I think we will need to use the "old" explicit API that Mike Hobson implemented.

**Comment by thomasmelvin** [comment]
Rupert,

I think the original logic is invalid, but it was caused by a worry that operators for discontinuous fields were being created only on owned cells but applied on halo cells. This is not the case as psyclone computes operators on the first halo by default.

The only remaining question is then if there are any benefits/hindrances to including the looping index in the function space, it appears you have a good reason for wanting to keep things as they are son in that case I think we can ignore this ticket (and the corresponding lfric one)

**Comment by rupertford** [comment]
Thanks Tom,

I don't think PSyclone cares where the loop indexing comes from as long as we can get access to the various bounds that we will need, so if it makes sense for LFric to move it to the function space (with the same functionality available) I don't think it matters to us - although I might be missing something.

**Comment by arporter** [comment]
After discussion we've decided that this is not an issue and there's no need/advantage to change anything so closing this ticket.
