### ISSUE TITLE
OpenACC support for GOcean 1.0

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#170]
OpenACC 2.6 (https://www.openacc.org/sites/default/files/inline-files/OpenACC.2.6.final.pdf) now supports "deep-copying" of members of Fortran derived types from the host to the device.
This makes adding support to PSyclone for OpenACC much more straightforward.
In this issue we will implement this support with the GOcean 1.0 API as the first target.

**Comment by arporter** [comment]
In fact, requiring that modules (that PSyclone does not currently touch) have OpenACC mark-up added to them is something that would have to be taken on by the infrastructure developer. It's very likely that other changes to infrastructure will be required to get OpenACC working anyway (e.g. I've added the `data_on_device` attribute to GOcean field objects).

**Comment by arporter** [comment]
The original work for OpenACC support was done under ticket 322 on the MetOffice SRS on branch https://github.com/stfc/PSyclone/tree/PSyclone_r3720_OpenACC_directives/src. However, that was 2 years ago so I'm going to start again with a fresh `openacc` branch.

**Comment by arporter** [comment]
I can get the basics working quite quickly but this involves putting GOcean API-specific code inside `psyGen.py`. This is because `AccParallelDirective.var_list()` creates a list of just the field names required by a given kernel (`Kernel.arguments.args[idx].name`) . For the GOcean 1.0 API we must append "%data" to get the actual array being passed to the kernel. For the OpenACC `copyin` directive I think I need the name of the field object *and* the data array within it.

**Comment by arporter** [comment]
Although this issue is explicitly targeting the GOcean API, I do need to design with other APIs in mind.
The Dynamo 0.3 code that we would be putting inside a parallel region might look something like:

      DO cell=1,mesh%get_last_halo_cell(1)
        !
        CALL matrix_vector_mm_code(cell, nlayers, v_proxy%data, s_proxy%data, &
                mm_proxy%ncell_3d, mm_proxy%local_stencil, ndf_any_space_1_v, &
                undf_any_space_1_v, map_any_space_1_v(:,cell))
      END DO

**Comment by arporter** [comment]
The kernel arguments for Dynamo 0.3 are marshalled by the `dynamo0p3.ArgOrdering` class. This would probably be the place to add an `acc_var_list()` method or similar. We will also need to deal with the fact that flagging that a field is on a device will be API specific (e.g. in GOcean we set `fld_obj%data_on_device = .true.`).

**Comment by arporter** [comment]
What I have so far will only successfully manage data lifetimes (on the device) for a single invoke. As soon as we have more than one invoke, potentially involving different sets of fields, we will need to be more careful about managing whether or not data is already on the device.

**Comment by arporter** [comment]
I've done a manual check in NEMOLite2D where I make sure that I do visit two `enter data` statements and both list `ssha, ssha%data` in the `copyin` clause. The second of these statements *does not* cause the host values for `ssha` to be copied over again so we are safe.

**Comment by arporter** [comment]
I can simplify the clause of the `if()then` by just introducing a "is this my first visit to this invoke?" variable and using that to decide whether or not to do the `enter data`:

    if(first_time)then
    !$acc enter data &
    !$acc copyin(sshn_t, sshn_t%data, sshn_u, sshn_u%data, sshn_v, sshn_v%data, &
    !$acc        ssha, ssha%data,  &
    !$acc        hu, hu%data, hv, hv%data, ht, ht%data, &
    !$acc        un, un%data, vn, vn%data, &
    !$acc        sshn_t%grid, sshn_t%grid%tmask, sshn_t%grid%area_t)
       first_time = .false.
       ssha%data_on_device = .true.
       ...
    end if

**Comment by arporter** [comment]
I've extended the `psyGen.Arguments` class with an `acc_args()` method (I probably need a better name). This method returns the list of things that need to be provided to the `copyin()` clause of `enter data`. The method is 'virtual' in `psyGen.Arguments` and implemented in `gocean1p0.GOKernelArguments`.

**Comment by arporter** [comment]
Next stage is to find a good way to deal with the setting of flags to indicate that a given field is on the remote device.

**Comment by arporter** [comment]
I now have no API-specifc code in psyGen. I've sub-classed `ACCDataDirective` (as `GOACCDataDirective`) and in that have implemented a `data_on_device()` method which adds the necessary nodes into the provided Schedule. `ACCDataDirective.data_on_device()` is virtual.
In order to ensure the transformation creates a `GOACCDataDirective` I've modified it to examine what type of `Schedule` it has been passed and then do the right thing.

**Comment by arporter** [comment]
The simplest thing to do is to simply call `acc_update_device(scalar_arg)` every time we enter an invoke. We can always optimise this later if it becomes a problem.

**Comment by arporter** [comment]
I've changed the code so that `data_on_device` now only generates a list of fields for gocean1.0. For other APIs we may need other quantities at well but having a `fields` method is much clearer than an `obj_list` method. I may be able to use `psyGen.args_filter()` to tidy-up what I've done so far.
TODO: 
1. get the logical variable support in (#173)
2. work-out how to get OpenACC-specific code to go through compilation tests (directives will be OK but I also use the run-time library)
If I manually edit the generated code to fix 1. above then the nemolite2d code almost compiles (I need to add `!$acc routine seq` to the kernels).

**Comment by arporter** [comment]
Hit trouble with un-qualified imports when running the build system for nemolite2d under Python3. I've fixed those now (last two commits) and the generated code compiles when OpenACC is not enabled. When it *is* enabled then the build fails because the kernels don't have `!$acc routine` in them yet.

**Comment by arporter** [comment]
Manually added the necessary directives to the kernels and the infrastructure modules (so that kernels can `use` module variables) and nemolite2d builds and runs (unoptimised on my Quadro K600):

    /home/me/Projects/GOcean/PSycloneBench/ocean/nemo/nemolite2d/psykal/psy_acc.f90
      invoke_0  NVIDIA  devicenum=0
        time(us): 50,895,697
        34: data region reached 1 time
            34: data copyin transfers: 105
                 device time(us): total=3,079 max=99 min=4 avg=29
        34: upload reached 2 times
            34: data copyin transfers: 2
                 device time(us): total=18 max=9 min=9 avg=9
        60: compute region reached 10 times
            60: kernel launched 10 times
                grid: [1]  block: [1]
                 device time(us): total=3,541,958 max=360,807 min=347,131 avg=354,195
                elapsed time(us): total=3,542,185 max=360,833 min=347,170 avg=354,218

Whoop!

**Comment by rupertford** [comment]
Whoop indeed!

**Comment by arporter** [comment]
Point 2. of my earlier TODO list is problematic because we do not currently support compilation testing for the gocean1.0 API. That feels like something for a separate Issue.

**Comment by arporter** [comment]
We currently generate code of the form:

      !$acc parallel default(present)
      DO j=1,jstop
        DO i=1,istop+1

This only parallelises the outer `j` loop. In the manual version we added a `loop collapse` directive:

    !$acc parallel default(present)
    !$acc loop collapse(2)
        do jj = 2, N, 1
          do ji = 2, M, 1

Although OpenMP has `collapse` too, we do not yet support it in PSyclone so it is a new concept here.

**Comment by arporter** [comment]
In fact, the `loop` directive is a new concept here - it is distinct from the `parallel` that we've implemented so far. Therefore I think it needs its own Transformation, e.g. `OpenACCLoopTrans`.

**Comment by arporter** [comment]
In fact, on reading the 2.6 spec., I think I've misunderstood and no worksharing takes place *unless* there is a loop directive - without that the gangs just compute the same thing redundantly. `!$acc parallel` is therefore equivalent to `!$omp parallel` and defines a region rather than only being applicable to a loop.

**Comment by arporter** [comment]
That being so, `!$omp parallel` and `!$acc parallel` are *very* similar so I've changed `OMPParallelTrans` into a general `ParallelRegionTrans`. I then sub-class this to get back `OMPParallelTrans` and `ACCParallelTrans`. Hopefully I can do the same trick for `!$omp do` and `!$acc loop`.

**Comment by arporter** [comment]
I can although I have to override the `apply` method for the OpenMP version as it has an optional `reprod` argument.

Moving on to look at `psyGen.OMPDoDirective`, I see this has a `_within_omp_region()` method which checks that it has an `OMPParallelDirective` as an ancestor (excluding `OMPParallelDoDirective`). This is used at code-generation time (i.e. with `gen_code()`). I need the same thing for `ACCLoopDirective` as it too must be within a parallel region. Given my use of `default(present)` when creating an OpenACC parallel region, it follows that such a region must have an `enter data` directive as ancestor. I need to add a check for this. There are therefore three cases that require a very similar check on the ancestry of a given Node. To further complicate matters, `Node` already has an `is_openmp_parallel()` method which checks for an `OMPParallelDirective` ancestor (i.e. including `OMP parallel do`). Possibly this should be re-named to `is_thread_parallel()` and could be re-written to use a general-purpose solution to the three ancestry tests I've already described above.

**Comment by arporter** [comment]
Given that `_within_omp/acc_region()` were only ever called just once, I've simplified them using `ancestor()` and in-lined them. I've extended `ancestor()` to take an optional list of classes to exclude when searching. Code is now fairly tidy but needs further tests I expect.

**Comment by arporter** [comment]
Can now update NEMOLite2D script to add a `!$acc loop` directive to each loop nest:

    60: compute region reached 10 times
        60: kernel launched 10 times
            grid: [2]  block: [128]
             device time(us): total=735,546 max=73,598 min=73,490 avg=73,554
            elapsed time(us): total=735,763 max=73,617 min=73,529 avg=73,576

i.e. 0.7s as compared to the 3.5s reported earlier (i.e. without the loop directive).

**Comment by arporter** [comment]
To reproduce the manual OpenACC version, I need to be able to add the `COLLAPSE` clause to the directive. This is also a valid thing to do in OpenMP.

**Comment by arporter** [comment]
We have `ACCLoopDirective->ACCDirective->Directive` and `OMPDoDirective->OMPDirective->Directive`. Given this structure I can't have both `ACCLoopDirective` and `OMPDoDirective` both inherit from some common class, e.g. `LoopDirective` or some such without doing multiple inheritance. I can either duplicate the functionality required to support `COLLAPSE` in both `ACCLoopDirective` and `OMPDoDirective` or, re-factor. e.g. should the flavour of directive (ACC or OMP) be a property of some generic loop-directive class?

**Comment by arporter** [comment]
Can now build and run NEMOLite2D with the COLLAPSE(2) clause on all of the parallel loops:

    60: compute region reached 10 times
        60: kernel launched 10 times
            grid: [510]  block: [128]
             device time(us): total=155,073 max=15,579 min=15,464 avg=15,507
            elapsed time(us): total=155,408 max=15,601 min=15,485 avg=15,540

**Comment by rupertford** [comment]
PR #177 is now on master. Closing this issue.
