### ISSUE TITLE
Rethink what happens with named arguments when we call replace_with in an argument

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#1704]
For example in Nemo dynzdf.f90:
```
CALL prt_ctl( tab3d_1=ua, clinfo1=' zdf  - Ua: ', mask1=umask,               &
    &         tab3d_2=va, clinfo2=       ' Va: ', mask2=vmask, clinfo3='dyn' )
```
has the node.argument_names:
[None, 'clinfo1', 'mask1', None, 'clinfo2', 'mask2', 'clinfo3']

**Comment by sergisiso** [comment]
After parsing it looks alright:
```
(Pdb) pp sched[-2].if_body[0].argument_names
['tab3d_1', 'clinfo1', 'mask1', 'tab3d_2', 'clinfo2', 'mask2', 'clinfo3']
```

The problem is that one transformation does: `reference.replace_with(new_ref)` for argument 1 and 4, which for the reconcile method it means it loses the name (from docs: an argument that has replaced a named argument will not be a named argument).

After this point it looks like:
[None, 'clinfo1', 'mask1', None, 'clinfo2', 'mask2', 'clinfo3']

Which the backend can not generate as it is not valid Fortran (non named argument after named argument)

@rupertford we may need to revise this. I don't think user code should check every time it wants to replace a reference where does it sit to know if it has to maintain a possible name argument. We could include a rule in reconcile that if a new argument is in a position where the previous id disappeared, it re-uses that argument name.

```
  9     def _reconcile(self):
 10         '''Update the _argument_names values in case child arguments have been
 11         removed, added, or re-ordered.
 12
 13         '''
 14         new_argument_names = []
 15         for child in self.children:
 16             for arg in self._argument_names:
 17                 if id(child) == arg[0]:
 18                     new_argument_names.append(arg)
 19                     break
 20             else:
 21                 # This argument did not exist before:
 22                 # If in its position there was a named argument that has lost
 23                 # its associated id, keep the name:
 24                 previous_id = self._argument_names[child.position]
 25                 if not any(id(c) == previous_id for c in self.children):
 26                     new_argument_names.append((id(child),
 27                         self._argument_names[child.position][1]))
 28                 else:
 29                     new_argument_names.append((id(child), None))
 30         self._argument_names = new_argument_names
```

I probably need to make this more robust (e.g if child.position is larger than previous argument_names list or if it can be tricked with multiple reorders/replaces between calls to reconcile). But does this new rule seem sensible?

**Comment by rupertford** [comment]
Hi @sergisiso, I think you said you were taking this on, is that right?

I worry about keeping the name of named arguments by default when we add in a new argument. We already have specialised functions for adding/modifying named args. Perhaps we should just extend those? One option would be to specialise `replace_with` and give it an additional argument that lets us say whether to keep a named argument or not? We could default this to keep or not-keep depending on what is most intuitive?
