### ISSUE TITLE
Support `if`s in PSyAD

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1720]
`momentum_viscosity_kernel_mod.F90` contains `if`s which are not yet supported in PSyAD.

I think the rule is pretty simple. The if itself does not change, we just have to check that any variables used for its condition are passive.

**Comment by rupertford** [comment]
momentum_viscosity_kernel_mod.F90 has an active variable that is part of the if condition but there are no active variables within the body. I think this is OK as we can re-order the if and then treat it normally. Something to ask the adjoint specialists.

**Comment by rupertford** [comment]
Created branch [1720_psyad_ifs](https://github.com/stfc/PSyclone/tree/1720_psyad_ifs)

**Comment by arporter** [comment]
> momentum_viscosity_kernel_mod.F90 has an active variable that is part of the if condition but there are no active variables within the body

I asked Christine about this and she said that such code is not linear and needs to be passed back to her.

**Comment by arporter** [comment]
I'll take this one on as it seems to be the most pressing issue. According to the ECMWF presentation:

    if (condition) TL code => if (condition) Adj code

If the code within the If block does not contain any active variables then it is entirely passive and can be moved to be with all of the other passive statements. If it contains active variables then its Schedule must be transformed.

**Comment by rupertford** [comment]
I think the schedule visitor will deal with the passive case and the code I've written in this issue will deal with the active case. We just need to raise an exception if any variables in the condition part of the if are active.

**Comment by arporter** [comment]
Ah, OK. It looks as though you haven't pushed anything on this branch yet. I can leave it until such times as you are able to do the push.

**Comment by rupertford** [comment]
PR #1747 is on master so this issue can be closed.
