### ISSUE TITLE
Update setup.py to fparser 0.0.15

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1748]
#1707 updated the PSyclone master to the lastest fparser submodule which is the 0.0.15 release. However, the `setup.py` in PSyclone still points to 0.0.14 as the prerequisite. This affects the installation of PSyclone from a working copy of the master by using the fparser from the `external` submodules. Installing fparser from the submodule downloads and installs 0.0.15 release first and then installs 0.0.14 from the PSyclone's `setup.py`.
I was a code reviewer for #1707 and overlooked this, so I am happy to fix it.

**Comment by arporter** [comment]
Thanks for fixing Iva. When installing PSyclone for production use, I don't think you should be using the version of fparser in the submodule.
