### ISSUE TITLE
Argument to display version string

### ISSUE THREAD

**Issue by MatthewHambley** [stfc/PSyclone#175]
It's a small thing but it would help those of us who maintain development environments if PSyclone offered an argument which returned its version number. At the moment I can use ``which psyclone`` but that only works if it's been installed in a version specific location.

It might be worth making the version string available through an API in case PSyclone is ever used as a library by other programs.

Agreement must also be reached on the format of the string. I suggest the classic `<major>.<minor>.<release>[-<tag>]` with "tag" being "SNAPSHOT" at head of trunk and nothing for releases.

**Comment by arporter** [comment]
PSyclone has the `-v` flag, introduced (by Joerg) with the 1.6.0 release. It prints the version number as specified in `psyclone.version` which is used by pypi and the documentation. Admittedly there's no API to access that information but it can easily be added to `version.py` should it ever be required.

I'll close this issue for now since there's no current need for an API.

**Comment by MatthewHambley** [comment]
I am in the process of updating our PSyclone installation which is why this came up. I saw a `-v` option and tried it but got a "too few arguments" error so I assumed it was for something else.

**Comment by rupertford** [comment]
Yes, the -v option is an optional addition so only outputs information if the required arguments are valid. This is not idea but it was easy to add in the first instance.

**Comment by hiker** [comment]
That is an unfortunate side effect of the way the arguments are defined atm: psyclone must have one filename as parameter, without this argparse throws an error. For now you can use psyclone -v non_existing_file ... though this will print a warning that the file does not exist :(  I can quickly just abort psyclone if -v is specified, but changing the argument parsing to make sure there is a filename in most cases might be a bit more work :(

**Comment by hiker** [comment]
Dang ... I should have checked if there already has been an answer first :)
