### ISSUE TITLE
Incorrect parameters to OMP transforms can lead to invalid code and python exceptions

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#176]
A x-failing test case is in:

https://github.com/hiker/PSyclone/blob/openmp-test/src/psyclone/tests/gocean1p0_transformations_test.py
(test_omp_region_with_slice_change_order, lines 290)

1) the omp transform can change the order of statements
2) a ValueError can be raised if the same child is listed more than once (imho it should be a TransformationError).

Note that my monitoring hooks have a fixed that should solve those issues, and I am happy once the monitoring hooks are merged to master to fix this issue properly.

**Comment by arporter** [comment]
Thanks for finding this @hiker. The link you give is to a file that only has ~224 lines and no `test_omp_region_with_slice_change_order`? Note that in my work on OpenACC (#170) I'm re-factoring the OpenMP-related code slightly so we may have some work to do to avoid clashes.

**Comment by hiker** [comment]
0p1 or 1p0 ... that's about the same, isn't it? So sorry for mixing up the two files, I've updated the link in the original report.

I'll certainly wait till #170 is done - my changes will likely be in a separate _validate method, so I don't expect problems with conflicts, as long as the input parameters are about the same :)
