### ISSUE TITLE
PSyclone errors due to fparser strict order change

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1764]
The strict order PR in fparser has uncovered some bugs in the test examples. It also causes the fparser2psyir translation to fail for one of the test codes (saying that a variable is undeclared even though it is). The reason for this is that the parse tree that is generated is different, but it should be correct. The test code failure needs to be checked to make sure it is an issue with fparser2psyir and not in the fparser parse tree itself.

**Comment by rupertford** [comment]
Created branch [1764_fparser_strict_order_errors](https://github.com/stfc/PSyclone/tree/1764_fparser_strict_order_errors)

**Comment by arporter** [comment]
#1766 is merged.
