### ISSUE TITLE
Re-factor DeclGen and TypeDeclGen

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#181]
`f2pygen.DeclGen` and `f2pygen.TypeDeclGen` are closely related but don't currently share/re-use any code. We also don't support declaring variables of type `character` (which I need in #174) so I shall take this opportunity to add that too.

**Comment by arporter** [comment]
Working on `decl_refactor` branch. While `DeclGen` had explicit arguments for the various attributes (such as pointer), `TypeDeclGen` just let the caller pass in a list of attributes. I think the former way is better so will check through the code to see how often we use the latter.

**Comment by arporter** [comment]
It turned out that only Joerg's new profiling code used the `attrspec` argument and that only once. I've therefore removed the argument from the constructor.

**Comment by arporter** [comment]
I've added support for character declarations but in doing so realised that they are special and have an extra 'length' attribute. This necessitates an extra argument to the constructor but this argument is not applicable to any other type of declaration. I'm not sure whether I should further sub-class `DeclGen` to e.g. `CharDeclGen`?

**Comment by rupertford** [comment]
I think sub-classing makes sense. In general objects shouldn't have invalid properties.

**Comment by rupertford** [comment]
PR #182 is now on master. Closing this issue.
