### ISSUE TITLE
OMPTargetTrans does not exclude CodeBlocks

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1815]
While working on https://github.com/stfc/PSycloneBench/pull/87 it turns out that `OMPTargetTrans` happily puts directives around a loop that does both a reduction and a WRITE. At the very least it should spot the CodeBlock containing the WRITE and refuse to transform it. Possibly `OMPTargetTrans` should sub-class `ParallelRegionTrans` rather than just `RegionTrans` and perhaps this is true for `ACCKernelsTrans` too? (See https://psyclone-ref.readthedocs.io/en/latest/_static/html/classpsyclone_1_1psyir_1_1transformations_1_1region__trans_1_1RegionTrans.html)

**Comment by arporter** [comment]
![image](https://user-images.githubusercontent.com/17409212/181108161-aa663834-8a05-442b-b937-227533322498.png)

**Comment by sergisiso** [comment]
I agree to exclude *all* codeblocks in the OMPTargetTrans, in the Nemo script I have it as a condition to the loop that walks the Loop nodes. But it would be safer to avoid it a the transformation level to prevent silent issues like in tracer advection.

I don't think reductions are invalid for OMPTargetTrans as the directive alone does not parallelise the body. The reduction should be catch and prevent the OMPLoopTrans though but we may still want to run a reduction serially on the GPU to avoid transfering data (or not but this is up to the psyclone script to decide)

**Comment by sergisiso** [comment]
I am taking this. I will not make it a `ParallelRegionTrans` since by itself is not really a Parallel Region (it needs another directive to make the contents parallel) but I will prevent CodeBlocks, UBOUNDS and LBOUNDS inside the directive body.
