### ISSUE TITLE
psyad should support generic and lfric-specific solutions

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1820]

**Comment by rupertford** [comment]
If this is an LFRic-specific implementation and the kernel metadata code points to an interface then adjoint all routines specified in the interface. If it points to a routine then only translate that routine. If this is a generic implementation then only support one routine as we don't know which one to support.

**Comment by rupertford** [comment]
We need a way to specify on the command line whether this is generic or lfric-specific. An obvious solution would be to add a -api xxx option with no api specified implying generic (or perhaps lfric if we have a config file to specify?).

**Comment by arporter** [comment]
In my work on the test harness I've introduced a `-api` flag for psyad (origin/1555_lfric_psyad_harness_2). It could be broken out as a separate PR though.

**Comment by rupertford** [comment]
I can wait for #1782 to introduce the -api flag. No need to break it out. Closing this issue.
