### ISSUE TITLE
Outdated tutorials

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1833]
Some tutorials appear to be outdated. In at least one case the solution file was fixed, but not the file the user is supposed to modify. Example:
```
psyclone/tutorial/practicals/LFRic/building_code/3_time_evolution$ diff prop_perturbation_kernel_mod.f90 solutions/prop_perturbation_kernel_mod.f90 
...
<   use argument_mod,      only: arg_type, func_type, &
<                                GH_FIELD, GH_REAL,   &
<                                GH_WRITE, GH_READ,   &
<                                CELLS
---
>   use argument_mod,      only: arg_type, func_type,   &
>                                GH_FIELD, GH_REAL,     &
>                                GH_SCALAR,             &
>                                GH_READWRITE, GH_READ, &
>                                CELL_COLUMN
67,70c68,71
<     type(arg_type), dimension(3) :: meta_args = (/ &
<          arg_type(GH_FIELD,   GH_WRITE, W3),       &
<          arg_type(GH_FIELD*3, GH_READ,  W3),       &
<          arg_type(GH_REAL,    GH_READ)             &
---
>     type(arg_type), dimension(3) :: meta_args = (/        &
>          arg_type(GH_FIELD,   GH_REAL, GH_READWRITE, W3), &
>          arg_type(GH_FIELD*3, GH_REAL, GH_READ,      W3), &
>          arg_type(GH_SCALAR,  GH_REAL, GH_READ)           &
72c73
<     integer :: iterates_over = CELLS
---
>     integer :: operates_on = CELL_COLUMN

Is that done on purpose (i.e. part of the training??) If not, should I open a ticket? 

<https://teams.microsoft.com/l/message/19:672ee0ea20994377803a1388d1e4a3a9@thread.tacv2/1660032682496?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&amp;groupId=38f4ed55-5f70-4478-b992-835e4011118a&amp;parentMessageId=1660032682496&amp;teamName=PSyclone&amp;channelName=Developers&amp;createdTime=1660032682496>
```

**Comment by TeranIvy** [comment]
From @hiker:

> Please do not remove the pre-processed include files, they are required for the kernel extraction. The problem with the compilation of the tutorials seems to be the refactoring of the setting of the LFRIc infrastructure include paths in [b7dff41](https://github.com/stfc/PSyclone/commit/b7dff413e71fd01b4ba18be329c70d7940222687).
> 
> I just quickly tried `tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/solutions`, and the following patch fixed compilation for me:
> 
> ```
> it diff Makefile
> diff --git a/tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/solutions/Makefile b/tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/solutions/Makefile
> index be64ec9b8..edcd91bc9 100644
> --- a/tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/solutions/Makefile
> +++ b/tutorial/practicals/LFRic/building_code/1_simple_kernels/part1/solutions/Makefile
> @@ -63,6 +63,7 @@ LFRIC_LIB=$(LFRIC_PATH)/lib$(LFRIC_NAME).a
>  
>  # This will add the required include flags to F90FLAGS
>  include $(LFRIC_PATH)/lfric_include_flags.inc
> +F90FLAGS += $(LFRIC_INCLUDE_FLAGS)
>  
>  # Object rules
>  DRIVER_OBJ = $(notdir $(filter %.o,$(DRIVER_SRC:.f90=.o)))
> ```
> 
> I didn't check if all compilation failures are caused by this, but am happy to properly fix this ... next week :)

Link: https://github.com/stfc/PSyclone/pull/2161#issuecomment-1571812059
