### ISSUE TITLE
pytest-pep257 only supports Python <= 3.4

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1874]
At the moment the `setup.py` file lists `pytest-pep257` as one of the dependencies in the `test` section. However, it seems that no one uses it and it does not work for (at least) 3.10.6-7.

I therefore propose to remove this dependency unless @TeranIvy or @sergisiso object. (Rupert and Joerg have already said they don't use it.)

**Comment by sergisiso** [comment]
No objection from me.
