### ISSUE TITLE
[NEMO] Implicitly-declared subroutine arguments are lost

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1891]
Chris has found that if PSyclone encounters code such as:

    module my_mod

    contains

    subroutine my_sub(iarg)
      write(*,*) iarg
    end subroutine my_sub

    end module my_mod

then PSyclone loses the `iarg` argument to the subroutine (presumably because it is never explicitly declared) and the resulting code is wrong.

**Comment by arporter** [comment]
Started to tackle this on branch `1891_implicit_arg`.

**Comment by arporter** [comment]
(How many NEMO files does this affect @deardenchris ?)

**Comment by rupertford** [comment]
I'm also concerned about trying to support implicitly declared data, so would go with catching it, at least for now. It feels like it is a pre-PSyIR problem.

**Comment by deardenchris** [comment]
> (How many NEMO files does this affect @deardenchris ?)

Hi @arporter There are three NEMO files affected, namely trcbdy.f90, trcdta.f90 and trcstp.f90, but it only occurs as a result of me building the GYRE configuration with `key_top` switched off. 

To illustrate, here is [the link to the raw NEMO source code for trcbdy.f90](https://forge.nemo-ocean.eu/nemo/nemo/-/blob/4.2.0/src/TOP/trcbdy.F90). You can see that for the case when `key_top` is not defined, argument `kt` is implicitly declared. I tend to agree that catching it would be the way to go. Perhaps this is one to follow up with the NEMO systems team; although it's not invalid fortran, it seems to me that best practice would be to ensure that `kt` is declared explicitly in both cases, for consistency with the rest of the code.
