### ISSUE TITLE
Update big-picture with those parts that are now complete

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#192]

**Comment by arporter** [comment]
I've just come to try and do this and had to install freemind again for some reason. I now have version 1.0.1 and when I come to edit our existing `thebigpicture.mm` it says it will convert it to a new format that can't be opened by older versions of FreeMind. The question is (looking @TeranIvy), what version of FreeMind do the MO use at the minute?

**Comment by arporter** [comment]
I've resorted to using Windows and succeeded in editing the picture. I propose using the "yellow traffic light" for work in progress unless you can think of anything better...

**Comment by rupertford** [comment]
PR #203 is now on master. Closing this issue.
