### ISSUE TITLE
Improve error output when `lower_to_language_level` fails in visitor.py

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#1922]
This is mostly a debugging/testing issue probably, but if you have an error during lowering, the output is very opaque and doesn't capture what is going on.

The output you get is something like:
```
E           psyclone.psyir.backend.visitor.VisitorError: Visitor Error: Failed to lower 'FileContainer[]
E           '. Note that some nodes need to be lowered from an ancestor in order to properly apply their in-tree modifications.
```

If there is an issue in the code, this is not correct, as:
1. The node that fails to be lowered is not necessarily of the type given (since it can be any child in the tree that needed lowering)
2. The error message is not representative of the actual error that occurs.

I think since we have the exception as err, we can do something like `err_str = traceback.format_exception(err)` to get this information and include it in the VisitorError that is being raised.

**Comment by sergisiso** [comment]
> I think since we have the exception as err, we can do something like err_str = traceback.format_exception(err) to get this information and include it in the VisitorError that is being raised.

Since the err is part of the raise-from expression I would expect this to already be the case and the original Exception to be above the error message-trace that you mention.. if you scroll up isn't there another backtrace+error message? What version of python do you use?

**Comment by LonelyCat124** [comment]
Maybe it does but I didn't see it anywhere in my pytest output, but maybe I just missed it. I'll reintroduce a bug tomorrow and check - I'm on 3.8 i think

**Comment by LonelyCat124** [comment]
@sergisiso It does show it, was just a long way up from pytest output - I imagine it would be better from general code so I will close this.
