### ISSUE TITLE
Work around for #1295

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1926]
Ticket #1295 points out that importing modules can execute code, and especially create a config object. Searching a bug in my LFRic patch to use a custom `psyclone.cfg` file (instead of having to modify the installed config file), revealed a severe problem:
Care has been taken that the command line option --config takes precedence over the value set in PSYCLONE_CONFIG. Unfortunately, this does not work as expected:
`generator.py` imports `RaisePSyIR2GOceanKernTrans` ... which imports `transformations.py` ... which imports `fric_constants.py`. Due to #1295,  importing `lfric_constants.py` creates an instance of the config file, which is then used to set the values for LFRicConstants.

After the import, before parsing the command line, a dummy config file is then created (i.e. the old one created above is thrown away) before parsing the command line (in order to query the config object for e.g. default API). After parsing the command line option, the real config file is loaded (the dummy one is thrown away), potentially using the value of the `--config` command line option.

From then on, the config file is well defined, based on command line (which takes precedence over PSYCLONE_CONFIG which takes precedence over the default locations).

BUT: the `LFRicConst` object was initialised before by the very first config file, and it is not recreated. Therefore, if PSYCLONE_CONFIG is defined (or a config file is found in a default location), the LFRicConst object is initialised with the wrong values, and as  a singleton these values stay around.

In case of my PR, this resulted in NOT using the local `psyclone.cfg` settings included in LFRic, instead it would pick up the default settings from the PSyclone installation (and LFRic needs a modified config file in order to work).

The following patch seems to fix the problem by forcing `LFRicConstants` to be re-created after parsing the command line and loading the right config file.

Fixing #1295 would of course be better, but this here is an easy work around (which would just need a comment or so :) ).
```
git diff generator.py
diff --git a/src/psyclone/generator.py b/src/psyclone/generator.py
index 0cf1f5672..f6aa25281 100644
--- a/src/psyclone/generator.py
+++ b/src/psyclone/generator.py
@@ -57,6 +57,7 @@ from psyclone.domain.common.algorithm.psyir import (
 from psyclone.domain.common.transformations import (
     AlgTrans, AlgInvoke2PSyCallTrans)
 from psyclone.domain.gocean.transformations import RaisePSyIR2GOceanKernTrans
+from psyclone.domain.lfric import LFRicConstants
 from psyclone.errors import GenerationError, InternalError
 from psyclone.line_length import FortLineLength
 from psyclone.parse.algorithm import parse
@@ -418,6 +419,7 @@ def main(args):
     # and config will load the default config file.
     Config.get().load(args.config)
 
+    LFRicConstants.HAS_BEEN_INITIALISED = False
     # Check API, if none is specified, take the setting from the config file
     if args.api is None:
         # No command line option, use the one specified in Config - which
```

I am happy to do a PR when I'm back from my leave next week. Note that (at least) the gocean_config object might need to be checked (though iirc it is not instantiated during import).

**Comment by arporter** [comment]
#1295 was closed in March 2023. @hiker can we close this one now?
