### ISSUE TITLE
Add extra options to ACCLoopTrans

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1932]
We don't currently support "gang", "vector" or "seq" clauses and these are used extensively in the manual port of NEMOVAR.

**Comment by arporter** [comment]
Victoria has just re-emphasised that `gang` and `vector` give useful performance improvements so I will look to implement this shortly.

**Comment by jwallwork23** [comment]
Hi @arporter. I implemented this on branch https://github.com/stfc/PSyclone/tree/jwallwork23/loop-gang-vector and would be happy to work on getting it merged. I just copied the approach for `acc loop seq`. It seems to work for the test code we are working on but not sure if there are any additional checks you'd want to add in there?

**Comment by arporter** [comment]
Hi @jwallwork23, that looks good thanks. There may be constraints on which combinations of options are valid although I can't think of any off the top of my head. It would be great to get this merged. We'll need to update the transformation too but that could be a separate PR.

**Comment by jwallwork23** [comment]
Oh yes good point. I think I can see how to do that update, too. Will do that and open a PR :)
