### ISSUE TITLE
add tl and adj kernel code

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1935]
Working adj code has been requested by the Met Office. Nearly working code (without any metadata changes) had been provided previously, but was not kept in the repo. It would be useful to keep the code in the repo to make testing easier.

Also, when trying to create some adjoint kernels that could previously be created, psyad raised some exceptions. These should be be fixed.

The first exception is to do with the `is_upper_bound` method returning false when it should be returning true. The second exception is to do with the kernel-name renaming method only accepting a single routine in a module (but there are multiple routines in multi-precision kernels).

**Comment by rupertford** [comment]
Created branch [1935_psyad_bugs](https://github.com/stfc/PSyclone/tree/1935_psyad_bugs)

**Comment by rupertford** [comment]
This now adds in all requested tl and adjoint kernels.

**Comment by arporter** [comment]
#1937 is on master.
