### ISSUE TITLE
Support for region stencils

### ISSUE THREAD

**Issue by thomasmelvin** [stfc/PSyclone#194]
LFRic [#1449](https://code.metoffice.gov.uk/trac/lfric/ticket/1449) introduces a new type of stencil, the region stencil. This is defined as being a two dimensional region defined by an integer `order` such that it contains at enough cells to fit `(order+1)(order + 2) + 1` polynomials.

It is generated iteratively:
1.Add the central cell to the stencil
1. Add all neighbours of cells in the stencil
1. Add all cells that are neighbours of at least 2 cells already in the stencil.
1. Repeat the 2 previous stages until there are enough cells

This means that on a cubed sphere the stencil will have different sizes at different points, e.g for `order=2`:
- For points away from corners it will contain 9 cells
- For points near corners it will contain 8 cells

The suggested metadata in the kernels is
`arg_type(GH_FIELD,   GH_READ,  W3,          STENCIL(REGION))`

The psy layer code is then:
```fortran
use stencil_dofmap_mod, only: stencil_dofmap_type, STENCIL_REGION
type(stencil_dofmap_type), pointer :: stencil => null()
integer, pointer :: stencil_map(:,:,:) => null()
integer :: stencil_extent, cells_in_stencil

  stencil => density_proxy%vspace%get_stencil_dofmap(STENCIL_REGION, order)
  stencil_map => stencil%get_whole_dofmap()
  stencil_extent = order/2

  do cell = 1,mesh%get_last_halo_cell(1)
      cells_in_stencil = stencil%get_local_size(cell)
      call kernel_code(...                       
                                 stencil_map(:,:,cell),       &
                                  cells_in_stencil )
```

Where `stencil_extent` is used to determine the depth of the halo swaps needed, for example see:
- `invoke_poly2d_flux` in `psykal_lite_mol_mod.F90`
- `poly2d_flux_kernel_mod.F90`

**Comment by TeranIvy** [comment]
The [branch](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/thomasmelvin/r14290_mol2d_version3) is part of [LFRic ticket #1449](https://code.metoffice.gov.uk/trac/lfric/ticket/1449), currently in code review. The new advection kernels are in [gungho/source/kernel/advection](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/thomasmelvin/r14290_mol2d_version3/gungho/source/kernel/advection) directory and PSyKAl lite code in [gungho/source/psy](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/thomasmelvin/r14290_mol2d_version3/gungho/source/psy) directory.

**Comment by arporter** [comment]
Thanks @TeranIvy. I see that `get_local_size` simply does a look-up into a 1D array. Would it be possible to add a method that just returned that whole array (i.e. a reference to it)?

**Comment by thomasmelvin** [comment]
Yes @arporter that should be straightforward, we could replace `get_local_size` with `get_stencil_size` that returns a pointer to the whole array of stencil sizes (currently called) `local_size(ncells)` and then just pass `local_size(cell)` into the kernel

so my psy code previously would be 
```fortran
use stencil_dofmap_mod, only: stencil_dofmap_type, STENCIL_REGION
type(stencil_dofmap_type), pointer :: stencil => null()
integer, pointer :: stencil_map(:,:,:) => null()
integer, pointer :: cells_in_stencil(:) => null()
integer :: stencil_extent

  stencil => density_proxy%vspace%get_stencil_dofmap(STENCIL_REGION, order)
  stencil_map => stencil%get_whole_dofmap()
  stencil_extent = order/2
  cells_in_stencil => stencil%get_stencil_size()
  do cell = 1,mesh%get_last_halo_cell(1)
      call kernel_code(...                       
                                 stencil_map(:,:,cell),       &
                                  cells_in_stencil(cell) )
```

**Comment by arporter** [comment]
I remember that @rupertford had concerns about the implications of this stencil for our dependency analysis. Unfortunately, I can't quite remember what the conclusion was. I see from the above that `stencil_extent = order/2` and looking at the psykalite code:

    if(density_proxy%is_dirty(depth=stencil_extent+1) ) &
       call density_proxy%halo_exchange(depth=stencil_extent+1)

So if we know the order at compile time (i.e. when PSyclone is run) then we know the depth of halo exchanges required. This means that our existing dependency analysis will be fine. If we don't know the order then we can't do any analysis and have to generate code that checks whether a halo-swap is required at run time. This is no different from our existing stencil support (http://psyclone.readthedocs.io/en/stable/dynamo0p3.html#stencil-metadata) where the extent of the stencil is passed down from the Algorithm layer and therefore is not known at compile time.

**Comment by arporter** [comment]
#1060 has been merged.
