### ISSUE TITLE
Evaluators on multiple function spaces

### ISSUE THREAD

**Issue by BShipway** [stfc/PSyclone#196]
Currently, evaluators evaluate on the function space of the first field that a kernel writes to.  It would be useful and potentially clearer to be able to specify the function spaces on which the evaluation is done.  This will require some new metadata, e.g. 
   integer :: evaluator_targets(2) = (/ W0, W1 /)

**Comment by arporter** [comment]
Hi @BShipway, are there any rules about which function spaces may appear in the new meta-data? i.e. presumably there must be a kernel argument on each of the listed spaces?

**Comment by arporter** [comment]
For the sake of backwards compatibility, do you want to keep the existing behaviour and have the new `evaluator_targets` as an optional element?

**Comment by arporter** [comment]
A more compact form of meta-data might be:

    integer :: gh_shape = gh_evaluator(W0, W1)

Can you see any issues with that?

**Comment by BShipway** [comment]
Sorry @arporter, seems I was sending comments to gmail address to the spam - I've now updated my email address to my work one.

I can't see any particular issues with your suggested metadata.  

Re rules: unless there is a reason to add a rule, I don't see why we should do so.  However, in this case, since you'll need to access the basis functions/dofs from a field, then I guess we must have this rule, i.e. that the evaluator_targets must be included as a kernel argument.

Re backwards compatibility: I think this would be helpful.  We could migrate to only use evaluator targets later on.

**Comment by arporter** [comment]
I've thought of a problem with my suggested meta-data - I can't think of a way to ensure that it is valid Fortran as `gh_evaluator` would become an array of arbitrary dimension (depending on the number of function spaces an evaluator is required for). I will therefore fall back to the form originally suggested by @BShipway.

**Comment by arporter** [comment]
Another problem - the statement parser (`expression.py`) cannot cope with array initialisation (`my_array = (/val1, val2/)` or `my_array = [val1, val2]`). This means it can't parse the new meta-data entry. There are two options:
 1. Fix the statement parser
 2. Use fparser2 instead for this specific case

**Comment by arporter** [comment]
I think fparser2 is the way to go, using it instead is straightforward:

    (Pdb) print(assign.items)
    (Name('gh_evaluator_targets'), '=', Array_Constructor('[', Ac_Value_List(',', (Name('w0'), Name('w1'))), ']'))

**Comment by TeranIvy** [comment]
More arguments in favour of using fparser2 :-)

**Comment by arporter** [comment]
Yep :-)

**Comment by rupertford** [comment]
In case it is not clear, there are cases when the required function space(s) is/are due to a field that is read. So I think the constraint should be that it is valid to specify an evaluator on a function space if any of the fields being passed to the kernel are on that function space. I think that is what has been said but I thought I'd check after meeting up with Ben as there are two issues being addressed.

**Comment by arporter** [comment]
Yes, that was my understanding. What about operators @BShipway - are the "to" and "from" spaces both able to appear in the `gh_evaluator_targets` list?

**Comment by TeranIvy** [comment]
Merged PR #210 so closing this issue.

**Comment by arporter** [comment]
Re-opening as I need to actually implement the functionality now that the meta-data support is on master :-)

**Comment by arporter** [comment]
@BShipway, I've just come back to this and am looking at the rules I wrote originally. I'm not entirely sure they're correct. Please could you help me by looking at the following example (ignoring whether or not my use of the various FS makes any sense). If we have metadata:

      type, extends(kernel_type) :: testkern_eval_type
         type(arg_type)  :: meta_args(2) =  (/    &
           arg_type(GH_FIELD,   GH_INC,  W0),     &
           arg_type(GH_FIELD,   GH_READ, W1)   /)
         type(func_type) :: meta_funcs(1) = (/    &
           func_type(W1, GH_DIFF_BASIS)         /)
         integer :: iterates_over = cells
         integer :: gh_shape = gh_evaluator
         integer :: gh_evaluator_targets(2) = (/W0, W1/)
       contains
         procedure, nopass :: code => testkern_eval_code
      end type testkern_eval_type

then am I correct in thinking that the associated kernel arguments will be:

      subroutine testkern_eval_code(nlayers, f0, f1, ndf_w0, undf_w0, map_w0, &
                                    ndf_w1, diff_basis_w1_w0, diff_basis_w1_w1, &
                                    np_xyz_w0, np_xyz_w1)
        integer :: nlayers, ndf_w0, undf_w0, ndf_w1, undf_w1
        integer, dimension(:) :: map_w0, map_w1
        real(kind=r_def), dimension(:) :: f0, f1
        real(kind=r_def), dimension(3,ndf_w1,np_xyz_w0) :: diff_basis_w1_w0
        real(kind=r_def), dimension(3,ndf_w1,np_xyz_w1) :: diff_basis_w1_w1
      end subroutine testkern_eval_code

i.e., the diff-basis arrays are dimensioned according to the FS upon which they are to be evaluated?

**Comment by arporter** [comment]
Having got a bit further with my first test, I see that we in fact assume that the differential basis arrays are dimensioned as:

    real(kind=r_def), dimension(3,ndf_w1,ndf_w0) :: diff_basis_w1_w0

This is not what our documentation says (we have ndf_xyz_w0 instead of ndf_w0 as the extent of the last dimension).

**Comment by rupertford** [comment]
pr #242 has been merged to master. Closing this issue.
