### ISSUE TITLE
Caching and setting datatype of structure references

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1966]
A StructureReference has a `datatype` method, which determines the actual datatype of an access. This of course only works if the datatype is known (i.e. the module where it is defined in was read). This can be expensive, and even determining the datatype of a reference every time it is queried seems overly complex.

I obviously also have problems with the driver creation if a StructureReference (since all I get is DeferredTypes :(  )

Suggestions:

1. Add caching of the determined datatype to a StructureReference.
2. In many cases (e.g. when used from KernCallArg list of a DynCollection class), we know the datatype of a StructureReference (e.g. we know that `ncell_3d` of an operator is an integer). The `create` method of a StructureReference should take an optional argument to easily set the datatype of the reference (i.e. setting the cached attribute). This would allow quickly to set all datatypes of kernel arguments without costly parsing of mod files ... and then to create driver in these cases.

**Comment by sergisiso** [comment]
I am a bit worried that we won't get the cache invalidation right. (although for now we don't do any crazy amount of tree transformations to trigger the conditions).

I would have thought that for the driver creation you would need to resolve the infrastructure modules necessarily (as you are kind of replacing the information that lives there). Is that not the case? If you do it, once the DeferedTypes are concretized in the PSy-layer symbol table, the datatype recursion should be a cheap operation.

**Comment by hiker** [comment]
Thanks a lot, @sergisiso .

Not sure if we will actually be changing existing references, I would assume we will always replace them with a reference to something else - so from that point of view caching can't hurt. Nor is there even a setter for the datatype. So the only option would be to change the symbol that the reference uses (which sounds like a bad idea :) ). 

Otherwise: at this stage I don't need to resolve the infrastructure modules: all symbols are created from the Dyn* classes, and they are then used to create the references for the kernel arguments in the ArgOrdering0based classes. The driver creator hard-codes the handling of fields and array of fields (to convert them to standard arrays) - I don't think this is avoidable.

Otherwise, most standard types are also declared properly (scalars and arrays), but in some cases the argument is a user defined type, e.g.:
```
some_arg_proxy%ncell_3d
```
While this can be properly declared (e.g. I have the module name needed), at this stage this is set as `deferred`. How can I try to properly declare the datatype when I create this reference in an ArgOrdering based class? Do I need to find the module source file, parse it, and then look in the symbol table? I had a quick look in the dev guide, and couldn't spot an example (I assume it's what you call a specialisiation??)

See how easy it would be here to just add a parameter 
```
..., ref_datatype=psyir.LfricIntegerScalarDataType())
```
when creating the reference in KernCallArgList, since we know it must be an integer?

Of course, I could just use the symbol as it is, i.e. `declare some_arg` as operator type, provide `some_arg%ncell_3d` as parameter to read in the values, and then the generic interface of the reading function would call the right implementation. But this then means that our stand-alone driver would depend on the infrastructure modules, which we don't want.

**Comment by sergisiso** [comment]
I can be persuaded if it is called `enforce_datatype=...` instead of caching, since this semantically does not expect invalidations. My concern is on caching things that are dependent on the tree structure, as it will be very difficult to make consistent to non-local changes and we should not give this expectation :)

In the long term I do want to reduce or reliance on reimplementing the LFric infrastructure logic as PSyclone classes, because at the moment if somebody changes some infrastructure detail without knowing about PSyclone it can very easily produce incorrect PSyclone-generated code, but maybe this is a discussion for the future.

**Comment by hiker** [comment]
Thanks, @sergisiso ! I am happy to take the caching component out, I just added this since it seems like an easy performance gain to get.

Otherwise I totally agree, there is a lot of hard-coded stuff in PSyclone. Ideal solution might be to write an fparser script that collects all the required data structures and precisions from the infrastructure files and allows us to 'insert' this into the psyclone config file. Then we could remove all the hard-coded references to (say) `ncell_3d` etc, and query the appropriate name from the config file (but admittedly that would be quite a bit of work, for not much gain, since de-facto LFRic won't really change that part of the code, and if they do, compilation will fail).

I'll do the enforcing, which allows me for now to make some progress :)
