### ISSUE TITLE
Add support for intergrid kernels with stencil accesses

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#1983]
At the moment PSyclone does not support intergrid kernels with stencils but Tom Bendall has a need for these.

**Comment by rupertford** [comment]
The metadata for an intergrid kernel makes use of a named argument when specifying the type of mesh (`GH_COARSE` or `GH_FINE`) that a field is associated with. For example `arg_type(GH_FIELD, GH_REAL, GH_READ, W3, mesh_arg=GH_FINE)`. This is the only `arg_type` metadata that does this. The upshot is that it has to be the last metadata in `arg_type`. Therefore, if allowing an optional stencil to be added to the kernel, we need to place it before `mesh_arg`. For example ... `arg_type(GH_FIELD, GH_REAL, GH_READ, W3, STENCIL(REGION), mesh_arg=GH_FINE)`.

There is some irony here - the optional stencil argument is not specified as an optional argument and the required mesh argument is specified as an optional argument.

We can work with the solution as it is, although it is going to be a pain for the new metadata parsing approach, which assumes the position of an argument is fixed for a particular type of metadata (but in this case the mesh metadata can be the 5th or 6th argument).

For the record, it would be more consistent to specify the mesh in the similar way to the stencil metadata, e.g. `mesh(GH_FINE)` (or simply `GH_FINE` directly and that would allow us to place the optional stencil metadata after the mesh metadata (and even potentially write the stencil metadata as an optional argument if we wanted). For example ...

`arg_type(GH_FIELD, GH_REAL, GH_READ, W3, GH_FINE, stencil=REGION)`

**Comment by rupertford** [comment]
A part of the new metadata processing support which is under development has just made it to master and allows intergrid stencils to be specified.. We are not planning to update the old metadata processing so are people happy to close this issue as resolved on the understanding that the new functionality will become available once the metadata

**Comment by tommbendall** [comment]
Yep, happy to close this if it will be resolved when LFRic picks up the new metadata processing. Thanks!
