### ISSUE TITLE
[PSyData] Support for checksum computation of fields

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#199]
As discussed with Rupert: add suppor for computing a checksum of fields, which can be used for various tasks:
- it can be printed (for each rank in case of DM) to compare two runs to see which fields are different.
- it can be used to detect if a readonly-field gets modified in a kernel.
- two different executables could run at the same time, and exchanging (to be determined how :) ) checksums to automatically detect differences.
- could be used for unit testing.

and more ... or less ;)

I see three ways of implementing the checksum computations:
- create the required Fortran code in PSyclone (i.e. a schedule with a checksum computation as kernel, or no kernel (i.e. function call), but explicitly put the code for the checksum inside of the loop).
- as before, but using a builtin (support for which would need to be added for gocean afaik).
- Make it part of the runtime library, then PSyclone would only need to create a function call.

I personally would tend to the last solution, but happy for suggestion.

Usage would be similar to profile: a command line option to automatically compute the checksum for each field before and after an invoke (and initially just print them out). Additionally there would be a transform that (optionally) takes a list of fields to compute the checksum for (defaulting to all fields in the invoke).

**Comment by hiker** [comment]
After some thinking it might actually be easier to use psyclone to create the code - mainly because in the GOcean API  we would need different loop indices depending on field-type and offset used (afaik), PSyclone already has the boundaries defined (well, tbh - not for all offset types, but they can easily be added if required), it would be some code duplication if we would also have this data in the infrastructure.

Does anyone have  are recommendation for a checksum method? Ideally I would have a function that can be used in any order on a subset of the global field - e.g. in case of DM each process could independently compute its own checksum, and those results could then be combined, and get the same result, independent of the actual domain decomposition.

One approach would be to cast the floating point values to int, and just xor the fields together. But this method would e.g. not detect if e.g. all values of a fields are negated (if the number of elements in the field is even at least). I'll probably still start with this, but if anyone has a better recommendation, please let me know.

**Comment by arporter** [comment]
Hi @hiker, I think generating the code in PSyclone is a good solution - the less we have to worry about a run-time library the better. As to what code to generate, I think you know better than I do. I might try the LFRic list to see whether anyone on there has a tried and trusted recipe.

**Comment by arporter** [comment]
Sam Adams has pointed me to https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/algorithm/checksum_alg_mod.x90. This computes a checksum by doing:

    call invoke( X_innerproduct_X(chksum1, field1) )

which, in turn, does:

    checksum = SUM(field(:)*field(:))

with a global sum performed if DM is in use. Presumably the result is then dependent on the number of MPI ranks in use.

**Comment by arporter** [comment]
@thomasmelvin has since pointed out that this was supposed to be a stop gap until they have "proper checksum support."

**Comment by arporter** [comment]
We had a brief discussion about this in the LFRic telco today. Conclusion was that some sort of hashing is what is required and that "someone out there must have done this before." I think @hiker's proposed solution sounds OK.

**Comment by hiker** [comment]
I had a chat with our ocean people, who recommended to look at MOM5, which I just did. MOM5 is using Fortran's transfer() intrinsic to convert the floating point fields to an integer format (so kind of a C cast ;) ), and then sum up the integer values, giving them reproducible results independent of domain decomposition.
I am happy to try both, sum() or xor(), and see which one works better :)

**Comment by arporter** [comment]
That sounds good - thanks very much for getting to grips with this.

**Comment by MatthewHambley** [comment]
I thought it would be useful to quickly summarise what was said at the telco.

Currently LFRic uses a rather stupid checksum. This is useful for performing KGO checks without having to carry around full fields for comparison. It probably shouldn't be considered any kind of good. As noted, some sort of hash is what is needed.

Implementing hashes in Fortran is tricky as every algorithm I've come across utilises unsigned integers, something which Fortran doesn't understand.

The other issue surrounds what you are trying to test. If you want to know if two fields are bit-for-bit identical then that can be achieved with any hash you like: MD5, SHA256, Adler32 or whatever.

However if you want to know if two fields are the same that is a much harder problem. If two fields differ only in their least significant bit you may well decide that they were identical. Unfortunately no hash I'm aware of can tell you that.

Maybe a hash which discounts a number of least-significant bits up to the accuracy you care about?

**Comment by hiker** [comment]
Great suggestions, thanks a lot! I am going to finish a few smaller issues first before starting with this issue ... I need to think about the unsigned issue a bit :) Inline assembler?? ;)  Best idea so far: either just setting the sign bit to 0 and using 31/63 bits - or using 2 smaller integers and doing some shifting of bits around to avoid the sign bit.
While the existing hashes are standard, afaik they do not allow to combine hashes of a smaller subsection into one overall hash (e.g. compute a hash independent of domain decomposition), so I would prefer one where we could compute a 'distributed' hash, and combine the results.

Then again, I already intended to support different hash functions, so throwing a few more in should not be a problem 👍

**Comment by MatthewHambley** [comment]
Unless there is a strong argument for it I really wouldn't try and implement a hashing function which requires unsigned integers in Fortran. In which case you would be looking to another language. In which case there's no need to go to assembler. C is more than adequate.

Currently the LFRic build system does not support building C/C++ but I have always assumed that it will be a requirement at some point.

**Comment by hiker** [comment]
Added [PSyData] to indicate that this will be handled as part of the PSyData support.

**Comment by hiker** [comment]
I think I over-thought a lot in this ticket. After looking at the LFRic code: the values of a field are just stored in a 1d-Fortran array. So in order to check that a field is not modified, all I need to compute is the checksum of this field - doesn't matter if there is halo or whatever, nothing should be modified there anyway, whatever these values exactly represent.

I've implemented a first test library to do this, and integrated it in the LFRic gravity-wave miniapp. And it indeed discovers if I modify a kernel to change a value in a read-only field (removing the intent(in) in order to compile this). BTW, my compliments to the build environment, it was pretty easy to integrate another library!! 

I am using a simple checksum ('cast' the double precision to 64-bit int, and add the values up. This works with signed ints, so we are using all 64 bits, but is of course not as good as a proper crc or so). It would actually also be possible to store a copy of the original field, then we could even diagnose which entries are changed :)  ... at a later stage.

There is one caveat though: I am not getting all arrays that are passed into a kernel. E.g., I am using:
```
module initial_buoyancy_kernel_mod
...
        type(arg_type) :: meta_args(2) = (/                               &
            arg_type(GH_FIELD,   GH_INC,  ANY_SPACE_1),                   &
            arg_type(GH_FIELD*3, GH_READ, ANY_SPACE_9)                    &
            /)
        type(func_type) :: meta_funcs(1) = (/                             &
            func_type(ANY_SPACE_9, GH_BASIS)                              &
            /)
```
which is called as:
```
        CALL initial_buoyancy_code(nlayers, buoyancy_proxy%data, chi_proxy(1)%data, chi_proxy(2)%data, chi_proxy(3)%data, &
&ndf_any_space_1_buoyancy, undf_any_space_1_buoyancy, map_any_space_1_buoyancy(:,cell), ndf_any_space_9_chi, undf_any_space_9_chi, &
&map_any_space_9_chi(:,cell), basis_any_space_9_chi_on_any_space_1_buoyancy)
      END DO
```
But my dependency analysis (at this stage) only tells me that the variable ``chi`` is read-only. I don't get any of the other fields/variables, and not even ``chi`` as three variables (chi(1,2,3) as it is provided in the kernel call), but only ``chi``. It works, because I implemented a PSyData function that takes an array of 3 fields (so that is hardcoded). But that can certainly be fixed (since PSyclone creates all the fields, splits the chi into three parameters, we can do the same when creating the PSyData field). I'll dig into this soonish.

So, it still needs a bit of work, but key message is: using PSyData to verify that read-only fields are not modified in a kernel call (or actually any code region) is possible :)

**Comment by rupertford** [comment]
Great stuff @hiker

**Comment by arporter** [comment]
Hi @hiker - I happened across this Issue. Can it be closed now?

**Comment by hiker** [comment]
Indeed. #812 was merged.
