### ISSUE TITLE
Kernel extraction driver: support compilation and building

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1991]
It can be very time consuming to find the right link line for a driver, since it might have a lot of dependencies on other modules (in some examples I had over a dozen additional modules required). Compiling a driver must be as easy as possible.

Potential improvements:

1. We create a kind of makefile (or link information ...). When fixing #1990 we will already have a list of all required dependencies that we could utilise.
2. We copy all the required modules into the driver. We need to check if the existing module inlining code would work for this case.

The additional advantage of the second solution is that it is **MUCH** easier to compile with a different compiler. If we need to link with already compiled other modules, they need to be compiled with the corresponding compiler, making it hard to 'quickly check if compiler XYZ works'.

**Comment by hiker** [comment]
I am currently implementing a `ModuleManager`, with the following functionality:

- You can add several search paths to the manager.
    - The user can select to automatically add all subdirectories recursively. 
- You can query the manager to give you the file name that contains a certain module (just based on the module name):
    - It first checks if there is cached information (i.e. filename) for the module name available. If so, it is returned (without additional IO operation).
    - If there is no cached information, it takes the first entry of the search paths, and gets the list of all files (only) in that directory. Each filename `F` is mapped to a module name (e.g. `a_mod.f90` --> contains module `a_mod` - a user could implement different rules here), and this information is cached. The path is then removed from the list of search paths. This is repeated, till either the module is found, or the search path is empty (in which case the module is not found and an exception is raised).
- It also offers the option to return a list of dependencies (i.e. all modules `use`d), which is done using fparser and walking the tree.

I have used this in gungho, just adding `working/gungho` recursively, to then automatically get all module dependencies, sort them (so that they are in the right order for the compiler), and then inline them into the driver. It could successfully create fully stand-alone drivers, with no more dependencies to infrastructure or any other LFRic files. The overhead should be minimal (compared with the current approach that repeatedly lists all files in the search path).

There is a lot of overlap with the existing search- and kernel-path handling, so there might be a mid-term advantage of merging the existing search/kernel path handling with the ModuleManager.

**Comment by arporter** [comment]
Can this be closed now @hiker?

**Comment by hiker** [comment]
Yep, thanks a lot!
