### ISSUE TITLE
[LFRic] Support r_tran_operator_type

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1998]
`r_solver_operator_type` is recognized by PSyclone, but not an `r_tran_operator_type` so it needs to be added to `LFRicConstants.DATA_TYPE_MAP`. Note that the support for `r_tran_operator_type` needs to first be added to the LFRic infrastructure.

**Comment by TeranIvy** [comment]
The support for `r_tran_operator_type` was added to LFRic in [ticket #3030](https://code.metoffice.gov.uk/trac/lfric/ticket/3030).

**Comment by arporter** [comment]
#2038 is merged so closing this.
