### ISSUE TITLE
[PSyIR] Support for 'static' (C) or 'save' (Fortran) symbols?

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2008]
At the moment, a variable declared with the `save` attribute ends up as an `UnknownFortrantype`. In the `InlineTrans` transformation we need to spot routines with such variables as they cannot be safely inlined. At the moment the 'solution' is simply to forbid Symbols of `UnknownType` but that is potentially going to give a lot of false positives.

The question is, should we extend `DataSymbol` to have some sort of `is_static` attribute?

**Comment by LonelyCat124** [comment]
I think the `is_static` attribute is easiest, but probably some sort of restriction on what is allowed to be set might be needed? E.g. I don't think (though I'm not that familiar with Fortran rules) you can have a `parameter, save` variable, so we'd need to disallow that in PsyIR probably?

I think this also relates to the race condition issue we saw in #1973 - if we had a loop containing a call to a subroutine with a `save` variable, it should also be disallowed in an ideal world, its probably much more unsafe than the condition we saw before.

**Comment by sergisiso** [comment]
>At the moment the 'solution' is simply to forbid Symbols of UnknownType but that is potentially going to give a lot of false positives.

Does it really create many false positives? I would say this is the right thing to do.

Also inlining SAVE is complicated because it must keep the data for non-inlined calls or calls inlined somewhere else. So unless there is a big need for it, I wouldn't support it.

**Comment by arporter** [comment]
Well, it might. I wasn't suggesting that we support inlining routines with `static` variables - just that it would be nice to be more nuanced when we check for them.

**Comment by LonelyCat124** [comment]
How does PSyclone/Fparser handle less common Fortran types, e.g. those from c compatibility? If they were unknown types that would be a potential cause of false positives.

**Comment by sergisiso** [comment]
At the moment there isn't any Gocean kernels with local symbols that are UnknownType.

If the problem is due to external (imported) symbols, these are fine being UnknownType (also SAVE) for inlining. Is this the problem?
