### ISSUE TITLE
[PSyData] Move get_in_out_parameter from DependencyTools to VariablesAccessInfo

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2033]
The three functions `get_input/output/in_out_parameters` do not actually use a DependencyTools instance. They would be better off in the VariablesAccessInfo class (which they actually use).

This would also be the time to split the three classes in `core/access_info` at least into two files (since further work would likely add more lines to `VariablesAccessInfo` (detecting external direct and indirect dependencies)

**Comment by arporter** [comment]
#2036 is on master.
