### ISSUE TITLE
Support for new GungHo function spaces: discontinuous W2 and trace spaces

### ISSUE THREAD

**Issue by thomasgibson** [stfc/PSyclone#204]
Howdy y'all

I'm a PhD student working on LFric and introducing some new solver infrastructure. I have already spoken to @TeranIvy and @thomasmelvin about this and I'm raising this issue to extend PSyclone to support a couple new function spaces. These spaces are implemented and summarized in this LFric ticket: https://code.metoffice.gov.uk/trac/lfric/ticket/1532.

All of this will lead up to a new preconditioner I'm writing up which uses a technique called "hybridization." Basically, this requires the following function spaces:

- A discontinuous variant of the velocity space `W2`, which is named `W2broken`. As the description suggests, this space is locally identical to the existing `W2` space. The exception here is that the degrees of freedom (dofs) are topologically discontinuous. This is, all face degrees of freedom are not continuous. Here is an example of what I mean (schematic of a next-to-lowest order `W2`/`W2broken` element). These are global diagrams. The key distinction is that `W2broken` should be treated like a `W3` space.

![w2-w2b](https://user-images.githubusercontent.com/14180421/43602184-1f501c76-9687-11e8-974e-c3ecae1f0bf5.png)

- The next space is the result of taking the "trace" of a `W2` element. The result is a scalar-valued function space defined only on the faces. The `W2trace` space is discontinuous between vertices/edges in 2D/3D. From a PSyclone perspective, they are continuous over faces as a single dof on a face should be associated with the face connecting two adjacent elements. Here is another diagram of a next-to-lowest order trace space:

![w2trace](https://user-images.githubusercontent.com/14180421/43602435-d48f7dde-9687-11e8-923d-fed7ac18cf74.png)

It sounds like it shouldn't be too difficult to add these to the existing elements lists. A quick glance at `dynamo0p3.py` suggests that `W2broken` should be included in the `DISCONTINUOUS_FUNCTION_SPACES`, and the `W2trace` space should be in `CONTINUOUS_FUNCTION_SPACES`. Perhaps the are subtle issues that we need to address as well.

Let me know if you need any more information!

**Comment by rupertford** [comment]
Hi @thomasgibson, thanks for raising this issue.

You are correct that support for W2broken and W2trace should simply be a case of adding them to the appropriate lists. A new function space was added recently with no problem so it should be fine. The larger effort will be documentation (which you've already helped with by your description), examples and testing.

When would you ideally need these new function spaces supported in PSyclone?

We are happy to add this in for you, particularly as I know you are busy with the implementation, but for the record you are welcome to take it on yourself if you would like to.

**Comment by thomasgibson** [comment]
The ticket that I mentioned is being prepared for code review, so we can try to coordinate based on when LFRic is about to merge these new spaces into `trunk`. I cannot give an exact time, as I do not know how long my ticket will take to be reviewed by the other developers. But I can update this issue with the current progress on the LFRic side.

@TeranIvy volunteered to take this on, but I am more than happy to provide some assistance or guidance on documentation, examples/tests, etc.

**Comment by rupertford** [comment]
Thanks for clarifying @thomasgibson. If @TeranIvy has volunteered then I'll leave it in her capable hands.

**Comment by TeranIvy** [comment]
**Note**: It looks like the ndofs for these new function spaces (on a quadrilateral element and for different orders) will have to be added to the `Dynamo0p3KernelConstTrans` transformation in `transformations.py`. This transformation modifies a kernel so that the number of dofs, number of layers and number of quadrature points are fixed in the kernel rather than being passed in by argument.

**Comment by rupertford** [comment]
pr #532 is now on master so closing this issue.
