### ISSUE TITLE
OMP parallel loop does not correctly identify a `firstprivate` variable

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2041]
@nmnobre has found that PSyclone generates incorrect OMP parallel code in NEMO's `icedyn_rhg_evp` module:

![image](https://user-images.githubusercontent.com/17409212/217834473-c5831861-a33f-46ef-9b60-e59a4bba1aa9.png)

In this case, if `ln_aEVP` is `.false.` then every thread will need the value of `z1_alph2` that is assigned before the loop. i.e. `z1_alph2` needs to be `firstprivate` and not `private`.

**Comment by arporter** [comment]
I've assigned this to @hiker as this relates to dependence analysis. However, he doesn't have to be the one to fix it :-)

**Comment by LonelyCat124** [comment]
I think `_get_private_clause` already has #598 , and I definitely had to workaround that as well when building the tests for #1822, maybe we need to reimplement the data sharing handling for non-arrays fully for `OMPParallelDirective`?

**Comment by arporter** [comment]
This is largely a duplicate of #598 so I'll close this one.
