### ISSUE TITLE
Re-name Transform._validate() and tidy abstract functions.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#208]
In #176 and #200 we have introduced a `RegionTrans` base class. Since the `_validate` method of the base class needs to be called from any sub-classes, it should actually be named `validate` to indicate that it is not private. There is also some tidying to be done in removing lines of executable code from abstract methods (which are therefore not covered by the test suite) - in particular `Transformation.apply()` and `Transformation._validate()`.

**Comment by TeranIvy** [comment]
I was looking through all children of the `RegionTrans` base class and the same code seems to be repeating in their `apply` methods:
```
...
        else:
            arg_type = str(type(nodes))
            raise TransformationError("Error in Extract transformation. "
                                      "Argument must be a single Node in a "
                                      "schedule or a list of Nodes in a "
                                      "schedule but have been passed an "
                                      "object of type: {0}".
                                      format(arg_type))
```
How about moving that into the `validate` method of the base class as well?

**Comment by TeranIvy** [comment]
P.S. Looking further into this it seems to me that 
```
        from psyclone.psyGen import Node
        if isinstance(nodes, list) and isinstance(nodes[0], Node):
            node_list = nodes
        elif isinstance(nodes, Node):
            node_list = [nodes]
```
is common to all children of `RegionTrans` so perhaps defining its own `apply` method would be useful.

**Comment by arporter** [comment]
This looks as though it is complete.
