### ISSUE TITLE
get_private_clauses of OMPParallelDirective incorrectly flagging non-array accesses as firstprivate

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2101]
I have the following test in the task branch which now fails (and before the `firstprivate` changes did not). I've slightly adjusted it as previously it was easy to argue "k wasn't set", but now k is an input parameter and PSyclone doesn't change its behaviour.

```
    code = '''
    subroutine my_subroutine(k)
        integer :: i, ii
        integer :: j, jj
        integer :: k
        do i = 1, 320, 32
            do j = 1, 320, 32
                do ii=i, i+32
                    do jj = j,j+32
                        k = k + ii
                        k = k * jj
                    end do
                end do
            end do
        end do
    end subroutine
    '''
    tree = fortran_reader.psyir_from_source(code)
    ptrans = OMPParallelTrans()
    strans = OMPSingleTrans()
    tdir = DynamicOMPTaskDirective()
    loops = tree.walk(Loop)
    loop = loops[1].children[3].children[0]
    parent = loop.parent
    loop.detach()
    tdir.children[0].addchild(loop)
    parent.addchild(tdir, index=0)
    strans.apply(loops[0])
    ptrans.apply(loops[0].parent.parent)
    correct = '''subroutine my_subroutine(k)
  integer :: k
  integer :: i
  integer :: ii
  integer :: j
  integer :: jj


  !$omp parallel default(shared), private(i,ii,j,jj)
  !$omp single
  do i = 1, 320, 32
    do j = 1, 320, 32
      !$omp task private(ii,jj), firstprivate(i,j), shared(k), \
depend(in: k), depend(out: k)
      do ii = i, i + 32, 1
        do jj = j, j + 32, 1
          k = k + ii
          k = k * jj
        enddo
      enddo
      !$omp end task
    enddo
  enddo
  !$omp end single
  !$omp end parallel

end subroutine my_subroutine\n'''
    assert fortran_writer(tree) == correct
```

For some reason, the access `k = k + ii` is being flagged as a `firstprivate` access - I think because its a non-array access, however since its an assignment to `k`, it should be `shared` - if this was in an `OMPDoDirective` then we'd obviously have a race condition (which is not allowed), however the data concurrency issue is handle by the dependency on the task.

The output from `fortran_writer(tree)` is instead:
```
subroutine my_subroutine(k)
  integer :: k
  integer :: i
  integer :: ii
  integer :: j
  integer :: jj

  !$omp parallel default(shared), private(i,ii,j,jj), firstprivate(k)
  !$omp single
  do i = 1, 320, 32
    do j = 1, 320, 32
      !$omp task private(ii,jj), firstprivate(i,j), shared(k), depend(in: k), depend(out: k)
      do ii = i, i + 32, 1
        do jj = j, j + 32, 1
          k = k + ii
          k = k * jj
        enddo
      enddo
      !$omp end task
    enddo
  enddo
  !$omp end single
  !$omp end parallel

end subroutine my_subroutine
```

I think this affects a lot of my tests, and are instances with PSyclone generating incorrect code.

@sergisiso @nmnobre What were the rules decided for determining if a variable in PSyclone is `firstprivate` as opposed to `shared`? Maybe this needs to be smarter - perhaps variable accesses inside OMPSerialRegions need difference rules?

**Comment by LonelyCat124** [comment]
I feel like to solve this we might end up solving #598

**Comment by nmnobre** [comment]
Hi Aidan,

Thanks for raising this issue.
I've tried playing a bit with the code, and even though intuitively I know what the semantics is meant to be, I can't get the syntax right. Have a look, https://godbolt.org/z/7qd1fEcKx, I'm getting a segfault...

**Comment by sergisiso** [comment]
> Perhaps variable accesses inside OMPSerialRegions need difference rules?

Probably.

First, I didn't consider the possibility of nested OpenMP data sharing regions, I didn't know it was possible :) 

But then reductions are typically are caught by the OpenMP loop transformations that we have and generate a TransformationError. So in other codes we don't have this scenario yet and reductions are a bit on an untested territory.

In this case, I think if we see the access to "k" protected by a reduction pragma, an atomic or the task in-out dependency, we could not mark it as private (and it would be shared by default). But we don't do any of this yet. I think we will need to extend the analysis to check that for any write-after-read (reduction) it has associated some of the mentioned locking OpenMP syntax with it.

**Comment by LonelyCat124** [comment]
Hi Nuno,
Issue with your examples is providing a constant value as a parameter to a data clause in OpenMP, easier fix (works with intel 23) is just:
```
program main
    integer :: k
    k = 2
    call my_subroutine(k)
    write (*,*) k
end program main
```
Since k is a dummy variable i think it causes the seg fault.

@sergisiso The issue with this a bit is that the dependencies are somewhat depending on whether we think the variable is shared or private, which was relying on the OMPParallelRegion's computation.

**Comment by nmnobre** [comment]
> In this case, I think if we see the access to "k" protected by a reduction pragma, an atomic or the task in-out dependency, we could not mark it as private (and it would be shared by default).

I was about to say this, this might be the way forward.

**Comment by sergisiso** [comment]
>  What were the rules decided for determining if a variable in PSyclone is firstprivate as opposed to shared?

At the moment the rational is (and was) that if it has overlapping writes it must be private (e.g. a scalar inside a loop) otherwise shared.

In the last PR we added that things that were marked private but have a read first (excluding  conditional writes before the first  read reference), are now marked as firstprivate.

**Comment by sergisiso** [comment]
There are some loops in Nemo that would benefit from a reduction clause, and some kernels in LFRic that would benefit from atomics (instead of coloring) maybe we have to think how we support all this cases.

If we follow the current strategy of allowing of inferring the directive clauses at the end (lowering/generation) we could do something like:
`private, fprivate, access_to_protect = get_sharing_clauses()`
and be the lowering of each class (OpenMPParallel, OpenMPTask, ..)to decide which syntax to use in each case.

Would that work?

**Comment by LonelyCat124** [comment]
I'm not sure I follow, how do you mean - as in sub classes might have to decide the parent's data sharing rules?

**Comment by nmnobre** [comment]
> Then each subclass lowering decides how to handle this 3rd set of symbols.

But wouldn't they need to be aware of each other? In this case, it's safe to mark `k` as shared in the `parallel` directive because we know the dependencies are taken care of in the `task` directive. So, sure, `k` would be in this new set for both directives, but there still needs to be a semantics-aware decision of what clause to use for each directive, no?
On the other hand, wouldn't this be solved if we simply stopped adding data sharing attribute clauses to `parallel` directives? Why do we do it?

**Comment by LonelyCat124** [comment]
I think private vs shared makes sense at a `parallel` directive level, and its sort of required (or well, ugly if not specified) for some OpenMP directives which don't support `shared` (e.g. `single`, which only allows `private` or `firstprivate` of the supported data sharing attributes in PSyclone). I also don't love the idea of every variable just being `shared` until declared again in another directive, though it does solve the issue/pass the problem to a later directive here.

Also if we want to enable reduction variables we might need to mark them as such at the parallel directive depending on where the accesses are (e.g. if they're in a task in the future when i support that, then they need to be declared as reduction in the parent parallel if i remember correctly)

I think distinguishing whether a variable is `firstprivate` or `shared` is inherently a difficult problem - the best we can guess is if we read first from a non-array variable and we later write to it inside a parallel region of code (e.g. worksharing loop) then its firstprivate, else its shared if we write to it?
The except here is I guess loop variables which are always private?

**Comment by LonelyCat124** [comment]
Or was there another use-case we needed a variable to be `firstprivate` as opposed to `shared` outside of task regions?

**Comment by arporter** [comment]
I'm a bit lost here so my only useful contribution is: do we need a design discussion?

**Comment by LonelyCat124** [comment]
I think it might be useful to have a discussion to decide what our combined use cases are and work out how things can fit together - especially if reductions are something we want to support soon?

**Comment by sergisiso** [comment]
> Or was there another use-case we needed a variable to be firstprivate as opposed to shared outside of task regions?

The change was motivated by this issue we had in NEMO https://github.com/stfc/PSyclone/issues/598#issuecomment-1424375469

> Specially if reductions are something we want to support soon?

I hope we do, the reductions in the maxval, minval and a couple other loops are the most significant part being left out of the GPU for the OpenMP offloading version.

**Comment by LonelyCat124** [comment]
Yeah that makes sense, I think the code is equally as correct if `z1_alph2` is shared at parallel level, and then just marked as `firstprivate` when appropriate, but that becomes certainly more complex.
I think some of the complexity comes from identifying the difference between scalars use for reductions scalars used for firstprivate vs those used by tasks (or inside serial regions). I expect those for reductions or used in tasks may have similar ideas behind them, but I'm not sure how they differentiate from those we're defining as firstprivate right now - i guess the only idea we have is firstprivate is used if an optional write occurs to something that is otherwise read from first, assuming that happens inside a non-dependency handled region of code? Otherwise its either a reduction or just shared depending on whether that takes place in a parallel region or a task/single region?

I think other counter examples (i.e. array access race conditions which could be handled by reductions) we simply don't care about as we don't expect to see them? e.g.
```
do i = x, y
  array(1) = array(1) + array2(i)
end do
```

**Comment by LonelyCat124** [comment]
Should we have a discussion about this next Tuesday or Weds?

**Comment by sergisiso** [comment]
Unfortunately I am away to IWOCL next week

**Comment by LonelyCat124** [comment]
Ok - I guess we can do over Zoom the week after then?

**Comment by LonelyCat124** [comment]
To further expand on this, this is wrong for the PSycloneBench's tracer advection if I use the OpenMP script. I get this:
```
# Start of variable declaration
real*8 :: zice
# Rest of variable declaration
    !$omp parallel default(shared), private(ji,jj,jk), firstprivate(zice)
    !$omp do schedule(auto)
    do jk = 1, jpk, 1
      do jj = 1, jpj, 1
        do ji = 1, jpi, 1
          if (tsn(ji,jj,jk) <= ztfreez(ji,jj) + 0.1d0) then
            zice = 1.d0
          else
            zice = 0.d0
          end if
          zind(ji,jj,jk) = MAX(rnfmsk(ji,jj) * rnfmsk_z(jk), upsmsk(ji,jj), zice) * tmask(ji,jj,jk)
          zind(ji,jj,jk) = 1 - zind(ji,jj,jk)
        enddo
      enddo
    enddo
    !$omp end do
    !$omp end parallel
```

Even the compiler warns here:
```
tra_adv_compute.f90:62:0:

   62 |     !$omp parallel default(shared), private(ji,jj,jk), firstprivate(zice)
      |
Warning: 'zice' is used uninitialized in this function [-Wuninitialized]
```

**Comment by sergisiso** [comment]
After discussing it with @LonelyCat124 and @arporter we agreed that currently there are 2 different issues:
- The first one is when we conservatively add firstprivate to something that is only private. This is not a big issue because the code is still correct (although it could be refined to avoid the compiler warning / extra copy).
- The second issue is when a reduction scalar is identified as firstprivate (or private). This is bad because we currently change the semantics of the loop. Luckily, the DependencyTools is able to identify these reduction scalars.

We agreed that the _get_private_clauses method (to be renamed) should identify the reduction symbols as a third category independent of private and firstprivate (and the default plain shared). And the lowering that calls it will have to deal with them appropriately:

- the loop-constructs could simple produce and error (which won't happen in actual code because the Do loop transformations already filter these cases). But this can be the precursor to implement the reduction clause in #1812

- The task-constructs already deal with it in its lowering (and could maybe incorporate and extra check to validate that these symbols are dealt appropriate)
