### ISSUE TITLE
Execute maxval intrinsic in NEMO stpctl.f90 on the GPU 

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2105]
#2085 added support for minval, maxval and sum IntrinsicCalls but this does not yet execute the new intrinsics on the GPU and is still one of the manual tweak necessary to improve the performance.

To run them on the GPU for the OpenACC kernels we need to:
- Introduce a minval2code, maxval2code and sum2code transformations
or
- Refactor the `if not have_loop:` in the try_kernel_trans method of examples/nemo/scripts/kernels_trans.py 

To run them on the GPU for explicit OpenACC or OpenMP we need to:
-  Add OpenMP reduction clause in addition to the maxval2code transformation

**Comment by rupertford** [comment]
A sum2code transformation already exists (`psyclone/psyir/transformations/intrinsics/sum2code_trans.py`) and given the similarity between sum, minval and maxval, it should hopefully not be too difficult to extend this. I would be happy to do that. However, in the meantime I would have thought that it would be relatively simple to extend the OpenACC script to accept certain intrinsics within a kernels region.

**Comment by sergisiso** [comment]
Could be, this is my bullet point 2 option. But currently the examples/nemo/scripts/kernels_trans.py fails in multiple files (at least for me with nvfortran 23.1- I believe because there is if conditions that need to be excluded) and needs to be brought up to date first.

**Comment by rupertford** [comment]
I'll implement the maxval2code and minval2code transformations as one of these is needed for one case and both could potentially be useful in the other.

**Comment by rupertford** [comment]
Created [2105_minmaxval2code](https://github.com/stfc/PSyclone/tree/2105_minmaxval2code)

**Comment by rupertford** [comment]
Pausing this while I add support for the huge() and tiny() intrinsics from issue #1161 as after discussion with @sergisiso it was decided that using these to initialise the min and max reduction variables respectively was the best solution.
