### ISSUE TITLE
Update the 'NEMO' tutorial

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2116]
For tutorials/practicals/nemo you need to set three environment variables in order to run a binary, e.g.:
```
IT=10 JPI=20 JPJ=20 JPK=30 ./tra_adv.exe
```
While this is in (same?) of the Makefiles, it appears not to be mentioned in the READMEs.

The README in 2 even states:
```
 application can be run (ensure you have
   the necessary environment variables set first - see
   ../1_nemo_psyir/README.md):

       $ ./tra_adv.exe
```

**Comment by arporter** [comment]
1_nemo_psyir/README.md does have it:
![image](https://user-images.githubusercontent.com/17409212/233363072-77b0a9d3-10bb-4aed-bd07-2007f8020d67.png)
but maybe we need to make it more obvious?

**Comment by hiker** [comment]
Ah - I looked for explicit setting of the variables. I grep'ed for JPI, and that only gave me:
```
Literal[value:'JPI', Scalar<CHARACTER, UNDEFINED>]
```
Ah, and yes, it is even in part 2, it's just not a command listed, but in the paragraph.

I would have to admit that this is easy to miss. I am probably a typical culprit to skip things when doing a tutorial ... get me to the meaty bits :)

The following works in making it more obvious, but is ugly:
```
. ../domain_setup.sh  && ./tra_adv.exe
```
Or
```
IT=10 JPI=20 JPJ=20 JPK=30 ./tra_adv.exe
```
as you wrote in the training ... that will certainly not be missed :) 

Don't know what's best. Seeing the variables make it easy to spot - and maybe change the error message to state: "You have to set the variables ..." instead of just "Width of grid, JPI, must be > 0" ??

**Comment by arporter** [comment]
We can do both. It's funny isn't it - you write an error message and you think it's obvious at the time!

**Comment by arporter** [comment]
I need to update the tutorial material ahead of the NG-Arch training at the end of June. Therefore, I will fix this as part of that (and in fact, have re-purposed this Issue for it).
