### ISSUE TITLE
Introduce fparser as a git submodule

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#212]
The current rapid evolution of fparser is causing problems for our CI. This is because we currently only use pip to install the latest *release* of fparser whereas we may need features that are on master but not yet in a release. We will therefore introduce fparser as a submodule of this project as this will then allow us to always have it pointing to a compatible version of fparser. 

However, when making a release of PSyclone we will require that it works with a particular fparser release. Therefore, part of the release process will be to edit the Travis YAML file and ensure that tests are run using the pip-installed version of fparser.

**Comment by arporter** [comment]
Since we already have `bin/install_optional.sh` I've extended it to take a single argument, "fparser". If present, the script then installs the version of fparser pointed to by the git submodule. In order to avoid py.test picking up the fparser tests, I've added an argument to the invocation of `coverage` in `.travis.yml` to specify the location of the PSyclone tests.

**Comment by arporter** [comment]
I've updated the "make a release" wiki page with instructions to ensure the "fparser" argument to `install_optional.sh` is removed from the YAML file.

**Comment by rupertford** [comment]
PR #213 is merged to master. Closing this issue.
