### ISSUE TITLE
Self-hosted runner to perform integration tests

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2132]
A self-hosted runner is useful to do integration tests with our local hardware (HPC-grade CPUs, GPUs) and installed compiler toolchains, that would take a lot of compute resources on the free GH cloud runners.

#967 adds two GH workflows that:
1. on reviewer's demand, push the branch to a private repo
2. a self-hosted runner executes integration tests workflow on the private repo commits.

The current solution has some limitations:
- It only executes pytest compilation tests, but we could also do PSycloneBench, NEMO, LFRic, ...
- The private repo is on @arporter account and username, it could be more generic.
- The self-hosted environment is currently custom made (not captured/replicable). It would be good to have a container file / spack script in this repository that set up the self hosted environment, so other people/orgs could run it locally if they wanted to. It would also document how to create it for the next time we need to do it.
- The private repo. currently runs all of the same actions that the public repo. does - this wastes GHA compute resources.

**Comment by arporter** [comment]
#2106 and #2107 have added integration tests for NEMO. However, we have not yet migrated everything over to the relevant user on the self-hosted runner. @sergisiso commented:

I have not moved the models and software(perl and intel netcdf). The former are quite big and I am unsure if we want to replicate them, the latter should maybe be ported to the module system, or find a reproducible (container?) way to be able to move the runner to other servers.

**Comment by arporter** [comment]
Of the original points in this Issue, only:

"The self-hosted environment is currently custom made (not captured/replicable). It would be good to have a container file / spack script in this repository that set up the self hosted environment, so other people/orgs could run it locally if they wanted to. It would also document how to create it for the next time we need to do it."

remains. Sergi has made quite a lot of progress towards using Spack to do this and work will continue in the background so I'm closing this issue.
