### ISSUE TITLE
Do PSyclone literals not sanity check string inputs during construction?

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2149]
I'm working on closer integration between my Particle DSL's IR and psyir, ideally removing nodes that are simply duplications.

When running my tests for `Literal` using PSyclone's Literal, I found that some of my integer based tests just passed regardless of input, which wasn't what I expected.

My tests was simply:
```
def test_literal_init_bad_int():
    with pytest.raises(ValueError) as excinfo:
        Literal("abc", INT_TYPE)
    assert("Constructing integer Literal but got a value of 'abc' instead "
           "of an integer value." in str(excinfo.value))
    with pytest.raises(ValueError) as excinfo:
        Literal("012", INT_TYPE)
    assert("Constructing integer Literal but got a value of '012' instead "
           "of an integer value." in str(excinfo.value))
```
However this test fails as it doesn't appear to be checked in PSyclone.

Looking at my own implementation, I had these additional lines:
```
_int_value = r'([+-]?[1-9][0-9]*|0)'

def __init__(...):
    ...
    if (datatype.intrinsic == ScalarType.Intrinsic.INTEGER and
        not re.fullmatch(Literal._int_value, value)):
   raise ValueError("Constructing integer Literal but got a value of "
        f"'{value}' instead of an integer value.")
    ...
```

I was expecting PSyclone to also perform this check, as it does do this check for `REAL` and `BOOLEAN` inputs - is there a reason it doesn't for `INT_TYPE` values?

**Comment by rupertford** [comment]
I agree that it should and don't know why it doesn't.
