### ISSUE TITLE
New precision fields

### ISSUE THREAD

**Issue by iboutle** [stfc/PSyclone#2159]
For single precision physics work we require 2 new field precision types (similar to `r_solver` and `r_tran`) to be recognised by Psyclone. Suggested names are:

- `r_bl`
- `r_phys`

Behaviour is exactly the same as `r_solver` or `r_tran`, i.e. fields will be variable precision (32 or 64 bit), configured at compile time by LFRic in the same way as `r_solver` or `r_tran`.

A link to an LFRic ticket & branch which uses such fields is here:
https://code.metoffice.gov.uk/trac/lfric/ticket/3732
https://code.metoffice.gov.uk/trac/lfric/log/LFRic/branches/dev/ianboutle/r42957_sp_bl/infrastructure

The new maps are as follows:

`
"r_bl_field": {"module": "r_bl_field_mod",
                             "type": "r_bl_field_type",
                             "proxy_type": "r_bl_field_proxy_type",
                             "intrinsic": "real",
                             "kind": "r_bl"},
`
`
"r_phys_field": {"module": "r_phys_field_mod",
                             "type": "r_phys_field_type",
                             "proxy_type": "r_phys_field_proxy_type",
                             "intrinsic": "real",
                             "kind": "r_phys"},
`
The default precision for both will be `8`, but as with `r_tran` and `r_solver`, this will be configured at compile time (between `8` and `4`) according to the CPP ifdefs

**Comment by hiker** [comment]
Can I point out #2018 - `r_quad` is defined in psyclone, but not exported from LFRic. I don't know what to do with that, but considering that it is somehow related, I thought I'd point it out ... maybe it could be done at the same time (likely in LFRic and then in our infrastructure - but that's exactly what I don't know :)  )
