### ISSUE TITLE
[SymPy] Allow user defined types to be converted back into Fortran

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2166]
ATM an access like `a(i)%b(j)` is converted to `mod(a(i), a_b(j))`, which cannot easily be converted back into Fortran.

Investigate if `a(i)%b(j)` can be converted to `a_b(i,j)` for sympy, and then back into the original representation. Problem is that `a%b(i,j)` would have the same sympy representation (`a_b(i,j)`). We need to be able to distinguish these two cases. With #1537 we can store information in the SymPyWriter object, since already the same writer must be used to convert into both directions (in order to store the proper lower/upper bound name).

Ideas:
- Can we maybe use tuples to group the indices? `a_b((i), (j))` and `a_b((i,j))`?
- Or maybe at least use a custom function (not `mod`) which would convert back to the user-defined types

**Comment by hiker** [comment]
The fact that `a(i)%b(j)` and `a%b((i,j))` would have the same representation (`a_b(i,j))` does not really matter, as long as the SymPyWriter instance keeps track of the newly defined symbols, and how they (and their indices) must be converted back.

**Comment by rupertford** [comment]
Would sympy say they were the same if they end up with the same representation?

**Comment by hiker** [comment]
No - if both expressions should turn up in a set of expressions, SymPyWriter will detect a clash and rename one of them to, so you end up with (say) `a_b(i,j)` and `a_b_1(i,j)` (using a PSyclone dummy symbol table to give us unique symbol names) That's why the SymPyWriter needs to keep state information - in case of name clash it needs to restore the original name, and at the same time it can store information about the indices, to correctly convert `a_b(i,j)` back to `a(i)%b(j)` and `a_b_1(i,j)` to `a%b(i,j)` - ignoring the fact that my example is semantically incorrect of course :)
