### ISSUE TITLE
Get partial type information from UnknownFortranType

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#2171]
Declarations such as those specified below become an `UnknownFortranType` in the PSyIR. In the first example this is purely because the declaration has an assignment. In the second example it is because of the assignment and the fact it is a pointer.

```
integer(kind=i_def)::extent=1
TYPE(field_type), POINTER :: ccw => null()
```

I need to be able to determine the data types of declarations like these in LFRic and don't think it makes sense to have to separately parse the string representation contained in an `UnkownFortranType`.

We could obviously aim to support the above directly in the PSyIR and there have already been discussions about capturing declarations with initialisation in the following way ...

```
integer(kind=i_def)::extent
extent=1
```
However, if we do this we need to ensure the assignment is only performed once in the case where variables keep their values when the declaration goes out of scope (i.e. saved variables).

The above solution does not allow support for pointer declarations. We could aim to support these too, or we could allow optional, partial, type information to be added to `UnknownFortranType`.

Or something else.

**Comment by rupertford** [comment]
After a discussion with @sergisiso it was agreed to look at capturing more type information in `UnknownFortranType` as it helps both of the above cases and another to do with arrays that Sergi mentioned.

**Comment by rupertford** [comment]
Created branch [2171_extend_unknownfortrantype](https://github.com/stfc/PSyclone/tree/2171_extend_unknownfortrantype)

**Comment by rupertford** [comment]
It is relatively simple to capture information when we have unsupported assignments and/or attributes as we can still create a valid PSyIR datatype e.g. a ScalarType or an ArrayType. However, if the intrinsic type is not known, e.g. complex, then it is not so simple to extract the precision and potentially array shape. Even if we were to do this, it is not clear how to store or provide this information as we will have part of the ScalarType or ArrayType being invalid. We could monkeypatch but that is not very nice, or keep the datatype, precision and shape separate from each other, but I can't see how that would extend to structures.

**Comment by arporter** [comment]
Can we have an `UnknownIntrinsicType` so that we can still have a valid `ScalarType`?

**Comment by rupertford** [comment]
PR #2174 is on master. Closing this issue.
