### ISSUE TITLE
LFRic eg14 won't build with nvfortran

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2179]
Despite previous work on this (e.g. #1678), I can't currently build LFRic eg14 with nvfortran. (I can with gfortran, albeit ignoring the ACC directives.) The problem seems to be duplicate symbols at the link stage:

    nvlink error   : Multiple definition of '_fs_continuity_mod_21' in '../../../src/psyclone/tests/test_files/dynamo0p3/infrastructure/liblfric.a:fs_continuity_mod.o', first defined in 'main_psy.o'
    nvlink fatal   : merge_elf failed
    pgacclnk: child process exit status 2: /apps/packages/compilers/nvidia-hpcsdk/Linux_x86_64/23.5/compilers/bin/tools/nvdd

(The initial error said there were multiple definitions of `_argument_mod_21` so I deleted the pre-processed file `argument_mod.f90` before rebuilding and it gave me this error.) Perhaps the build system is building both the .f90 and .F90 files?

**Comment by arporter** [comment]
Assigning @hiker as he was previously (i.e. in #1678) talking about compiling with nvfortran as part of the BOM test suite. Did you ever do this?

**Comment by arporter** [comment]
In the Makefile we have:

    ALL_SRC := $(subst $(LFRIC_PATH),,\
                        $(shell find $(LFRIC_PATH) -name '*.[Ff]90' -print))
    ALL_OBJ = $(subst .F90,.o,$(subst .f90,.o,$(ALL_SRC)))

So I think we'll get each .o file listed twice.

**Comment by hiker** [comment]
Oops, only noticed your answer. Using `...-name '*.f90' -print)` should work (removing the F90 files, since they are all available as pre-processed files.

**Comment by arporter** [comment]
> Oops, only noticed your answer. Using `...-name '*.f90' -print)` should work (removing the F90 files, since they are all available as pre-processed files.

Oh yes, so it does. I've gone for that instead.

**Comment by arporter** [comment]
Discovered that the example doesn't work correctly without managed memory because my previous modification to field_mod to bring back data from the GPU has been lost (I think in the move to mixed precision). I shall re-instate it.

**Comment by sergisiso** [comment]
libOpencl.so comes with CUDA, you can do:
```
module load nvidia-hpcsdk
find $NVHPC_ROOT -name libOpenCL*
```
to find one that matches the CUDA libraries that you are loading (I still compile it with gfortran though)
