### ISSUE TITLE
halo exchange removal for vectors is broken

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#219]
When redundant computation is applied to a loop it can result in halo exchanges no longer being required.  To support this, halo exchanges implement their own `required` method which checks if they are needed or not. However, when redundant computation results in a set of halo exchanges associated with a vector field then only the first of these is removed. A similar issue occurs wih asynchronous halo exchanges. See tests `test_vector_halo_exchange_remove()` and `test_vector_async_halo_exchange()` in `dynamo0p3_transformations_test.py`, currently on the branch associated with issue #214.

**Comment by rupertford** [comment]
created branch halo_exchange_vectors

**Comment by arporter** [comment]
#225 has been merged to master. Closing issue.
