### ISSUE TITLE
LFRic alg layer error when using PSyIR: visibility symbol

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#2213]
`lfric_xios_tie_axis_mod.x90` causes PSyclone to fail when using the new PSyIR algorithm parsing approach. A cut down version of the problem is below. The problem appears to be with the use of `public :: update_interface` with the backend saying that it is not declared anywhere.

```
module test
  abstract interface
     subroutine update_interface()
     end subroutine update_interface
  end interface
  public :: update_interface
contains
  subroutine alg()
    use constants_mod,     only: r_def
    use field_mod,         only: field_type
    type(field_type)       :: a
    real(r_def)            :: x
    call invoke(inc_a_times_x(x,a))
  end subroutine alg
end module test
```

**Comment by rupertford** [comment]
The `update_interface` symbol is unknown to the PSyIR as its specification is within an unnamed interface whose content is kept within a RoutineSymbol of UnknownFortranType. It should therefore cause an exception in the front-end at the moment. However, it gets through the front end as in LFRic we artificially add a wildcard use statement to ensure that PSyIR does not complain about builtins. However, this is subsequently removed after processing leaving the `update_interface` symbol with no possibility of being declared (according to the PSyIR). The backend therefore raises an exception.

**Comment by rupertford** [comment]
One solution to this problem would be to better deal with interface code so that the symbol was declared.

Another is to allow a symbol to exist if there is an unnamed interface. However, the symbol would need to be identified as being one that is associated with a PUBLIC or PRIVATE clause so that the backend could reproduce the required PUBLIC or PRIVATE statement. This is different to how things work now, as PUBLIC or PRIVATE clauses are associated with the symbol in the PSyIR.

So if we were to do that latter approach we would need to create a new symbol type with a name like VisibilitySymbol, and such symbols would only exist if they were not declared and there were a wildcard import of some sort. The backend could then add PRIVATE/PUBLIC for all such symbols.

I may be wrong but we probably need such a thing in general as we may come across code that declares an imported variable or function as being public or private but we never get to see it as it is in another file that we do not have access to.

**Comment by rupertford** [comment]
So my current thinkng is to add a new symbol type called `VisibilitySymbol` and to create these in the front end if there is an import or interface with unknown content. @sergisiso and @arporter, what do you think?

**Comment by sergisiso** [comment]
I don't understand what the VisibilitySymbol sovles, the generic Symbol (which I expect it is what is created) already has a visibility parameter. The backend may not reproduce it back because public is the default visibility? but the symbol exists.

The problem to solve is that currently we check that there is at least one wildcard import before producing symbols with unknown origin, while in this case it comes from a declaration inside an UnknownType. We need to account for that in the check.

**Comment by rupertford** [comment]
After discussion it has been agreed to create a new interface called VisibilityInterface. This would be used for symbols where the only information we know about them is their visibility. Once done we need to check that these get specialised correctly if we subsequently determine the type of the symbol (e.g. after inlining).

**Comment by rupertford** [comment]
The support for `public/private [:: a]` in the front-end is a bit patchy. It only seems to work if the input code is a module. Even in this case, everything ends up in module scope even if things are specified in a subroutine. Further, any symbols are ignored in the back-end and `public :: a` becomes `public`. The backend also raises an exception if public/private is specified in both a subroutine and its surrounding module (which I think is valid). If there is no module the public/private clauses and/or symbols do not get created at all, so just disappear in the output.

**Comment by rupertford** [comment]
Ah, it looks like it is being clever (and I'm not). As the default is public, then `public :: a` is not required so it just outputs public, whereas if I specify private :: a I get `public\nprivate :: a` which is what I would expect.
