### ISSUE TITLE
sympy comparison fails if variable is called lambda

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#2215]
A comparison using a reference to a variable called lambda causes sympy.equal to fail.

**Comment by hiker** [comment]
Yes, lambda is a reserved symbol. Guess I need to add support to rename symbols (esp. renaming them back when converting back from SymPy to PSyIR :(  )

**Comment by rupertford** [comment]
Hi @hiker, I would be happy to fix this. Can you point me to the right part of the code?

**Comment by hiker** [comment]
@rupertford , see PR #2241 - though that first needs pr #2184 to be merged, I would otherwise expect some conflicts.
