### ISSUE TITLE
Performance degradation in NEMO OpenMP GPU

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2234]
There has been a performance degradation (form 11s to 19s) in the NEMO OpenMP GPU performance, if I look at the CI recorded timings it was first seen in the .eqv. vs .eq. fix (#2209)

2206_fix 9a3a55f2b64bcc056bae97b4171bc717f7a37e07 11.481 11.481
1419_loop_var_unknowntype 4f56807878f7b13be8dddbddfb222e7b0c54bb1c 11.420 11.420
2183_psyad_alg_names 39c0d8469a301d71bedfc437f33dca90a3d4d166 11.419 11.419
2204_fix 592ce49646ba0abb7200f2e9b7fb88a5c3ab7d8a 19.282 19.282
2171_extend_unknownfortrantype 6634a81ca8615be3d05c223698358b4df021bec7 19.242 19.242

Now if I profile this and the the one merge before in master I see that some GPU gaps are introduced: e.g. in tra_ldf
Before:
![image](https://github.com/stfc/PSyclone/assets/1449555/b5c1a058-1da2-4b2e-a99a-719aee859df3)
After:
![image](https://github.com/stfc/PSyclone/assets/1449555/e79898bf-ecfb-4411-85ff-0edfc744cbc7)

Now the strange thing is that if I diff the output step.f90, and ldftra.f90 (which has ldf_tra and ldf_eiv) there is no changes, but somehow the second version does not even produce the nvptx profile records !?

The are changes in other output files (CASE statements with booleans), but I don't see how this have influence here

**Comment by sergisiso** [comment]
There is only 6 files with differing outputs and examining them the most relevant difference is that expressions like:
```
 SELECT CASE (nldf_dyn)
      CASE (np_lap_i)
```
Are now not cannonicalized to if-statements and therefore the body is not parallelised. This is because nldf_dyn and np_lap_i are defined in other modules and we don't have the datatype.

Copying the files over shows that restituting these fixes the performance problem.

Unfortunately I can not simply add the resolve_import at the nemo utils.py as I do in other similar cases because this is a frontend decision and by the time I resolve_imports it is already too late.

**Comment by sergisiso** [comment]
I want to solve this because it is a substantial performance decrease. Also Select/Case string comparisons create lots of problems in the OpenACC and maybe we can also solve them (I need a simple reproducer of this!).

One alternative would be to try to resolve datatypes, but this is hard, we need to follow dependencies which needs to call more fparser which is slow, and even with this there may be unknown types or codeblocks in the expressions.

Another alternative that I am starting to exploring is doing the select-case cannonicalisation with a custom comparison generic interface. It is not that bad because the standard says "case-expr shall be of type character, integer, or logical." So maybe somthing like this could work?:
```
Interface __psyclone_cmp
	logical function _psyclone_cmp_int( op1, op2 )
	    integer, intent(in) :: op1, op2
	    return op1.eq.op2
	end function
	logical function _psyclone_cmp_logical( op1, op2 )
	    logical, intent(in) :: op1, op2
	    return op1.eqv.op2
	end function
	logical function _psyclone_cmp_char( op1, op2 )
	    character, intent(in) :: op1, op2 ! with dimension(*) ?
	    return op1.eq.op2 !or something that doesn't break OpenACC?
	end function
End Interface
```
```
if (__psyclone_cmp(select_expression, case_expression)) then
 ! case body
else ..
```

**Comment by nmnobre** [comment]
> Prints "This if right!" when compiling with gfortran or nvfortran But it prints "This is wrong!" when compiling nvfortran -acc

nvfortran 23.7 refuses to compile the snippet, so the problem will be caught at compile time. :-)

**Comment by nmnobre** [comment]
#2238 also *partially* fixes the OpenACC performance degradation.
The other part of the OpenACC performance hit seems to stem from #2085.

**Comment by sergisiso** [comment]
For OpenACC kernels it may be the same as https://github.com/stfc/PSyclone/issues/1837, once we have a list of valid intrinsics we can make the `valid_acc_kernel` exclude Call but not IntrinsicCalls, but if we do it now we would allow non-valid intrinsics.

For better performance we can inline/unroll the intrinsic and this is monitored on https://github.com/stfc/PSyclone/issues/2105

**Comment by nmnobre** [comment]
> For OpenACC kernels it may be the same as #1837, once we have a list of valid intrinsics we can make the `valid_acc_kernel` exclude Call but not IntrinsicCalls, but if we do it now we would allow non-valid intrinsics.

Let me see if I understand, what you suspect is happening is that, now, more code is being left out of the GPU because we recognise more intrinsic calls as such?

**Comment by sergisiso** [comment]
> Let me see if I understand, what you suspect is happening is that, now, more code is being left out of the GPU because we recognise more intrinsic calls as such?

Not the new intrinsics, which move from being CodeBlock to IntrinsicCall<-Call , and both are excluded from GPU.

What I suspect is that we moved some operators (e.g. sum on the PR you pointer) from being an Unary/Binary/NaryOpeator to just being an IntriniscCall, and probably the former was allowed to be on the GPU while the later is excluded.

**Comment by nmnobre** [comment]
> Not the new intrinsics, which move from being CodeBlock to IntrinsicCall<-Call , and both are excluded from GPU.

By new intrinsics, I'm guessing you mean something that was previously completely left out in a Codeblock, which was already not the case for the Fortran intrinsics SUM, MINVAL or MAXVAL.

> What I suspect is that we moved some operators (e.g. sum on the PR you pointer) from being an Unary/Binary/NaryOpeator to just being an IntriniscCall, and probably the former was allowed to be on the GPU while the later is excluded.

I think that's what I meant, we now interpret the Fortran intrinsics SUM, MINVAL and MAXVAL as some different entity that won't be placed on the GPU. That is, they were already recognised by PSyclone before (as NaryOperator), but now are something different (IntrinsicCall)?

**Comment by sergisiso** [comment]
> I think that's what I meant, we now interpret the Fortran intrinsics SUM, MINVAL and MAXVAL as some different entity that won't be placed on the GPU. That is, they were already recognised by PSyclone before (as NaryOperator), but now are something different (IntrinsicCall)?

yes exactly
