### ISSUE TITLE
Readthedocs failed to build the reference guide on master

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2242]
The last PR does not contain anything that the reference guide uses and it works well in my local environment. 
So I assume it is an issue introduced with latest package dependencies.

It say "An error happened in rendering the page autogenerated/psyclone" https://readthedocs.org/api/v2/build/21482296.txt

So probably something autogenerated by AutoAPI or Doxygen

**Comment by sergisiso** [comment]
The issue is an incompatibility with the sphinx_rtd_theme and Sphinx 7, it works by pinning down sphinx to 6.2.1

@arporter I am not sure where the ReadTheDocs instructions are in order to pin one of the dependencies, but in any case the issue is already solved in sphinx_rtd_theme master so we could wait for their next release for this to be solved (which they already have a release candidate for).

**Comment by arporter** [comment]
I think it's the various `pip_requirements.txt` files although for the User Guide we've moved to using a `.readthedocs.yaml` file. We could wait until we're ready to make a release and if it's still an issue then we fix it.

**Comment by arporter** [comment]
I'll take this and move the dev and ref guides over to using yaml files too.

**Comment by arporter** [comment]
Strangely, it turns out they do both already have yaml files. Perhaps I can remove the `pip_requirements.txt` files?

**Comment by arporter** [comment]
Actually, the standard thing to do is to point to the `pip_requirements.txt` file from the yaml file. Seems a bit weird but hey. I've updated all three docs to do this now and builds are in progress.

**Comment by arporter** [comment]
Note that there is 'nearly' a release of sphinx_rtd_theme out that fixes this - a second release candidate was created 3 weeks ago (https://github.com/readthedocs/sphinx_rtd_theme/tags).
