### ISSUE TITLE
`Fparser.py` fails to process select case statements if the SELECT element is a structure element(?).

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2246]
Not sure if this is a bug I introduced with changes, or something that already existed, but in socrates there are files with a statement like
`SELECT CASE(orbit%i_elements)`

PSyclone crashes at `fparser.py`:3375:
```
                    if (child.symbol.datatype.intrinsic ==
                            ScalarType.Intrinsic.BOOLEAN):`
```

with the error `AttributeError: 'DataTypeSymbol' object has no attribute 'intrinsic`

Standalone test case:
```
def test_type_case(fortran_reader):
    code = '''module container
        type test_type
            integer :: case_element
        end type test_type
    contains
        subroutine test_subroutine()
            type(test_type) :: my_test

            select case (my_test%case_element)
            case(0)
                print *, "hello"
            case(1)
                print *, "Not hello"
            end select
        end subroutine
    end module container
    '''

    psyir = fortran_reader.psyir_from_source(code)
```

**Comment by sergisiso** [comment]
Can you check if it is still a problem with branch "2234_select_case_improvements"?

**Comment by LonelyCat124** [comment]
No, that fixes it - can you add a test into that branch if you don't already have one to ensure this doesn't arise in the future?

**Comment by sergisiso** [comment]
Agreed, this has been resolved
