### ISSUE TITLE
[LFRic] Error when using GH_WRITE and continuous fields in intergrid kernels

### ISSUE THREAD

**Issue by tommbendall** [stfc/PSyclone#2253]
I've run into a very specific issue when using intergrid kernels which have a continuous field with the `GH_WRITE` permission, e.g.: https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/kernel/intermesh_transforms/restrict_w2_kernel_mod.F90?rev=41236

For kernels like this, we should loop up to `mesh%get_last_edge_cell()`, and there is generally no need to perform a halo exchanges.

However it seems that we are looping up to `mesh%get_last_halo_cell(1)`, and therefore may be performing some halo exchanges that we don't need to on the other fields. For intergrid kernels, we may be reading from a field on a fine mesh -- if we have more than 2 `ntarget_cells_per_source_x` or `ntarget_cells_per_source_y` then we may be trying to read from information that isn't in the halo cells of those fields, leading to a segmentation fault.

I can bypass this at the LFRic end by changing the kernel metadata so that it is `GH_WRITE` with some `ANY_DISCONTINUOUS_SPACE`.

This is very related to #1542, so happy to close this issue and just post an update on there.

**Comment by arporter** [comment]
Hi @tommbendall, that looks like a bug (especially having read through #1542). I'll take a look...

**Comment by arporter** [comment]
Strangely, I have explicitly turned-off the special handling of `GH_WRITE` access for inter-grid kernels:
https://github.com/stfc/PSyclone/blob/75b2bc719795dd255994f831b4646e82b7342074/src/psyclone/dynamo0p3.py#L8047-L8060
I can't remember why I did this. If I simply comment out the check at L8054-8056 then all of our tests still pass. If I make a branch with this change would you be able to test it?

**Comment by arporter** [comment]
The LFRic integration test failed. Specifically, applying the `everything_everywhere_allatonce` script failed for:

    gungho_model$ psyclone -s optimisation/psyclone-test/global.py -d working working/gungho/algorithm/runtime_constants/limited_area_constants_mod.x90

where the wrong number of indices are supplied to a colour-map array. The problem occurs when colouring is applied to a loop containing an inter-grid kernel that has GH_WRITE access for a field on a continuous space. I think it's something to do with the loop being given an upper bound of `ncell` where previously it was a halo access.

**Comment by arporter** [comment]
Thankfully the fix was fairly straightforward - previously we only added the 'last-edge-cell' map if DM was off. Now I always create it (alongside the one that includes halos) and then can just it as appropriate.
