### ISSUE TITLE
Could we make it possible to toggle DM (MPI) from within an optimisation script?

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#226]
@MatthewHambley and @TeranIvy have asked whether it would be possible to control whether or not PSyclone generates DM code from within the optimisation script (rather than/as well as via command-line flag). This would simplify their build system.

**Comment by arporter** [comment]
`DynLoop.load()` populates a Loop object from a kernel and sets the upper bound according to whether or not DM is enabled. Therefore, I suspect a fair amount of refactoring will be required to allow DM to be toggled *after* a Schedule has been constructed.

**Comment by arporter** [comment]
@rupertford has pointed out that DM can be controlled from the configuration file and in turn, which configuration file to pick up can be controlled by the `PSYCLONE_CONFIG` environment variable.

**Comment by hiker** [comment]
I was about to write this as well, and also point out that the config file can be specified on the command line now, which might (or might not) be easier/better to understand:
```--config dm.config 
```

**Comment by TeranIvy** [comment]
No worries, @arporter  and @rupertford, we will manage with the configuration files. As I said on the LFRic Telco last Tuesday I think that we will have to adjust our build process to use PSyclone in a more flexible way (e.g. more than one makefile for the entire code base and individual optimisation scripts for different algorithms) anyway. I just need to open design discussion tickets and wait 6 months until people come to this conclusion (as it happened with named invokes) :grin:

@hiker, could you please re-post your example? All I can see is a grey line. Thanks!

**Comment by arporter** [comment]
One thing I learnt on Friday (that you probably already know, but just in case you don't...) is that Gnu make cannot pick-up files created during the build process. It caches the contents of the working directory upon startup and any wildcards simply filter that cached content. If the files are created in some other directory then you have more chance but it is not nice as it is hard to predict when make will construct its cache.

**Comment by hiker** [comment]
> @hiker, could you please re-post your example? All I can see is a grey line. Thanks!
Oops - I fixed the comment above, thanks

**Comment by arporter** [comment]
@TeranIvy - can I close this now?

**Comment by TeranIvy** [comment]
Yes, please!
