### ISSUE TITLE
Add simple OpenACC example

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#227]
We're really lacking a bare-bones OpenACC example that lets us test basic functionality without all the additional complexity of NEMOLite2D.

In this issue we'll add a single-kernel example.

**Comment by arporter** [comment]
Strangely, I'm having great trouble getting the simple example to work - it fails, complaining about an invalid address on the GPU. This happens on both glados and my desktop.

**Comment by arporter** [comment]
Things were OK until I put back the call to the kernel from within the loop. That then gave memory address errors again. I got back to NVIDIA and Brent Leback says: "We don't support assumed shape array passing in OpenACC compute regions."
If I change the kernel subroutine to also accept the dimensions of the array then my toy example is fine.

**Comment by arporter** [comment]
For the moment I've added the array extents as explicit kernel arguments. Provided that the pgi compiler is told to inline (-Mipa=inline:reshape) the example builds and runs.

**Comment by rupertford** [comment]
pr #233 has been merged to master. Closing this issue.
