### ISSUE TITLE
Files containing a `Program` and `Subroutine` seem to just drop the `Subroutine`s

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2315]
I thought I already had an issue for this, but I couldn't find it under socrates tag.

A number of the `program` files in socrates also have `Subroutine`s inside, but the subroutines are lost upon passing through PSyclone.

**Comment by arporter** [comment]
#2329 fixes this by ensuring that we get a CodeBlock in such cases. #2205 will improve this in the longer term.
