### ISSUE TITLE
Update fparser version in setup.py

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#2316]
PSyclone `setup.py` still requires fparser 0.1.1 release despite the newer 0.1.2 release being on PyPI. 

When installing PSyclone from the master or a branch both fparser 0.1.1 release and 0.1.2 submodule are pulled in. This complicates testing on our end, so I would like to have it fixed for the final testing of PSyclone master before finalising the release.

For info, `lib/python3.7/site-packages` directory of PSyclone test installation built from the current master or a branch looks something like this

```
drwxrwsr-x.  PSyclone-2.3.1.dist-info
drwxrwsr-x.  fparser
drwxrwsr-x.  fparser-0.1.1.dist-info
drwxrwsr-x.  fparser-0.1.2.dev29+gca11947.dist-info
drwxrwsr-x.  psyclone
```

**Update:** We agreed to release fparser 0.1.3 and update `setup.py` to point to that version, as well as point PSyclone master to the latest fparser. The relevant fparser issue is https://github.com/stfc/fparser/issues/427.

**Comment by arporter** [comment]
fparser 0.1.3 is out! I'll do this next...

**Comment by TeranIvy** [comment]
@arporter, I'm happy to finish this :) I'll update the `setup.py` and pull in the most recent fparser master as submodule.
