### ISSUE TITLE
Reformat DynStencil into LFRicArgStencil namedtuple

### ISSUE THREAD

**Issue by oakleybrunt** [stfc/PSyclone#2319]
Sub-issue of #2235 
Parallel issue to #2265

After splitting DynStencil from Dynamo0p3 and renaming to LFRicStencil, APorter sees that there is no verification of LFRicStencil setter and getter methods. APorter proposes to replace LFRicStencil with a `namedtuple` LFRicArgStencil. This is to stay in Dynamo0p3.py.

**Comment by arporter** [comment]
#2321 is on master.
