### ISSUE TITLE
Maxval2CodeTrans with operator/intrinsics as top-level argument

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2323]
I tried applying the new Maxval2CodeTrans to the NEMO missing GPU region.
The intrinsics that we aim to transform look as following:
```
stpctl.f90:
119:      zmax(1) = MAXVAL(ABS(sshn(:,:) + ssh_ref * tmask(:,:,1)))
121:      zmax(1) = MAXVAL(ABS(sshn(:,:)))
123:    zmax(2) = MAXVAL(ABS(un(:,:,:)))
134:      zmax(3) = MAXVAL(-tsn(:,:,:,jp_sal), mask=llmsk)
135:      zmax(4) = MAXVAL(tsn(:,:,:,jp_sal), mask=llmsk)
137:        zmax(5) = MAXVAL(-tsn(:,:,:,jp_tem), mask=llmsk)
138:        zmax(6) = MAXVAL(tsn(:,:,:,jp_tem), mask=llmsk)
140:          zmax(9) = MAXVAL(cu_adv(:,:,:), mask=llmsk)
151:            zmax(8) = MAXVAL(ABS(wi(:,:,:)), mask=wmask(:,:,:) == 1._wp)
```

See output below, some good and bad news. 1 of them (line 140) has been converted and the dependency analysis properly reports "maxval_var" as a reduction 🥳   The the rest are refused because there is an intrinsic (ABS) or UnaryOperator (MINUS) as top-level node or a fixed dimension in the array accessor:
```
Transformation Error: Maxval2CodeTrans only supports arrays or plain references for the first argument, but found 'IntrinsicCall'.
MAXVAL(ABS(sshn(:,:) + ssh_ref * tmask(:,:,1)))
Transformation Error: Maxval2CodeTrans only supports arrays or plain references for the first argument, but found 'IntrinsicCall'.
MAXVAL(ABS(sshn(:,:)))
Transformation Error: Maxval2CodeTrans only supports arrays or plain references for the first argument, but found 'IntrinsicCall'.
MAXVAL(ABS(un(:,:,:)))
Transformation Error: Maxval2CodeTrans only supports arrays or plain references for the first argument, but found 'UnaryOperation'.
MAXVAL(-tsn(:,:,:,jp_sal), mask=tmask(:,:,:) == 1._wp)
Transformation Error: Maxval2CodeTrans only supports arrays with array ranges, but found a fixed dimension in 'tsn(:,:,:,jp_sal)'.
MAXVAL(tsn(:,:,:,jp_sal), mask=tmask(:,:,:) == 1._wp)
Transformation Error: Maxval2CodeTrans only supports arrays or plain references for the first argument, but found 'UnaryOperation'.
MAXVAL(-tsn(:,:,:,jp_tem), mask=tmask(:,:,:) == 1._wp)
Transformation Error: Maxval2CodeTrans only supports arrays with array ranges, but found a fixed dimension in 'tsn(:,:,:,jp_tem)'.
MAXVAL(tsn(:,:,:,jp_tem), mask=tmask(:,:,:) == 1._wp)
Transformation Error: Maxval2CodeTrans only supports arrays or plain references for the first argument, but found 'IntrinsicCall'.
MAXVAL(ABS(wi(:,:,:)), mask=wmask(:,:,:) == 1._wp)
Loop not parallelised because: Transformation Error: Dependency analysis failed with the following messages:
Warning: Variable 'maxval_var' is read first, which indicates a reduction.
Loop not parallelised because: Transformation Error: Dependency analysis failed with the following messages:
Warning: Variable 'maxval_var' is read first, which indicates a reduction.
Loop not parallelised because: Transformation Error: Dependency analysis failed with the following messages:
Warning: Variable 'maxval_var' is read first, which indicates a reduction.
```

We could allow operators and elemental intrinsiccalls as arguments in this transformation because we can assume that the array inside them will give use the shape that we need, or we could go a more generic route and continue the #685, since this seems the simpler case for node datatype inference. What do you think @rupertford @arporter ? Has any of you started #685?

**Comment by arporter** [comment]
It looks like Rupert started doing it 2.5 years ago! I haven't done anything on it.

**Comment by rupertford** [comment]
I've done pretty much nothing on #685 so would treat it as a new issue. It should not be too difficult to add support for operators and elemental intrinsic calls in the *2codetrans transformations, so if that fixes the issues in NEMO I would go for that. I could take that on for minval, maxval and sum.

**Comment by sergisiso** [comment]
As you prefer, the node datatype is also going to be useful for other things, and it may be the safer way to do expression like `MAXVAL(ABS(sshn(:,:) + ssh_ref * tmask(:,:,1)))`. But the specific case alternative maybe quicker, e.g. if we want to show progress in the esmwf workshop

**Comment by rupertford** [comment]
Adding support for expressions for the first (array) argument which allows elemental intrinsic calls, unary operators and binary operators.

**Comment by rupertford** [comment]
First working version in [2323_maxval_op_intrinsic_arg](https://github.com/stfc/PSyclone/tree/2323_maxval_op_intrinsic_arg)

**Comment by rupertford** [comment]
Sergi has suggested a new approach to supporting MAXVAL, MINVAL and SUM which contain expressions. He has also suggested that we end up using MAX, MIN and SUM intrinsics as they can vectorise (run on GPU and CPU efficiently), rather than converting completely to code. I think this latter change will require a change to the names of the transformations as they will not be to code anymore - unless we have an option?

**Comment by rupertford** [comment]
Sergi's suggestion (taken from PR #2344) is the following ...

Also, looking at the implementation I feel like we are making things more complicated that it needs to be, the array range to loop for expressions is already implemented, and it took some time to do it well, so we should re-use it:

Step 1) from `x = maxval(a(:)+b(:))`, extract the expr and put it in the rhs of an assignment:
```
a(:) = a(:) + b(:)
```
use a copy of one of the arrays on the lhs because the transformation below needs an array in the lhs and it uses it for the bounds expressions.

Step2) call nemoarrayrange2loop_trans.py on the assignment and get
```
do idx = LBOUDN(a,1), UBOUND(a,1)
   a(idx) = a(idx) + b(idx)
enddo
```
Step3), convert again the assignment to its intrinsic form by dropping the lhs and doing INTRINSIC(original_lhs, <expr>)
```
do idx = LBOUDN(a,1), UBOUND(a,1)
   MAX(x, a(idx) + b(idx))
enddo
```
Step 4) Add x initialisation.
```
x = tiny()
do idx = LBOUDN(a,1), UBOUND(a,1)
   MAX(x, a(idx) + b(idx))
enddo
```

**Comment by rupertford** [comment]
But what about the `dim=x` and `mask=y` options? Mask can go around the resultant `MIN/MAX/SUM` but I'm not sure about `dim`

**Comment by sergisiso** [comment]
As we discussed on the call, it is similar, but step 3 must be reducing the appropriate dimension, .e.g:
`x = maxval(a(:,:)+b(:,:), dim=1)`

Step 1:
`a(:,:) = a(:,:) + b(:,:)`


Step 2:
```
do idx = LBOUDN(a,1), UBOUND(a,1)
   do idx2 = LBOUDN(a,2), UBOUND(a,2)
        a(idx,idx2) = a(idx,idx2) + b(idx,idx2)
   enddo
enddo
```

Step 3:
```
do idx = LBOUDN(a,1), UBOUND(a,1)
   do idx2 = LBOUDN(a,2), UBOUND(a,2)
        MAX(x(idx), a(idx,idx2) + b(idx,idx2))
   enddo
enddo
```
Step 4 add:
`x = tiny()`

**Comment by rupertford** [comment]
Creating a new branch [2323_new_maxval_implementation](https://github.com/stfc/PSyclone/tree/2323_new_maxval_implementation)
