### ISSUE TITLE
`VERIFY` IntrinsicCall has its `name` attribute set incorrectly

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2340]
```
        VERIFY = IAttr(
            'TRIM', True, True, False,
            ArgDesc(2, 2, DataNode), {"back": DataNode, "kind": DataNode})
```

This results in `VERIFY` from read Fortran turning into `TRIM` when output.

**Comment by arporter** [comment]
I'll take this as Daley has hit it already with NEMO (and it's my fault because I should have insisted on full testing when I reviewed the PR).

**Comment by arporter** [comment]
The strange thing about this bug is that our integration tests didn't pick it up, despite the fact that the version we use has VERIFY in iom.f90.

**Comment by arporter** [comment]
Sergi has pointed out that we exclude iom.f90 (in process_nemo.py) *unless* we're adding profiling (which we don't in our tests).
