### ISSUE TITLE
Remove habakkuk as dependency (NEMO API)

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#235]
Currently, the trial NEMO API has habakkuk as a dependency. In this issue we will decide whether or not that is necessary and make the required changes.

**Comment by arporter** [comment]
The only *actual* dependency at the moment is on the `get_child()` utility routine. I'm moving this into fparser2 in https://github.com:stfc/fparser/issues/126

**Comment by arporter** [comment]
There is commented-out code that uses Habakkuk's DAG generation/analysis to work out the inputs and outputs of a kernel. However, that is not currently used.

**Comment by arporter** [comment]
Rupert has kindly reviewed and merged my branch to add the Habakkuk functionality into fparser2. I've updated the git submodule to point to this version. (Note that the commit above that talks about DO-WHILE loops was not actually for this Issue - I just used the wrong number in the commit msg.)

**Comment by TeranIvy** [comment]
Merged PR #243 so closing this issue.
