### ISSUE TITLE
Using dataclasses in PSyclone

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2352]
@sergisiso writes:

Since we are starting using dataclasses and python type hints, I think we should decide how we use them in the whole codebase going forward:

1. Regarding type hints. If we annotate method signatures and dataclasses with them, do they appear in the generated documentation?, and if they do, should we start removing them from the docstring (leaving just the descriptions there)?

2. Regarding dataclasses, in the python ecosystem there are some competing libraries (e.g. attrs, pydantic), see https://stefan.sofa-rockers.org/2020/05/29/attrs-dataclasses-pydantic/#:~:text=Data%20classes%20use%20the%20optional,prohibit%20this%20for%20good%20reason. We should choose the one more convenient for us, some allow to annotate which class fields to use in equality, or frozen classes to avoid state mutability, which would allow us to remove some code and manual checks. Also note that any of them do automatic run-time type checking. We need to decide if we use validators or post_init hooks to keep our current functionality.

**Comment by arporter** [comment]
@rupertford writes:

I don't know about the documentation either so can't comment. As for 2) using 3.7+ dataclasses seems to be reasonable rather than things that are not in the standard library.

**Comment by arporter** [comment]
`Attrs` (https://www.attrs.org/en/stable/) has been around a while now and is presumably pretty stable. It offers the significant advantage of allowing the user to provide validation methods.

**Comment by hiker** [comment]
I don't know anything about dataclasses etc, so can't contribute much. I couldn't even find where we are using it :(

**Comment by arporter** [comment]
> I don't know anything about dataclasses etc, so can't contribute much. I couldn't even find where we are using it :(

We're not yet :-) @oakleybrunt has PR #2321 which currently uses a dataclass but we need to decide if that's the option we like the best.

**Comment by arporter** [comment]
The documentation generated by Sphinx AutoAPI for Oakley's new class looks like:
![image](https://github.com/stfc/PSyclone/assets/17409212/be2a6033-343f-48b7-a043-146bd96be400)

**Comment by arporter** [comment]
Doxygen produces the following:
![image](https://github.com/stfc/PSyclone/assets/17409212/d8ea6524-682e-4763-9469-8941bf11cf84)
It would be good if the documentation of the parameters appeared in the "Static Public Attributes" section really.

**Comment by arporter** [comment]
You can document the parameters but it has to be done as comments beginning with `##`.

**Comment by arporter** [comment]
If I switch to using `attrs` `define` decorator:
![image](https://github.com/stfc/PSyclone/assets/17409212/f30601df-e304-4f40-8152-d18673ef29b1)
which is pretty much the same as before.

**Comment by arporter** [comment]
Unfortunately, the Doxygen version is less good:
![image](https://github.com/stfc/PSyclone/assets/17409212/24d55a97-8095-4d70-9625-cb8565bbf8d4)

**Comment by arporter** [comment]
I guess if all we're doing is replacing namedtuple then having `frozen=True` is no problem? I like the fact that pydantic provides a decorator that will type-check argument calls for you but that's heavier weight. (I'd always assumed that type hints got used for that kind of thing automatically otherwise what's the point?)

**Comment by arporter** [comment]
BTW, the doc produced for the pydantic equivalent is not so nice either:
![image](https://github.com/stfc/PSyclone/assets/17409212/16c3118d-58a8-4a44-b04c-357bffe714df)

**Comment by sergisiso** [comment]
> I'd always assumed that type hints got used for that kind of thing automatically otherwise what's the point?

Unfortunately python is too dynamic to avoid it to trick it in some way, so type hint can not be used for optimizations or runtime guarantees.

They are only for static tools, like documentation generators, linters, ...

**Comment by sergisiso** [comment]
> The documentation generated by Sphinx AutoAPI for Oakley's new class looks like

I was hoping we could also remove the duplicated type inside the docstring, something like in:
https://sphinx-autoapi.readthedocs.io/en/latest/how_to.html#how-to-include-type-annotations-as-types-in-rendered-docstrings

**Comment by arporter** [comment]
> > The documentation generated by Sphinx AutoAPI for Oakley's new class looks like
> 
> I was hoping we could also remove the duplicated type inside the docstring, something like in: https://sphinx-autoapi.readthedocs.io/en/latest/how_to.html#how-to-include-type-annotations-as-types-in-rendered-docstrings

That looks good. Ideally we'd do away with building both Doxygen and Sphinx AutoAPI but I still prefer the output of Doxygen :-)

**Comment by sergisiso** [comment]
But the doxygen still looks good for method signatures with type hints? Was your "##" comment specifically about dataclass fields?

**Comment by arporter** [comment]
> But the doxygen still looks good for method signatures with type hints? Was your "##" comment specifically about dataclass fields?

Yes, it was just for class attributes.

**Comment by sergisiso** [comment]
Didn't we already has this problem before? I think I have seen some "#:" comments that I thought it was to add documentation to class variables. Did this only work for one documentation?

**Comment by arporter** [comment]
Yes, sorry, I didn't mean to imply it was a new problem. I was just hoping that moving to a `dataclass` might help with it.

**Comment by hiker** [comment]
Could you update the example to use the required type-hint and dataclass usage? I've just tried using type-hints, and I noticed that the created documentation looks like this:
![image](https://github.com/stfc/PSyclone/assets/6138652/8bc40989-1cf9-474d-8ad1-818b0d6d4125)

(i.e. the type info is not in the parameters list anymore).  Is that expected, and is this what we should be doing? 

I also tried specifying a PSyclone class as return type:
```
    def get_parse_tree(self) -> :py:class:`fparser.two.Fortran2003.Program`
```
... in various combinations (with adding ":" in different spots). What should I do here?

Also, it would be great to add the 'expected' use of dataclass in this example.

I am happy to update the wiki, if someone confirms that what I did was what is expected :)

**Comment by arporter** [comment]
> (i.e. the type info is not in the parameters list anymore). Is that expected, and is this what we should be doing?

Yes, that's expected and correct (since it now appears in the routine signature).

Currently, we're only anticipating using `dataclass` in place of `namedtuple`.

The ":py:class:" stuff is Sphinx markup, not Python. I think this will help: https://stackoverflow.com/questions/44664040/type-hints-with-user-defined-classes

So probably just `-> Fortran2003.Program` if `Fortran2003` has been imported.
