### ISSUE TITLE
Add `get_siblings` function/method

### ISSUE THREAD

**Issue by jwallwork23** [stfc/PSyclone#2369]
It'd be useful to have a way to get all 'siblings' of a node, i.e., all of its parents' children.

**Comment by sergisiso** [comment]
I see I am already late for reviewing the previous PR :) but the current implementation would fail for root nodes with no parent.
Currently it will say someting like .children is not a valid attribute of NoteType.
It needs a special case for when parent is None to return a list with just one item: [self]. This would still satisfy the docstring and prevent the exception
