### ISSUE TITLE
bug in PSyAD harness generation

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#2404]
@DrTVockerodtMO has reported that the PSyAD harness code fails on full debug as the bounds used for the kernel `setop_random_kernel_code` are `loop_stop = mesh%get_last_halo_cell(1)` but should go to `op_proxy%ncell_3d`. The former bounds have a lower value than the latter leading to NANs in some of the output.

It is not clear what the problem is because the code giving the problem is generated by PSyclone which is extensively tested and used.

**Comment by DrTVockerodtMO** [comment]
Can confirm that this now works on full-debug.

**Comment by rupertford** [comment]
Created branch [2404_setop_random_fix](https://github.com/stfc/PSyclone/tree/2404_setop_random_fix)
