### ISSUE TITLE
Remove NemoKern

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2411]
A grep shows NemoKern is used in many places, but most of them seem selfreferential - only needed because it exists and it must be inserted/tested/.... I don't think its used in any optimization logic since we use NEMOLoops.loop_type for these.  

This has two goals:
- Continue moving NEMO towards generic code transformation
- Leave room/simplify the refactoring of InlinedKern with the properties needed to fit with the other components of PSyKAl (e.g. inline Kernels without breaking DM)

@arporter @rupertford Is this what we agreed? Who wants to take this?

**Comment by arporter** [comment]
This sounds sensible to me. Since it's 'NEMO' I could take it unless either of you would like to :-)

**Comment by arporter** [comment]
We currently support `--profile kernels` for the NEMO API and in fact `--profile invokes` isn't at all obvious for a user processing existing code. Should we perhaps remove the `kernels` option and allow `routines` as well as `invokes`?

**Comment by arporter** [comment]
Or we could keep the `kernels` option and have it mean "loop nests containing only computation"?
