### ISSUE TITLE
Extend PSyIR support for polymorphic routines (INTERFACEs)

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2422]
In both NEMO and LFRic it turns out that the routines that we want to inline are mostly polymorphic (have implementations for different precisions or different ranks of array).

Currently, the fparser2 frontend captures and reproduces InterfaceBlocks as `RoutineSymbols` of `UnknownFortranType`:

https://github.com/stfc/PSyclone/blob/4c758df520bd64d11196eb4b1564e3c68d500ccf/src/psyclone/psyir/frontend/fparser2.py#L2392-L2420

If we are going to inline a polymorphic routine then we need to know to which implementations a particular call may be mapped and then:

  a) try to statically work out which one is actually being called, or
  b) module inline all of them and leave it to the compiler.

At minimum, we therefore need to know which `RoutineSymbols` a given Interface is for. Could we perhaps have a `PolymorphicRoutineSymbol` that itself then kept a list of `RoutineSymbols`?

**Comment by arporter** [comment]
What do @sergisiso, @rupertford  and @hiker think?

**Comment by rupertford** [comment]
That sounds good to me. I presume PolymorphicRoutineSymbol would be a subclass of RoutineSymbol so it could be referenced as a RoutineSymbol. I'm also guessing we only want to support `interface <name>` to start off with.

**Comment by hiker** [comment]
Sounds good to me. I am just not entirely sure if polymorphic is the right term? Doesn't this imply that the number of parameters are the same (but of different type), but a generic interface might have different number of parameters??

FWIW, here my code that collects some information from a generic interface:

https://github.com/stfc/PSyclone/blob/a4f630ccb46e1b6dda9b5393285a342d91c79fe2/src/psyclone/parse/module_info.py#L200

**Comment by sergisiso** [comment]
IMO is better to keep naming as close to Fortran as possible because otherwise it is surprising for people unfamiliar with the PSyclone internals when they write the users scripts. (And the language-independent is something that we only take advantage at the backends anyway). So may vote would be for something like InterfaceSymbol/GenericInterfaceSymbol
