### ISSUE TITLE
[LFRic] unused CMA matrix declared in PSy layer

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2442]
@TeranIvy has found that PSyclone is declaring an unused CMA matrix in the PSy layer:

    (psyclone310) me@laptop gravity_wave$ psyclone -d ./source/ -d ../../gungho/source ./source/algorithm/gw_pressure_precon_alg_mod.x90 | grep mm_w3_inv_cma_cma
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w3_inv_cma_cma_matrix => null()
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w3_inv_cma_cma_matrix => null()

I've done some digging and this bug was introduced at bc5a3f21a791567bd037e0fba4b7cf4fa63148a7 - this was from #2197 where we (I) changed to using pointers in the generated PSy layer (to get data movement working with the nvidia compiler).

**Comment by arporter** [comment]
call invoke( name="create_W3_mass_matrix",                                  &
                 compute_mass_matrix_kernel_w_scalar_type(mm_w3, chi, panel_id, &
                                                          extend_mesh, qr) )

Gives a whole bunch of declarations with 'incorrect' names:

      ...
      INTEGER(KIND=i_def) nlayers
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: diag_dhmdht_cma_cma_matrix => null()
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w2v_inv_diag_cma_cma_matrix => null()
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: grad_v_cma_cma_matrix => null()
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: div_v_cma_cma_matrix => null()
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w3_inv_cma_cma_matrix => null()
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w3_cma_cma_matrix => null()
      TYPE(columnwise_operator_proxy_type) mm_w3_cma_proxy, mm_w3_inv_cma_proxy, div_v_cma_proxy, grad_v_cma_proxy, mm_w2v_inv_diag_cma_proxy, diag_dhmdht_cma_proxy
      REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w2h_local_stencil => null()
      ...

**Comment by TeranIvy** [comment]
To be fair, it looks like accidentally duplicated code with another `_cma_` thrown into the variable name. We have this that is used and is passed to a kernel call  `REAL(KIND=r_solver), pointer, dimension(:,:,:) :: mm_w3_inv_cma_matrix => null()`.

`<cma_arg>_cma_matrix` is fine, however `<cma_arg>_cma_cma_matrix` seems to be a duplicate.

**Comment by arporter** [comment]
I think this is the culprit:
https://github.com/stfc/PSyclone/blob/133792afe2f80fc6bb4b2da2c1dfb26f58848434/src/psyclone/dynamo0p3.py#L3486-L3495
I don't think it's using the correct tag to lookup the variable name. However, that does beg the question: where is the 'correct' declaration being created if not here?

**Comment by arporter** [comment]
It turns out that the kernel arguments in the PSy layer (for this example) already end in "_cma" and so the "_cma_cma_" names are actually what I would expect to see:

    call invoke(                                                       &
                 ! Pressure mass matrix M_3
                 columnwise_op_asm_kernel_type( mm_w3,                 &
                                                mm_w3_cma ),           &
                 ! Inverse mass matrix M_3
                 columnwise_op_asm_kernel_type( mm_w3_inv,             &
                                                mm_w3_inv_cma ),       &

The question therefore is really, why are we still getting/using the old names?
