### ISSUE TITLE
Extend PSyIRe AST to express kernel implementations

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#245]
Currently kernel subroutines are not being parsed to PSyIRe. The Nemo API can parse any Fortran code using the `ASTProcessor` but it encapsulates unrecognized sections of code as `NemoCodeBlocks`. This issue will propose a generalisation of `ASTProcessor` and `CodeBlocks`, and an extension PSyIRe with the constructs commonly found inside kernel subroutines. This will allow for PSyclone code transformations inside kernels.

**Comment by sergisiso** [comment]
See commits 8eed43653fb75ed26c97a39f76d44b37bf1ffd53 and  c7e283ad943153944c10ff118c31151b4c406bf2

**Comment by rupertford** [comment]
pr #247 has been merged to master. Closing this issue.
