### ISSUE TITLE
Handling of Namelist files

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2463]
Trying to use PSyclone with the Nemo API on UM physics code showed that the handling of namelist files need to be improved. ATM, if a namelist statement is found in the source code, the whole module is converted to a code block, so we are getting a useless PSyIR (of just one node, instead of just having the namelist declaration as an Unknown Fortran).

While the namelist statement can be fixed in UMN-LFRic physics (as far as I can tell no namelists are actually read by LFRic, e.g. the reading of the namelist file is #ifdef'ed out for LFRic), this need to be handled better, since it takes a long way to find out why a file is not parsed. fparser itself handles it just fine, and most of PSyclone as well (as one big code block :) ), only when accessing symbol table etc things go wrong.

FWIW, the original exception is raised in line 2536 of fparser2, with node being:
```
NAMELIST /run_bl/ i_bl_vn, 
```
a `Namelist_Stmt` (and the rest of the code, e.g. the actual subroutines is not even touched anymore).

Even if this is not improved, we have to print a proper error message to guide the user to the problem. Identifying which line is causing fparser2 to fail can take a long time!

**Comment by arporter** [comment]
At least part of the answer to this is logging.
