### ISSUE TITLE
[nemo] add OpenACC transformations

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#248]

**Comment by rupertford** [comment]
#185 is looking at adding OpenACC for the gocean api and the gocean need openacc directives to be added to kernels, so makes use of fparser2.

In this issue we will do a similar thing for the nemo API. We will add the ability to use an OpenACC kernels transformation (i.e. one that adds !$acc kernels to a routine) in the prototype nemo api.

**Comment by rupertford** [comment]
Work is on branch nemo_acc_kernels

**Comment by rupertford** [comment]
I've agreed with @arporter that in the first instance we will add support for the following directives

a) kernels/end kernels
b) loop (+ collapse and independent as options)

The spec I'll follow is here ... [OpenACC API 2.6 Reference Guide](https://www.openacc.org/sites/default/files/inline-files/OpenACC%20API%202.6%20Reference%20Guide.pdf)

**Comment by arporter** [comment]
For reference, the list of Fortran intrinsics that I have at the moment (on glados) is:

    fortran_intrinsics = ["MIN", "MAX", "ABS", "SIGN", "MOD", "SUM",
                          "FLOOR", "CEILING", "REAL", "KIND", "EXP", "SQRT",
                          "SIN", "COS", "TAN", "LOG", "LOG10", "NINT",
                          "MINVAL", "MAXVAL", "MINLOC", "MAXLOC", "TRIM",
                          "RESHAPE", "CMPLX"]

**Comment by rupertford** [comment]
pr #287 is now on master. Closing this issue.
