### ISSUE TITLE
Loop fusion transformation producing wrong code when fusing loops on different variables.

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2488]
I have the following loops:
```
                do ll = 1, n_strong, 1
                  l = strong_list(ll)
                  path_base = sph%common%path_base(l,ii)
                  temp(ll) = SUM(-k_abs_layer(l,:path_base,iex,i_abs_band) * sph_mass_path(l,1:path_base,ii))
                enddo
                do i_3 = 1, n_strong, 1
                  temp_exp(i_3) = EXP(temp(i_3))
                enddo
                do ll = 1, n_strong, 1
                  l = strong_list(ll)
                  flux_direct_term(l,ii) = esft_weight * temp_exp(ll)
                  sph_flux_gas(l,ii) = sph_flux_gas(l,ii) + flux_direct_term(l,ii)
                enddo
```
I wanted to fuse the 3 loops into 1 loop (in theory to parallelise them as a single loop, although in this case its not going to be possible).

Using the base class `LoopFuseTrans`, I attempted to do this, and it produced no longer correct code (which PSyclone shouldn't do):
```
                do ll = 1, n_strong, 1
                  l = strong_list(ll)
                  path_base = sph%common%path_base(l,ii)
                  temp(ll) = SUM(-k_abs_layer(l,:path_base,iex,i_abs_band) * sph_mass_path(l,1:path_base,ii))
                  temp_exp(i_3) = EXP(temp(i_3))
                  l = strong_list(ll)
                  flux_direct_term(l,ii) = esft_weight * temp_exp(ll)
                  sph_flux_gas(l,ii) = sph_flux_gas(l,ii) + flux_direct_term(l,ii)
                enddo
```

It has fused the loops (which I think it can do without problem), but it doesn't consider at any point that the name of the loop variable of the 2nd fused loop isn't the same. If `i_3` was changed to `ll` then probably we'd have correct code.

I notice that there are specialisations of this class, however this one is capable of performing a transformation to produce incorrect code for some cases - should we fix it? @arporter @sergisiso

**Comment by arporter** [comment]
I think we should fix it. I've had a quick look at the 'nemo' specialisation and it doesn't seem to bring anything to the party apart from restricting loop variables to have the same name (which seems a bit restrictive). Ideally I think we'd remove the specialisation and bring anything useful from it into this base class.

**Comment by LonelyCat124** [comment]
Yeah, I was hoping the NemoLoopFuseTrans would just work for the above without attempting anything but alas it just doesn't fuse them, presumably due to the thing you say. I'll try to have a look then.

**Comment by arporter** [comment]
Good point @hiker - it would be good to 'modernise' it. (I thought you were on leave ;-) )

**Comment by LonelyCat124** [comment]
Its sort of a duplicate (the name is for sure) - i think I've found a different issue/improvement than is highlighted in that issue. I'll adjust the name of this issue.

**Comment by LonelyCat124** [comment]
Going to have to reopen this as there's a bug in the implementation which I immediately hit with socrates.

I have these loops being fused in socrates:
```
        DO l=1, n_profile
          sum_flux(l, n_layer, j)=0.0e+00_RealK
        END DO
        DO i=1, n_layer
          DO l=1, n_profile
            flux_gas(l, i)=0.0e+00_RealK
            sum_k_flux(l, i, j)=0.0e+00_RealK
          END DO
        END DO
```

and the result of the merge is just totally wrong:
```
          do l = 1, n_profile, 1
            sum_flux(l,n_layer,j) = 0.0e+00_realk
            do l = 1, n_profile, 1
              flux_gas(l,i) = 0.0e+00_realk
              sum_k_flux(l,i,j) = 0.0e+00_realk
            enddo
          enddo
```

It appears multiple checks have failed to fail correctly:
1. The loops should have the same iteration range, but the fused loops have iteration ranges of `1, n_profile` and `1, n_layer` which PSyclone shouldn't expect to be the same.
2. The loops have different loop variables, but the first loop's variable is used inside the second loop, so it should fail with the new check. This is not happening which means something else is going wrong.

@sergisiso I will reopen this issue here and try to solve it.

**Comment by LonelyCat124** [comment]
Hmm, this might be my mistake with being on the wrong branch, hang on.

**Comment by LonelyCat124** [comment]
I merged latest master into the branch I'm working on (924_module_inline) so its not an old version of the branch now I think.

I cannot replicate this from a standalone example though at the moment so I'm a bit confused.

**Comment by LonelyCat124** [comment]
Not an issue with this, but more so an issue with having PSyLoop when I didn't think I would, no problem, will reclose this.
