### ISSUE TITLE
Automatically generate OpenCL kernels when the OCLTrans is invoked

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#249]
Once PSyIRe is able to express kernel code we can generate a C representation of the PSyIRe nodes in order to dump a C version of the kernel. Ultimately this Issue intents to target the generation of simple OpenCL kernels for accelerators (e.g. FPGAs).

**Comment by sergisiso** [comment]
This requires  #245, #247, #255 and #216, and it is the first target outcome we planned for Hartree work on EuroExa Project WP2.

**Comment by arporter** [comment]
#387 has been merged to master.
