### ISSUE TITLE
Introduce GH_READWRITE access (for discontinuous quantities)

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#25]
This was previously ticket 831 on SRS.

During discussions with Tom on SRS 576 it has become clear that there is a requirement to have kernels that accumulate a result into a W3 (i.e. discontinuous) field. Since we use GH_INC to mean that multiple cells contribute to a shared quantity (which then requires some sort of reduction operation in parallel), we will re-introduce the GH_READWRITE access descriptor. This can then be used to describe operations that accumulate into a discontinous quantity and thus do not require a reduction when performed in parallel.

The same situation arises when applying boundary conditions to an operator (#22) - the operator needs to be INTENT(inout) because it is both read and written. However, since the operator is discontinuous this access can safely be performed in parallel.

**Comment by TeranIvy** [comment]
Hi @aporter! When "pytlinting" `dynamo0p3.py`, I get the following message:  `Relative import 'f2pygen', should be 'PSyclone.src.psyclone.f2pygen'`. I guess I need to change that, as well as other similar instances?

**Comment by arporter** [comment]
Hi @TeranIvy, I think I've fixed all those in a ticket that's currently in review so you can leave them for the moment.

**Comment by arporter** [comment]
Hi @TeranIvy that's disappointing! The code does look nicer but, as you say, we can't be having randomly-ordered arguments or our sanity will suffer. Just forget I ever mentioned sets :-)

**Comment by TeranIvy** [comment]
Hi @arporter and @rupertford! I am figuring out how RW access would work in transformations by playing with the existing tests for `w3` (discontinuous field), so I have a question about interpretation of RW metadata depending on first access and its impact on transformations. I set intents of RW quantities same as W (`inout` if first read, `out` if not in `psyGen.py`).

In `testkern_w3_only.f90` there are 2 `w3` fields:
```
     type(arg_type), dimension(2) :: meta_args =  (/  &
             arg_type(gh_field,gh_write,w3), &
             arg_type(gh_field,gh_read, w3)  &
           /)
```
They are called in 3 tests in `dynamo0p3_transformations_test.py`; issues with two of them described here.
1. `test_rc_no_loop_decrease` (file `1_single_invoke_w3_only.f90`)
  ```
  call invoke( testkern_w3_only_type(f1,f2) )
   ```
   Q1.1: My guess here was that defining `arg_type(gh_field,gh_readwrite,w3)` for `f1` should still be valid as the intents behave the same depending on the first access. However, the test fails (`Transformation Error: In the Dynamo0p3RedundantComputation transformation apply method the first argument is not a Loop`). Do we want (RW,R) to behave the same as (W,R) and where can I add it?

2. `test_loop_fusion_different_loop_name` (uses `4.12_multikernel_invokes_w3.f90`, write to read dependence)
  ```
    call invoke( testkern_w3_only_type(f1,f2),  &
                testkern_w3_only_type(f3,f1)  )
  ```
Q2.1: I also thought that `arg_type(gh_field,gh_readwrite,w3)` for `f1` should be valid here but the test fails (`Transformation Error: Error in LoopFuse transformation. At least one of the nodes is not a loop`).
Do we want RW->R dependence to behave the same as W->R dependence?
Also, if both fields are `GH_READWRITE`, do we want PSyclone to figure out which should be given R and which W behaviour depending of first access? Can we allow both `w3` fields to be RW here?

**Comment by TeranIvy** [comment]
I think that RW intent should really be `inout` if the first access is `readwrite` as well as `read`, as we need to assume that the field values in this case are set somewhere else and then read from. Also, can we allow mappings from RW fields to RW fields?

**Comment by arporter** [comment]
Hi @TeranIvy, apologies for the delay in responding. I think the good news with the test failures is that something fairly fundamental is going wrong! `At least one of the nodes is not a loop` simply shouldn't happen just because we've changed the type of access that an argument has. Therefore, I think you'll have to dig in to the code where that error is raised and see what's happening.

**Comment by arporter** [comment]
(Apologies if this is teaching you to suck eggs but I find `print type(my_obj)` and `print dir(my_obj)` to be good debugging aids if you've got an object but are not sure what it is. Hopefully the push to fully document all interfaces in the code should reduce the need to do this when debuggging...)

**Comment by rupertford** [comment]
pr #149 is on master. Closing issue.
