### ISSUE TITLE
Update codecov action in CI to use latest API

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2548]
Currently the GHA coverage reports are not being added to PRs. This is because CodeCov has updated its API. To fix this we need to:

![image](https://github.com/stfc/PSyclone/assets/17409212/6156a15b-6872-42fb-a653-4c88503a6172)

(from https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/) for all GHA yml files.

**Comment by sergisiso** [comment]
CodeCov status checks is now working for new commits. Closing issue
