### ISSUE TITLE
NEMO OpenACC kernels transformation fails to build with nvhpc 24.3

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2591]
In our integration test it first fails because the mpi library include location has changed, but this can be fixed with:
`export MPI_INC_DIR=$(dirname $(which mpif90))/../include/`

But then the OpenACC kernels transformation fails with:
```
NVFORTRAN-S-0000-Internal compiler error. size_of: attempt to size assumed size character 
0  (/home/gh_runner/NEMO/cfgs/SPITZ12_openacc_kernels/WORK/domvvl.f90: 684)
```
Note that it succeeds with the OpenMP loop acceleration

**Comment by nmnobre** [comment]
Reported in #1596.
