### ISSUE TITLE
Update psyclone transformation script interface for generic code

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2600]
Now that #1779 is out of the way, the next step is to clean the PSy-Invokes-Invoke-InvokeSchedule for Nemo and only do frontend->transformation_script->backend. This can mostly change under-the-hood, but the psyclone script API is currently:
```python

def trans(psy):
    """
    :param psy: the PSy object which this script will transform.
    :type psy: :py:class:`psyclone.psyGen.PSy`
    :returns: the transformed PSy object.
    :rtype: :py:class:`psyclone.psyGen.PSy`
    """
    print(f"Invokes found in {psy.name}:")
    for invoke in psy.invokes.invoke_list:
        subroutine = invoke.schedule
```
Which does not make sense for PSyIR-only workflows and we shouldn't pollute generic code transformation with PSyKAl notation. In addition, the ability to skip files (by also skipping the parser step) in `process_nemo.py` has been quite useful, now is integrated in nemo but it could still be useful for other apps and be an optional part of the script API. So, I propose using something like:

```python

SKIP_FILES = ("file1.f90", "file2.f90")

def trans(psyir_root):
    """
    :param psyir_root: root node of the IR.
    :type psyir_root: :py:class:`psyclone.psyir.nodes.FileContainer`
    """
    for subroutine in psyir_root.walk(Subroutine):
```

This is not something that we want to change often as it breaks backwards/forward compatibility of scripts, but it seems the moment to do it as the next release is the first one that supports proper generic code transformation. What do @arporter and @hiker think?

There is another related change in the "psyclone command" as currently we still use `psyclone input.f90 -opsy output.f90 -oalg /dev/null` for generic code. Again, I would adopt the more standard process_nemo.py `-o` in psyclone witout -api and let -opsy/-oalg 
 and -dm complain if they are not together with a `-api`

**Comment by arporter** [comment]
I think your suggestion is sensible Sergi. I did wonder about having the `trans` be passed just the `Routine` node but then I realised that we normally work on a file-by-file basis and will want to module inline etc. so it makes more sense to pass the whole PSyIR. I also like the tidying-up of the command line options that you describe.
