### ISSUE TITLE
lfric eg17 full_extract now printing warnings.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2610]
I've realised that the kernel extraction (e.g. examples/lfric/eg17/full_example_extract) is now producing warning messages:
```
fparser.common.utils.AnalyzeError: entity name 'dummy_code' is not in module 'dummy_mod'
[CallTreeUtils._resolve_calls_and_unknowns] Cannot find a routine 'dummy_var3' in module 'dummy_mod' - ignored.
[CallTreeUtils._resolve_calls_and_unknowns] Cannot find a routine 'dummy_var2' in module 'dummy_mod' - ignored.
[CallTreeUtils._resolve_calls_and_unknowns] Cannot find a routine 'dummy_var1' in module 'dummy_mod' - ignored.
[CallTreeUtils._resolve_calls_and_unknowns] Cannot resolve routine 'dummy_func' in module 'dummy_mod' - ignored.
[CallTreeUtils._resolve_calls_and_unknowns] Cannot resolve routine 'dummy_code' in module 'dummy_mod' - ignored.
```
or see https://github.com/stfc/PSyclone-mirror/actions/runs/9401299910/job/25892770196#step:9:18354

I suspect this is because of the work I did generalising the ModuleManager. @hiker, is this news to you?

**Comment by hiker** [comment]
Seems to be at least two problems. The messages about `dummy_var...` are indeed a spurious warning added as part of #2462.  The cannot resolve was likely there before. I'll fix them.
