### ISSUE TITLE
Re-visit design of KernCallArgList and DynKernelArguments

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#268]
In #224 I've done a bit of re-factoring to tidy-up the use of the gen_code() method for Kernel objects.
I've moved class-specific kernel-argument set-up into `GOKernelArguments`. This is then picked-up by the `Kernel.gen_code()` method of the base class. However, this does not carry through into the Dynamo API because there we've already tidied things up and have another class, `KernCallArgList` that handles the complexity of setting up the argument list. Since this is outside of the `DynKernelArguments` class, it is not available in the base class and so we have to do a little bit of poking to ensure the argument list is set correctly before the `Kernel.gen_code()` method of the base class is called. It seems to me that the functionality for managing the kernel argument list ought to be within the `DynKernelArguments` class (or at least accessible from it). I'll investigate this in this issue.

**Comment by arporter** [comment]
I've brought @rupertford in to this Issue as he did the `KernCallArgList` refactoring originally.

**Comment by arporter** [comment]
In #224 I have refactored so that `DynKernelArguments` has a `raw_arg_list()` method that itself uses the `KernCallArgList` class to generated the argument list. This then avoids the need to do the poking described in my first comment. However, it has revealed that KernCallArgList breaks encapsulation because, while setting up the kernel argument list, it can also modify the PSy AST to declare and assign an array required by the boundary-conditions kernel (in `KernCallArgList.field_bcs_kernel()`).

**Comment by rupertford** [comment]
The only reason that parent is passed into raw_arg_list is because KernCallArgList needs it to modify the PSy AST. Because of this we have had to make it an argument to the psyGen.py:Argument/raw_arg_list method and also pass it in psyGen.py:Kern/gen_code. However, parent is not required in the gocean1.0 api raw_arg_list method so we get a pylint error at the moment saying we are changing the interface (as it does not have parent).

If this issue manages to remove the need for passing parent into raw_arg_list (which I think it should) then we should also remove the parent argument from the two psyGen.py locations mentioned above.

**Comment by arporter** [comment]
Constructing the list of arguments for a kernel (or kernel stub) is a
complex task. The `psyclone.dynamo0p3.ArgOrdering` base class
provides support for this.

This class is then sub-classed in order to support the generation or
arguments lists when *calling* kernels (`KernCallArgList`) and when
*creating* kernel stubs (`KernStubArgList`).

Unlike the base class, both of these classes allow the parent PSyIR
node to be passed in to the constructor. This information is then used
to modify the PSyIR in order to add declarations of various quantities
associated with kernel arguments.

`KernCallArgList` is only used in `DynKernelArguments.raw_arg_list()`.
`KernStubArgList` is only used in `DynKern.gen_stub()`.

What needs to happen is that the modification of the PSyIR be broken out of the code that is responsible for constructing the kernel argument list.

**Comment by arporter** [comment]
In gocean we have `GOKernelArguments` which sub-classes the `psyGen.Arguments` class. We then have the `GOKernelArguments.raw_arg_list()` method which, like `DynKernelArguments.raw_arg_list()`, generates the actual list of arguments for a kernel call. Note that we do not have a kernel-stub generator for the GOcean API so life is simpler there.

**Comment by arporter** [comment]
GOcean also differs from Dynamo in that we tend to do all of our object de-referencing in-place in the kernel call itself, e.g.:

    call my_kernel(my_field%data)

whereas in Dynamo we generally have a set-up section where we do all the de-referencing. The variables created in that section are then used as arguments to the kernel call(s).

**Comment by arporter** [comment]
In the `DynInvoke` class we have moved to having separate classes to handle the set-up for each type of entity required by an invoke (e.g. all information related to grids for multi-grid). I think what is needed is to extend this approach to handle the invoke set-up for other kernel arguments (and thus remove it from the kernel-argument-list setup). I need to think about how this affects the kernel-stub generator though.

**Comment by arporter** [comment]
The kernel-stub generator relies on `KernStubArgList()` to generate both the argument list and the associated declarations. This functionality needs to be separated and the declarations part shared with the PSy-layer generation where possible. In fact, I think the natural way to do this is to add support for stub-generation to each of the classes that we have already, e.g. `DynInvokeDofmaps`, `DynMeshes` etc.

**Comment by arporter** [comment]
e.g. take the functionality of `KernStubArgList.indirection_dofmap()` and move the declarations part of it to `DynInvokeDofmaps.stub_declarations()` or similar.

**Comment by TeranIvy** [comment]
I'm all in favour for separating the argument list from the associated declarations. This way declarations for kernel calls, kernel stub generation and write/read statements in kernel extraction can be handled separately without replicating the creation of arguments as it is done now. In most cases the argument list is the same and the only difference between `KernCallArg` and `KernStubArg` is declarative part with explicit `dimension` (and I will need to add `allocatable` for kernel extraction).  I think keeping definitions of arguments in their respective classes (e.g. `DynMeshes`) and using those definitions for different declarations would make changing/adding declarations more flexible (e.g. for things like changing `r_def` when doing mixed precision later).

**Comment by arporter** [comment]
It's coming together and I'm starting to remove the generation of declarations from the code that deals with the argument list. However, do I need to also re-visit the generation of the argument list itself?

**Comment by arporter** [comment]
I think I have now unified the handling of stencil arguments between the psy- and kernel-stub-generators. Next up is operators.

**Comment by arporter** [comment]
Working my way through `dynamo0p3_test.py`. I need to re-name all my `DynInvokeXXX` classes as they're used by both Invokes and kernel stubs. I also need to make sure they're all up-to-date/consistent in supplying `_stub_declarations` and `_invoke_declarations` methods (to be called by the base-class' `declarations()` method. Finally, I suspect I can just have a list of all these classes, common to both the Kernel-stub- and Invoke-generating code.

**Comment by arporter** [comment]
`DynKernelArguments` creates names for variables to hold stencil extent and direction, if required. Unfortunately this is currently separate from the use of `DynInvokeStencils` to manage the names and consequently we're getting different names generated. The invoke constructor creates the `DynInvokeStencils` object but if we're dealing with a kernel stub then we don't have an Invoke.
The situation is further complicated by the fact that the Algorithm writer can specify the same variable name for two or more stencil extents. The generated PSy-layer routine will have just one argument for these extents.

**Comment by arporter** [comment]
The creation of the `KernelArguments` is done during the construction of the `Kern` object. Therefore the PSyIR is not yet in a consistent state and we can't walk back up the tree from the Kernel object to find an enclosing Invoke (and thus the `DynInvokeStencils` object). Originally, the NameSpaceManager was used to hold state between the construction of each `KernelArguments` but then we're back to the fact that the `label` supplied in creating a name in `DynKernelArguments` is not the same as the `label` supplied in `DynInvokeStencils`.

**Comment by rupertford** [comment]
#306 has been merged to master so closing this issue.
