### ISSUE TITLE
Un-needed code generated if an Invoke contains only kernels that iterate over DoFs

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#269]
@thomasmelvin has reported that PSyclone generates several unnecessary infrastructure calls when an Invoke contains only calls to built-ins:

    call invoke(setval_c(shear, 0.0_r_def))

results in:

    SUBROUTINE invoke_0(shear)
      USE mesh_mod, ONLY: mesh_type
      TYPE(field_type), intent(inout) :: shear
      INTEGER df
      INTEGER ndf_any_space_1_shear, undf_any_space_1_shear
      INTEGER nlayers
      TYPE(field_proxy_type) shear_proxy
      TYPE(mesh_type), pointer :: mesh => null()
      !
      ! Initialise field and/or operator proxies
      !
      shear_proxy = shear%get_proxy()
      !
      ! Initialise number of layers
      !
      nlayers = shear_proxy%vspace%get_nlayers()
      !
      ! Create a mesh object
      !
      mesh => shear%get_mesh()
      !
      ! Initialise number of DoFs for any_space_1_shear
      !
      ndf_any_space_1_shear = shear_proxy%vspace%get_ndf()
      undf_any_space_1_shear = shear_proxy%vspace%get_undf()
      !
      ! Call kernels and communication routines
      !
      DO df=1,shear_proxy%vspace%get_last_dof_owned()
        shear_proxy%data(df) = 0.0_r_def
      END DO
      !
      ! Set halos dirty/clean for fields modified in the above loop
      !
      CALL shear_proxy%set_dirty()
      !
      !
    END SUBROUTINE invoke_0

when it could just be:

    SUBROUTINE invoke_0(shear)
      USE mesh_mod, ONLY: mesh_type
      TYPE(field_type), intent(inout) :: shear
      INTEGER df
      TYPE(field_proxy_type) shear_proxy
      !
      ! Initialise field and/or operator proxies
      !
      shear_proxy = shear%get_proxy()
      !
      ! Call kernels and communication routines
      !
      DO df=1,shear_proxy%vspace%get_last_dof_owned()
        shear_proxy%data(df) = 0.0_r_def
      END DO
      !
      ! Set halos dirty/clean for fields modified in the above loop
      !
      CALL shear_proxy%set_dirty()
      !
      !
    END SUBROUTINE invoke_0

If we're lucky the compiler will spot that we're initialising things we never use and will optimise them out but it's never good to rely on that kind of thing.

**Comment by arporter** [comment]
Doing the work for this on the `builtin_only` branch.

**Comment by arporter** [comment]
In fact, I realise that it shouldn't be "builtins only" but rather "dofs only" as we don't want to limit built-in kernels to those that only iterate over dofs. This then is Dynamo0.3 specific as the base classes don't know about dofs.

**Comment by arporter** [comment]
Drop previous changes and now work on `dofs_only` branch.

**Comment by rupertford** [comment]
pr #273 has been merged to master. Closing this issue.
