### ISSUE TITLE
[PSyData] Improvement to value verification

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2690]
The nan library tests for nan and inf, but it would be useful if a user could specify a range for variables in a certain kernel. E.g. 'in kernel ABC variable B should be between 0 and 1000).

Proposed solution: each variable in each kernel can be assign an environment variable, e.g. `PSYVERIFY__MODULE_REGION__VAR=1-2`, indicating that the variable `VAR` in the specified kernel must be between the two specified values (also supporting 1-, -2). These variables could be collected over time, improving verification.

**Comment by arporter** [comment]
#2694 is now on master.
