### ISSUE TITLE
[nemo] replace eager conversion of implicit loops with transformation

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#272]
In #244 we found that the current implementation of eager conversion of implicit loops to explicit loops caused problems (because it is not yet robust). It is also likely to be unnecessary for OpenACC. Therefore we will move this functionality into a Transformation rather than have it happen by default.

**Comment by arporter** [comment]
Cherry-picked commits 365eeb7b2b043ee9ba2e25c018a54746398c96a83 and 3ade5b672af5b6ecc661c72355e463c10716dd9 to bring in the code changes done under #244.

**Comment by rupertford** [comment]
Closing this issue as PR #277 is now on master
