### ISSUE TITLE
Update LFRic transformation signature?

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2739]
Since we are talking about 3.0, one aspect that I wanted to discuss is if we should also update the LFRic scripts signature in this major release to use the root psyir node as scprit input argument (like in the generic transformation scripts).

Instead of:
```python
def trans(psy):
    '''
    :param psy: the PSy object that PSyclone has constructed.
    :type psy: :py:class:`psyclone.dynamo0p3.DynamoPSy`
    '''

    # Loop over all the Invokes in the PSy object
    for invoke in psy.invokes.invoke_list:
        print("Transforming invoke '"+invoke.name+"'...")
        schedule = invoke.schedule
```

it would be:
```python
def trans(psyir):
    '''
    :param psyir: the PSyIR of the generated PSy-layer
    :type psyir: :py:class:`psyclone.psyir.nodes.FileContainer`
    ''''
    # Loop over all the Invokes Subroutines
    for schedule in psyir.walk(InvokeSchedule):
        print("Transforming invoke " + schedule.name)
```

The main advantage is that it hides the PSy->Invokes->Invoke->InvokeSchedule structure:
- Opens the door to modify it without breaking existing scripts
- Less concepts to know about (and documentation needed) for users writing scritps

Other minor advantages are:
- Allows to modify non invoke subroutines in a natural top-down approach (`psyir.walk(Routines)` instead of `invoke.schedule.root.walk(Routines)` that we do now)
- Converges some code with the generic transformations, so we can simplify the generate.py
- Simpler for people writing scripts for UM parts integrated into PSyclone, as they just need to know 1 script signature instead of 2.

What do @arporter @hiker @christophermaynard @TeranIvy  think?

**Comment by arporter** [comment]
Thanks @sergisiso, I like this proposal a lot. Presumably, if we were dealing with a named invoke (i.e. a `call invoke(name="big-science", kernel1(x,y))`) then that name would still be available in the script as the name of the `InvokeSchedule`?

**Comment by sergisiso** [comment]
Yes, I didn't discuss it here but there are some scripts that use `psy.invokes.get("invoke_0")` which would then be a `schedule.name == "invoke_0"` check. Some print `psy.name` which will then be `psyir.name`. And since we would be touching all these loops we could also rename InvokeSchedule to InvokeRoutine (since it inherits from Routine) and it will be even clearer to do: `for subroutine in psyir.walk(InvokeRoutine):` (since Schedule is a very specifc PSyclone concept but Routine is a broader Fortran concept).
