### ISSUE TITLE
[LFRic] [PSyAD] Function space pointers declared and assigned in random orders in generated adjoint test

### ISSUE THREAD

**Issue by DrTVockerodtMO** [stfc/PSyclone#2742]
This is a critical issue that prevents the development of further patches for LFRic adjoint test algorithms.

Essentially if you have a test which generates the following function space code

```
function_space_1_ptr => get_fs(mesh, element_order, fs_1_id)
function_space_2_ptr => get_fs(mesh, element_order, fs_2_id)
```

you can write a patch that will expect the generated ordering as `fs_1` followed by `fs_2`. Making a patch with these in the hunks will result in patching errors 50% of the time because PSyAD will eventually set the ordering to

```
function_space_2_ptr => get_fs(mesh, element_order, fs_2_id)
function_space_1_ptr => get_fs(mesh, element_order, fs_1_id)
```

There are developments in LFRic that are going to require the patching of these function space pointers, whereas previously it was avoided. These function space pointers ought to be sorted in some way so that they consistently produce a correct ordering.

**Comment by DrTVockerodtMO** [comment]
@arporter Tagging for visibility.

**Comment by arporter** [comment]
Thanks @DrTVockerodtMO. I think this is as simple as changing https://github.com/stfc/PSyclone/blob/e615b2bcaf65c62f22d14bed1b47c1dbae1d6950/src/psyclone/domain/lfric/algorithm/lfric_alg.py#L273
to be `for space in sorted(fspaces)`. This may break the text comparisons in a few tests so they will have to be fixed. Do you want to have a go at this?

**Comment by DrTVockerodtMO** [comment]
> Thanks @DrTVockerodtMO. I think this is as simple as changing
> 
> https://github.com/stfc/PSyclone/blob/e615b2bcaf65c62f22d14bed1b47c1dbae1d6950/src/psyclone/domain/lfric/algorithm/lfric_alg.py#L273
> 
> to be
> 
> ```python
> for space in sorted(fspaces)
> ```
> 
> This may break the text comparisons in a few tests so they will have to be fixed. Do you want to have a go at this?

I can have a go at this yes!
