### ISSUE TITLE
Update to fparser submodule following release of PSyclone

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#275]
Having released 1.7.0 of PSyclone to work with (the newly-released) 0.0.8 of fparser, we have forgotten to update the version of fparser pointed to by the git submodule. Attempting to install that version fails because pip spots that it is version 0.0.7 and PSyclone requires 0.0.8.

In this issue we will update the submodule version of fparser and update the instructions for when making a new release of PSyclone.

**Comment by arporter** [comment]
I've just updated the wiki page (https://github.com/stfc/PSyclone/wiki/NewRelease) with the need to update the fparser git submodule.

**Comment by rupertford** [comment]
pr #276 has been merged to master. Closing this issue.
