### ISSUE TITLE
[LFRic] [PSyAD] PSyAD no longer computes adjoint of vector assigments properly in PSyclone 3.0-dev

### ISSUE THREAD

**Issue by DrTVockerodtMO** [stfc/PSyclone#2755]
In testing PSyclone 3.0, we find that forward code that looks like

```
vector(:) = vector(:) + constant(:) * scalar
```

where `vector` and `scalar` are active no longer adjoints to

```
do idx = vector_ubound, vector_lbound, -1
  scalar = scalar + constant(idx) * vector(idx)
end do
```

but instead does

```
scalar = scalar + constant(:) * vector(:)
```

which fails to compile. The former behaviour is expected.

**Comment by arporter** [comment]
Thanks @DrTVockerodtMO, could you provide some Fortran source that shows this problem when running PSyAD?

**Comment by DrTVockerodtMO** [comment]
> Thanks @DrTVockerodtMO, could you provide some Fortran source that shows this problem when running PSyAD?

Sure! For the forward `strong_curl_kernel` we have the lines

```
do df1 = 1,ndf1
  curl_u(:) = curl_u(:) + u(map1(df1)+k)*diff_basis_w1(:,df1,df2)
end do
```

these used to get adjointed pre 3.0 to

```
do df1 = ndf1, 1, -1
 do i = 3, 1, -1
   u(k + map1(df1)) = u(k + map1(df1)) + diff_basis_w1(i,df1,df2) * curl_u(i)
 enddo
enddo
```

which is correct, but now they get adjointed to

```
do df1 = ndf1, 1, -1
  u(k + map1(df1)) = u(k + map1(df1)) + diff_basis_w1(:,df1,df2) * curl_u(:)
enddo
```

which is not.

The other kernel that exhibit this new behaviour is `vorticity_advection_kernel`.

**Comment by arporter** [comment]
In the psyad examples, we do:
```
psyad -api lfric tl_vorticity_advection_kernel_mod_tweaked.F90 -oad ../adjoint_partial/adj_vorticity_advection_kernel_mod.F90 -a r_u res_dot_product vorticity_term cross_product1 cross_product2 j_vorticity u_at_quad mul2 vorticity_at_quad wind vorticity
```

**Comment by arporter** [comment]
As suspected, the transformation (called from preprocess.py) rejects the assignment:
```
Assignment2LoopsTrans cannot expand expression because it contains the access 'wind(map_w2(df) + k)' which is an UnresolvedType and therefore cannot be guaranteed to be ScalarType. In:
u_at_quad(:) = u_at_quad(:) + wind(map_w2(df) + k) * w2_basis(:,df,qp1,qp2)
```

**Comment by arporter** [comment]
`ArrayMixin._effective_shape()` hadn't been updated now that we do support getting the `datatype` of an Operation. Once I do that we get:
```
          do df = ndf_w2, 1, -1
            do idx_3 = UBOUND(u_at_quad, dim=1), LBOUND(u_at_quad, dim=1), -1
              wind(k + map_w2(df)) = wind(k + map_w2(df)) + w2_basis(idx_3,df,qp1,qp2) * u_at_quad(idx_3)
            enddo
          enddo
```
