### ISSUE TITLE
[LFRic] [PSyAD] Change in operator index ordering does not match PSyAD's matmul standard

### ISSUE THREAD

**Issue by DrTVockerodtMO** [stfc/PSyclone#2774]
Previously, an valid operator from PSyAD's perspective would be of the form `operator( : , : , idx )`, i.e.: the first two indices are full ranges. LFRic is now changing the index accessing to be like `operator( idx, : , : )` which does not fit the standard imposed by PSyAD. This causes the following failure:

```
psyclone.psyir.transformations.transformation_error.TransformationError: Transformation Error: To use matmul2code_trans on matmul, the first two indices of the 1st argument 'operator' must be full ranges.
```

**Comment by DrTVockerodtMO** [comment]
This is related to https://github.com/stfc/PSyclone/issues/2766

**Comment by DrTVockerodtMO** [comment]
I'm thinking you might just be able to count the number of full range indices, if it's not equal to 2 then you throw a modified error message.

If it is simple enough to get the number of matrix indices out then I don't mind having a go at this!

**Comment by DrTVockerodtMO** [comment]
I think the validation would still throw an error since the forward code will use operators that fail that validation. Of course, only fixing the validation ought to run into errors if it is only operating on `matrix1.children[2:]` say (since some of those ranges will be full whereas currently they are not), so the resulting adjoint ought to not be correct. Both would need to be fixed to run PSyAD without needing to patch it.

**Comment by arporter** [comment]
For an array reference, the `indices` method is what you want. You'd need to count the number of `Range` nodes.

**Comment by arporter** [comment]
I don't think it should be part of #2766 (although may be required for it). It's a self-contained change to the transformation.
