### ISSUE TITLE
CI for Python 3.8 failing at install stage

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#2777]
We still test against Python 3.8 but that has reached end of life:
![image](https://github.com/user-attachments/assets/a5654f0d-0d42-45c8-b960-098f6f901bf5)
Presumably, this is the reason that the GHA run for this python version is failing (https://github.com/stfc/PSyclone/pull/2776#issuecomment-2474217428)?

**Comment by arporter** [comment]
@TeranIvy what's the minimum Python version you require?

**Comment by arporter** [comment]
AFAICS, the only use of jupyter in the CI is to run the example in gocean/eg1. These example notebooks aren't mentioned in the READMEs!

**Comment by schreiberx** [comment]
In case this matters (or incentivises to give up Python 3.8): The minimum Python version we support for Poseidon is 3.9.

**Comment by arporter** [comment]
Since the GI has magically been fixed I'm closing this for now but it would be good to review what minimum Python version the Met Office requires.
