### ISSUE TITLE
Removal of extraction #TODO that are actually done.

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#2778]
❯ rg "\#647"
examples/gocean/eg5/extract/extract_transform.py
44:missing (TODO: #647)

examples/gocean/eg5/extract/main.f90
34:! TODO: #647 - Once this is implemented, this function can be removed.

examples/lfric/eg17/full_example_extract/extract_transform.py
45:missing (TODO: #647)

❯ rg "\#644"
src/psyclone/tests/domain/gocean/transformations/gocean_extract_test.py
531:    pytest.xfail("#644 Scalars not supported yet.")

examples/gocean/eg5/extract/extract_transform.py
43:At this stage it does not compile (TODO: #644), and the comparison is

examples/lfric/eg17/full_example_extract/extract_transform.py
44:At this stage it does not compile (TODO: #644), and the comparison is

**Comment by arporter** [comment]
The PR for this has been merged :-)
