### ISSUE TITLE
[LFRic] [PSyAD] Initialisation of arrays of fields in adjoint test features non-integer accesses in PSyclone 3.0-dev

### ISSUE THREAD

**Issue by DrTVockerodtMO** [stfc/PSyclone#2816]
Solely in the initialisation part of the adjoint tests using `setval_random`, the different accesses into arrays of fields follows the form e.g.: `1.0_i_def` instead of `1_i_def`. This causes compilation errors when trying to build in LFRic, since `n.0_i_def` are treated as floats instead of ints despite the `i_def` kind being integer based.

This is new behaviour that wasn't present in PSyclone 2.5.0. Example kernels that reproduce the error are `tl_hydrostatic_kernel_mod` and `tl_moist_dyn_mass_kernel_mod`.

**Comment by arporter** [comment]
Thanks Terry. Is this with the very latest master?

**Comment by TeranIvy** [comment]
> Thanks Terry. Is this with the very latest master?

@arporter, it was with your `nlayers` branch which is now the master.

**Comment by TeranIvy** [comment]
> Thanks Iva, I'll take a look.

@arporter, the LFRic Apps branch with the relevant kernels and @DrTVockerodtMO's patches is [r5299_AdoptPSyclone3.0.0](https://code.metoffice.gov.uk/trac/lfric_apps/browser/main/branches/dev/ivakavcic/r5299_AdoptPSyclone3.0.0) ([changesets for adjoints](https://code.metoffice.gov.uk/trac/lfric_apps/changeset?reponame=&new=5399%40main%2Fbranches%2Fdev%2Fivakavcic%2Fr5299_AdoptPSyclone3.0.0&old=5368%40main%2Fbranches%2Fdev%2Fivakavcic%2Fr5299_AdoptPSyclone3.0.0)). The relevant LFRic ticket is https://code.metoffice.gov.uk/trac/lfric_apps/ticket/409.
