### ISSUE TITLE
get mesh via proxy

### ISSUE THREAD

**Issue by christophermaynard** [stfc/PSyclone#290]
Almost infrastructure calls in the PSy layer are done via a proxy (to the field), get_mesh() is called on field, rather than the proxy. There is no real problem with this accept it triggers a compiler bug in PGI fortran. The work-around is to call get mesh via the proxy. This is also consistent with other PSy layer code.

**Comment by christophermaynard** [comment]
This has been done on a branch but is a little out of date.
[](https://github.com/stfc/PSyclone/compare/pgi_workaround)

**Comment by christophermaynard** [comment]
[pgi_workaround](https://github.com/stfc/PSyclone/compare/pgi_workaround)

**Comment by christophermaynard** [comment]
Again, out of date so making a new branch ...

**Comment by christophermaynard** [comment]
[PGI_get_mesh_proxy](https://github.com/stfc/PSyclone/tree/PGI_get_mesh_proxy)

**Comment by christophermaynard** [comment]
Made changes to dynamo0p3.py and associated tests so that mesh is accessed via the proxy.

**Comment by christophermaynard** [comment]
I have modified the generation code and the tests so that fields now access the mesh via the proxy and `vspace`. In the tests, I have also modified how operators access the mesh, so they too go via the proxy, but `fs_from` in this case. The tests pass, but I haven't modified the generation code, which is a bit odd. I can't seem to find the generation code for operators. Any clues, @arporter

**Comment by arporter** [comment]
Hi @christophermaynard, please could you begin your commit messages with '#issue_number my great commit...'. That way github picks them up and lists them here which makes life nice :-)

**Comment by arporter** [comment]
The generation code worries about whether or not a mesh is required, not the type of variable from which to get it - it just uses the first suitable variable in the argument list. Therefore, if you've updated that then you're done (modulo the need to support inter-grid kernels where there's more than one mesh to get).

**Comment by christophermaynard** [comment]
Ah. I see, the first changes to get generation code apply to a general object, either a field or and operator. OK. I guess we are done then. I think that is all I need to do.

**Comment by christophermaynard** [comment]
Sorry, will in future pre-pend my commit messages. I'll issue a pull request!

**Comment by arporter** [comment]
The PR for this was merged a while ago so closing issue.
