### ISSUE TITLE
Make parent-child connection always coherent

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#294]
We may want to ensure the PSyIR parent-child connection is always coherent. Simply adding to Node `__init__` or `addChild` methods something like:
```
self._children.append(child)
if child.parent is not self:
    child.parent = self
```
breaks the unittest

**Comment by sergisiso** [comment]
This is the encapsulation issue referenced in #411. I think the child-parent tree relationship could be done with 'atomic' addChild, removeChild, moveChild (or similar names) that handled the parent pointer of the child appropriately, this would move this bit of logic away from the transformations code.

At the moment there are parent and children setters, `__init__` has a parent parameter, and some nodes has `load()` methods that also set the parent. We have to think if we need all of those and in that case if the atomic/consistent operation should be performed by all of them.

**Comment by hiker** [comment]
I love the 'atomic' operations 👍 They would make transforms a lot easier to write.
Not sure about the __init__ handling - it is a bit odd that Node.__init__ takes both parent and children ;)

Semantic-wise: addChild should (imho) also remove a child from the previous parent, which (I think) then makes moveChild unnecessary. Or maybe the other way around: you move a child that has no parent to a node, so no addChild but only moveChild.
