### ISSUE TITLE
Make PSyclone compute setval_* to the level 1 halo by default

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#295]

**Comment by rupertford** [comment]
The recent halo exchange optimisations by PSyclone can lead to data being read before it is initialised. Whilst this sounds like an error it is not actually a correctness issue as the data that is being read is related to redundant computation in the halo where the results of this computation are not used.
However, reading data before it is initialised is not good practice and causes at least one architecture/compiler combination to fail with a seg fault. The problem occurs when we initialise a continuous field with a kernel that iterates over dofs and subsequently access this field with a gh_inc access within a kernel that iterates over cells.

The only cases where we initialise a continuous field with a kernel iterating over dofs are setval_c and setval_x. Therefore if we compute setval_c and setval_x to the level1 halo by default then we will never access uninitialised data.

The general rule is that a kernel that iterates over dofs and writes to a continuous field should iterate to the level 1 halo. At the moment the two cases of this (setval_c and setval_x as mentioned earlier) do not access any other fields. This means that no additional halo exchanges will be generated so there is no communication cost. However, if in the future a new kernel were written which wrote to a continuous field and read from other fields, then additional halo exchanges might be generated.

It might be worth constraining kernels that iterate over dofs and write to a continuous field to not be able to read from other fields if that is feasible. If not, we will need to be careful about resultant performance. I think that to start off with we should raise an exception if such a constraint were broken.

**Comment by rupertford** [comment]
So, what I said previously is not true. setval_x copies the value from another field. This means that if we compute setval_x redundantly by default then it would force a halo exchange for the field that it reads.

One option would be to change tack and to have the infrastructure mark halos as being untouched at the start and we could add runtime logic to perform halo exchanges at the start. However, this would cause performance issues for temporary fields.

Another option would be to always compute setval_c redundantly and to copy the data from the read to the write in setval_x without performing a halo exchange beforehand as the halo for the reader must have been touched.

Another option would be to zero all halos at the start (but that could causes Nans if we were to perform division).

A more complex addition would be to use the dependence analysis to work out what to do (where possible).

None of these are suggested solutions, I'm just thinking out aloud, although computing setval_c to level 1 halo by default seems to make some sense as a partial solution.

**Comment by TeranIvy** [comment]
We had a discussion in LFRic and we think that it makes sense to initialise fields to all halo depths when using `setval_c` and `setval_X` built-ins (and their integer counterparts). The related LFRic ticket is [1740](https://code.metoffice.gov.uk/trac/lfric/ticket/1740).

**Comment by rupertford** [comment]
This can be done very simply in the script. In fact it is already done to level1 I think.

**Comment by arporter** [comment]
Can this issue be closed now?

**Comment by rupertford** [comment]
The Met Office seem happy adding redundant computation via a PSyclone script rather than doing it by default so I would say so.
