### ISSUE TITLE
Inlining a kernel can cause incorrect code to be created

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#308]
While adding compilation test for gocean, I found the following bug in files in tests/test_files/gocean1p0/time_smooth_mod.f90 (only important code pasted here):
```
module time_smooth_mod
  REAL(go_wp), save :: alpha

  SUBROUTINE time_smooth_code(i, j, field, field_new, field_old)
    field_old(i,j) = field(i,j) + &
         alpha*(field_new(i,j) - 2.0d0*field(i,j) + field_old(i,j))
  END SUBROUTINE time_smooth_code

```
So basically time_smooth uses alpha, a module variable. If time_smooth is inlined into the psy layer, it can't find alpha anymore.

Easy solution: add a use statement to the subroutine ... but that only works if 'alpha' is not private. Other solution? Add the psylayer to the kernel module file instead? Or accept that this is unsupported and document it?

I've added an x-failing test case to my (upcoming) pull request for gocean compilation.

**Comment by arporter** [comment]
This is a known and documented limitation and therefore it's quite embarrassing that we have such a thing in one of our test files :-(

**Comment by hiker** [comment]
Not embarrassing ... this is why we are doing compilation tests, right?

And for the record: I did check the .rst files to see if this was documented, and I didn't see it. So I now created the pdf and found it ... of course I missed that part of the documentation is created from the py files *sigh* Sorry for having wasted your time.

How do you want me to fix this for the compilation testing branch? Just fix the Fortran file to avoid the usage of the module variable? Or leave it as x-failing separate test in (in case that we want a proper fix later)? Or just add a comment why this one test does not offer a compilation option?

**Comment by arporter** [comment]
Good point. I shall not be embarrassed :-) No worries on the documentation front - you've not wasted my time.
I think leaving it as x-failing is the way forward as we may well want to fix it properly.

**Comment by hiker** [comment]
ok, x-failing done in https://github.com/stfc/PSyclone/commit/b5e891fd915372c788999afd82531c080181e4d1 (line 1254), so I'll close this issue now.
