### ISSUE TITLE
Robust identification of readers and writers using dependency analysis

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#309]
#287 introduces rudimentary support for identifying the variables that a given section of code reads from or writes to. This Issue is to improve that support, particularly for derived types.

**Comment by arporter** [comment]
Re-assigning to @hiker since he's already doing it :-)

**Comment by hiker** [comment]
Work is done in:
https://github.com/stfc/PSyclone/tree/dependency-analysis
and a reasonable subset of statements is supported: assignments, do-loops, if-statements.

Known issues atm:
- Documentation missing
- Maybe more test cases
- subroutine calls not supported
- user defined types not supported
- Variables used in loop boundaries are not marked as read
Some issues are dependent on work on PSyIR.

**Comment by arporter** [comment]
This is actually a duplicate of #399 so I'm going to close it.
