### ISSUE TITLE
Compilation test in utilities_test.py not working

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#311]
It seems to happen only on some installations (guess might depend on hardware, or python version??), but the test_compiler_works() function does not always work as expected. I verified this by modifying the sample Fortran code to be invalid - the test on one of my systems still succeeded (though not on all).

Reason is that (under unknown circumstances) at the time the compiler is called, the file was not flushed (because it was not closed):
```
    try:
        with open("hello_world.f90", "w") as ffile:
            ffile.write(HELLO_CODE)
            success = _compile.compile_file("hello_world.f90", link=True)
```
While the fix (moving the compile_file called back one level, out of the with statement) is trivial, I propose to do a better test by actually trying to link the file (which fails since the compiler compiles an empty file, so it has no main, so linking fails). I'm fixing this as part of my compilation tests for gocean.

**Comment by arporter** [comment]
Hi @hiker, can this Issue be closed now. (I'm just waiting on the final Travis run before I merge #313.)

**Comment by hiker** [comment]
Yes ... but I am too slow ;)
