### ISSUE TITLE
Validate method of kernel-inline transformation does not check for module variables

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#315]
If a kernel is inlined that has a use statement, the resulting code can not be compiled. While this is a documented issue (see class KernelModuleInlineTrans), the inline transform should raise a proper error in this case. Note that this also effects some test cases, which can not be compiled during testing because of this restriction.

**Comment by hiker** [comment]
The test cases that can not be compiled are marked with 
# TODO: can not be compiled because of #315
(in pull request #313)

**Comment by arporter** [comment]
For OpenACC/CL transformations we also need to check that we know where all of the data accessed by a kernel comes from. Currently we do not check but as the PSyIR and its SymbolTable become more mature we will be able to implement these checks.

**Comment by arporter** [comment]
In addition, we need to check that any accesses of module-data in a kernel are read only.

**Comment by rupertford** [comment]
PR #407 is now on master so closing this issue.
