### ISSUE TITLE
It's not possible to compile opencl code 

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#316]
Main reason seems to be that dl_esm_inf has not been updated to contain the code (module) for opencl compilation.

**Comment by hiker** [comment]
Looking at the opencl_support branch in dl_esm_inf, there has been a directory added called 'FortCL', but it is empty. It would be great if a temporary version of those files could be added and merged to master, so we can get partial opencl compilation working.There is already a ticket in dl_esm_inf (https://github.com/stfc/dl_esm_inf/issues/10).
Alternatively, I could add a dummy module file to dl_esm_inf, just to get opencl Fortran compilation tests to work.

**Comment by arporter** [comment]
Hi @hiker. Yes, this is all work in progress. I guess we could do the adding of the FortCL submodule as a separate PR if that would allow you to make progress. I shall investigate.

**Comment by hiker** [comment]
Thanks, I think it would be quite useful if we could at least show that opencl compiles 'somewhat' ;) And avoid having tests with many xfails  which I would need to add otherwise :P

**Comment by arporter** [comment]
FortCL is now a submodule of dl_esm_inf on master. Closing this issue.
