### ISSUE TITLE
Kernel file search should be case insensitive

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#319]
@TeranIvy has reported the following bug:

Not able to find kernel because of upper case "dA" in the algorithm and lower case "da" in kernel name.
"calc_da_at_w2_kernel_mod.F90" is in gungho/source/kernel directory, just the case "dA" is different.
When "dA" is replaced with "da" in the algorithm the error goes away, however fparser should be case-insensitive.

[ikavcic@eld470 gungho]$ psyclone -d source/kernel/ source/algorithm/runtime_constants_mod.x90
"Parse Error: Kernel file 'calc_dA_at_w2_kernel_mod.[fF]90' not found in /net/home/h06/ikavcic/PSyclone_work/fparser2_work/r17724_test_fparser2/gungho/source/kernel"

**Comment by rupertford** [comment]
Created branch fix_kernel_search

**Comment by rupertford** [comment]
The match is performed by `get_kernel_filepath` in `parse/kernel.py` using `fnmatch.filter(filenames, search_string)`. I think the problem is that this filter is case sensitive (in a case sensitive os). There doesn't appear to be a case insensitive option so one option would be to revert to a regex ...

`options = [filename for filename in filenames if re.search(search_string, filename, re.IGNORECASE)]`

**Comment by TeranIvy** [comment]
Merged #331 so closing the issue.
