### ISSUE TITLE
Build generated code when testing

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#32]
At the moment we do not build any code when performing PSyclone tests. Therefore we do not know if the code will compile or not, we just trust this by inspection. This will help reduce mistakes by us before shipping new versions to users. In this ticket we will look at adding the building of code as part of our testing system i.e. within py.test. This was previously 469 on SRS.

**Comment by arporter** [comment]
Created `test_compilation` branch.

**Comment by arporter** [comment]
In order to be able to (nicely) generate a list of the Use statements in the PSy layer, I've had to re-jig things so that we store the f2pygen AST within the PSy object - previously we just created it when `gen()` was called and then immediately disposed of it. I've then added a `walk()` method to the f2pygen `BaseGen` class so that we can walk down the AST and find nodes of a particular type. This then allows us to pull out all of the `UseGen` nodes.
I've got a hard-coded list of 'infrastructure' modules (e.g. `field_mod`). I've done it this way so that we can ensure they are compiled in the correct order to satisfy dependencies between them.

I've added the new compilation-check to two tests so far and both fail. One because our `testkern.F90` doesn't have the necessary use statements for things like `kernel_type`. The other fails because my current stub infrastructure modules are missing key elements.

**Comment by arporter** [comment]
Now have compilation test working for a built-in example. I think I can move the `walk` method I added to `PSy` and put it as a module routine in `utils`. I also need to add a test that the user-supplied compiler and flags work.

**Comment by arporter** [comment]
Now have working compilation tests for both a built-in and a user-supplied kernel. I've also added a few tests for the new code that performs these tests.
Next step is to remove commented-out code from the infrastructure modules.

**Comment by rupertford** [comment]
Pull request #39 has been merged to master. Closing this issue.
