### ISSUE TITLE
Document the rules for module use statements in transformed kernels

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#321]
Document the restrictions on use statements in kernels that are candidates for transformations.

**Comment by arporter** [comment]
![use_stmts_kernels_whiteboard](https://user-images.githubusercontent.com/17409212/54786620-3ea2d000-4c21-11e9-8e05-a791dab2c4ad.jpg)

**Comment by rupertford** [comment]
pr #325 is now on master so closing this issue.
