### ISSUE TITLE
Create examples/test cases of use statements in kernel code

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#322]
So far we have identified three typical cases:

 1. a kernel accesses module data via a use statement;
 2. a kernel calls another routine that accesses module data via a use statement. We will support
    call trees of arbitrary depth;
 3. a kernel accesses a routine/function via a use statement.

In this PR we will create suitable test code for each of these cases and identify any PSyIR-related issues.

**Comment by rupertford** [comment]
#343 has been merged to master. Closing this issue.
