### ISSUE TITLE
Capture symbols from use stmts in the SymbolTable

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#323]
Capture any symbols accessed via module use statements (in kernels) in the SymbolTable. This is a first step towards being able to convert those symbols that are variables into kernel arguments instead.

**Comment by arporter** [comment]
I've begun adding code to handle any USE statements in the parse tree. For the moment I think it would be best to postpone attempting to resolve any symbols brought in via USE statements until we know we need to do so. That way we only parse additional code if we need to.

**Comment by arporter** [comment]
In #347 @sergisiso is adding support for annotations (via a new `Node._annotations` list of `str`). Although we'll need annotations here I think these will live in the `SymbolTable` and will hold the name of the module from which the symbol is imported.

**Comment by arporter** [comment]
Just realised that my new scope name of `global_use` is Fortran specific :-( Maybe it should just be `global`?

**Comment by sergisiso** [comment]
#366 added support for symbols with `use module, only: xxx` statements. I keep this issue open as other symbols inside modules are not resolved yet.

**Comment by sergisiso** [comment]
#518 is on master, it is now possible to extend the #366 to `use` statements without `only:`. This is different than #190 where `use` (with or without `only`) are found in a kernel and the generated kernel /programming modes does not support `use` statements. However, both solutions need to parse the `use`.

**Comment by rupertford** [comment]
@arporter, can this issue be closed now?

**Comment by arporter** [comment]
Yes, I think so.
