### ISSUE TITLE
xpassing test on master

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#327]
Master has an xpassing test. I think this is down to a merge for one of @hiker s PRs and am therefore assigning it to him in the first instance to check.

```
> pytest tests/gocean1p0_transformations_test.py::test_module_inline_and_compile
```

**Comment by hiker** [comment]
I have to admit that this confused me, till I realised that you were likely not using --compile (since it is only the compilation test that fails). Fixed in pull request 328.

**Comment by rupertford** [comment]
PR #328 has been merged to master. No need to close this issue as this seems to have been done automatically by the merge.
