### ISSUE TITLE
Global Variables in psyGen causes test failures

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#329]
While working on #257, I have discovered the magic of psyGen.MAPPINGS_ACCESSES, which is used to map from the internal access mode like 'read' to the API-specific access string 'gh_read'. There is some really sophisticated coding involved in managing this global variable, and while I managed to get it to work with gocean, this then broke some psyGen tests. Basically what happens is that when importing dynamo0p3 it modifies psyGen's variable. Which means that depending on the order of imports psyGen.MAPPINGS_ACCESS is either defined for dynamo, or gocean, and in at least one test case it happens to be the wrong one.

I'd suggest to avoid overwriting (or more precisely even using) this global variable, by moving this functionality into the api-specific config section. For example:
```
[dynamo0.3]
  access_mapping = read:gh_read, write=gh_write, ...
[gocean0.1]
  access_mapping = read:go_read, write=go_write, ...
```
Then we would also have to define a 'current' API in the config class, so psyGen can do:
```
Config.get().getCurrentAPI().getMappingAccesses() 
```
(or maybe even short: ``Config.get().getMappingAccess()``)

In case of typical PSyclone usage, the 'currentAPI' would be defined by the --api command line option. In case of tests each test would have to define the API (which could mostly done once-per-test-file using a fixture), and if there is a mixture of APIs used in one file, this might to have to be done from test to test. 

Besides fixing failed tests because of the import order, it would actually move some infrastructure specific strings into the config file. Imho PSyclone should try not to use any infrastructure specific strings (this would make it easier to add different infrastructure libraries without modifying PSyclone), and this would be a nice start for that.

Feedback welcome :)

**Comment by rupertford** [comment]
Hi @hiker. If we can move this to configuration that would be great.

I think I originally wrote it this way as I wanted/needed base classes to be able to compare with api-specific strings and it was the simplest way. In theory it is simple ... when you create a new API you just need to specialise some base classes, extend some factories and override some global variables. In theory only one API should be active at a time so they should only be overwritten once but I agree it is not the most maintainable code in the world and it is classic configuration information which would sit perfectly in config.

I also agree with, and appreciate your, gradual purging of api-specific content in PSyclone.

**Comment by hiker** [comment]
The code now looks like this:
```
access_mapping = Config.get().api_conf().get_access_mapping()
inc_args = self.unique_declarations(datatype,
                                        access=access_mapping["inc"])
```
api_conf returns the 'default' API object if it has no parameter (hope that's ok).

But I noticed one thing: somehow all of this appears to be the wrong way round: we store the original value ('gh_read'), and then we compare with the mapped value. Wouldn't it be easier to convert the value from the parsed code ('gh_read') to 'read' (etc) and just store this?

Example:
```
if arg.access.lower() == mapping["inc"]:
```
would become:
```
if arg.access.lower() == "inc":    
# or maybe even better:
if arg.access.is_inc():
```

Is there any reason why we store the original value?

**Comment by hiker** [comment]
Just to summarise our discussion on the video conference: there appears to be no reason that the argument class stores API-specific strings (like 'gh_read' instead of 'generic' access types like 'read'), so I will try if this can be simplified.

**Comment by hiker** [comment]
I have decided to implement the access type using a python Enum. That's new to python 3.4 (iirc), but has been backported to python 2.7 (and others). Now I tested all python installations at BOM, and they all work fine (except for one machine that has python 2.6.9 by default, but 2.7.6 is available there as well).
But at least on travis that does not work (not entirely sure why). There is a pip port (enum34) which we could try. But could I first get some feedback if you (@rupertford, @arporter, @TeranIvy , @sergisiso ) if you are ok with me using enums? I think enums are the much better data type compared with a string (no more lower(), and I think we can even remove most correctness tests since an AccessType MUST be valid, so we only need to check on reading a user function, not internally).

A simple test to see if it works for you:
```
python -c "import enum"
```
If you get error messages, then enums are not available ;)
Here a link to the code in question:
https://github.com/stfc/PSyclone/blob/df335838d09cceb0a6fa1319f729968ce2fe7560/src/psyclone/psyGen.py#L91

Some random example usage:
```
VALID_ACCESS_DESCRIPTOR_NAMES = [AccessType.READ, AccessType.WRITE, AccessType.READWRITE, AccessType.INC]
inc_args = self.unique_declarations(datatype, access=AccessType.INC)
if first_arg.access != AccessType.WRITE:
```
I am trying to get completely rid of the global variable names, but for now I am just trying to get all test cases to work again :)

**Comment by arporter** [comment]
IWFM under my local Py 2 and Py 3 environments and I really like the idea of not using strings to identify things so I vote "yes."

**Comment by hiker** [comment]
OK, I am mostly done, but I have one issue where I need some clarification for:
```
class DynArgDescriptor03(Descriptor):
    ''' This class captures the information specified in an argument
    descriptor.'''

    def __init__(self, arg_type):
        '''
        :param arg_type: dynamo0.3 argument type (scalar, field or operator)
        :type arg_type: :py:class:`psyclone.dynamo0p3.DynKernelArgument`
        #TODO: This seems to be wrong, it's FunctionVar!!
```
First question: the documentation describes the first argument to be DynKernelArgument, but from what I see in the tests it is FunctionVar ... is this only because of the tests and it is something else when you use PSyclone normally? Or is the documentation just wrong?

Then there is the test test_arg_descriptor_repr() in dynamo0p3_test.py:
```
    metadata = DynKernMetadata(ast, name="testkern_qr_type")
    field_descriptor = metadata.arg_descriptors[0]
    result = repr(field_descriptor)
    assert 'DynArgDescriptor03(arg_type(gh_real, gh_read))' \
        in result
```
The problem is the 'gh_read' in the output of repr(): The DynArgDescriptor03 class stores the FunctionVar argument just for outputting it in repr(). repr() relies on the str() output for this FunctionVar to assemble the expected output. With my changes, one of the children of this FunctionVar is the new AccessType class (and not a string anymore as it was previously). So it actually calls __str__ of the AccessType. Now in order to reproduce the same output, __str__ of AccessType has to return the API specific string (gh_read) ... which imho just feels wrong! I'd suggest that str(AccessType.READ) is just "READ", which then breaks this test.

So there are a few options:
1) is repr() actually needed? Removing it would be a great solution, and afaik there are not too many repr() calls in psyclone

2) Particularly this output seems kind of useless, since it's not proper Fortran. If it's for debugging only, using "READ" instead of gh_read would make sense - so we could adjust the test to expect DynArgDescriptor03(arg_type(gh_real, READ)) instead.
3) We redo __repr__ of DynArgDescriptor03 to output the right string without using the FuncArc argument at all, which (if you look at the __str__ function) is a bit involved, and results in a lot of code duplication between __str__ and __repr__.
4) We indeed let __str__ of AccessType return the API specific string (which I do atm, and it now passes all tests).

Any comments?

Next minor issue: the documentation states:

> Since configuration of these tests uses a pytest fixture, the tests must be run from the ``tests`` directory when requesting that compilation checks be performed

Can you quickly tell me what the problem is? I did a quick test and it seems to work. Main point is that I am adding a new directory psyclone/core/tests (since I moved AccessType into psyclone/core/access_type.py), so in order to run all tests we must be able to start the tests in psyclone (and not psyclone/tests).

**Comment by arporter** [comment]
First answer: I think the docstring is wrong.
Second answer: Rupert and I don't know why we've even got a repr so if you can delete it then that's great.
Third answer: I thought (and perhaps found) that py.test didn't pick-up the settings from `conftest.py` if it wasn't run from the `tests` directory. However, I just tried again now and it works fine. Looking at https://docs.pytest.org/en/2.7.3/plugins.html?highlight=re indicates that we should be OK when running from a directory above `psyclone/tests`. However, I've just tried from within `psyclone/tests/nemo` and that also appears to work and I don't understand why. Anyway, please could you delete that line from the docs?

**Comment by arporter** [comment]
I've read a bit more and it seems that it works because we have `test*/conftest.py`.

**Comment by hiker** [comment]
*grin* You just made my day with all those statements :) Removal of __repr__() indeed only broke the one test (which I then removed). The rest is WIP - thanks!!!

**Comment by arporter** [comment]
#371 is merged to master. Closing issue.
