### ISSUE TITLE
algorithm parsing for invoke kernel arguments fails for "- 1.0_r_def"

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#332]
As reported by @teranivy, the algorithm parsing fails with LFRic code with the following ...

Unsupported argument structure '<class 'fparser.two.Fortran2003.Level_2_Unary_Expr'>', value '- 1.0_r_def', kernel 'inc_aX_plus_Y(- 1.0_r_def, rhs_np1(igh_u), rhs_n(igh_u))'

**Comment by rupertford** [comment]
Created branch 332_parse_error

**Comment by arporter** [comment]
#333 has been merged so closing issue.
