### ISSUE TITLE
kernel and use statement match should be case insensitive

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#337]
The following should match ...

'''
"Parse Error: kernel call 'calc_dA_at_w2_kernel_type' must either be named in a use statement (found [... 'calc_da_at_w2_kernel_mod', ...]) or be a recognised built-in (...)]' for this API)"
'''

**Comment by rupertford** [comment]
Created branch 337_fix_kernel_use_error

**Comment by rupertford** [comment]
The problem is that use statement functions specified in an only list are stored with their original case and then matched with a kernel name in a case insensitive way. The simplest solution would be to store in lower case and match in lower case as the match is performed as a dictionary lookup (which does not lend itself to case insensitive matching).

**Comment by arporter** [comment]
#341 has been merged. Closing issue.
