### ISSUE TITLE
Better management of PSyIR operators

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#339]
Right now BinaryOperation and UnaryOperation are strings with the operator given by fparser.
This works well for simple operators: `+`, `-`, `*`, ... but will fail for other operators which are different for C and Fortran e.g. `.and.` <-> `&&`. There is also the issue of operators that just exist as functions on the other language e.g. `%` <-> `mod()`, `pow() of math.h` <-> `**`.

PSyIR needs a language-independent operator entity that makes PSyIR more robust and knows how to map C and Fortran operators into PSyIR and out to the target language.

**Comment by sergisiso** [comment]
Some intrinsic functions and built-ins can be handled as Unary/BinaryOperations, but Fortran, C math.h, and OpenCL built-ins have different functions and/or naming:
- https://gcc.gnu.org/onlinedocs/gfortran/Intrinsic-Procedures.html
- https://www.tutorialspoint.com/c_standard_library/math_h.htm
- https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/mathFunctions.html

**Comment by sergisiso** [comment]
NemoLite2D kernels have: sign, sin and sqrt Fortran intrinsics

**Comment by arporter** [comment]
@sergisiso The list of intrinsics I used in Habakkuk (which works for the majority of NEMO) is:

FORTRAN_INTRINSICS = ["SIGN", "SIN", "COS", "ACOS", "MAX", "MIN", "EXP",
                      "MOD", "NINT", "SUM", "ATAN", "TAN", "TANH", "SQRT",
                      "ABS", "LOG", "INT", "REAL", "DBLE", "PRESENT"]

**Comment by sergisiso** [comment]
The fparser PR#199 adds the Intrinsic_Type_Spec that will make this easier.

**Comment by arporter** [comment]
Of that list, the ones not yet implemented are: MAX, MIN, EXP, MOD, NINT, SUM, INT, DBLE, PRESENT.

EXP, INT, DBLE and PRESENT are unary.
MOD is binary.
MAX, MIN and SUM can take an arbitrary number of arguments >= 2.

**Comment by arporter** [comment]
Working with @rupertford's branch of fparser, I've added support for all of those apart from DBLE and PRESENT. Leaving PRESENT as a CodeBlock feels like the right thing to do at the minute. DBLE probably ought to map onto the binary form of REAL (which we don't yet support). The tests will fail on Travis as it won't have the right branch of fparser.

**Comment by arporter** [comment]
`DBLE(X)` is probably exactly equivalent to `REAL(X, KIND(1.0d0))`

**Comment by arporter** [comment]
When processing zdftmx.f90 I get a SUM() interpreted as an array access when it is the second argument to a MAX intrinsic.

We could also reduce code duplication by having an `Operation` base class which the Unary, Binary and Nary Operations could sub-class.

**Comment by arporter** [comment]
The fomer problem is a bug in the fparser branch - it's producing a `Part_Ref` node for the `sum`.

**Comment by arporter** [comment]
I still get a lot of CodeBlocks in zdftmx.f90 because of code like the following:

    ze_z = SUM( e1t(:,:) * e2t(:,:) * zav_tide(:,:,jk) * tmask_i(:,:) )

i.e. a SUM over the elements of the result of an element-wise product of various matrices.

**Comment by arporter** [comment]
An assignment involving an element-wise product of matrices does *not* result in a CodeBlock though.

**Comment by sergisiso** [comment]
I am closing this issue as PSyIR properly manages Operations now. The remaining issues are due to the Fortran array notation which is followed by #412
