### ISSUE TITLE
Split out Developers' Guide if ReadTheDocs supports it

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#340]
ReadTheDocs offers support for 'subprojects' and also allows the path to your conf.py to be specified. This issue will investigate whether this means we can have a separate Developers' Guide that is also hosted on ReadTheDocs.

**Comment by arporter** [comment]
It seems that subprojects are essentially separate git repos - I tried creating one and it just offered me a list of my GitHub projects.

**Comment by arporter** [comment]
Although RTD does let you specify the path to your conf.py file, it still assumes there's only one of these. I'm therefore investigating RTD's 'version' support with the hope that I can have a separate branch.

**Comment by arporter** [comment]
I can have another version associated with a different branch. However, there is no option to specify a different location for the conf.py file to use with a particular version - all versions are assumed to use a single conf.py file.

**Comment by arporter** [comment]
The best solution therefore seems to be to have multiple RTD projects. e.g. I've created 'PSyclone-dev' (https://psyclone-dev.readthedocs.io/en/developers_guide/) which just builds the documentation in doc/developer_guide. We could then move the existing doc into doc/user_guide perhaps. What do @rupertford, @sergisiso, @TeranIvy and @hiker think? Something to discuss on Wednesday perhaps.

**Comment by arporter** [comment]
#267 contains some developer documentation. We need to check whether we already have it and, if not, merge it in.

**Comment by arporter** [comment]
We have agreed we will have 'PSyclone-dev' and 'PSyclone-ref' on RTD. The latter will use doxygen.

**Comment by rupertford** [comment]
pr #380 has been merged to master so closing this issue.
