### ISSUE TITLE
[nemo] PSyIR does not distinguish DO WHILE loops

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#346]
The master version of PSyclone attempts to represent DO WHILE loops as a `NemoLoop` in the PSyIR. However, `NemoLoop` only represents DO loops with start, stop[, increment] control.
In this issue we shall ensure that DO WHILE loops are rejected (probably put into code blocks).

**Comment by arporter** [comment]
The code that triggered this problem is from crsdom.f90:

      DO jj = 1, jpj_crs
         DO ji = 1, jpi_crs
            jk = 0
            DO WHILE( tmask_crs(ji,jj,jk+1) > 0.)
               jk = jk + 1
            ENDDO
            mbathy_crs(ji,jj) = float( jk )
         ENDDO
      ENDDO

which is setting up the bathymetry for a coarse mesh.

**Comment by arporter** [comment]
Also, src/nemo/icbdyn.f90 has a loop over a linked-list of icebergs:

    DO WHILE (ASSOCIATED(berg))
      pt => berg % current_point

which updates the positions of all the current bergs.

**Comment by arporter** [comment]
obs_sort.f90 has:

    inner_loop : DO

            IF ( jchild > jn ) EXIT inner_loop
            IF ( jchild < jn ) THEN
               IF ( pval(kindx(jchild)) < pval(kindx(jchild+1)) ) THEN
                 jchild = jchild+1
               ENDIF
            ENDIF
            IF  ( pval(jt) < pval(kindx(jchild))) THEN
               kindx(jparent) = kindx(jchild)
               jparent = jchild
               jchild  = jchild*2
            ELSE 
               jchild = jn + 1 
            ENDIF

    END DO inner_loop

**Comment by arporter** [comment]
Created branch `346_do_while`

**Comment by arporter** [comment]
I had previously done some work to explicitly exclude DO WHILE loops. I've now brought in some of that from the old `nemo_derisk` branch.

**Comment by rupertford** [comment]
pr #357 is on master. Closing this issue.
