### ISSUE TITLE
Represent SELECT CASE in PSyIR

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#354]
SELECT statements are used in the NEMO code base but currently the PSyIR does not capture them.

**Comment by arporter** [comment]
The format of a select block is:

    SELECT CASE (selector)
       CASE (label-list-1)
          statements-1
       CASE (label-list-2)
          statements-2
         .............
       CASE DEFAULT
          statements-DEFAULT
    END SELECT

Note that `label-list` can use `:` to indicate a range of values. This is of course a Fortran-specific construct, akin to `switch` in C. In the PSyIR therefore, we should probably represent this as an IF block (with annotation so that we can recover the original form of the SELECT if required).

**Comment by arporter** [comment]
That being so, this Issue depends on @sergisiso's work on generalising If blocks in #347.

**Comment by sergisiso** [comment]
@arporter I agree the PSyIR If block should be enough with an annotation for reconstructing. I believe it is just a matter to add a new fparser2 node handler to the ASTProcessor. I will explore this solution in the current PR.

**Comment by sergisiso** [comment]
@arporter  Do Nemo CASE label-lists contain `:` ? There isn't any Range functionality in PSyIR yet.

**Comment by arporter** [comment]
Only a handful (for the configuration I'm looking at at the minute). A handful also do e.g. `CASE(1,3)`. For the moment we could leave anything we don't support in a CodeBlock?

**Comment by sergisiso** [comment]
I think I got the `:` functionality covered as well now. I don't need to expand the range at compile-time, it is just syntactic sugar for:
`Case (5:10)`  -> `if (selector >= 5 .and. selector <= 10) then `

**Comment by arporter** [comment]
#347 is on master now and has implemented support for Select blocks that do not have default clauses or Case statements with ranges. Any Select blocks that contain either of those things are left as CodeBlocks.
Presumably a `default` clause should be handled in exactly the same way as an `else` in an If block? That being so I'm happy to have a go at implementing this if @sergisiso agrees (and so long as it won't clash too badly with anyone else)?

**Comment by sergisiso** [comment]
@arporter I didn't attempt to implement the ranges or the default because the PR was already getting big and my priority was the IfBlock infrastructure but if you want to implement them my thoughts were:
- Ranges `lboudn:ubound` are just logical comparisons to `selector >= lbounds .and. selector <= ubound`
- `DEFAULT` can be found anywhere but should be placed at the deeper nested if (no other case is true).

I believe it won't clash to anybody else work as it is mostly extending the ASTProcessor Select_Construct Handler

**Comment by arporter** [comment]
Great, thanks @sergisiso and I quite understand about your prioritisation - it's the right thing to do.

**Comment by sergisiso** [comment]
#384 (support for case DEFAULT) is on master now. I will still keep this issue open for the `:` cases.

**Comment by arporter** [comment]
And now the cases we don't support are causing us to leave significant bits of NEMO running on the CPU because we can't transform it :-).
I shall therefore look at the `:` and `x,y` cases...

**Comment by rupertford** [comment]
pr #434 is now on master so closing this issue. Note, there are apparently still some issues with case statements (when a string is provided? However, this can be a separate issue.
