### ISSUE TITLE
Represent DO WHILE in the PSyIR

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#359]
#346 ensures that DO WHILE's are put into CodeBlocks for the NEMO API. However, we should probably capture them correctly in the PSyIR in case they are contain computationally-significant work.

**Comment by arporter** [comment]
Similarly, DO constructs with no loop control are also currently put into CodeBlocks (#805).

**Comment by sergisiso** [comment]
I think this should also close https://github.com/stfc/PSyclone/issues/1422

**Comment by nmnobre** [comment]
> I think this should also close #1422

As the special case `do while (.true.)`, right?

**Comment by nmnobre** [comment]
Oh, I was thinking of doing it the other way around, the unbounded loop is a `do while (.true.)` with presumably some exit condition in its body?

**Comment by arporter** [comment]
I think we should keep the structure as similar as possible to the existing `Loop`. i.e. have a child which is a Schedule and which may be obtained using a property named `body`.

**Comment by nmnobre** [comment]
> Oh, I was thinking of doing it the other way around, the unbounded loop is a `do while (.true.)` with presumably some exit condition in its body?

Either that, or it's an iterative loop with no stop condition, both work.
But I think it's `do while` that should have an entity of its own, we should _not_ create an unbounded loop node.
Specially if we want to envision support C/C++ where `while` loops also exist...
