### ISSUE TITLE
Refine identification of NEMO Kernels

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#361]
`NemoKern.match` currently does not check that that there are no subroutine calls in the candidate section of code. It also rejects implicit loops which seems a bit unnecessary and means we miss a lot of code when adding `!$ACC KERNELS` regions.

**Comment by arporter** [comment]
If I allow a `NemoKern` to contain implicit loops then this breaks the `NemoExplicitLoopTrans` tests. This is because after one application of this transformation to a nested implicit loop, the remaining implicit loop statement is now identified as a kernel (inside the newly-created, outer explicit loop).

**Comment by arporter** [comment]
Some of the code in `icecor.f90` that inspired this Issue is:

    SELECT CASE (kn)
    CASE (1)
      DO jj = 1, jpj
        DO ji = 1, jpi
          diag_heat(ji, jj) = - (SUM(e_i(ji, jj, 1 : nlay_i, :) - e_i_b(ji, jj, 1 : nlay_i, :)) + SUM(e_s(ji, jj, 1 : nlay_s, :) - e_s_b(ji, jj, 1 : nlay_s, :))) * r1_rdtice
          diag_sice(ji, jj) = SUM(sv_i(ji, jj, :) - sv_i_b(ji, jj, :)) * rhoi * r1_rdtice
          diag_vice(ji, jj) = SUM(v_i(ji, jj, :) - v_i_b(ji, jj, :)) * rhoi * r1_rdtice
          diag_vsnw(ji, jj) = SUM(v_s(ji, jj, :) - v_s_b(ji, jj, :)) * rhos * r1_rdtice
        END DO
      END DO
      zafx(:, :) = SUM(a_i(:, :, :) - a_i_b(:, :, :), dim = 3) * r1_rdtice
      afx_tot(:, :) = zafx(:, :)
      IF (iom_use('afxdyn')) CALL iom_put('afxdyn', zafx(:, :))
    CASE (2)
      ...

where, on closer inspection, the explicit loop over `ji` and `jj` does *not* actually contain any implicit loops - the `:` are for the arguments to the `SUM` intrinsic. Therefore, the problem in this case is that the code analysis is too simplistic (it currently just checks the parse tree for `Subscript_Triplet` members.

**Comment by arporter** [comment]
If I use the PSyIR instead of the parse tree then I already have more sophisticated ways of checking for implicit loops. This is a fairly simple change to make but has consequences - notably the Schedule in some of the tests no longer has the expected structure. I also need to update the `NemoKern` constructor so that it will take an existing PSyIR sub-tree as argument.

**Comment by arporter** [comment]
Since the PSyIR does not currently handle Fortran derived types, any statements involving these are put into code blocks and we then refuse to create a `NemoKern` for such a region. This is a step back from where we are at the minute (where we support reads from derived types in ACC regions) but is possibly more consistent with getting things working with the PGI compiler and managed memory where derived types seem to cause problems.

**Comment by arporter** [comment]
Since the PSyIR does not currently handle Fortran derived types, any statements involving these are put into code blocks and we then refuse to create a `NemoKern` for such a region. This is a step back from where we are at the minute (where we support reads from derived types in ACC regions) but is possibly more consistent with getting things working with the PGI compiler and managed memory where derived types seem to cause problems.

**Comment by rupertford** [comment]
#365 has been merged to master. Closing this issue.
