### ISSUE TITLE
Represent Fortran derived types in the PSyIR

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#363]
Some sections of NEMO (notably those dealing with sea ice and ice bergs) make use of Fortran derived types. These are currently not handled by the PSyIR and are left as CodeBlocks which then means we can't have Kernels that contain derived types.

**Comment by arporter** [comment]
I can follow what has been described here: https://psyclone-dev.readthedocs.io/en/latest/psyir_symbols.html#datatypes

When processing existing code we will often encounter variables that are declared as being of a certain derived type. At that point we will know that there is such a derived type but not what it consists of (because it will typically be defined in some other Container).

**Comment by arporter** [comment]
Brought Rupert, Sergi and Joerg into the discussion (that I'm currently having with myself) in case they spot anything.

**Comment by arporter** [comment]
Obviously, one can have an array of structures/derived types. Currently the `ArrayType` constructor expects the supplied datatype to have `intrinsic` and `precision` attributes which a derived type won't. However, support for arrays of structures might be a separate Issue - I'll see how it goes.

**Comment by sergisiso** [comment]
>  At that point we will know that there is such a derived type but not what it consists of

Would then declaring it as 'DeferredType' be enough or there is some information that it would miss.

> constructor expects the supplied datatype to have intrinsic and precision attributes which a derived type won't.

I think that was to simplify the modifications on existing code at the time, but I agree an ArrayType should support any kind of DataType as its element.

**Comment by arporter** [comment]
> > At that point we will know that there is such a derived type but not what it consists of
> 
> Would then declaring it as 'DeferredType' be enough or there is some information that it would miss.
> 
Yes, I was wondering that - I'll have a look and see.

**Comment by arporter** [comment]
A derived type isn't just a list of types (and routines), it contains *named* entities, e.g.:

    type :: my_type
      integer :: flag
      real :: g
    end type my_type

contains a member named "flag" that is of type integer. This is precisely the type of information that is captured in the SymbolTable. So, does it make sense for a StructureType to have its own SymbolTable?

**Comment by arporter** [comment]
The scope in which `my_type` is declared must have a symbol for it. I think this means we need a new type of symbol, `TypeSymbol` perhaps?

**Comment by arporter** [comment]
The trouble with giving a `StructureType` its own `SymbolTable` is that this doesn't fit with the existing hierarchy. Currently a `SymbolTable` is typically associated with a `Node` (which may be provided via an optional argument to its constructor). The `SymbolTable.lookup()` method uses `SymbolTable._all_symbols` which uses `self.node.parent.scope.symbol_table` to get the next `SymbolTable` in the hierarchy (`if self.node is not None`). When dealing with a derived type that itself contains components of derived type we need still need to check the hierarchy of `SymbolTable`s but it has to be accessed in a different way.

**Comment by arporter** [comment]
For now I've added a new `parent` property to `SymbolTable` which *first* checks whether the current table is nested inside another one (as it will be for the definition of a derived type) and then, whether there's a parent Node with a table. This enables me to use all of the existing functionality fairly transparently which is good. I also had to extend `find_or_create_symbol()` so that I could tell it what kind of Symbol to create if it failed to find one (this fixes #876 incidentally). In order to support updating of existing symbols (as more information becomes available), I also extended it to return the SymbolTable in which it had found the symbol. This then allows the symbol to be replaced by one of a more specific type if applicable.

Having said all that, I'm still not totally convinced that what I've done is good. I need to think about the issue of SymbolTable hierarchies a bit more.

**Comment by arporter** [comment]
Currently, `_process_use_stmts` always creates a `DataSymbol` for each name specified in a `use xxx, only: yyy" statement. However, that's not right because sometimes `yyy` will actually be a routine or derived type. If I change it so that it creates a `Symbol` instead then I hit problems because only `DataSymbol` has the `resolve_deferred` method (which searches for the associated module, parses it and replaces the `DeferredType()` of the symbol with the correct details). To do this with a Symbol instead, I think I'd have to create a new Symbol of the correct class and then delete the original one. Obviously that would have to be e.g. a static method as it has to delete an instance and then create a new one.

**Comment by arporter** [comment]
Currently a the `Reference` constructor always takes a `Symbol` argument - the thing to which it refers. If we have a derived type:

    type :: my_type
        integer :: count
    end type my_type

    type(my_type) :: var

    var%count = 1

then we would have a `TypeSymbol` named "my_type". This would be of type `StructureType`. We would also have a `DataSymbol` named "var" which would be of the type associated with the `TypeSymbol` "my_type". In common with standard Symbols, we would have to support 'lazy evaluation' of this type - e.g. if the TypeSymbol is imported from some other container.
The question is, how would we capture that? Would the type of `var` then be a `Reference` to the `TypeSymbol`? Resolving that would then be a matter of resolving the type symbol and then copying its type (a StructureType) over to the definition of the `var` symbol.

**Comment by arporter** [comment]
We also need to decide on how references to members of a derived type will work. In the above example we have `var%count = 1` which is a reference to the `count` member of the `var` variable. `var` is represented by a `DataSymbol` of type `StructureType`. Ideally I think we would do something like `Reference(count)` where `count` would be some object that knew it belonged to the `var` DataSymbol. Maybe we need a new concept like `ComponentSymbol` which would have a `parent` Symbol. We would keep going up parents until we hit a `DataSymbol` and that would give us the full reference to the given data component.

**Comment by arporter** [comment]
We also need to think about the Fortran frontend. If we encounter some code, e.g.:

    use my_types_mod
    type(my_type) :: obj
    obj%grid%nx = 10

then we will be able to create a `DataSymbol` named "obj" and that will have a type defined by the "my_type" `TypeSymbol` which itself will be of `DeferredType` because it's not locally defined. However, we then encounter the assignment statement and need to create a reference to `obj%grid%nx`. At this point we know that `obj` must be of `StructureType` and that that type must contain a component named `grid`. Similarly, we know that the `grid` component must also be of `StructureType` and contains a component named `nx`. I think we have two options:
 1. Resolve the definition of `my_type` (and any types it contains) and then create a reference;
 2. Somehow create a partial type with the information that we have but don't do any resolving.

**Comment by arporter** [comment]
As pointed out by @sergisiso, data types do not have any storage associated with them - they are just a concept. In contrast, DataSymbols do have storage associated with them. I'm then not sure what we do about a `TypeSymbol`. I think it has to be a symbol because it lives in the symbol table but it is really just a name/reference for a `StructureType`. Similarly, a `StructureType` defines a list of names, types and accessibilities but these are not actually symbols because they do not have storage associated with them.

**Comment by arporter** [comment]
So a Symbol (a `StructureSymbol`?) representing a derived type contains other Symbols for its components, as defined by the names and types in the associated `StructureType`. `StructureSymbol.components[name].components[2nd_name]`

**Comment by arporter** [comment]
Perhaps the 'child' symbols should be `ComponentSymbol` - a subclass of `Symbol` with the addition of a `parent` property.

**Comment by arporter** [comment]
I'm taking this approach on a new `363_component_types` branch.

**Comment by sergisiso** [comment]
PR #911 with support for derived types is now merged, but I understand that the back-end support is still needed in order to resolve this issue.

**Comment by arporter** [comment]
If I have some Fortran:

    type(fld_type) :: my_fld
    type(fld_type, dimension(3) :: fld_bundle
    my_fld%data(:) = 0.0
    fld_bundle(1)%data(2) = -1.0

then, in my current implementation, I will have two `ComponentSymbols` with name `data` - one belonging to the `my_fld` symbol and one to the `fld_bundle` symbol. I think that's correct because those different symbols *are* representing different regions of memory.

**Comment by sergisiso** [comment]
PR #1021 has added PSyIR derived type accessors support, but there are some edge cases and TODOs that  need to be fixed to close this issue.

**Comment by arporter** [comment]
Started work on frontend support in `363_dtype_frontend`.

**Comment by arporter** [comment]
Have realised that ArrayOfStructuresReference and probably StructureReference require the supplied Symbol to be a DataSymbol. However, if it is being imported via a Fortran USE then it is only a Symbol because we don't know what type it is. I've added a TODO for now.

**Comment by sergisiso** [comment]
> Have realised that ArrayOfStructuresReference and probably StructureReference require the supplied Symbol to be a DataSymbol. However, if it is being imported via a Fortran USE then it is only a Symbol because we don't know what type it is. I've added a TODO for now.

#1042 May help with this

**Comment by arporter** [comment]
> > Have realised that ArrayOfStructuresReference and probably StructureReference require the supplied Symbol to be a DataSymbol. However, if it is being imported via a Fortran USE then it is only a Symbol because we don't know what type it is. I've added a TODO for now.
> 
> #1042 May help with this

Yes, I was wondering that over lunch :-)

**Comment by sergisiso** [comment]
PR #1053 added frontend support and semantic navigation. I don't close the issue because there are 4 TODOs left but derived types support is almost complete now.

**Comment by arporter** [comment]
Most of the remaining TODOs were related to loop bounds in GOcean. Fixing these went well :-) However, doing that now causes other tests to fail because they use dependence analysis and that's not implemented for structures yet (#1028). I started to think about doing that here but decided it's probably best done as part of the move to use Symbols instead of strings.

**Comment by arporter** [comment]
The failing tests are those that add OMP to GOcean without constant loop bounds. The loop bounds then contain structure references and the `psyGen._get_private_list()` (which uses `reference_accesses`) then fails.
