### ISSUE TITLE
Re-structure class hierarchy for Kernels

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#364]
Currently we have:

    Node <-- Call <-- Kern <-- NemoKern
                 \        \____DynKern
                  \ BuiltIn
                        
but actually, all of our current `BuiltIn`s are implemented in-line and not as calls. Similarly, `NemoKern`s are currently in-line code. Therefore we propose to re-structure like so:

    Node <-- Kern <--BuiltIn
                 \___CodedKern

where `Kern` now has an attribute that captures whether or not it is in-lined or a call.

**Comment by TeranIvy** [comment]
`CodedKern` is a bit confusing name for what is essentially still a subroutine **call** and not really "coding" Kernel contents. Kernel Stub and Kernel Generation from #393 would be good examples of "coding" (adding content) to a Kernel subroutine.

**Comment by arporter** [comment]
@TeranIvy `CodedKern` is so named because it is a kernel that is implemented in code. Whether it is called or is in-line is an attribute (and may change as the result of transformations. Does that make sense?

**Comment by arporter** [comment]
All `dynamo0p3_*` tests pass now.
