### ISSUE TITLE
Re-create a Fortran Kernel from the PSyIR

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#368]
At the moment we are able to parse Fortran kernels and create PSyIR but are not able to create Fortran kernels from PSyIR.

Given that the PSyIR will support more than one "back-end" language (currently C and OpenCl are being developed), I think it makes sense for the translation to be kept separate from the PSyIR (which would mean modifying the current C and OpenCl work at some point).

One possibility would be to keep the Fortran Kernel -> PSyIR with the PSyIR -> Fortran Kernel as one would assume that they would have a similar structure.

Another would be to follow the famed visitor pattern solely for the PSyIR -> Fortran Kernel translation.

Lastly, the PSyIR -> Fortran Kernel translation should support the inclusion of Fortran code blocks.

Any thoughts @sergisiso?

**Comment by sergisiso** [comment]
I favour separate frontend and backend implementations with the visitor pattern in some shape. Something like:

- PSyIR.py (PSyIR definition and functionality)
- frontends/fparser2ASTProcessor.py (fparser2 front-end already exist just separate to different file)
- backends/FortranGenerator.py (visitor with current gen_code and f2pygen)
- backends/Cgenerator (current gen_c_code)
- backends/OpenCLGenerator(inherits from CGenerator, maybe 2 implementations: data-parallel, control-flow parallel)

fparser2 frontend and the C and OpenCL backends are just a reorganization of existing code.

**Comment by rupertford** [comment]
Created branch 368_fortran_kernel_gen
