### ISSUE TITLE
Represent constants in the PSyIR

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#369]
One kernel optimisation that has been shown to improve performance (by being tested manually) is to make the number of degrees of freedom constant in a kernel. This allows the compiler to see the size of the loop bounds (which are small) and then unroll rather than vectorise - or at least do a better job.

In order to do this in PSyclone we need to be able to create a constant in the PSyIR. This is not currently supported.

I think a natural place to add this would be the symbol table.

Any thoughts @sergisiso?

**Comment by sergisiso** [comment]
I agree the optimization is probably useful. I will just add some ideas:

- An alternative implementation would be to not modify the current PSyIR (no awareness of constants) and just create a transformation that change all lhs References with a certain name to a Literals with certain value. (also check there are no rhs references to the symbol)
- In C/C++ a constant (const keyword) is a runtime immutable reference and not a compile-time fixed value. We should define what we mean in PSyclone.

**Comment by rupertford** [comment]
Created branch 369_PSyIR_constants

**Comment by rupertford** [comment]
> I agree the optimization is probably useful. I will just add some ideas:
> 
> * An alternative implementation would be to not modify the current PSyIR (no awareness of constants) and just create a transformation that change all lhs References with a certain name to a Literals with certain value. (also check there are no rhs references to the symbol)
> * In C/C++ a constant (const keyword) is a runtime immutable reference and not a compile-time fixed value. We should define what we mean in PSyclone.

I agree that we could replace the variable with literals. However that would mean parsing all of the kernel and we do not do that yet so I will stick with modifying the symbol table for the moment as it is more robust.

I agree that we need to document what we mean by constant, parameter, immutable etc. or whatever other word we use to describe something with a fixed known value. In my view, constant is the best generic word.
