### ISSUE TITLE
[LFRic] Write modified kernel code to file

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#373]
Once it is possible to modify LFRic kernels they need to be written to file. The hope is to be able to re-use code that already does this for the gocean api.

**Comment by rupertford** [comment]
It is now possible to modify LFRic kernels so I need to be able to write the modified kernels out to file.

**Comment by rupertford** [comment]
Created branch 373_write_lfric_kernels

**Comment by arporter** [comment]
#441 has been merged.
