### ISSUE TITLE
[PSyIR] needs to capture Fortran kind declaration information

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#375]
Fortran declarations can include the `kind` attribute, for example `integer(kind=i_def) :: idx`. This information needs to be captured in the PSyIR somehow so that the `kind` information can be reproduced if deparsing from PSyIR back to Fortran.

**Comment by arporter** [comment]
Currently the Fortran back-end to the PSyIR is hardcoded to insert `use constants_mod, only: r_def, i_def` but this is LFRic specific. This means that kernel generation does not work for the GOcean API which does not have `constants_mod`.

**Comment by arporter** [comment]
We've agreed that a Symbol needs a new size property that can be either a value, a reference (to a Symbol holding the KIND parameter) or None if it is a default type (e.g. real with no KIND specified).

**Comment by arporter** [comment]
For e.g. `real(kind=wp) :: var` we get a `Fortran2003.Kind_Selector`:

    (Pdb) type_spec.items[1].items
    ('(', Name('wp'), ')')

**Comment by arporter** [comment]
This means that the new `precision` argument that I've added to the `Symbol` constructor can be either a reference to another Symbol, an integer or a string (label).

**Comment by rupertford** [comment]
Note that this PR #563 does not complete this issue as

1) the backends do not yet generate the appropriate code.
2) the following form of input is not yet captured rtime = real(istep,go_wp) * rdt.

Both of the above reference this issue in the source code. Note, the first should definitely be fixed before closing this issue, however the second is probably a separate issue as it is not to do with declaring data.

**Comment by rupertford** [comment]
PR #563 is on master so closing this issue.
