### ISSUE TITLE
Using AutoAPI to generate documentation

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#390]
AutoAPI is a Sphinx plugin that claims to enable automatic generation of API documentation.
However, it relies on the `__all__` property of each module being populated with the names of the public entities. I'm therefore not sure what advantage it gives over us simply writing an rst file containing a list of the classes we want to document. Also, I cannot work out how to reference an existing html file from within a rst source file. (I was hoping to generate both the doxygen and AutoAPI output and have a link between them.)

**Comment by arporter** [comment]
After some sleep and some more faffing, I've managed to get what I want:

https://psyclone-ref.readthedocs.io/en/autoapi_ref_guide/

In theory Sphinx can put in a link to an existing html file but I could not for the life of me get the path specified correctly so that it would find it. Instead I've opted for the `.. raw::html` directive and stuck in the raw html link to the Doxygen-generated documentation. I'm sure there's a better way and if I find it I'll use it...

**Comment by arporter** [comment]
In fact, maybe the `html_additional_pages` Sphinx configuration option (https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path) is what I want?

**Comment by arporter** [comment]
Nope, that doesn't work - it expects templated files (using Jinja) and so, although it does create me a page, it's broken and doesn't contain much of the Doxygen-generated content.

**Comment by arporter** [comment]
I've smartened up the output a bit (see link above). The question is, are we (@TeranIvy, @rupertford, @sergisiso, @hiker) happy to manually populate `__all__` lists in each of our source files? It's possible we could auto-generate these lists (c.f. the way fparser2 works) as long as that doesn't have other consequences - I don't know what, if anything, uses the `__all__` list in Python.

**Comment by sergisiso** [comment]
@arporter AutoAPI reference guide is now on master, do you want to close the issue or wait until we fill the `__all__` fields?

**Comment by arporter** [comment]
I'll close - we can do a new one for the `__all__` fields and it feels good to close an issue :-)
