### ISSUE TITLE
Crash in Nemo API when adding openmp directives around two loops in if statement

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#396]
Complicated title. In short, I am adding OpenMP to the two loops in a code like:
```
 IF (1 == 1) THEN
    DO jj = 1, m
      DO ji = 1, n
        a1(ji, jj) = c(ji, jj)
      END DO
    END DO
    DO jj = 1, m
      DO ji = 1, n
        a2(ji, jj) = c(ji, jj)
      END DO
    END DO
  END IF
```
If a script uses OMPParallelTrans around both loops, trying to create Fortran code causes a crash.

The modified tree looks fine:
```
InvokeSchedule[]
    If[]
        BinaryOperation[operator:'EQ']
            Literal[value:'1']
            Literal[value:'1']
        Schedule[]
            Directive[OMP parallel]
                Loop[type='lat',field_space='None',it_space='None']
                    Loop[type='lon',field_space='None',it_space='None']
                        KernCall[]
            Directive[OMP parallel]
                Loop[type='lat',field_space='None',it_space='None']
                    Loop[type='lon',field_space='None',it_space='None']
                        KernCall[]
...

E       ValueError: Item 'DO jj = 1, m
E         DO ji = 1, n
E           a1(ji, jj) = c(ji, jj)
E         END DO
E       END DO' not found in list: [Nonlabel_Do_Stmt('DO', Loop_Control(None, (Name('jj'), [Int_Literal_Constant('1', None), Name('m')]), None)), Block_Nonlabel_Do_Construct(Nonlabel_Do_Stmt('DO', Loop_Control(None, (Name('ji'), [Int_Literal_Constant('1', None), Name('n')]), None)), Assignment_Stmt(Part_Ref(Name('a1'), Section_Subscript_List(',', (Name('ji'), Name('jj')))), '=', Part_Ref(Name('c'), Section_Subscript_List(',', (Name('ji'), Name('jj'))))), End_Do_Stmt('DO', None)), End_Do_Stmt('DO', None)]

../psyGen.py:151: ValueError

```

x-failing test is added in my branch nemo_two_loops_in_if.
I have started to debug this, something goes wrong in the line 2734 of psyGen.py:
```
        parent = self._parent.ast
        while parent:
            if hasattr(parent, "content") and \
               parent is not self.children[0].ast:
                break
            parent = parent._parent
```
For the first loop, the while loop is executed twice, while for the second omp-directive the loop is only executed once (which then means it can't find a start index). I am not yet sure what goes wrong - if the first omp+loop subtree creates an incorrect tree, ... 

I am happy to debug this, but if anyone has an idea or suggestion (or even better ... a fix), feel free to take this ticket :)

**Comment by hiker** [comment]
I think I understand the problem now - unfortunately I am not sure about the best solution. Note that I am happy for you all to ignore this issue, it might be easier to discuss this when I am on site! But I need to document the root cause, so that we don't have to start from scratch again.

The broken code in question has a comment referring to fparser #105 for a proper solution, but I don't think this is related to this issue(it would get rid of the if hasattr(parent,"content") test potentially, but I don't think this would affect the issue at all.).
 
The fparser tree for the code looks like this:
```
If_Construct
   If_Then_Statement
   Block_Nonlabel_Do_Construct
      Nonlabel_Do_Stmt
      Block_Nonlabel_Do_Construct
         ! More for inner I loop
      End_Do_Stmt
   Block_Nonlabel_Do_Construct
      Nonlabel_Do_Stmt
      Block_Nonlabel_Do_Construct
         ! More for inner I loop
      End_Do_Stmt
   End_If_Stmt
```
The corresponding PSyIR after inserting the two omp directives is:
```
IfBlock
   Schedule
      OmpParallelDoDirective
         NemoLoop(j)
            ...
      OmpParallelDoDirective
         NemoLoop(j)
            ...
```
The Schedule node has ``ast`` as a link to the first ``Block_Nonlabel_Do_Construct`` of the fparser tree(1), and ``ast_end`` is the link to the second (last) last ``Block_Nonlabel_Do_Construct``.

The omp directives are inserted into the fparser tree into the ``If_Construct`` node, e.g. after the first omp directive is inserted it will look like this:
```
If_Construct
   If_Then_Statement
   OMP Do
   Block_Nonlabel_Do_Construct
      ...
   OMP EndDo
   Block_Nonlabel_Do_Construct
      ...
   End_If_Stmt
```
In order to find the ``If_Construct`` node into which the two omp directives need to be inserted, the following code is used in psyGen's ``OMPParallelDoDirective.update()`` function:
```
parent = self._parent.ast
while parent:
    if hasattr(parent, "content") and \
       parent is not self.children[0].ast:
        break
    parent = parent._parent
```
So for the OMP directive of the first do loop ``parent`` is initialised with the ``Block_Nonlabel_Do_Construct`` node for the first loop (parent of OMP is the ``Schedule`` node, then see (1)). The second part of the if statement fails, since then self(i.e.OmpParallelDoDirective).children[0] (which is the outer Do loop) is the same as parent. As a result, ``parent=parent._parent`` 'goes up' in the tree, becomes the ``If_Construct``, and the loop finishes on this second iteration (since the ``If_Construct`` is not the ``Block_Nonlabel_Do_Construct`` for the first loop anymore). ``Parent`` now contains the ``If_Construct`` node. Then the OMP do directives are inserted correctly into this ``If_Construct`` node.

Now when the same code is executed for the second do loop, this does not work anymore:
``parent`` is initialised as ``self._parent.ast``, which is the ``Block_Nonlabel_Do_Construct`` of the first(!) node (see (1) ... the parent of the second OMP directive is ``Schedule``), while ``self`` is the  ``Block_Nonlabel_Do_Construct`` of the second(!) loop. The while loop immediately aborts since ``parent`` is not ``self.children[0].ast``. Now we have that ``parent`` is the ``Block_Nonlabel_Do_Construct`` of the first node, and then the code aborts (when trying to find the ``Block_Nonlabel_Do_Construct`` for the second loop, in the ``Block_Nonlabel_Do_Construct`` of the first loop ... instead of looking for that as intended in the parent which is the ``If_Construct``).

Hope that can be followed somehow.

At this stage I see a few solutions, I just don't know about other plans you have to decide which one is best:
1) instead of testing if ``parent`` is self.children[0].ast, we need to check if ``parent`` is ANY of the children of its parent. So we avoid the problem that the AST of the OMP parent (the Schedule) only points to the first node, we would test all nodes of the schedule, including the first and second ``Block_Nonlabel_Do_Construct.`` This sounds a bit messy to explain, feels a bit like a band aid instead of a proper solution :crying_cat_face: 
2) I don't know if there is a way to get a list of all fparser nodes between ``ast`` and ``ast_end`` (likely this will basically have to go up the fparser tree, get its content ... which is the same as solution 1) above), or maybe instead of ``ast`` and ``ast_end`` we maintain an ``ast_list`` or so?? This sounds even messier than 1) :crying_cat_face: 
3) Instead of inserting the OMP nodes into the parent fparser node (i.e. the ``If_Construct``), we insert the directives into the ``Block_Nonlabel_Do_Construct``. E.g. after inserting the OMP nodes it would look like this:
```
If_Construct
   If_Then_Statement
   Block_Nonlabel_Do_Construct
      OMP Do
      ...
      OMP EndDo
   Block_Nonlabel_Do_Construct
      ...
   End_If_Stmt

```

I can't really say what is the best approach (while the third suggestion sounds nice,it might interfere with what else is happening), one that would also align with future plans, but any comments would be appreciated. At least I now better understand the connection between PSyIR and AST :smiley: 

Note that this issue is not urgent (I can just change my source code to avoid the problem), and it might be easier to discuss this next week when I am on site (and bring my scribbled diagram showing the trees and pointers between them:) ), it might be easier to explain than following the details here.

**Comment by arporter** [comment]
We plan to do-away with this linking between the PSyIR and Parse Tree altogether once we have the Fortran backend for the PSyIR working (#376 plus others). We only have this linking at the minute because we rely on the fparser2 Parse Tree de-parser to generate Fortran in the final step. As you say, it is complicated and therefore error prone. We need to talk to @rupertford about how long it's likely to be before the Fortran backend is functional enough for NEMO/ROMS. If that's going to be too long then I think your first solution is the best - as you say in 2), there's no easy way to get the list of Parse Tree nodes between the start and end points.

**Comment by arporter** [comment]
If @hiker is happy, I think this can be closed now as we've done away with the fparser2 tree manipulation (hurrah).

**Comment by hiker** [comment]
Wow - we should celebrate. I've dug out my old ROMS version, remove the work-arounds I had in place, and it all worked!!
Thanks!
