### ISSUE TITLE
Dependency Analysis

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#399]
I am looking at dependency analysis of (nemo) kernels next, to make sure OMP will only be used for loops that can be parallelised. I looked at the existing DAG for kernels, but this seems to be on a completely different level (between kernels, not within one kernel), so not really related to this.

1) Is there any other work planned or in progress that would work on a kernel dependency analysis that I should be aware of or wait for?

2) I can see at least three different ways of implementing this: 
    a) as part of fparser
    b) as part of PSyclone on the fparser tree
    c) as part of PSyclone, on the PSyIR (if there is enough info, which I still would have to check)
   Any preferred/recommended solution?

Ideally this would allow us to verify (or even created) e.g. access information (at least in gocean1) kernels, maybe it could even be extended to verify (or create) stencil information.

@rupert, @arporter @sergisiso @TeranIvy - it would be great if I could get some feedback from one of you soonish, since I intend to start working on this before I arrive :)

**Comment by sergisiso** [comment]
@hiker when I start optimizing for better performance on the NemoLite2D OpenCL back-end for FPGAs (I expect to start this soon), I don't believe that simply modifying the OpenCL back-end will be enough, and I suspect I will need a proper dependency analysis of the kernel's PSyIR.

A simple way to have this analysis would be to extend the `Node` `forward/backward_dependence` functionality to look for references in the PSyIR, but this has some limitations. I think it just works for sibling nodes now and we would need a way to promote up and down the AST the data-flow information.

Another possibility would be to implement some PSyIR inter-node structure that facilitates the analysis (e.g. https://github.com/flang-compiler/f18/blob/master/documentation/ControlFlowGraph.md)

I am not sure what is the best solution for our needs yet.

**Comment by arporter** [comment]
My view is that this should be done in the PSyIR although, as Sergi says, it is probably not quite there yet in terms of necessary functionality. In general we're trying to do as much as possible in the PSyIR and are moving away from dealing with the fparser parse tree directly. (Incidentally, I did dependence analysis using the Parse Tree in Habakkuk (https://github.com/arporter/habakkuk) but I/someone will probably re-implement this using the PSyIR.)

**Comment by hiker** [comment]
Thanks Sergi (and sorry for the delay) - good link :) OK, PSyIR it is then :)

**Comment by TeranIvy** [comment]
Is the `Node` class is then to be used for Nodes through all functional levels of code (Alg, Psy, Kern, depending on the API)? If so, it would be worth thinking whether it would be good to subclass `Node` for different functional levels it needs to operate on and extend/modify methods in the subclasses.

**Comment by hiker** [comment]
Fixed with pull request #485 .
