### ISSUE TITLE
Add scripts for processing NEMO

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#402]
I need some revision control for the (not so simple) scripts being developed for NEMO. This issue and associated branch is for them.

**Comment by arporter** [comment]
I want to make the transformation script more sophisticated so that it will add `!$acc routine` directives to *functions* that contain no recognised looping structures. However, the `ACCRoutineTrans` does not support the NEMO API - it expects to be passed a `Kern` object while, in the NEMO API as it stands, we want to add this directive to the 'PSy layer.'

**Comment by arporter** [comment]
The current implementation of `ACCRoutineTrans` makes *no* use of the PSyIR - it gets the fparser Parse Tree of the kernel and modifies it directly. This is because it predates our use of the PSyIR to describe kernel code and also, the PSyIR does not yet represent directives. Once it does *and* we have a fully-functioning Fortran backend, then this transformation should be re-written to manipulate the PSyIR and not the Parse Tree.

**Comment by arporter** [comment]
I've managed to generalise what was already there to work with the NEMO API too. It's not ideal but will do until we reach the PSyIR panacea described in my previous comment (and for which I need to create an Issue). All that remains is to alter the transformation script to only put KERNELS regions around loops of recognised types.

**Comment by arporter** [comment]
Unfortunately, the updated code now expects either a `NemoInvoke` or a `Kern` which would indicate that my current solution is a fudge. On chatting with Rupert I've realised that the problem is actually that we end up with Function calls within OpenACC regions. This happens because fparser thinks those calls are array accesses. So, the solution is actually to identify those function calls. Eventually this will be fixed by extending fparser but, for the moment, it may be sufficient to workaround this limitation in my transformation scripts.

**Comment by rupertford** [comment]
PR #1109 is now on master. Closing this issue.
