### ISSUE TITLE
Where are the if-statements?

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#409]
I am trying to add a 'schedule=dynamic' to an 'omp do' directive if there is an if-statement inside a nested loop. This works in one case, but not in the other. Reason is the PSyIR in the two cases. When it works as expected:
```
     DO np=Ns,Ne
        DO mp=Ms,Me
          Ipos(mp,np)=IJspv
          Jpos(mp,np)=IJspv
          IF (rectangular) THEN
            foundi=.FALSE.
-->
NemoLoop
  NemoLoop
    list [Assignment, Assignment, ...]
```
and when it doesn't work:
```
     DO j=Jstr,JendR
        DO i=Istr,IendR
          IF ((wetdry(i-1,j  ).gt.0.5_r8).and. (wetdry(i  ,j  ).gt.0.5_r8).and.(wetdry(i-1,j-1).gt.0.5_r8).and.(wetdry(i  ,j-1).gt.0.5_r8)) THEN
            pmask_wet(i,j)=1.0_r8
          else if ...
-->
NemoLoop
  NemoLoop
    NemoKern
      --> no children, 
          if-statements are in: self._kern_schedule, not in self._children
```
At first I thought the reason was that in the first loop the loop type was not recognised (loop indices np and mp were not defined). But even if I add them to my config file, it still works.

Any idea why those loops result in different PSyIR representations?

**Comment by arporter** [comment]
This is a deliberate design decision. Kernels appear as leaves in the PSyIR tree but then, as you say, have their own Schedule that can be walked.

**Comment by hiker** [comment]
Confirmed that pull request #559 will fix this. Since #483 has the same root cause as this issue, I'll close this as duplicate of #483.
