### ISSUE TITLE
builtins do not allow arguments with loop indexing

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#41]
It has been reported that arguments to builtins which have an index e.g. a(k) cause the parser to fail. This should not be the case as kernel arguments support this feature. It therefore sounds like there is a bug somewhere. This issue is raised to check what the problem is and to fix it.

**Comment by rupertford** [comment]
I ran a simple test and that seemed to work OK so I've modified part of the original example code that was reported to be failing and this seems to work OK.

The original code snippet looks like:

```
        do k = 1, j
          !PSY call invoke ( inner_prod(v(k),w,h(k,j)))
          call invoke_inner_prod( v(k), w, h(k,j)  )
          !PSY call invoke ( axpy(-h(k,j),v(k),w,w))
          call invoke_axpy( -h(k,j), v(k), w, w )
        end do
        !PSY call invoke ( inner_prod(w,w,err))
        call invoke_inner_prod( w, w, err  )
        h(j+1,j) = sqrt( err )
        if( j < GCRk ) then
          !PSY call invoke ( copy_scaled_field_data(1.0_r_def/h(j+1,j),w,v(j+1)))
          call invoke_copy_scaled_field_data(1.0_r_def/h(j+1,j), w, v(j+1))
        end if
      end do
```

The modified code snippet looks like ...

```
        do k = 1, j
          call invoke ( inner_product(v(k),w,h(k,j)))
	  minus_h = -h(k,j)
          call invoke ( inc_axpy(minus_h,v(k),w))
        end do
        call invoke ( inner_self_product(w,err))
        h(j+1,j) = sqrt( err )
        if( j < GCRk ) then
	  inv_h = 1.0_r_def/h(j+1,j)
          call invoke ( copy_scaled_field(inv_h,w,v(j+1)))
        end if
      end do
```

**Comment by rupertford** [comment]
@TeranIvy, could you please check the indexing error that you reported. As far as I can tell it seems to work. If you have an example where PSyclone or the parser fails could you please add it to this issue.

**Comment by TeranIvy** [comment]
Modifications of built-ins so far in Dynamo eg3/solver_mod.x90 (issue #40) regarding simple loop indices report no errors unless arithmetic operations are combined with loop indices (e.g. 1.0_r_def/h(j+1,j)). This is correct behaviour and it means that more built-ins are needed to cover these cases (this will be addressed in a separate issue).
Everything works as it should so I am closing this issue.
