### ISSUE TITLE
Why is 'walk' implemented the way it is?

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#410]
When trying to work around #409, my first thought was to add a walk function for NemoKern that looks in self._kern_schedule instead of self._children, but then I noticed that walk has a very strange implementation:
```
    def walk(self, children, my_type):
        for child in children:
...
            local_list += self.walk(child.children, my_type)
        return local_list
```
Notice that 'self' is only used to determine the walk function used (which as far as I can see is always Node.walk), the parameter children can be something else. That leads to odd calls:
```
nodes = self.root.walk(self.root.children, ...)
```
Why is it not implemented by taking 'children' from self:
```
 def walk(self, my_type):
        for child in self.children:
...
```
then it could be called as
```
nodes = self.root.walk(...)
```
I know there are calls in the form:
```
all_nodes = self.walk(self.root.children, Node)
```
but considering that there appears to be only one walk implementation, I can't see a problem this being changed to:
```
all_nodes = self.root.walk(self.root.children, Node)
```
which would then also allow this to be called as:
```
all_nodes = self.root.walk(Node)
```
with this implementation.

Main reason why I ask: with this implementation I could then overwrite NemoKern.walk to do what I want it to do :to work around #409)

I am happy to discuss this next time we meet, it's not urgent for me.

**Comment by hiker** [comment]
Since we agreed that this can be simplified, I might quickly do that. One question: atm the walk function is always only applied to the children, i.e. the node itself is never returned. I think the implementation would be more natural if a node would check itself and add itself if required (instead of adding the children which fit the type condition). Are you aware of any reasons why we might not want the root of the tree to be included? Of course, this is assuming that all test cases pass 😃

**Comment by arporter** [comment]
I'm happy to go with that if you think it would be more natural :-) (Sorry for radio silence, we've been out at a meeting all day.)
