### ISSUE TITLE
PSyIR navigation syntax

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#411]
Updating the Loop structure is proving very challenging not because the Loop class implementation itself but because all the tests are written in a navigation syntax going through the children property (e.g. node.children[0].children[1].children[0]). I think this has several problems:
- It is not future-proof (any restructuring of a Node children list could break all the tests and PSyclone scripts!)
- It is not readable (too verbose) (I end up using the debugger and just print the end node to know where exactly I am)
- Not good OO encapsulation (but I leave this for another Issue)

Given that this is a partial update to Loop and I will end up modifying Loop again to accommodate other types of loops I would like to open a discussion about the 'navigation/node selection' syntax by proposing some additions:
1) Overload the '[int]' operator of node to shorthand node.children[int]
2) Add semantic navigation(?), I already started in IF and LOOP (e.g. IF.condition, IF.if_body, IF.else_body, LOOP.stop_expr, ...)
3) Overload '[string]' so that it does a by id/name node selector (or even regex if we want to be really really fancy :)).

And then write the tests / PSyclone scripts node selection expressions in a way which relies in as few implementation details as possible. 

With this addition we would have:

```
# Children syntax: difficult to read, changes could break this statement but full control.
schedule.children[2].children[0].children ...

# Shorthand syntax: Nicer to read/follow (and same full control?), but also not resistant to changes 
schedule[2][0][0]

# Semantic syntax: Readable, more resistant to future changes(?)
schedule['loop_id'].loop_body[2].if_body
schedule['kernel_name']
```

**Comment by hiker** [comment]
[...]
> Updating the Loop structure is proving very challenging not because the Loop class implementation itself but because all the tests are written in a navigation syntax going through the children property (e.g. node.children[0].children[1].children[0]). I think this has several problems:

Can't agree more!

>     1. Overload the '[int]' operator of node to shorthand node.children[int]

Sounds good.

>     2. Add semantic navigation(?), I already started in IF and LOOP (e.g. IF.condition, IF.if_body, IF.else_body, LOOP.stop_expr, ...)

Yes please!! Just one issue to think of:
atm if_body returns self._children[1]._children
In some cases I found it more convenient to get self._children[1] (so the instant that contains the list of all statements), then I either need to get the parent ... or not use if_body (etc). Now my usage might be special (I would need to dig out the example, but I think it was for variable usage: just by getting the parent class that contains all statements in the if body, I could simply get the dependencies of every statement by calling the corresponding function once. But if I get a list (i.e. the children of this class), I have to write a loop.


>     3. Overload '[string]' so that it does a by id/name node selector (or even regex if we want to be really really fancy :)).

Not sure if this should be overloaded or a separate functions (what does it return if there is more than one matching item? A list? That might be confusing that ["string"] returns a list, and [int] return a node.

Everything else: +1000   :)

**Comment by sergisiso** [comment]
> atm if_body returns self._children[1]._children
> In some cases I found it more convenient to get self._children[1]

I found the same with loop bodies, I initially implemented the list access to write simpler expressions, but if we have the [] overloaded for the Schedule then IF.if_body could return the Schedule and IF.if_body[0] would return the specific statement. So both use cases are solved.

I may only overload the [int] for Schedule, which I think it is the one that makes semantic sense to have an integer enumeration (for the sequence of statements) and add some semantical properties to specific classes (ASSIGNMENT.rhs/lhs , ...)

I will leave the [string] out for now, it was just an idea to consider.

**Comment by TeranIvy** [comment]
Semantic syntax looks very appealing as it gives the type of a Node and not only its position. BTW, would this change how a Schedule is displayed? I am asking because of issue #303 which I created in frustration of having to manually count through a printed Schedule to figure out where to apply `Extract` transformation. Would it still make sense to display indices in front of Nodes?

**Comment by sergisiso** [comment]
@TeranIvy It does not change how it is displayed, but it simplifies now we navigate the tree, hopefully making the code more readable. I will reply to your #303 separately.

**Comment by arporter** [comment]
#413 is merged. I'll leave whether or not to close this issue up to @sergisiso (I don't know whether you want to take more steps in this direction...)

**Comment by sergisiso** [comment]
I will close this issue as the remaining bits are already captured by #294 and #303
