### ISSUE TITLE
Support Fortran array syntax in the PSyIR

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#412]
Any use of Fortran array syntax (e.g. a(:,:) = b(:,:) * c(:,:)) is currently not represented in the PSyIR and is thus put into CodeBlocks.

Of course, this notation is language specific and the PSyIR is language independent. Therefore I think such syntax will have to be converted into explicit loops in the PSyIR (with an annotation to record the fact that it was originally an implicit loop). @sergisiso is currently adding support for loops to the PSyIR in #385.

**Comment by sergisiso** [comment]
They can be normalized to the PSyIR Loop, but we will need something similar to the `lbound`, `ubound` and `size` intrinsics in the PSyIR. Or maybe have the Array Symbols be a more specialized entity that has methods for these array utility operations?
Although it should be not the priority, it would be good if the solution has a direct translation to C/OpenCL.
What do you think?

**Comment by arporter** [comment]
After much whiteboard discussion today, we agreed that we would introduce a new `Range` base class in the PSyIR. This will then be sub-classed as `EntireRange` and `ExplicitRange`, the former to capture the use of a bare colon (e.g. `a(:,3)`) and the latter to capture a range with bounds (and optional step), e.g. `a(4:6,3)`. Once we have this then an `Array` can have a `Literal`, a `Reference`, an expression or a `Range` as children (with one child for each dimension).

**Comment by rupertford** [comment]
PR #656 is now on master so a Range Node exists but the front-end needs to support the translation from Fortran Array slice notation to this new Node and, at least, the Fortran back-end needs to support translating from Range back to Fortran before we can close this issue.

**Comment by rupertford** [comment]
Created branch 412_array_slice_to_loop. This will translate Fortran array slice notation to standard PSyIR loops making use of the Range, lbound and ubound classes as appropriate.

**Comment by rupertford** [comment]
Note, the PSyIR supports array slices so the translation to loops will be a transformation, it will not be part of the front end.

**Comment by arporter** [comment]
@rupertford can this issue be closed now or is there more to do?

**Comment by rupertford** [comment]
Yes, it can be closed and I have just done so :-)
