### ISSUE TITLE
Modify PSyclone contributions/install script

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#43]
The way the installation of PSyclone works now is (script `constributions/install`):
1) Copy everything from unpacked `PSyclone-<version>/src` to `<installroot>/psyclone` directory except `tests` and `generator.py`,
2) Copy `PSyclone-<version>/src/generator.py` to `<installroot>/bin/psyclone`,
3) Change `<installroot>/bin/psyclone` permissions to "-rwxr-xr-x".

This works well for compiling the LFRic code, but not for PSyclone code which complains about missing `generator.py`.

The proposed modifications are:
1) Copy everything from unpacked `PSyclone-<version>/src` to `<installroot>/psyclone` directory except `tests`,

2) Make relative symbolic link from `<installroot>/bin/psyclone` to `<installroot>/psyclone/generator.py`,
3) Change `<installroot>/psyclone/generator.py` permissions to "-rwxr-xr-x".

Manual creation of Linux symlink works well for our current version of PSyclone 1.4.1 for both LFRic and PSyclone code generation and PSyclone py.test. 

The modified install script is attached as [install.txt](https://github.com/stfc/PSyclone/files/1029170/install.txt) due to Github attachment rules. Modified 
`install` was tested on Met Office Linux environment for Python 2.6.6 and 2.7.6 versions and produces the correct directory structure. PSyclone works normally with it.

**Comment by rupertford** [comment]
pull request #44 is now on master so closing issue.
