### ISSUE TITLE
Fix pytest ExceptionInfo strings

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#438]
Pytest 5.0 changed the ExceptionInfo objects returned by pytest.raises (https://docs.pytest.org/en/latest/changelog.html).

This breaks many of PSyclone tests that contain a `str(error)` expression after a pytest.raises from a clean pip installation or if you do a pip update.

A quick fix is limiting pytest to version < 5.0, but the proper fix requires updating the tests.

**Comment by arporter** [comment]
I've been naughty and already done this fix as part of work on another Issue. (I hadn't realised it was pytest that had changed - I just went ahead and fixed the failing tests.) However, it would be nicer if we did it as a separate PR so I propose we keep this Issue open.

**Comment by arporter** [comment]
Just to correct what I said earlier - it turns out that the fix I thought I'd done was actually in fparser, not in PSyclone.

**Comment by rupertford** [comment]
Created branch 438_fix_pytest_strings

**Comment by arporter** [comment]
#573 is merged.
