### ISSUE TITLE
Coding Style for interface docstrings

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#443]
There are some variations in the formatting of interface descriptions in doc strings. One example is that @arporter recently suggested to have an empty line before the closing ''' of a doc string. I could not find a coding style guide in PSyclone, but there is https://github.com/stfc/fparser/wiki/InterfaceMarkup in fparser, which is pretty close.

Some differences between recent changes that have been requested and the above web page:
1) The \ at a continued line for a parameter etc is missing
2) The newline between parameter and return is missing
3) The newline between return and exception is missing.
4) The newline between the last documentation and the final ''' is missing.

Point 4) is being somewhat 'questionable' :grin:  - imho an empty line between the comment and code is good since it helps readability, but it should not be part of the comment (since this could influence layout of documentation). So my suggestion would be ''' and an optional newline before the code - with the exception that small functions (e.g. setter/getter) might skip the new line to keep the code shorter.

@rupertford, @sergisiso @TeranIvy - any comments? I offer a TimTam for your vote if you drop by my desk :grin:

I would also suggest to add this section to the developers guide. The above coding guide has not been changed in the last 1.5 years, so the duplication (wiki + docs) should not create too much overhead.

**Comment by rupertford** [comment]
If it were a Hobnob ...

**Comment by hiker** [comment]
I've created:
https://github.com/stfc/PSyclone/wiki/InterfaceMarkup

@arporter, @rupertford, @sergisiso, @TeranIvy - please provide feedback, once most of us are happy with the description, I'll add it to the developers guide ('most' you ask ... empty line before '''? I checked ... my emacs does not do this :grin: :grin: :grin: ).

**Comment by arporter** [comment]
Thanks for doing this @hiker. I'm happy with most of the description apart from the capitalisation of the lines describing parameters and exceptions. I think these should be lower case as the generated documentation looks like, e.g.:

https://user-images.githubusercontent.com/17409212/61281774-1e8bb380-a7b2-11e9-8582-1564bd0e00b7.png

**Comment by hiker** [comment]
I just learned that apparently I needed to remove my _build directory in order to get a consistent html layout between users' guide and developers' guide :unamused:  Interestingly enough, your picture shows the old layout as well (or ... maybe something in between, I had some areas that were a light purple colour, which you seems not to have): you do have a ":" after "Parameter" and "Raises", while I just deleted my _build and recreated the html file, and now I have no colons, and a new line after Parameter and Raises, which you have. It looks a bit like this (just the leading '-' should be bullet points)
```
Parameters
        - filename (str) – The file containing the algorithm specification.

[...]
Returns
    2-tuple containing fparser1 ASTs for the algorithm code and the psy code.
Return type
    (fparser.one.block_statements.BeginSource, fparser.one.block_statements.Module)
Raises
        - IOError – if the filename or search path do not exist
```
@arporter can you just confirm that my layout is the intend one? Move _build out of the way and recreate the html files.

This seems to have one severe disadvantage: the layout of table tables in html is now broken - it does not wrap lines anymore, instead we have horizontal scroll bars. This is apparently a [known issue](https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html), but it used to work just fine in the past (and it still works in pdf). Check configuration.html in the user's guide, which has a table in the section "DEFAULT Section". In the past it used to wrap around.

I have tried various ways of formatting the somewhat confusing layout instructions (we have nearly all combinations of capital/non-capital letter at start and punctuation or no punctuation at the end), and at this stage I favour a table layout ... which now does not work anymore (and it breaks the existing configuration table in the user's guide, and maybe others).

@arporter, when you have time, could you have a look at the table layout and see if there is an easy fix? Then I'll continue with my documentation and formatting tests once this is done. I've pushed my branch to https://github.com/stfc/PSyclone/tree/interface-coding-style, feel free to just add it there (or if you prefer I can pull from a branch). Note that the developer's documentation is a bit messed up with duplicated sections and some unnecessary information ... as I've said, I was testing various layouts to see what works best with html and pdf, and there is a lot of testing stuff there atm :blush:

**Comment by arporter** [comment]
Hi @hiker. I've just done as you suggested and the resulting docs look identical to those on RTD (including with working tables). Maybe this is a versioning issue with the Sphinx-RTD theme? I'm using sphinx-rtd-theme 0.4.3

**Comment by hiker** [comment]
I've pushed a branch which should mostly do what you described. The only thing I wasn't sure of is the handling capitalisation after ":" (which is in 'returns' in html only, not in pdf *sigh*).  I am attaching two screenshots of a sample interface description that should have every element we have.
HTML look:
![psyclone-html](https://user-images.githubusercontent.com/6138652/62522777-bc384700-b875-11e9-937a-4733c632b120.png)

PDF look:
![psyclone-pdf](https://user-images.githubusercontent.com/6138652/62522781-bc384700-b875-11e9-9bde-ff2cbf8b9ef5.png)

Oh, I also decided to apply a small fix to avoid scrolling of long lines in html - sorry, that just made any table layout kind of useless. If we are happy with this description, the pull request should be ready :)

**Comment by arporter** [comment]
Thanks @hiker. Since a colon does not start a new sentence I think the beginning of the "Returns" string should be lower case. This then makes sense in both layouts.

**Comment by hiker** [comment]
While I totally disagree with that, who am I to argue with a native speaker (I am somewhat used to APA style, which requires capitalisation after : ) Though there is this funny thing from https://apvschicago.com/2011/04/capitalization-after-colons.html:
```
Chicago (6.61): Lowercase the first word unless it is a proper noun or 
the start of at least two complete sentences or a direct question.
```
Obviously not written in Chicago style :)
OK, no arguing, pull request done: #464
