### ISSUE TITLE
Loop boundaries are not defined when transformations are applied

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#444]
At least in gocean1.0 the loop boundaries and step size are only defined when gen_code() is being called:
```
def gen_code(self, parent):
 [...]
       self._start = self._lower_bound()
       self._stop = self._upper_bound()
       Loop.gen_code(self, parent)
```
And self._step does not even appear to be set (though it will default to '1' in this case).

This means that transformation can not access loop boundaries, and dependency analysis will be missing accesses. This might be somewhat related to #385 (to convert loop boundaries from strings to PSyIR nodes).

**Comment by sergisiso** [comment]
@hiker The first version of the Loops won't solve this issue but I captured the problem in the second part of #440 specifically the last two points.

**Comment by hiker** [comment]
Closing this as a duplicate of #440.
