### ISSUE TITLE
[LFRic] set_dirty() and set_clean() calls in OpenACC kernels and parallel directives

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#450]
At the moment any "set_dirty" or "set_clean" calls are added immediately after a loop. Currently these appear within acc kernels or acc parallel regions. In OpenMP these calls are protected by the "single" directive. However, in OpenACC it might be better to avoid calling these functions on a gpu and instead call them on the cpu. This still needs to be clarified (I will check with NVIDIA) but, if so, the set_dirty and set_clean placement would need to be re-written.

One option would be to add these calls just before a halo exchange. Another would be to add them as part of the PSyIR and them move them using transformations. The PSyIR option might seem the simplest but it would require similar dynamic logic to halo exchanges as the content and existance of such calls change as transformations are applied.

**Comment by arporter** [comment]
As mentioned in #713, `examples/lfric/eg14` currently produces invalid code because of this problem.

**Comment by arporter** [comment]
`DynLoop.gen_code()` currently places the set_dirty/clean calls.

**Comment by arporter** [comment]
Got distracted by trying to make eg14 compile which in turn needed the test LFRic infrastructure to be updated and that got complicated, hence #1667.
