### ISSUE TITLE
[LFRic] loop bounds should be a constant value for OpenACC

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#451]

**Comment by arporter** [comment]
@christophermaynard has been working on getting the Gravity Wave Miniapp going on GPU and this is one of (several) issues that he encountered.

**Comment by arporter** [comment]
Loop bounds are generated by the `DynLoop._lower_bound_fortran/upper_bound_fortran` methods. These can be changed by transformations (e.g. when doing redundant computation).

**Comment by arporter** [comment]
The Fortran code itself is generated in `Loop.gen_code()` using the `Loop` `start_expr` and `stop_expr` properties (which are PSyIR).

**Comment by arporter** [comment]
Although I can quite easily implement this functionality, it really requires a new sub-class of `DynCollection` in order to ensure that the assignments to loop bounds are carried out after all of the other quatities have been initialised (since the former use the latter occasionally). I don't really want to implement any more code in the 'old way' but it might be an awful lot of work to get this working in the PSyIR.

**Comment by arporter** [comment]
Actually, it turns out that a new `LFRicLoopBounds` collection is really simple to do. A harder problem is the fact that the upper bound of a loop within colours is currently indexed by colour. This requires an LFRic infrastructure change (I think).

**Comment by arporter** [comment]
i.e. my current code will generate `loop1_stop = mesh%get_last_halo_cell_per_colour(colour,1)` (for DM=True) or `loop1_stop = mesh%get_last_edge_cell_per_colour(colour)` without DM. We will need the full 1d array holding the last edge/halo cell for each colour but I'll need to check with the LFRic infrastructure code.

**Comment by arporter** [comment]
I've had a look in our stripped-down version of the LFRic infrastructure and the relevant arrays live in mesh_mod. @TeranIvy would you be so kind as to create an LFRic ticket to add new calls that will return these arrays in their entirety? I think the arrays in question are:

    integer(i_def),allocatable           :: last_inner_cell_per_colour(:,:)
    integer(i_def),allocatable           :: last_halo_cell_per_colour(:,:)
    integer(i_def),allocatable           :: last_edge_cell_per_colour(:)

We probably need to bring @christophermaynard into the loop as I know he's hit data-copying issues with the pointers to arrays that some of the infrastructure calls already return.

**Comment by arporter** [comment]
There is a problem with my current implementation - the various collection `initialise()` calls happen *before* the `InvokeSchedule.gen_code()` call and it is only in the latter that the SymbolTable associated with the InvokeSchedule is copied. Therefore, the symbols that I currently add in the `initialise()` call stay in the 'original' SymbolTable of the InvokeSchedule and therefore I get clashes if `gen()` is called a second time.
In GOcean, the GOInvoke does not generate any code before the `InvokeSchedule.gen_code` is called. This seems right as generating the code for the InvokeSchedule should be the responsibility of that object, not the parent Invoke.

**Comment by arporter** [comment]
One solution would be to move all of the Collection objects out of DynInvoke and into DynInvokeSchedule. I would then have to override `DynInvokeSchedule.gen_code` so that it called the various `declarations` and `initialisation` methods of those objects, *after* it had taken a copy of the SymbolTable.

**Comment by arporter** [comment]
Apparently @stevemullerworth  wrote the relevant bit of the LFRic infrastructure so inviting him to join the party... :-)

**Comment by stevemullerworth** [comment]
I have tested the following. Note that I've not fully decided whether I like the names of the new functions or got the code reviewed. The 4 New/modified code are commented.

Would it meet the requirement @arporter ? 

For this call (and for the inner halos) would you prefer to get a 2D array of colour X halo-depth? e.g. if doing redundant computation deeper into the halos.
```

      integer(i_def), allocatable :: last_halo_cell_all_colours(:) ! New

      last_halo_cell_all_colours = mesh%get_last_halo_cell_all_colours(1) ! New
      DO colour=1,ncolour
        DO cell=1,last_halo_cell_all_colours(colour) ! Modified
          !
          CALL pressure_gradient_bd_code(nlayers, rhs_tmp_proxy%data, exner_proxy%data, exner_stencil_size(cmap(colour, cell)), &
&exner_stencil_dofmap(:,:,cmap(colour, cell)), theta_proxy%data, moist_dyn_proxy(1)%data, moist_dyn_proxy(2)%data, &
&moist_dyn_proxy(3)%data, cp, ndf_w2, undf_w2, map_w2(:,cmap(colour, cell)), basis_w2_qrf, ndf_w3, undf_w3, map_w3(:,cmap(colour, &
&cell)), basis_w3_qrf, ndf_wtheta, undf_wtheta, map_wtheta(:,cmap(colour, cell)), basis_wtheta_qrf, nfaces_re_h, &
&out_normals_to_horiz_faces, adjacent_face(:,cmap(colour, cell)), nfaces_qrf, np_xyz_qrf, weights_xyz_qrf)
        END DO
      END DO
      deallocate(last_halo_cell_all_colours) ! New
```

**Comment by stevemullerworth** [comment]
LFRic ticket: https://code.metoffice.gov.uk/trac/lfric/ticket/2894

**Comment by stevemullerworth** [comment]
@arporter if you are happy with the following I'll submit the code change for LFRic review. It now returns 2D arrays dimensioned by colour and depth.

Here for details

https://code.metoffice.gov.uk/trac/lfric/wiki/ticket/2894/TicketSummary?version=3

Here's an example use.

`

      integer(i_def), allocatable :: ncells(:,:)

      ncells = mesh%get_last_halo_cell_all_colours()

      DO colour=1,ncolour
        DO cell=1,ncells(colour,1)
          !
          CALL pressure_gradient_bd_code(nlayers, rhs_tmp_proxy%data, exner_proxy%data, exner_stencil_size(cmap(colour, cell)), &
             exner_stencil_dofmap(:,:,cmap(colour, cell)), theta_proxy%data, moist_dyn_proxy(1)%data, moist_dyn_proxy(2)%data, &
             moist_dyn_proxy(3)%data, cp, ndf_w2, undf_w2, map_w2(:,cmap(colour, cell)), basis_w2_qrf, ndf_w3, undf_w3,     map_w3(:,cmap(colour, &
             cell)), basis_w3_qrf, ndf_wtheta, undf_wtheta, map_wtheta(:,cmap(colour, cell)), basis_wtheta_qrf, nfaces_re_h, & 
             out_normals_to_horiz_faces, adjacent_face(:,cmap(colour, cell)), nfaces_qrf, np_xyz_qrf, weights_xyz_qrf)
        END DO
      END DO

      deallocate( ncells )
`

**Comment by arporter** [comment]
@stevemullerworth that looks good to me - I have PSyclone generating this now. Just a matter of updating the tests...

**Comment by stevemullerworth** [comment]
Thanks. Have submitted code for review. I'll let you know of any requested changes to the API - hopefully none!

**Comment by stevemullerworth** [comment]
The related LFRic change is now on trunk.

https://code.metoffice.gov.uk/trac/lfric/wiki/ticket/2894
