### ISSUE TITLE
Add any_space_10

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#455]
The LFRic infrastructure defines the any_space_* metadata name up to 10 whereas PSyclone accepts an any_space_* metadata name up to 9.

**Comment by TeranIvy** [comment]
Besides adding `any_space_10`, as well as `any_d_space_*` identifiers in #133, `argument_mod` is very out of date from its origin [argument_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/field/argument_mod.F90) in the LFRic trunk. In particular, function space identifiers have moved to [fs_continuity_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/function_space/fs_continuity_mod.F90) and new metadata have been added.
I suggest extending this issue to update argument_mod in general after merging #133.

**Comment by TeranIvy** [comment]
I decided not to update the PSyclone version of `argument_mod.F90` for now as
- There will probably be more changes from the reference element support,
- It serves the purpose,
- We need to think about how to use LFRic infrastructure library when it becomes available.

**Comment by rupertford** [comment]
pr #531 merged to master so closing this issue.
