### ISSUE TITLE
Document the test fixtures

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#457]
We have quite a number of test fixtures now. These need to be documented in the Developers' Guide.

**Comment by arporter** [comment]
While working on #594 I thought I was going to need to update the dev. guide so I broke it up into separate files. I then realised that a) I should be doing that in a separate Issue and b) I didn't need to update the dev. guide after all. Therefore I've moved the two commits over to the branch associated with this work.

**Comment by rupertford** [comment]
pr #607 is now on master. Closing this issue.
