### ISSUE TITLE
Duplicate operator tests in dynamo0p3_test.py

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#465]
Extending tests in #133 uncovered duplicate operator tests in `dynamo0p3_test.py` and `dynamo0p3_lma_tests.py`. The latter test file was added in PR #306 (associated issue #268) and majority of the operator tests were moved there as a part of this change. However, there seem to be duplicates of these tests remaining in `dynamo0p3_test.py`. 

The specific duplicate tests in `dynamo0p3_test.py` are:
- `test_operator`
- `test_operator_different_spaces`
- `test_operator_nofield`
- `test_operator_nofield_different_space`
- `test_operator_nofield_scalar`
- `test_operator_nofield_scalar_deref`
- `test_operator_orientation`
- `test_op_orient_different_space`
- `test_operator_deref`
- `test_operator_no_dofmap_lookup`
- `test_operator_read_level1_halo`
- `test_operator_bc_kernel`

Tests for operators in `dynamo0p3_test.py` that could be moved to `dynamo0p3_lma_test.py` are:
- `test_get_op_orientation_name`
- `test_operator_gh_sum_invalid`
- `test_op_any_space_different_space_1`
- `test_op_any_space_different_space_2`

**Comment by TeranIvy** [comment]
The versions of tests in `dynamo0p3_lma_test.py` seem to be newer/extended in comparison with `dynamo0p3_test.py` so I will modify operator tests for `any_d_space` support (#133) in `dynamo0p3_lma_test.py` and delete the duplicate test in `dynamo0p3_test.py`.

**Comment by rupertford** [comment]
PR #469 is now on master so this issue can be closed.
