### ISSUE TITLE
[PSyIR] PSyIR Literal Node should include the type of the literal value

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#468]

**Comment by arporter** [comment]
I will take this on as I need support for Character literals in the NEMO API.

**Comment by arporter** [comment]
For this issue, I obviously need to introduce the concept of a datatype to the `Literal` class and the nicest way to do that is with some sort of enumeration. Currently the `Symbol` class has the concept of datatype but this is implemented using strings. I think it would be nicer if both the `Literal` and `Symbol` classes made use of a common way of specifying data-type. What do @rupertford, @sergisiso and @hiker think?

**Comment by sergisiso** [comment]
That's a good idea and the constant_value parameter already does something similar using a map from Fortran intrinsics to Python intrinsics which can be reused, as part of #544 I also added floats/reals into the map.

I also recommend holding this until #544 is merged as I am moving the Symbol implementation to separate files.

**Comment by arporter** [comment]
Thanks @sergisiso. I'll pause this for now then and wait on #544.

**Comment by arporter** [comment]
#544 is done so I can proceed with this now...

**Comment by rupertford** [comment]
pr #600 is on master. Closing this issue.
