### ISSUE TITLE
[SIR] Supporting scalars

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#472]
The tridiagonal solve example consists of multiple loops with one of the loops setting and reading from a temporary scalar.

In the original SIR example, the variable is declared in place ...

makeVarDeclStmt(
    makeType(BuiltinType.Integer),
    "m", 0, "=",

In PSyclone the scalar assignment is specified with makeVarAccessExpr("m"), which presumably means it is never declared and this causes Dawn to fail.

I need to find out whether scalars can be set outside of loops in SIR and/or add logic to determine if a scalar is used as a temporary inside a loop (and then declare it appropriately).

**Comment by rupertford** [comment]
Carlos has kindly explained that makeVarDeclStmt is a node as is VerticalRegionDecl. This means that makeVarDeclStmt can be declared outside of, or inside of a VerticalRegionDecl, giving us the constant scalar or temporary scalar option. He points out that this particular makeVarDeclStmt would fail if it were outside a VerticalRegionDecl as it includes a makeFieldAccessExpr which does need to be in a VerticalRegionDecl. However, I could just declare and create the variable with an initial value if necessary.

**Comment by rupertford** [comment]
Created branch 472_sir_scalars

**Comment by rupertford** [comment]
The simplest solution is to add a `VarDeclStatement` to the list of nodes (`vertical_region_fns`) for any required scalar variables. The natural place to do this is in `nemoinvokeschedule_node`. At the moment `nemoinvokeschedule` does not create and populate a symbol table. Therefore I will need to search for scalar accesses.

**Comment by arporter** [comment]
How urgent is this? I've been thinking that we really ought to start down the road of having the NEMO API use the SymbolTable (albeit with a flag that enables it to ignore symbols for which we cannot find a declaration).

**Comment by rupertford** [comment]
I completely agree with adding NEMO symbol table information but this is the next thing on my list for SIR so I think I'll go ahead with it anyway. It's pretty simple to find what I need without the symbol table, although I will have to assume the type information for the time being ...
```
        scalar_names = set()
        for kernel_node in node.walk(NemoKern):
            kernel_schedule = kernel_node.get_kernel_schedule()
            for assignment_node in kernel_schedule.walk(Assignment):
                lhs = assignment_node.lhs
                if not lhs.children:
                    # This is an assignment to a scalar
                    scalar_names.add(lhs.name)
```

**Comment by rupertford** [comment]
I now generate the code, but Dawn still complains. If I manually move the declaration to just before it is used (in the same make_ast) then it works. So it seems that you can't declare in one ast and use in another. I thought Carlos said this was possible so I've sent the code to him to see what I'm doing wrong.

**Comment by rupertford** [comment]
Tobias Wicky kindly replied explaining that the best way to do this is to create a temporary field as the Dawn back end will recognise that it only needs to create a scalar. Creating a temporary field is the same as creating a field except that there is a second argument that is set to True e.g. ```make_field("m", True)```, or if we want to name the optional argument ```make_field("m", is_temporary=True)```

**Comment by arporter** [comment]
#524 is merged so closing Issue.
