### ISSUE TITLE
File/module restructuring

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#474]
I did a quick test: beginning of the year psyGen hat around ~3900 lines, now it has ~7300 lines - any prognosis where we will be at in 2 years (47k lines assuming 1.86 fold increase in 8 months :stuck_out_tongue_winking_eye: )?

The default for pylint is 1000 lines. Some bad side effects of those long files that code duplication might get unnoticed (e.g. compare psyGen.Symbol.Access and core/access_info - basically identical classes, but now we have: 
```
>>> from  psyclone.psyGen import Symbol
>>> from psyclone.core.access_type import AccessType
>>> Symbol.Access.READ == AccessType.READ
False
```
Could we come up with a new directory structure that will allow us to reduce file size? I am not sure if this might have a performance impact (reading multiple smaller files vs reading bigger files with a lot of code that might not be actually used) - probably tbh. 

I usually prefer one class per file (with file name derived from class name ... e.g. class Node --> node.py, VariableAccess-->variable_access.py etc), only exception would be helper classes that are 'closely related' (yes, vague). Example: VariablesAccessInfo contains VariableAccessInfo and AccessInfo  as helper class, which will very unlikely ever be used by itself (except for tests).

Directory layout ... not sure, but as a suggestion:
- core Contains core classes, that might be used in many different places (e.g. access type, symbol table, errors)
- psy_ir  (to avoid camel case ... or maybe psyir?) Anything related to psyir
- gocean0p1, gocean1.0, dynamo0.3, ... - one directory per API
- transformations
- tools

That already raises a few questions:
1) do we want to move the API-directories into a common sub directory (api/gocean0.1, api/gocean1.0, ...) ? I actually don't like directories to be nested too deep (which might make it harder to find things), but I don't mind one way or another

2) should the API-specific transforms go into the one transformations directory? Or should only be the base classes in transformations, and all API-specific transforms go into the API classes?

3) Would it make sense to have paradigm-specific directories? E.g. opencl, openacc, omp, mpi, ...

And I am sure I have forgotten quite a bit :) So I leave this open to start a discussion :)

**Comment by arporter** [comment]
Rupert and I chatted a bit about this and agree. Of course most of the growth in psyGen.py is because much of the PSyIR functionality has been put in there when it should, as you say, go in one or more files under the (existing) `psyir` directory. If we're going to try to keep under the 1K line limit (and it seems sensible to me) then we will have to break up existing files and your suggestion of ~1 class per file with sensible flexibility seems like a good one. I think we should tackle this a bit at a time but the PSyIR seems like a good place to start IMO...

**Comment by hiker** [comment]
Great to hear that :) It leaves a few details:
1) All PSyIR related code goes into the PSyIR directory
2) We create a subdirectory for each API - I would say it without version number, so gocean0.1 and gocean1.0 all go in gocean; dynamo0p1 and 0p3 go into one dynamno directory(?)
3) we create a directory for all transformations, but what do we do with API-specific transformations? We can either put them into the transform directory, or with the API-specific directory. I might have a slight preference for keeping all transforms in one directory (seeing that this way all inheritance happens in one directory, and all imports will happen from transform - in case that there are transforms that are not API specific), but an equally good case can be made for API specific transforms. Imho - if we have API-independent transforms, then all (including api-specific) transforms should be in transforms, otherwise api-specific transform go into the api directory. This way the user always has to use the same import statement.

And yes, do this a few at a time - this will cause massive merge conflicts :)

**Comment by sergisiso** [comment]
I think an obvious one is to separate the Fparser2ASTProcessor (which is alone ~1500 lines) to a `psyir/frontend/fparser2.py`. Also changing the class name appropriately (fparser2Reader?) and make the visitor implementation style coherent with the back-ends when possible.

I am happy to make this change, but again the main worry is causing conflicts with other PRs. So @arporter @rupertford @hiker @TeranIvy , do you have any open PR/branches that touch the Fparser2ASTProcessor class?

**Comment by arporter** [comment]
That sounds good although I have just today started working on a branch that adds functionality to the Fparser2ASTProcessor class. That said, obviously I've not done that much work yet so it's OK with me if you want to do this work in the short term...

**Comment by rupertford** [comment]
Hi Sergi,

If you could hold off a little bit until #498 is on master (I'm not far from it being ready for review) that would be appreciated.

Rupert

--

Computational Scientist
STFC Daresbury Laboratory
t: 01925 60 3217


________________________________________

**Comment by hiker** [comment]
I won't touch it.

**Comment by sergisiso** [comment]
@rupertford @arporter no worries it is just to be aware of the open pieces of work regarding this class and find the proper time. I will coordinate it with you before doing the changes.

**Comment by sergisiso** [comment]
The first bit is done (#419) but psyGen is still +6600 lines. Probably next step is to separate the PSy-layer logic from the PSyIR Nodes. The latter should probably be moved into the `src\psyclone\psyir` folder (or a sub-folder inside it?). Also should Nodes be placed as one per file (although I would be good to maintain the single import point) ?

**Comment by hiker** [comment]
During today's telco we decided:
- create separate directories for each API, without any version number. If there should be more than one version of an API (e.g. gocean0.1/1.0 - if 0.1 can not be deleted anyway), they would go in the same directory (gocean).
- Translations will be split apart: the typical base classes will go into psyir/transformations; the API-specific specialisations will go into api-specific transformation subdirs (gocean/transformation/...).

Then we can iteratively improve the situation by creating separate files when we touch a class. If you want to do one of the APIs, please synchronise with all devs to avoid conflicts.

One concern: please don't move transformations before #556 is merged, otherwise more or less this whole big patch could become a messy conflict.

**Comment by rupertford** [comment]
An additional suggestion to the above is to have another directory level which encompasses nemo, gocean and lfric. @sergisiso  and I tried to find an appropriate name for this directory and our suggestion is "domain". So we would have ...

```
psyclone/
    psyir/
        ...
    domain/
        lfric/
        nemo/
        gocean/
```

**Comment by hiker** [comment]
Domain is fine, but as alternative suggestion: 'api'? And even though it's an acronym, I would prefer lower case (think of the poor people running a VM on a windows filesystem, which is case insensitive ;) )

**Comment by rupertford** [comment]
Yes we went through a few options: 'dsl', 'config', 'interface', 'api', 'frontend' and 'domain', but both liked 'domain' best, with 'api' the only other contender. The reason for this is that PSyclone is a configurable domain-specific compiler and lfric is designed for the mixed finite element domain, nemo for the finite difference domain and gocean for the 2d finite difference domain. Of course you could say they provide a domain-specific API which is true and this also captures the fact that the API's are different for each, but 'domain' seemed more general as that is what it is. Having said that, api would be OK too and is what we currently call them so let's go with the majority.

**Comment by hiker** [comment]
While I am OK with 'domain', when seeing 'domain' I would expect then to have subdirs names like: "finite_elements", "2d_finite_difference", "generic_finite_difference" (technically nemo is 3d, but since it can be used with 2d ROMS. I picked generic). But obviously those names are not ideal ... so, domain it is :)

**Comment by hiker** [comment]
Some of the paths are getting rather long, e.g.:
```
from psyclone.psyir.transformations.extract_region_trans \
    import ExtractRegionTrans
```
I wonder if we should drop the 'trans' in both the file name and the class?
```
from psyclone.psyir.transformations.extract_region import ExtractRegion
```
The 'from' part makes it obvious that it is an transformation.

Similarly (and even worse), what about the domain (API) specific instances? ATM we would have:
```
from psyclone.domain.lfric.transformations.dynamo_extract_region_trans \
    import DynamoExtractRegionTrans
```
The fact that it is a transformation is conveyed twice (path and filename), same for the fact that it is lfric (lfric in path, dynamo in filename). Should we shorten the name to DynamoExtractRegion at least? I don't think we can get rid of 'Dynamo', since otherwise we have identical file (and class) names in psyir/transformations/extract_region.py and domain/lfric/transformations/extract_region.py (and I would be strongly in favour of using a file name based on the class name).

I don't mind leaving it the way it is - I just thought we might consider shortening some names (TBH, I would prefer removing 'domain', since I don't think we will have that many API-specific directories to justify the additional 'domain' directory - and it would just to shorten the paths a bit).

Last point: Should DynamonExtractRegion be also renamed to LFRicExtractRegion?

**Comment by rupertford** [comment]
We should probably follow @sergisiso's approach in psyir/symbols/__init__.py. That would remove one level of the hierarchy.

I don't mind losing Trans in the class name if there is agreement for it.

We will move from dynamo to lfric at some point but I'm not sure how best to do this to avoid too much disruption.

I personally don't mind dropping Dynamo/LFRic from the class name as well for the same reason I don't mind dropping Trans, but I take your point about having the same class names. Is there a accepted Pythonic approach to this problem?

**Comment by arporter** [comment]
I was about to say the same thing as @rupertford!

**Comment by hiker** [comment]
> We should probably follow @sergisiso's approach in psyir/symbols/**init**.py. That would remove one level of the hierarchy.

That's clever, I didn't know that. 

> I don't mind losing Trans in the class name if there is agreement for it.

That's +3 (including Andy).

> We will move from dynamo to lfric at some point but I'm not sure how best to do this to avoid too much disruption.

I have to change (at least) the test cases for DynamoExtractRegionTrans anyway - so I might as well start this process by renaming this to LFRicExtractRegionTrans. Just the spelling issue: filename would be lfric_extract_region.py, and the class LFRicExtractRegion? Or Lfric? LFRIC?

> 
> I personally don't mind dropping Dynamo/LFRic from the class name as well for the same reason I don't mind dropping Trans, but I take your point about having the same class names. Is there an accepted Pythonic approach to this problem?

Well, we could just not import the symbol directly I guess - in domain/lfric/lfric_extract_region.py:
```
from psyclone.psyir.transformation import extract_region

class ExtractRegion(extract_region.ExtractRegion):
```
Though ... not sure if I like this :) Better suggestions welcome :)

**Comment by TeranIvy** [comment]
"LFRic" is the project/source name so `LFRicExtractRegion`. I think renaming the `DynamoExtractRegionTrans` now does not disrupt things too much as it is not used.

About dropping "Trans", I think we may be in danger of not having a clear way of differentiating between classes that represent PSyclone "infrastructure" and classes that operate on them (transformations). I do not have a good suggestion for an alternative name, though!

**Comment by hiker** [comment]
My suggestion would be to add 'node' to the PSyIR Node classes, which then results in:
```
from psyclone.psyir.profile_node import ProfileNode
from psyclone.psyir.transformation import Profile
```
And even shorter if we use Sergi's __init__ approach. To me if reads fine if we use:
```
    profile=Profile();
    profile.apply(node_list)
```
But if you prefer to leave 'trans', I won't object (e.g. I am not sure if we might negatively affect LFRic if we rename transformations ... though some work is required when we refactor anyway).

**Comment by sergisiso** [comment]
I think using the `__init__` is quite nice to avoid duplication in the import statement and hide a little bit some internal classes. Also separating general transformations and api transformations will make things much clear as the user can apply all transformations of a given import statement.

I am OK with dropping 'Trans' I think the user already sees that each class is referring to when writing the import statement.

> My suggestion would be to add 'node' to the PSyIR Node classes

I would prefer to keep the Nodes names simple as well, so maybe just add the postfix Node when we know there is a transformation with the exact same name?

**Comment by rupertford** [comment]
> I would prefer to keep the Nodes names simple as well, so maybe just add the postfix Node when we know there is a transformation with the exact same name?

I think it should consistent i.e. either they all have Node as postfix or None do, otherwise it will make the API confusing.

**Comment by hiker** [comment]
I have the first pull request for extract+profile nearly ready, but we need to agree on the names, and I agree with @rupertford that consistency would be good.

Some transforms added 'Region' to the name (ExtractRegion, ProfileRegion) when they are based on RegionTrans (though not all, e.g. AccDataTrans or OMPParallelTrans). My suggestion: we remove all 'Trans' and 'Region' from the name when moving them into the final directory (psyir/transformations; or domain/API/transformations).

Then in order to avoid potential name clashes with the corresponding Node class, I would then say to add "Node" to all PSyIR node classes. Example:
```
user_code():
    from psyclone.psyir.transformation import Profile
    # or: from psyclone.domain.lfric.transformation import LFRicTransformation
    ....
    profile = Profile()
    profile.apply(node_list)
...
Profile.apply():
    from psyclone.psyir import ProfileNode
    ...
    node = ProfileNode(children, parent).
```

But I am equally happy with any other combination you can agree on :) One obvious alternative would be to put all psyir nodes into a subdir of psyir (psyir/nodes??), then we import from ``psyclone.psyir.nodes``.


Re \_\_init__: That works indeed fine, and is a great shortcut! In case that someone else stumbles over this: I had some issues with circular dependencies when I used the 'shortcut' name inside the module, so I had to use:
```
from psyclone.psyir.transformations.region_trans import RegionTrans
#Elsewhere I could use:
#from psyclone.psyir.transformations import RegionTrans
```
Maybe that's a temporary issue because I only moved some classes around.

**Comment by arporter** [comment]
I think that must be a temporary issue - I've not hit similar problems.
In #468 I'm in the process of adding a `psyir/nodes` directory to contain a new `DataType` class (since it's used by both Literals and DataSymbols).
I vote for all Nodes to have the "Node" suffix but am happy to lose "Region" and "Trans" from the transformation names.

**Comment by rupertford** [comment]
If I have to choose then I think having Trans as a postfix makes it obvious what it is so would vote to keep it, but it sounds like I'm in the minority. Let's vote on Wednesday.

**Comment by hiker** [comment]
I have more the feeling @rupertford and @TeranIvy want to keep Trans, and @arporter  and @sergisiso don't mind removing it, but seem to be more ... neutral??

I am kind of neutral, too tbh - with Sergi's __init__ trick most of the imports are a shorter now, so I am ok with leaving 'trans' as postfix.

Same with having 'node' or not as postfix. At this stage we have some with (ExtractNode, ProfileNode, ...), some without (*ACCEnterDataDirective, ...). I'm happy to leave it this way, or make it consistent one way or another - tbh, I like the sound of both ExtractNode, but also ACCEnterDataDirective (adding 'Node' to that makes it quite a mouthful).

**Comment by arporter** [comment]
I am more neutral and happy to keep Trans. However, I do also think that we should add "Node". In the specific case of ACCEnterDataDirective we could drop the "directive" since I don't think we use that on other nodes that also happen to be directives.

**Comment by hiker** [comment]
Summary from telco: all transform will have 'Trans' as postfix, all nodes will have 'Node', and 'Region' is going to be removed from the transformation names. And for the record (so he can say later: I told you so): @sergisiso preferred the shorter version 😁

**Comment by sergisiso** [comment]
With #669 and #657 . The error classes and `Node`, `Schedule`, `Return`, `Assignment`, `Operation`s,  `Reference`, `Array`, `IfBlock`, `Loop`, `CodeBlock`, `Container`, `Literal` have been moved outside psyGen bringing it down to ~4200 lines.

The remaining PSyIR nodes in psyGen are:
- Directive (and sub-classes)
- GlobalSum, HaloExchange
- Kern (and CodedKern, InlinedKern, BuildIn)
- InvokeSchedule, KernelSchedule

For the mentioned classes I have some doubts where it is the barrier between being PSyIR core nodes and PSyLayer specific functionality. So I would not continue the restructuring until we discuss and have more clarity about this.

**Comment by hiker** [comment]
I think we can close this ticket. The new directory structure has been in place, and while some files still need splitting, this can (as usual) just be done when someone works on classes in these 'super-files'.
