### ISSUE TITLE
Fix move transform for NEMO API

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#481]
I have a quick fix to make the move transform working with the nemo api:
```

         parent = node.parent

-        my_node = parent.children.pop(node.position)
+        old_position = node.position
+        my_node = parent.children.pop(old_position)
+        if parent._ast:
+            my_ast_node = parent._ast.content.pop(old_position)

         location_index = location.position
         if position == "before":
             schedule.children.insert(location_index, my_node)
+            if parent._ast:
+                schedule._ast.content.insert(location_index, my_ast_node)
         else:
             schedule.children.insert(location_index+1, my_node)
+            if parent._ast:
+                schedule._ast.content.insert(location_index+1, my_ast_node)

         return schedule, keep
```
So I basically manipulate the AST (if available) same way as the PSyIR. 

I am just not sure if you are interested in putting this in - should we just wait for the PSyIR to be fully supported instead?

**Comment by arporter** [comment]
If this is something you need for ROMS now then I would suggest creating a PR (provided that there's not lots of overhead in doing so - e.g. writing tests etc.). I'm not sure how long it's going to take to get a fully functional PSyIR->Fortran backend (something to discuss at the telco?).

**Comment by hiker** [comment]
At this stage I don't need it immediately, and will instead focus on working on the Fortran backend to PSyIR instead.
