### ISSUE TITLE
Broken OMP private variable detection or ... missing parent??

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#483]
Fixing the handling of loop boundaries (i.e. they are now available in PSyIR, not just as a string) broke my detection of OMP private variables:
```
    !$omp parallel default(shared), private(cff1,cff2,i,j)
    Jstr = BOUNDS(ng) % Jstr(tile)
...
    !$omp do schedule(static)
    DO j = Jstr, Jend
      DO i = IstrU, Iend
        cff1 = 0.25_r8 * (vbar(i, j, krhs) + vbar(i - 1, j, krhs) + vbar(i - 1, j + 1, krhs))
        cff2 = SQRT(ubar(i, j, krhs) * ubar(i, j, krhs) + cff1 * cff1)
...
    !$omp end parallel
...
    DO j = Jstr, Jend
```

Now this code needs #478 (to disable the node type check in the omp transform, which on master does not allow the assignment to be done in parallel) in order to work.

Issue is that in the past jstr was only detected with one WRITE access (because the READ in the loop was not detected).

My detection of omp private variables now sees a write statement, followed by a read statement, and decides to make jstr a private variable. Which then breaks the second loop, since now jstr is not initialised.

I totally agree that the handling of scalar variables need to be improved (ideally by renaming variables to distinguish shared and private use ... ROMS often uses the same variable sometimes shared, sometimes private in the same OMP region), but this is a complicated issue ;)

I decided to just improve my private variable detection  above by checking if the write (that triggers the declaration of jstr being a private one) happens in a loop. This way I can distinguish the handling WRITE followed by READ access of jstr as shared, and cff1 as private. So if I find a write followed by read access, I go up in the tree, till I either find the omp parallel (do) directive, or I find a loop. If it is a loop, the variable must be private. Unfortunately this does not work, since I get a node without a parent before the loop node is reached. Here the tree I see following the _children attribute (and I indicate the parent as well):
```
OMPParallelDirective
  Assignment
  ...
  OMPDoDirective: parent: OMPParallelDirective
    NemoLoop: parent: OMPDoDirective
      Start
      Stop
      Step
      Schedule: parent: NemoLoop
        NemoLoop: parent: Schedule
          Start
          Stop
          Step
          Schedule: parent: NemoLoop
            NemoKern (via _kern_schedule, attribute, not _children):  --> NO PARENT
              Assignment: parent: NemoKern
              Assignment
              Assignment

```

The NemoKern node does not have a parent, so I never reach the loop (and I should go up till I reach the OMPDoDirective node in order to make sure the assignment is indeed in a parallel node).

There is an easy fix:
```

diff --git a/src/psyclone/nemo.py b/src/psyclone/nemo.py
index 652efa4f..33ad863c 100644
--- a/src/psyclone/nemo.py
+++ b/src/psyclone/nemo.py
@@ -352,6 +352,7 @@ class NemoKern(CodedKern):
         self._ast = parse_tree
         # Create a kernel schedule
         self._kern_schedule = KernelSchedule(self._name)
+        self._kern_schedule._parent = self
         # Attach the PSyIR sub-tree to it
         self._kern_schedule.children = psyir_nodes[:]
         # Update the parent info for each node we've moved
```
Or properly: pass self as parent to the constructor of KernelSchedule and set parent in the constructor. And it might also be that the issue is that the CodedKern constructor is not called(?)

This seems indeed to work: the write assignment in a loop finds the loop node, and this fixes the declaration. I am just not sure if this is the way to go (and it might need to be done for the other APIs as well, and/or in a base class instead).

Is there a reason why the Kernel Schedule does not have a parent?

**Comment by hiker** [comment]
While @rupertford pointed out that there is a reason (switch between different kind of trees), the fact is that it is important that we can find all parents, so we need this pointer back.

@rupertford suggested that we might consider a different names functions (similar to NemoKern using _kern_schedule), but imho this makes it unnecessary complicated to go up in the tree: instead of
```
while not right_node_found(node):
    node = node.parent
```
we would have to do something like:
```
while not right_node_found(node):
    if hasattribute(node, _parent):
        node = node.parent
    else:
       node = node.get_parent_in_other_tree_type
```
So unless someone complains, I'll add the reference to the parent.

**Comment by arporter** [comment]
Apologies for the delay in getting back to you Joerg. We discussed this in the office last week and concluded that we think it makes sense to maintain the distinction between Schedules inside kernels and those in the PSy layer. (Although Rupert did point out that we don't manage this very well in the NEMO API as yet.) Therefore, for consistency we think that the process of going up a tree and out of a (Kernel) Schedule should mirror that for diving down into a Kernel - it shouldn't be something that just happens automatically if you keep getting `parent`.

**Comment by hiker** [comment]
> Apologies for the delay in getting back to you Joerg. We discussed this in the office last week and concluded that we think it makes sense to maintain the distinction between Schedules inside kernels 

I am not disagreeing with that. Though since Rupert insists on me giving use cases: could you give a use case where this is actually used atm? I.e. if we replaced _schedule with _children everywhere, what would stop working? From my experience, just understanding/debugging the code is a lot more complex since I am never certain if I need to look for children, or some other name.

> and those in the PSy layer. (Although Rupert did point out that we don't manage this very well in the NEMO API as yet.) Therefore, for consistency we think that the process of going up a tree and out of a (Kernel) Schedule should mirror that for diving down into a Kernel - it shouldn't be something 

Again I agree - it should be the same - going down should be using children (or []), and going up using parent. So we mirror the behaviour of going up with when going down 😜 

> that just happens automatically if you keep getting `parent`.

OK, that's the point where we start to disagree ;)  I don't understand why we need to misuse the way of getting access to a child (or parent) is used to distinguish between the cases. We could (maybe) just use a different base class (Node and PSyIRNode or so?? - I admit I am not sure if this is actually possible), and then use isinstance(), or add a flag added to the object? I guess I really need to understand the use case for that.

For me an algorithm like walk_ast in fparser:
```
        if hasattr(child, "content"):
            local_list += walk_ast(child.content, my_types, indent+1, debug)
        elif hasattr(child, "items"):
            local_list += walk_ast(child.items, my_types, indent+1, debug)
```
(and same for get_child) just indicates bad code design, since it makes coding any algorithm to work on the tree a pain ... i.e. unnecessary difficulty - and that would be the kind of code I am now forced to write. I guess I don't get the use case - let's talk about it at the next conference call

**Comment by rupertford** [comment]
Hi Joerg,

My reason for wanting to have separate schedules is to do with supporting code generation in the PSy-layer and code transformation in the Kernel layer. I am particularly talking about the LFRic and gocean API's here. We want to be able to generate these codes separately and we want to have transformations that act on these layers separately. In fact that is how our transformations are currently set up. When traversing the PSy-layer I don't want to accidentally go into Kernels and when traversing Kernels I don't want to accidentally go into the PSy-layer. Keeping them as separate trees makes it easier to traverse them separately.
Now I know you have the opposite problem (you want to traverse both), but I wonder if that is due to you using the NEMO API. Now the NEMO API is different to the other APIs as we *currently* treat code within a loop structure as being kernel code. I am not convinced that this is what we should be doing. This is essentially inlined kernel code and in the LFRic and gocean APIs I would expect those to be supported by simply moving the kernel schedule into the PSy-layer, so one might expect the same thing for the NEMO API.
An alternative option would be to have the concept of an *inlined kernel* that had a parent/child relationship. However, it would really just end up being a grouping of statements (so could end up just being a schedule or perhaps some subclass thereof?).
Would adding the concept of "inlined kernels" with parent/child relationships, or simply using schedules, solve your problem?

**Comment by hiker** [comment]
Hi Rupert,

thanks for the answer.

> My reason for wanting to have separate schedules is to do with supporting code generation in the PSy-layer and code transformation in the Kernel layer. I am particularly talking about the LFRic and gocean API's here. We want to be able to generate these codes separately and we want to have transformations that act on these layers separately. In fact that is how our transformations are currently set up. When traversing the PSy-layer I don't want to accidentally go into Kernels and when traversing Kernels I don't want to accidentally go into the PSy-layer. Keeping them as separate trees makes it easier to traverse them separately.

Hmm - I think I understand that, but aren't you more interested in the fact if a node is kernel or PSy-layer? This issue itself is not a huge problem for me - it's obvious trivial to add a 'getParentSchedule' or whatever function instead of parent. But I have the feeling that we are using different kind of pointer in the tree (_schedule vs _children) because we need to distinguish the nodes - wouldn't it then make more sense to distinguish the nodes instead of distinguishing the connection between the nodes? E.g. (made up example):
```
while True:
    if node.parent.isPSYLayer(): 
        break
    node = node.parent
```
Or isinstance(node.parent, PSyLayer)  or whatever. Instead atm we need to write:
```
while True:
   if not node.parent: break
   node = node.parent
```
The first code makes it imho much more obvious what this loop is trying to achieve: find the top kernel node. The second loop looks like you are searching for the top of the tree (the subroutine or module calling the kernel?). 

And my standard example (which caused this discussion): what if you need to know if the code is part of an OMP parallel section? For gocean/dynamo you need to go out of the kernel and into the PSy-layer in order to identify this, which now requires the tree search algorithm to explicitly handle the case of going from kernel to PSy-layer.

I will try to have a look at same of the transform to understand this a bit better. My concern is only that I have the feeling we are making the code a lot harder to understand - atm it needs the implied assumption that no-parent means you go from kernel to PSy (or no child meaning from PSy to kernel). It wasn't obvious for me that this is the case - so I obviously lacked some understanding there. But still, testing the node directly if it is PSy or kernel layer is much more self-documenting.

> Now I know you have the opposite problem (you want to traverse both), but I wonder if that is due 

Yes, but I am not entirely sure if this is really NEMO specific, see my example to test if a kernel is executed OMP parallel or not. I admit it's not really a use-case ... since I am not sure that this test is actually needed in non-NEMO APIs :(

> to you using the NEMO API. Now the NEMO API is different to the other APIs as we _currently_ treat code within a loop structure as being kernel code. I am not convinced that this is what we should be doing. This is essentially inlined kernel code and in the LFRic and gocean APIs I would expect those to be supported by simply moving the kernel schedule into the PSy-layer, so one might expect the same thing for the NEMO API.

I think it depends a bit on how we are going to implement inlining. I assume a transform that takes a Kernel schedule, moves it into the PSy-layer? But then things get complicated. Now the Kernel schedule should have a parent (since it is in the PSy layer), but the children ... should they not have a parent anymore, since they are kernel? Probably not (i.e. they should have one). Not to mention renaming variables ..  OK ... ignore this, I need to think this through :)

> An alternative option would be to have the concept of an _inlined kernel_ that had a parent/child relationship. However, it would really just end up being a grouping of statements (so could end up just being a schedule or perhaps some subclass thereof?).
> Would adding the concept of "inlined kernels" with parent/child relationships, or simply using schedules, solve your problem?

I do like this concept, since it would indeed make it more obvious what type of kernel we are talking of. And we could create a Kernel from InlineKernel and vice versa using a nice transform. I am not sure about the implications of your use case, when you move kernels into the PSy-layer. I might need to look at some of the dynamo transforms to get a better understanding.

Thanks a lot!
   Joerg
