### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#484]
This will help potential contributors know what our guidelines are, see ...

https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by arporter** [comment]
I don't think this needs the full PR->review cycle but I guess we should all at least be happy with what CONTRIBUTING.md says. I've had a first stab. Any comments from @TeranIvy, @rupertford, @hiker or @sergisiso?

**Comment by rupertford** [comment]
Well done @arporter, it reads very well. I was going to suggest adding some words about labels, PR's and developing from our repo vs a clone but I think the documentation the file points to already gives enough information. I am happy with it as is.

**Comment by rupertford** [comment]
PR #528 is on master so closing this issue.
