### ISSUE TITLE
[LFRic] Incorrect handling of scalars when quadrature is present

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#488]
When a kernel has scalar arguments in addition to quadrature PSyclone seems to generate different calls depending whether the scalars are listed first or last in the `arg_type` arguments list. For instance:
```
  type(arg_type) :: meta_args(4) = (/               &
       arg_type(GH_REAL,    GH_READ),               &
       arg_type(GH_REAL,    GH_READ),               &
       arg_type(GH_FIELD,   GH_WRITE, ANY_SPACE_1), &
       arg_type(GH_FIELD*3, GH_READ,  ANY_SPACE_2)  &
       /)
  type(func_type) :: meta_funcs(1) = (/ &
       func_type(ANY_SPACE_2, GH_BASIS) &
       /)
```
will  generate this call
```
        CALL test_scalars_first_kernel_code(nlayers, scalar1, scalar2, field1_proxy%data, chi_proxy(1)%data, chi_proxy(2)%data, chi_proxy(3)%data, ndf_any_space_1_field1, undf_any_space_1_field1, map_any_space_1_field1(:,cell), ndf_any_space_2_chi, undf_any_space_2_chi, map_any_space_2_chi(:,cell), basis_any_space_2_chi_qr, np_xy_qr, np_z_qr, weights_xy_qr, weights_z_qr)
```
whereas moving scalars to the back of the list
```
  type(arg_type) :: meta_args(4) = (/               &
       arg_type(GH_FIELD,   GH_WRITE, ANY_SPACE_1), &
       arg_type(GH_FIELD*3, GH_READ,  ANY_SPACE_2), &
       arg_type(GH_REAL,    GH_READ),               &
       arg_type(GH_REAL,    GH_READ)                &
       /)
```
generates this call
```
        CALL test_scalars_last_kernel_code(nlayers, field1_proxy%data, chi_proxy(1)%data, chi_proxy(2)%data, chi_proxy(3)%data, qr, scalar1, ndf_any_space_1_field1, undf_any_space_1_field1, map_any_space_1_field1(:,cell), ndf_any_space_2_chi, undf_any_space_2_chi, map_any_space_2_chi(:,cell), basis_any_space_2_chi_scalar2, np_xy_scalar2, np_z_scalar2, weights_xy_scalar2, weights_z_scalar2)
```
with `scalar2` being ignored and only added to the quadrature points and weights.
Moreover, `scalar2` is incorrectly assumed to be a quadrature in PSy layer declarations and quadrature `qr` is incorrectly assumed to be a scalar:
```
      REAL(KIND=r_def), intent(in) :: qr, scalar1
      TYPE(field_type), intent(inout) :: field1
      TYPE(field_type), intent(in) :: chi(3)
      TYPE(quadrature_xyoz_type), intent(in) :: scalar2

...

      ! Look-up quadrature variables
      !
      scalar2_proxy = scalar2%get_quadrature_proxy()
      np_xy_scalar2 = scalar2_proxy%np_xy
      np_z_scalar2 = scalar2_proxy%np_z
      weights_xy_scalar2 => scalar2_proxy%weights_xy
      weights_z_scalar2 => scalar2_proxy%weights_z
```
The toy program and kernels producing this output are attached with their names changed to .txt for GitHub: 
- [test_scalars_alg.f90.txt](https://github.com/stfc/PSyclone/files/3569111/test_scalars_alg.f90.txt)
- [test_scalars_first_kernel_mod.f90.txt](https://github.com/stfc/PSyclone/files/3569113/test_scalars_first_kernel_mod.f90.txt)
- [test_scalars_last_kernel_mod.f90.txt](https://github.com/stfc/PSyclone/files/3569115/test_scalars_last_kernel_mod.f90.txt)

**Comment by arporter** [comment]
I'll take this one since I touched the quadrature-related code most recently.

**Comment by arporter** [comment]
It turns out that PSyclone is actually behaving correctly according to the specification (https://psyclone.readthedocs.io/en/latest/dynamo0p3.html#quadrature) which says that the qr argument must be the last argument supplied to the kernel (in the algorithm layer). I'm not sure whether there's anything we can do to catch this user error without parsing the algorithm layer but I'll try to think of something...

**Comment by arporter** [comment]
Well, I can't think of anything so closing this.
