### ISSUE TITLE
Make the validate function of transformations public

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#492]
As summarised in #478, it would be useful for tools to be able to call validate directly, without using apply (e.g. auto tuning might need a list of valid transformations; a GUI might provide a list of allowed transformations).

This should be a simple rename, but I am holding off with this till @rupertford has reviewed @arporter's pull request, which apparently also involves validate vs _validate (I believe #407??)

**Comment by TeranIvy** [comment]
There is issue #208 to make Transformation validate public. Does this issue extend on that?

**Comment by hiker** [comment]
Oops - I wasn't aware of this. I'm closing this ticket then as duplicate.
