### ISSUE TITLE
[PSyIR] support for WHERE loops

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#497]
NEMO makes quite a lot of use of WHERE loops and therefore there's quite a bit of code that we're not able to put onto the GPU. The WHERE construct takes the form:

    where (logical-array-expr)
      array-assignments
    elsewhere
      array-assignments
    end where

**Comment by arporter** [comment]
A concrete example from NEMO:

    WHERE (ptsu(:, :, :) /= 0._wp)
      z1_st(:, :, :) = 1._wp / ptsu(:, :, :)
    ELSEWHERE
      z1_st(:, :, :) = 0._wp
    END WHERE

Obviously, within this construct, the use of array notation does *not* imply several, separate loops. Instead, this is equivalent to:

    DO jk=1, SIZE(ptsu, 3)
      DO ji=1, SIZE(ptsu, 2)
        DO ji=1, SIZE(ptsu, 1)
          IF(ptsu(ji, jj, jk) /= 0._wp)THEN
            z1_st(ji, jj, jk) = 1._wp / ptsu(ji, jj, jk)
          ELSE
            z1_st(ji, jj, jk) = 0._wp
          END IF

**Comment by arporter** [comment]
Within a WHERE or ELSEWHERE, we are requiring that all array references use explicit array syntax (e.g. `my_array(:, :, :)`). However, if a (NEMO) code developer makes a mistake and omits this explicit syntax then we have a problem because it will then appear to be a scalar reference and we won't create an indexed reference for it in the PSyIR. The only solution to this is to be able to work out whether or not the symbol is an array reference. That in turn requires the SymbolTable (which we don't yet use in the NEMO API) *and* the ability to handle USE statements without ONLY clauses :-(

**Comment by arporter** [comment]
Actually, at the moment the NEMO API does not use the Fortran backend to the PSyIR so this isn't a problem yet. A first step towards a solution would be to make the SymbolTable configurable so that we don't reject undeclared symbols and then only flag a problem if we find an undeclared, possibly scalar symbol within a WHERE construct.

**Comment by arporter** [comment]
I've opened #500 to cover this problem and I'll proceed with the assumption that we're not yet using the Fortran backend.

**Comment by rupertford** [comment]
#516 is now on master. Closing this issue.
