### ISSUE TITLE
Use SymbolTable in the NEMO API (and validate WHERE constructs)

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#500]
In converting WHERE constructs into the PSyIR the FParser2ASTProcessor has to identify which variable references within a construct are arrays. So long as the NEMO coding convention is followed this can be done by looking for refs of the form `a(:,:,:)`. However, if a developer omits the colon notation (or we are tackling a code where this convention is not used), then we need to be able to distinguish array references from scalars.

A first step towards this will be to start using the SymbolTable with the NEMO API and rejecting any constructs for symbols which we cannot identify as scalars/arrays. This will mean making the SymbolTable a bit more configurable and allowing for symbols without explicit declarations (since NEMO has lots of USEs without ONLY clauses).

**Comment by arporter** [comment]
The existing NEMO frontend creates an Invoke for each routine/program unit found in a source file, passing a pointer to the appropriate part of the parse tree each time. In contrast, the frontend used to create kernel schedules (`generate_schedule()`) expects to find a source file containing a single module which itself contains the named subroutine. It then creates a Container to represent the module and a KernelSchedule for the subroutine.

**Comment by arporter** [comment]
Every NEMO source file that we process contains a MODULE. @hiker is this true of ROMS too?

**Comment by arporter** [comment]
If we were to follow the same approach as done for Kernels then for each NEMO source file we would have a `Container` with one or more `InvokeSchedule`s as children. This seems sensible but would (at least initially) limit us to source files containing a single MODULE. It will probably also break a lot of tests in the short term.

**Comment by arporter** [comment]
I've noticed that `Fparser2Reader.generate_schedule()` actually creates a parent `Container` but returns the child `KernelSchedule`. It is also Kernel specific and therefore really ought to be `generate_kernel_schedule()`.

**Comment by sergisiso** [comment]
> I've noticed that Fparser2Reader.generate_schedule() actually creates a parent Container but returns the child KernelSchedule. It is also Kernel specific and therefore really ought to be generate_kernel_schedule().

I agree the name should be `generate_kernel_schedule`, also note that in #545 I added a second entry point called `generate_container()` that returns the whole module (useful for finding `use` global vars), it is still limited to just one module but if needed it can be easily extended (or create a new function) to return a list of containers.

**Comment by arporter** [comment]
I've generalised the Fparse2Process.get_kernel_schedule slightly and am using this to attempt to create a NemoSchedule, rather that doing this from within the constructor of the NemoInvoke. As expected, I immediately hit problems due to un-declared variables, specifically `jpi` used to dimension an automatic array. This is the subject of #584.

**Comment by arporter** [comment]
Working through the nemo tests. Discover that we don't yet support the ALLOCATABLE attribute.

**Comment by arporter** [comment]
For a single Fortran file cotaining one module with multiple subrourtines I'm currently generating:

    Container
    |
    - NemoInvokeSchedule
    |     |
    |     \_...
    |
    - NemoInvokeSchedule
    |    |
    .    \_...

whereas I expect each routine to be represented by a NemoInvoke.

**Comment by arporter** [comment]
Re-organised things so that a `NemoInvokes` has an associated `Container` and each routine is represented by a `NemoInvoke` with a `NemoInvokeSchedule`.

**Comment by arporter** [comment]
`transformations.NemoExplicitLoopTrans` is now causing failures because it creates variables but does not put them in the SymbolTable. The short term solution to this is to add some of the namespace-manager functionality to the SymbolTable. However, longer-term, we need to capture implicit loops in the PSyIR, not just for the NEMO API. In common with what is done for WHERE and SELECT, I think we probably want to convert them into a canonical representation using explicit loops (#412).

**Comment by arporter** [comment]
Now have only 8 failing NEMO tests and most of those are because one of the test files is taken from NEMO and imports `kjpts` with a 'generic' use (i.e. without an ONLY clause).

**Comment by arporter** [comment]
I can't really do anything about that until we have the concept of deferred interface on master. Once that's there then I need a configuration option that says "so long as there's a module that could be providing a symbol's definition, don't worry about it".

**Comment by arporter** [comment]
I've fixed a lot more tests but am running up against the situation where a symbol is accessed via an un-qualified USE. This is related to #586 and feels like a separate PR.

**Comment by rupertford** [comment]
PR #596 has been merged to master. Closing this issue.
