### ISSUE TITLE
[LFRic] Redundant arguments for built-in kernels

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#501]
Currently, a kernel call implies generating getters to number of degrees of freedom (`ndf`), unique degrees of freedom (`undf`), number of layers (`nlayers`) and mesh object (`mesh`). All of them are required for the user-supplied kernels but not for the built-in kernels as they loop over dofs and get their upper loop bound directly from the proxy of the field they loop over. 

For example
```
do i = 1,3
  call invoke( setval_c(physical_wind(i), 0.0_r_def) )
end do
```
in [diagnostic_alg_mod.x90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/algorithm/diagnostic_alg_mod.x90) produces
```
      ! Initialise number of layers
      !
      nlayers = physical_wind_proxy%vspace%get_nlayers()
      !
      ! Create a mesh object
      !
      mesh => physical_wind%get_mesh()
      !
      ! Initialise number of DoFs for any_space_1_physical_wind
      !
      ndf_any_space_1_physical_wind = physical_wind_proxy%vspace%get_ndf()
      undf_any_space_1_physical_wind = physical_wind_proxy%vspace%get_undf()
      !
      ! Call kernels and communication routines
      !
      !$omp parallel default(shared), private(df)
      !$omp do schedule(static)
      DO df=1,physical_wind_proxy%vspace%get_last_dof_halo(1)
        physical_wind_proxy%data(df) = 0.0_r_def
      END DO 
      !$omp end do
```
which then confuses Cray Intel compiler
```
ftn-5001 ftn: ERROR INVOKE_4, File = diagnostic_alg_mod_psy.f90, Line = 677 
  Local variable "NDF_ANY_SPACE_1_PHYSICAL_WIND" is assigned a value but never used.

ftn-5001 ftn: ERROR INVOKE_4, File = diagnostic_alg_mod_psy.f90, Line = 677 
  Local variable "UNDF_ANY_SPACE_1_PHYSICAL_WIND" is assigned a value but never used.

ftn-5001 ftn: ERROR INVOKE_4, File = diagnostic_alg_mod_psy.f90, Line = 677 
  Local variable "NLAYERS" is assigned a value but never used.

ftn-5001 ftn: ERROR INVOKE_4, File = diagnostic_alg_mod_psy.f90, Line = 677 
  Local variable "MESH" is assigned a value but never used.
```
The above is an error in Cray compiler. It would be useful, though, no to generate redundant getters for built-ins.

**Comment by TeranIvy** [comment]
Another example of redundant arguments for built-in and general-purpose kernel is
```
call invoke( X_minus_Y( rho_diff, rho_num, rho_analytic ),                            &
             dg_matrix_vector_kernel_type( w3_rho_diff, rho_diff , mm_w3 ),           &
             X_innerproduct_Y( sum_diff, w3_rho_diff, rho_diff ),                     &
             dg_matrix_vector_kernel_type( w3_rho_analytic, rho_analytic , mm_w3 ),   &
             X_innerproduct_Y( sum_analytic, w3_rho_analytic, rho_analytic ) )
```
in [diagnostic_alg_mod.x90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/algorithm/diagnostic_alg_mod.x90) where a call to built-in kernel assumes an operator is used (as in [dg_matrix_vector_kernel_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/kernel/dg_matrix_vector_kernel_mod.F90)) so it generates redundant `ndf` and `undf` for operators which also leads to Cray compiler crashing
```
ftn-5001 ftn: ERROR INVOKE_2, File = diagnostic_alg_mod_psy.f90, Line = 390 
  Local variable "UNDF_ANY_SPACE_1_W3_RHO_ANALYTIC" is assigned a value but never used.

ftn-5001 ftn: ERROR INVOKE_2, File = diagnostic_alg_mod_psy.f90, Line = 390 
  Local variable "NDF_ANY_SPACE_1_W3_RHO_ANALYTIC" is assigned a value but never used.

ftn-5001 ftn: ERROR INVOKE_2, File = diagnostic_alg_mod_psy.f90, Line = 390 
  Local variable "NDF_ANY_SPACE_1_W3_RHO_DIFF" is assigned a value but never used.

ftn-5001 ftn: ERROR INVOKE_2, File = diagnostic_alg_mod_psy.f90, Line = 390 
  Local variable "UNDF_ANY_SPACE_1_W3_RHO_DIFF" is assigned a value but never used.
```
The generated PSy layer is attached in txt format:
[diagnostic_alg_mod_psy.f90.txt](https://github.com/stfc/PSyclone/files/3589626/diagnostic_alg_mod_psy.f90.txt)

**Comment by rupertford** [comment]
Hi @TeranIvy, I agree that we should try to avoid redundant code in general and that this should be fixed. However, I am surprised that Cray considers assigning to local variables and not using them an error. What flags are being used on the Cray compiler in this case? I am wondering if they are ones that specify warnings should be treated as errors?

As a more general comment, I don't think there is necessarily a direct mapping between builtins and iterating over dofs and user kernels and iterating over cells. I know that this is what we have at the moment, but I can envisage us writing builtins that iterate over cells in the future (matvec for example) and users writing kernels that iterate over dofs (perhaps some specialised operation).

**Comment by AdamVoysey** [comment]
This was compiled additionally using the compiler flags `-M E287,E5001`

**Comment by rupertford** [comment]
For the record @AdamVoysey explained that the above flags are required for him to chase bugs in the compiler (associated with constructors).

A side effect is that unused variables in PSyclone-generated code now also cause the compiler to fail.

We've not worried too much about unused variables in the past, as the compiler will typically remove them and it is easier to just add something in when generating code rather than code for particular conditions.

However it should not be a difficult task to add in appropriate clauses and it will help Adam when debugging.

**Comment by TeranIvy** [comment]
Closing the issue as a duplicate of #269 and the related PR #273. I can confirm that the unnecessary code is no longer generated by PSyclone 1.8.1 as that led to small KGO changes in one of LFRic miniapps when moving to PSyclone 1.8.1 (see LFRic [ticket 1926, comment 29](https://code.metoffice.gov.uk/trac/lfric/ticket/1926#comment:29)).
