### ISSUE TITLE
Add support for the Fortran SIZE() intrinsic to the PSyIR.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#502]
In #497 we need to construct loop bounds using the Fortran SIZE intrinsic. The PSyIR does not yet have support for this. I'm unsure how to do this in a language-agnostic way since languages like C don't provide this functionality - it's entirely up to the programmer to keep track of how much memory they allocated to a variable.

**Comment by sergisiso** [comment]
This would also help with #440 and #412

**Comment by rupertford** [comment]
pr #503 is on master so closing this issue.
