### ISSUE TITLE
Include a PSyIR section in the User Guide

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#504]
Right now the description of each PSyIR node and how to interact with them is mostly found on the Developer's Guide. However, this information is necessary for writing and manipulating the PSyclone scripts which is part of the HPC-expert User role of PSyclone, so it would make sense to bring the PSyIR descriptions to a new section in the User Guide and leave just the internal details and reasoning on the Developer's Guide.

**Comment by arporter** [comment]
I could do this as part of #505 since I need to document the indexing of the text view of the PSyIR. Actually, on reflection, it might be better (smaller PR) if I just create an initial PSyIR section and put my new bit in it but leave the moving of content from the dev guide for this Issue?

**Comment by sergisiso** [comment]
The User's Guide PSyIR section has been written through multiple PRs, I will close the issue now.
