### ISSUE TITLE
Labeled section groups and home page in the User Guide

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#509]
Thinking about there to add #504 I thought it is already a bit difficult to find things in the User Guide. Maybe something like grouping the sections with common topics (see blue labels in
https://docs.readthedocs.io/en/stable/ ) would make it easier.

Also the empty Home page with the long TOC when first opening the RTD is something that should be improved.

This would be an easy change as it just requires updating the index.rst (all the other files stay the same). I propose something like:

Move Intro to the top of Home page and reduce the number of layers in the TOC

[Introduction]
- 	Getting Going
- 	Examples
- 	System-specific Set-up for Users
- 	Configuration
- 	Changelog (if we could generate this automatically)

[PSyKAl] (For the science domain user)
- 	Kernel Layer
- 	Algoritm Layer
- 	PSy Layer
- 	Built-ins

[PSyclone Scripts] (For the HPC user)
- 	PSyclone Scripts
- 	Distributed Memory
- 	The PSyIR
- 	Transformations

[APIs] (do we still call them APIs?)
- 	Dynamo 0.3
- 	GOcean 1.0
- 	Nemo

[Utilities]
- 	Stub Generation
- 	PSy Kernel Extractor
- 	Profiling

[Conventions/Gotchas ?]
- 	Line Length
- 	Fortran Naming Conventions

Bibliography

What do you think?

**Comment by arporter** [comment]
I like that suggestion - it makes the documentation more user-friendly. Possibly we're replacing "API" with "front-end"?

**Comment by sergisiso** [comment]
My worry with "front-end" is that can be misleading with the  compiler front-end terminology, which for the PSyIR would the fparser2 at the moment. But I don't have a better suggesting.

**Comment by rupertford** [comment]
I like the suggestion too.

If we're going to continue to use back-ends to describe transforming from PSyIR to something else then I think we should have front-ends to describe transforming from something else to PSyIR.

The one change I would make to the proposed structure is to put APIs/Front-Ends before PSyclone scripts as this section is also for the science domain user so follows PSyKAl naturally and would need to be introduced before transformations/scripts in any case as some of these are API/front-end specific.

Oh, and isn't linelength a utility?

**Comment by arporter** [comment]
PR now on master.
