### ISSUE TITLE
[PSyIR] Support OMP directives for NEMO

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#512]
I never opened a ticket for what I am working on ... and I only new realised that I was supposed to put the ticket reference in my commits - I admit I didn't know, but will do so now.

@arporter , @sergisiso I just have one question: I run into a few PSyIR issues (i.e. certain structures are not yet supported). I am working around those issues, but need to add # TODO. My question: is there a general 'finish PSyIR' ticket, or should I open a new generic ticket (we could add a todo list in that ticket), or should I open a ticket for each and every node type not working?

In case that you want to have a look: https://github.com/stfc/PSyclone/tree/psyir-support-directives. This is what I do in the directive visitor to handle missing nodes:
```
           try:
                result_list.append(self._visit(child))
            except VisitorError:
                # TODO: Ignore unsupported nodes for now, to allow all
                # tests to work.
                result_list.append("Node type {0} not yet supported\n"
                                   .format(type(child)))  
```

**Comment by sergisiso** [comment]
I am a bit confused about why do you need this try/except instead of just `self._visit(child)`. Wouldn't unsupported features be in Codeblocks. So the Fortran back-end may still generate them without returning a VisitorError and the C back-end should just fail anyway.

If it is just temporal code to make things work before the full PR is finished I don't think the # TODO needs to reference an issue if it is not going into master.

**Comment by hiker** [comment]
I need this in order to test gocean, to see if the visitor pattern works with that API as well, which has unknown pattern. I also have implemented the directives for C, which I want to test, but it has as well missing nodes. For example, the visitor would return:
```
$omp parallel private(i,j)
Node type <class 'psyclone.gocean1p0.GOLoop'> not yet supported - Visitor Error: Unsupported node 'GOKern' found: method names attempted were ['gokern_node', 'codedkern_node', 'kern_node', 'node_node'].
!$omp end parallel
```
(though renaming 'nemokern_node' to 'kern_node' seems to fix that problem :) I still need to verify that )

So it's more of a problem with C:
```
#pragma omp parallel private(i,j)
{
Node type <class 'psyclone.gocean1p0.GOLoop'> not yet supported - Visitor Error: Unsupported node 'GOLoop' found: method names attempted were ['goloop_node', 'loop_node', 'node_node'].
}
```
And while I am tempted to just implement a few additional basic C functions, this is not exactly high priority for me, and I might be interfering with what you (and others) are doing, so I won't :)

Yes, the subject of this ticket is ... nemo, but I designed the directives handling so that it works easily with C (like 2 2-line functions in c.py if we ignore comments),so I am just throwing this in as well but need to test it.

**Comment by sergisiso** [comment]
Ah I see what you are trying to do but unfortunately `*kern_nodes` (PSy-layer kernel calls) are not implemented in the back-ends yet, so I think it will just work for inlined code for now. Maybe you could replace the `kern` with a `assignment` in your tests or monkeypatched to return an empty string?

**Comment by hiker** [comment]
Good idea ... I thought I take the easy way ... just walk the parsed GOcean code and find an assignment ... but of course (see #483, specifically https://github.com/stfc/PSyclone/issues/483#issuecomment-530179573 - not accidentally going from PSylayer to kernel) that didn't work. So I ended up with something like
```
omp_sched[0].children[0].loop_body[0].loop_body[0].get_kernel_schedule()
```
OK, I could probably use two walks (one to find the GOKern, then one more to find the Assignment). But it seems to be easier to use:
```
    assignment = Assignment()
    lhs = Literal('a')
    rhs = Literal('b')
    assignment.addchild(lhs)
    assignment.addchild(rhs)
```
which just seems to work as well. I think with some minimal work that should even work for the C case.

Thanks!

**Comment by hiker** [comment]
OK, this ticket went somewhat off topic (but was extremely useful), so I'll close this and will open separate tickets for various issues related to PSyIR then. Thanks for your help, @sergisiso
