### ISSUE TITLE
[SIR] Add support for ifs

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#513]
The SIR supports if conditions as does the PSyIR. Therefore support to translate ifs from PSyIR to SIR should be added to the PSyclone SIR back-end.

**Comment by rupertford** [comment]
Created branch 513_sir_ifs

**Comment by rupertford** [comment]
If we generate SIR in the order in which PSyIR nodes are visited then for ifs we end up with a lot of nested functions for if statements.
For example, in the following code the first argument to the `make_if_stmt` would contain the condition part, but this is not working at the moment, the second argument contains a `make_block_statement` which itself contains a list of all the assignment statements in the then part of the if statement and the third argument has a similar structure to the second argument but for the else part of the if statement.
'''
if_stmt = make_if_stmt(***, make_block_stmt([make_assignment_stmt(
  make_field_access_expr("zslpx", [0, 0, 0]),
    make_binary_operator(
      make_literal_access_expr("0.5D0", BuiltinType.Float),
      "*",
      make_binary_operator(
        make_field_access_expr("zwx", [0, 0, 0]),
        "+",
        make_field_access_expr("zwx", [-1, 0, 0])
        )
      ),
    "=")]), make_block_stmt([make_assignment_stmt(
    make_field_access_expr("zslpx", [0, 0, 0]),
    make_literal_access_expr("0.0D0", BuiltinType.Float),
    "=")]))
])
'''
Therefore the `make_if_stmt` function contains functions which will create all of the code within the if. This could be a lot of code in general (more loops, more if etc) so I think a different approach will need to be taken at some point.
One option would be to create the condition, then and else parts separately and then bring them together. To do this I think the if would need to be computed within another Python function as, at the moment it is computed within a list which means it is not possible to create temporary variables.

**Comment by rupertford** [comment]
At the moment I am not able to generate the condition part of the if as there does not seem to be a way of creating a logical comparison e.g. (a > b). I've asked Carlos about this.

**Comment by rupertford** [comment]
Carlos forwarded the question to Tobias Wicky who explained that I should use a BinaryOperator. After some testing I can now generate ifs. The condition needs to be a statement therefore I need to wrap the binary operator in an expression statement : `make_expr_stmt(make_binary_operator(lhs, "!=", rhs))`

I found a couple of issues which I passed on to him.

1) there is a bug in the Python if wrapper in the current version of dawn (In python/dawn/sir.py function make_if_stmt(), if I change the three lines with stmt.expr.*  to stmt.cond_part, stmt.if_part and stmt.else_part then code is generated rather than me getting an exception.)
2) There are no tests for the operator when using `make_binary_operator` so you can put anything in there.

**Comment by arporter** [comment]
#517 is merged, closing issue.
