### ISSUE TITLE
[NEMO] Insertion of profiling around a CASE block fails

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#519]
Since a CASE has no direct representation in the PSyIR the business of getting a pointer back into the parse tree is a bit ropey and in some circumstances we fail to get that location right.

**Comment by arporter** [comment]
Unfortunately, my 'fix' breaks the test for profiling of case statements. I need to re-visit the actual bug I found when processing NEMO source...

**Comment by hiker** [comment]
Fixed in #522 .
