### ISSUE TITLE
[nemo] fparser2 frontend does not handle REAL intrinsic with two arguments

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#529]
Currently, processing code such as `REAL(jk, wp)` results in a `CodeBlock` whereas it should give a `BinaryOperation`.

**Comment by arporter** [comment]
I'm taking the opportunity to support `INT(jk, wp)` too. I suspect this Issue will fix some of the `CodeBlock`s found in #336.

**Comment by arporter** [comment]
There is a question as to whether/how to represent e.g. `REAL(jk, wp)` in the (ideally) language-agnostic PSyIR since that expression means convert `jk` to the type specified by the Fortran `kind` value held in `wp`. The result of this operation is then dependent on the compiler (and compiler flags). In order to have a hope of generating e.g. the equivalent C for this expression we would need some externally-supplied information on what a kind of `wp` means on the current platform.
What do @sergisiso and @rupertford think? We could simply literally represent this (Fortran-specific) expression in the PSyIR and punt the problem to the backend?

**Comment by rupertford** [comment]
> What do @sergisiso and @rupertford think? We could simply literally represent this (Fortran-specific) expression in the PSyIR and punt the problem to the backend?

I think we should aim to support the concepts rather than something language specific (but I think this probably ends up being the same thing i.e. the Fortran information is generic) ...

The idea of converting a variable from one type to another is pretty generic so it seems reasonable to add that, (but probably limit support to integer->real to start off with?).

I guess the main problem is the size of the type i.e. real*4, real*8 etc. It seems to me that we therefore need the concept of size as well for a type. This is, of course, information we would expect a Symbol to have as well. I was going to say that we should be able to infer the type and size from the LHS, but someone might write something weird like:

```iresult = (integer,(real(iscalar1,wp) / real(iscalar2,wp))```

So in general I think we do need to add the size concept to the Symbol and conversion function.

The size concept could be
1) a known value in bytes (1,2,4,8,16) or
2) an unknown value with an associated label. This label should then be used in all cases where the same (unspecified) size is required (and perhaps we should have a `default` label as well?). It would then be configuration information that would need to supply appropriate mappings for unknown sizes to the back ends.

Would that work?

**Comment by sergisiso** [comment]
I think the use case we always have, at least in gocean and LFRic is that it is an unknown value. It is `kind=go_wp` or `kind=r_def` which are defined in the infrastructure and therefore unknown for PSyclone (at least for now).

Would it be an easier solution to just consider `real(i,wp)` as `real(i)` which we already support. Then have an assumption (or a config parameter) that says the backend to work always with a certain type of precision?

The full type/size infrastructure it is a better solution, but this seems like a big task to me.

**Comment by arporter** [comment]
Given that there are plans in LFRic to support mixed precision (I think that means that certain kernels will work with a lower precision), we are already looking at a situation where we can expect to have fields with different kind parameters. We already have PSyIR support for `REAL(jk)` and `INT(x)` which is a bit lax at the moment - I think we assume 8-byte reals and 4-byte integers, or at least that they map to `(float)jk` and `(int)x` in C? Allowing for a size property that is either a number of bytes or a label seems like the best solution.

**Comment by arporter** [comment]
We've just had a discussion about this and agreed that a `Symbol` needs a new `size` property that can be either a `value`, a `reference` (to a Symbol holding the KIND parameter) or `None` if it is a default type (e.g. `real` with no KIND specified).

**Comment by arporter** [comment]
I've brought the branch up-to-date with master. It turns out that all I'd actually done was add REAL and INT as members of BinaryOperator. I've not addressed the meaning of the second argument which is where the complexity is.
@rupertford this is a NEMO-related issue identified by Chris. You'd be very welcome to pick it up (given that I've pretty much done nothing on it so far) :-)

**Comment by arporter** [comment]
Simon Mueller has just reported encountering this problem when using PSyclone on MEDUSA. Given all the work done on adding type information to the PSyIR I think it's time I took another look at this.

**Comment by arporter** [comment]
The optional, second argument to the Fortran `REAL` intrinsic is:

    An INTEGER initialization expression indicating the kind parameter of the result.

The question is, how does this map to a representation of a type conversion in the PSyIR?

**Comment by arporter** [comment]
I think the only language-independent way of dealing with the precision of the conversion is to store the number of bytes needed to represent the result. This means that the second argument must be mapped to a number of bytes. In the general case, the second argument will be a kind parameter, e.g. `r_def` for LFRic or `wp` for NEMO. In an ideal world we would chase down this parameter and find its definition. However, this could be expensive if the parameter isn't named in an `ONLY` list. In the worst case, it could even be a variable (i.e. known only at run time) rather than a parameter although this seems unlikely.
We could therefore add some domain-specific configuration and capture the storage size associated with each kind parameter used in a code.
Having said all that, we only need to get hold of a number of bytes if we're using a different language in the backend. Until that point we can simply keep a reference to the symbol defining the size?

**Comment by arporter** [comment]
After some discussion on Teams, we have agreed that we should use the same mechanism that we currently have for capturing the precision of Literals. (Even though there is possibly more work to do there to deal with the fact that a Fortran KIND does not directly map to precision.)

**Comment by arporter** [comment]
Currently, precision is a property of the `ScalarType` class:

https://github.com/stfc/PSyclone/blob/6749f7fba97846d9a661329580acb0ddd94a95f2/src/psyclone/psyir/symbols/datatypes.py#L158-L179

whereas I think I now need precision as a separate class.

**Comment by arporter** [comment]
Looking at 13.5 of the Fortran standard and testing with gfortran, I now realise that the KIND argument to the REAL() intrinsic must be a parameter (compile-time constant). However, as with other Fortran parameters, arithmetic expressions are permitted, e.g.:

    REAL(ivar, 2+2)

is fine.

**Comment by arporter** [comment]
Currently the `BinaryOperation.create()` method will accept any operands that are instances of `DataSymbol`. Mostly this is fine but for the REAL operation, there is an additional constraint that the second argument cannot be of floating point type. If coming from Fortran, any referenced symbols must also be compile-time constants but that's harder to check.

**Comment by arporter** [comment]
This has two aspects I think: 

 1. the need to be able to do type checking of symbols (#658)
 2. should we have a new subclass, e.g. `RealBinaryOperation` so as to permit the operation-specific checks?
