### ISSUE TITLE
How to get examples for non-developers

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#530]
I just had a user trying to learn psyclone. He installed psyclone from pip (1.7.0) ... but then he didn't have access to the examples at all. The user doc only mentions to look at the examples subdirectory, which is very confusing.

We need at the very least explain in the PSyclone documentation (user's guide) that you need to clone the git version in order to get the examples (you don't need to install it obviously). But maybe we should consider providing the examples? No idea how to do this best and automatically. Maybe a separate psyclone-examples package?

**Comment by TeranIvy** [comment]
I agree that the very least is to mention this in the user guide. Another thing which is not clear in the user guide is when `$PSYCLONE_DIR` refers to the location of PSyclone installation and when it refers to location of PSyclone repository clone. As @hiker commented, different things are available from each.
Finally, I think the examples should be included with the installation.

**Comment by arporter** [comment]
As part of an investigation into the use of Jupyter notebooks (for training), we realised that we needed the Fortran source files that are part of the examples. I've therefore developed a way of getting the examples installed. From reading the documentation it sounds like MANIFEST.in should do what we want but possibly it only controls what gets put in the WHEEL. I've therefore also added code to setup.py that enumerates all the files we want to install and specifies them via the `data_files` argument to `setup()`.

**Comment by rupertford** [comment]
PR #576 is now on master so closing this issue.
