### ISSUE TITLE
[PSyIR] Translate sign(), min() and abs() intrinsics to explicit code

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#536]
The NEMO tracer advection benchmark makes use of sign(), min() and max() intrinsics. These are captured by the PSyIR but are not supported in the SIR. Transformations should be added to transform PSyIR from intrinsics to inline code.

**Comment by arporter** [comment]
The only use of MAX in the tracer-advection code is in a loop that accesses 2D arrays and is consequently commented-out (because we're not yet sure what to do about 2D arrays in SIR). Therefore, this issue (PR #541) has only implemented transformations for MIN, SIGN and ABS.

**Comment by arporter** [comment]
#541 is merged, closing
