### ISSUE TITLE
[psyir-fe] Add support for NINT and FLOAT operations.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#537]
NEMO makes use of NINT() and this currently ends up in a CodeBlock.

**Comment by arporter** [comment]
NEMO also makes use of FLOAT() which is a non-standard extension supported by (at least) Gnu and Intel.

**Comment by arporter** [comment]
Happily, fparser does already support FLOAT.

**Comment by arporter** [comment]
NINT is one of those pesky Fortran intrinsics that takes an optional kind parameter as argument. In a recent discussion we agreed that 'kind' is a Fortran concept and therefore should not be a first-class entity in the PSyIR. i.e. `NINT` is really a unary operator but we need to keep a record of the KIND parameter so that a backend can attempt to produce the correct equivalent code (using e.g. some config. file that provides a mapping from kind parameter to the actual precision of the variable).

**Comment by arporter** [comment]
Thus far, we've used the `annotations` property of a PSyIR node to hold details on the (Fortran) code from which it originated. We could continue with this approach in this case and simply add a `kind=blah` annotation. Since annotations are simply stored as a list of strings at present, this may require them to be made a bit more sophisticated (maybe a `dict`?). However, a kind parameter can also be supplied via the `KIND` query intrinsic, e.g. `NINT(a, KIND(1.0d0))` or even `NINT(a, KIND(b))` at which point things get complicated. Should we keep the PSyIR for the second argument? That doesn't seem possible because, as already mentioned, 'kind' is a Fortran concept and therefore the `KIND` intrinsic is peculiar to Fortran.

**Comment by rupertford** [comment]
In Fortran, given ```R = NINT(A, KIND(B))```, the KIND(B) argument appears to specify the type of the result R. If this is the case then could we not translate this to two things in the PSyIR i.e. ``` TMP = NINT(A); R = KIND(B) TMP```. Please forgive the fake Fortran but hopefully you get what I mean.

**Comment by arporter** [comment]
Yes, we could do that. We'll need a more general casting operator in PSyIR or at least extend what we have. Currently I think we are a bit lax and have `int` and `float` without specifying the precision of the result.

**Comment by arporter** [comment]
This brings us back to the fact that we don't capture the kind/precision of variable declarations and therefore I'm going to tackle #375 first.

**Comment by arporter** [comment]
Support for the unary form of NINT was added recently (#833 - I overlooked this issue) but we still don't yet support the binary form where the kind of the result is specified.
