### ISSUE TITLE
Use colours when viewing a schedule

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#54]
PSyclone already has a dependence on numpy and (deep) within numpy there is support for outputting coloured text to a terminal (see https://docs.scipy.org/doc/numpy/reference/distutils.html). It would therefore be nice to make use of this when `view()`ing a schedule.

**Comment by arporter** [comment]
I've created the `coloured_sched` branch for this work.

**Comment by arporter** [comment]
I've hit trouble when trying to write tests for this functionality. In the py.test environment numpy appears to conclude that the terminal does not support colours and thus does not produce the necessary control codes. I've tried monkeypatching the sys.stdout module and got the numpy `miscutil.terminal_has_colors()` routine to return 1. However, I'm not sure whether this is too late as the calls to e.g. `red_text()` still don't produce control codes.

An alternative is to use the `termcolor` package (https://pypi.python.org/pypi/termcolor). When I do this the control codes *are* generated within the test environment and all is well. However, this approach does then give PSyclone an additional dependency which seems a high price to pay for some colour.
Now that I've said that, I think I can make it an 'optional' dependency, just like graphviz...

**Comment by arporter** [comment]
Have updated things so that if termcolor is available then we use its `colored` routine. If it isn't, we supply our own `colored` routine that just returns the string it is passed. All tests pass/xfail both when termcolor is installed and when it isn't.

**Comment by arporter** [comment]
My last comment indicates a problem: how to ensure that we remember to test both with and without termcolor? Happily, travis can support multiple configurations through its `env` feature. I've modified the .travis.yml script so that it defines two different environments, one with `WITH_TERMCOLOR=1` and one with it set to zero. I've then added a custom step to the `before_install` section that runs a (new) shell script. Within that script I check the value of `WITH_TERMCOLOR` and, it is is 1, simply do a `pip install termcolor`.

**Comment by arporter** [comment]
Have to dig down into the 'raw' log provided by Travis and then you see:

    $ ./bin/install_optional.sh
    Installing termcolor package...
    Collecting termcolor
    Downloading termcolor-1.1.0.tar.gz
    Installing collected packages: termcolor
    Running setup.py install for termcolor
    Successfully installed termcolor-1.1.0

So all is well.

**Comment by rupertford** [comment]
Issue closed as pull request #63 has been merged onto master.
