### ISSUE TITLE
[PSyIR] ExtractNode and ProfileNode should both have a Schedule

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#542]
In #507 we agreed that all nodes that can have statements as children should have a Schedule. #505 implements this for directives. In this issue we'll complete the implementation by adding Schedules to ExtractNode and ProfileNode.

**Comment by arporter** [comment]
#505 is merged so this Issue is next up.

**Comment by rupertford** [comment]
pr #580 has been merged to master. Closing this issue.
