### ISSUE TITLE
[LFRic] Built-in for Fortran intrinsic sign

### ISSUE THREAD

**Issue by BShipway** [stfc/PSyclone#560]
LFRic ticket #1834 introduced psykal_lite code to return the sign of a field using the Fortran intrinsic.  This could be done with a builtin.  Example code...

`subroutine invoke_sign(field_res, scalar, field)
    use log_mod,  only : log_event, LOG_LEVEL_ERROR
    use mesh_mod, only : mesh_type ! Work around for intel_v15 failures on the Cray

    implicit none
    type( field_type ), intent(in )    :: field
    type( field_type ), intent(inout ) :: field_res
    real(kind=r_def),   intent(in )    :: scalar
    type( field_proxy_type)            :: field_proxy,      &
                                          field_res_proxy
    integer(kind=i_def)                :: i,undf
    integer(kind=i_def)                :: depth, dplp
    type(mesh_type), pointer           :: mesh => null()

    field_proxy = field%get_proxy()
    field_res_proxy = field_res%get_proxy()

    !sanity check
    undf = field_proxy%vspace%get_last_dof_owned()
    if(undf /= field_res_proxy%vspace%get_last_dof_owned() ) then
      ! they are not on the same function space
      call log_event("Psy:sign:field and result_field live on different w-spaces" &
                    , LOG_LEVEL_ERROR)
      !abort
      stop
    endif

    !$omp parallel do schedule(static), default(none) &
    !$omp&  shared(field_proxy,field_res_proxy, &
    !$omp&  undf, scalar),  private(i)
    do i = 1,undf
      field_res_proxy%data(i) = sign(scalar, field_proxy%data(i))
    end do
    !$omp end parallel do

    mesh => field_res%get_mesh()
    depth = mesh%get_halo_depth()

    do dplp = 1, depth
      if( field_proxy%is_dirty(depth=dplp) ) then
        call field_res_proxy%set_dirty()
      else
        call field_res_proxy%set_clean(dplp)
      end if
    end do

  end subroutine invoke_sign
`

**Comment by TeranIvy** [comment]
I am adding this built-in in #1107 as part of the preparations for PSyclone 2.0.0. Closing this issue as a duplicate.
