### ISSUE TITLE
Check whether force-profile is required

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#566]
Once #565 is on master it may not be necessary to have a force-profile command line option to the psyclone script as profile nodes are added after the optimisation script has been applied and this should work in the general case.

**Comment by rupertford** [comment]
Now that automatic profiling is added after any transformations, there is no need for the --force-profile option as it should always be possible to add profile nodes to an invoke or around kernels. Changes associated with #567 ensure that the generated names are valid and unique.

**Comment by rupertford** [comment]
Created branch 566_remove_force_profile

**Comment by arporter** [comment]
Associated PRs have all been merged.
