### ISSUE TITLE
Test failures with pytest 5.2.2

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#568]
This is a heads-up that upgrading pytest results in (lots of) failures in our test suite. I've not done any investigation yet but doing `pip install --upgrade pytest==4.5.0` fixes it :-)

**Comment by sergisiso** [comment]
Is it related to #438 ? That one requires to convert all `str(error)` to `str(error.value)` I think.

**Comment by arporter** [comment]
Oops, yes of course it is. I just upgraded pytest (because the `--lf` option wasn't working properly) and forgot this!
