### ISSUE TITLE
unicode support has broken master

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#571]
The unicode support added to fparser 0.0.9 has caused one of the f2pygen routines to fail (it needs to use six.string_types) and causes a number of tests to fail due to two issues:

1) writing out function space names writes u'string' for Python 2.x as it is now unicode
2) stencil values are not being extracted correctly as they are converted from string to int and this is failing now that these strings are unicode in Python 2.x.

**Comment by rupertford** [comment]
Created branch 571_unicode_fixes

**Comment by arporter** [comment]
#572 is on master.
