### ISSUE TITLE
Obtain list of supported built-ins for Dynamo 0.3 by parsing Fortran meta-data

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#58]
Currently the list of built-ins supported for the Dynamo 0.3 API is specified in the dynamo0p3 module. However, this information is also available from the Fortran file containing the meta-data for the built-in operations. In this ticket we will remove this duplication by generating the list of supported built-ins from the parsed content of the meta-data file. Was previously 588 on SRS but no work was done there.

**Comment by arporter** [comment]
Although we could generate the list of built-ins in this way I've thought of two problems that may mean it is pointless:
 1. We still need a way of mapping from the built-in name to the name of the corresponding PSyclone class - this isn't (and probably shouldn't) be in the Fortran meta-data file.
 2. Fortran is not case-sensitive and therefore we lose our nice capitalisation conventions if we get the
names by parsing Fortran.

**Comment by TeranIvy** [comment]
What if we parse Fortran file for function names and not medatada (not using fparser but Python string functions)? An example: Fortran function name `inc_X_plus_Y` can be stripped of "_" characters and all parts of the name can be capitalised to make the "core" Python name -> `IncXPlusY`. After that we need prefix "Dyn" and suffix "Kern" to make the full Python name: `DynIncXPlusYKern`. This would be also a good way to detect if anything is missing.

**Comment by arporter** [comment]
Although it would be nice to detect whether anything is missing, I think that the pain and difficulty of robustly getting hold of function names using Python string functions probably out-weighs the benefit :-(
Actually, we could add a check (to the current implementation) that every kernel described in the meta-data is present in the mapping dictionary.

**Comment by TeranIvy** [comment]
Ok, the check you suggested sounds reasonable. I guess this would be a separate issue, though?

**Comment by arporter** [comment]
I've just had a look through the code and have come to the conclusion that adding this check wouldn't significantly improve things and would make testing more complex. We already have tests for various situations (e.g. a built-in kernel missing from the meta-data file). I'm therefore going to close this issue.
