### ISSUE TITLE
GOcean: Write Kernel Data to file

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#583]
This is based on @TeranIvy's work on the extract node: it actually writes the input and output data for a list of nodes to a file, based on the dependency analysis.

The idea is that we add functionality for writing data to the infrastructure library, so PSyclone would just need to create calls to to the library in order to write data.

Some questions that need discussion:
1) what file format should we use? We can introduce our own file format, or we could use an existing format like netcdf.
2) Should we try to generalise it by providing an API layer similar to profiling, and allow different implementations to write their own file format? Eg. we could have an ASCII format, netcdf Format, my-own-special-compress-binary-format, ...  Obviously the data api #415 raises its head :)
3) While we certainly need a Fortran interface, would it be possible to do the actual writing in a C++ library? If we implement the IO layer in Fortran, we need to deal with the stupid Fortran unit numbers, ... Even if we use inquire to find an unused unit number, there is no guarantee that it might not be used later, so we need an option to specify an available unit number to use, ... messy, compared with a decent language ... and I admit: I just like C++ :)

My suggested design would be a smallish API that can read/write the required Fortran basic data types to a file (scalar, n-dimension arrays, single, double, complex(?)). The infrastructure library would then use this API to read/write its user defined data types to file. Ideally this would end up like this - pseudo code showing the call sequence from PSyclone created code via the infrastructure library to the common C-based io library:
```
  ! psyclone create code:
  call infra_library_write(my_field, "my_field")
--------------------------------------------------------
  ! infrastructure library:
   subroutine infra_library_write(my_field, name):    ! 2d functionality here
    call c_io_lib_write_2d_real(name, my_field%x_min, my_field%x_max,
                                my_field%y_min, my_field%y_max, my_field%data)
   end subroutine
--------------------------------------------------------
   
   // C io library:
   int c_io_lib_write_2d_real(name, xmin, xmax, ymin, ymax, data)
   {
     write("2d-real-array\n");
     write(xmin); write(xmax); write(ymin); write(ymax);
     write(data, (xmax-xmin+1)*(ymax-ymin+1)*sizeof(real))
   }
```
So the c_io_library would be shared between all infrastructure libraries (and could potentially be used for NEMO api  using a thin Fortran layer as well) - and different versions of the c_io library would  create different file formats.

**Comment by rupertford** [comment]
I vote for 2), providing a general API layer allowing for different library implementations. If you think that adding another f2c++ layer as part of the distribution would help developers then that is certainly fine by me but I just see that as a library implementation that happens to need another library implementation i.e. it is essentially outside of PSyclone.

**Comment by arporter** [comment]
I vote for 2) as well. I don't really care how the underlying IO is implemented as long as it's simple and portable (at least, for anything that we undertake to support).

**Comment by hiker** [comment]
Here a list of todo items - not really worth opening a ticket for each of them imho.
- [ ] Rewrite Profile documentation to use the PSyDataAPI
- [ ] Update the remaining profiling wrapper to use the new API.
- [ ] Update the psyke documentation to use the PSyDataAPI.
- [ ] Check where to put the driver generation - in ExtractNode or a special GOceanExtractNode.
- [ ] Check the usage of xstop/ystop - there seems to be different usage when using const_loop_bounds (const_loop using grid%subdomain%internal%xstop:, the other case uses internal%xstop). Make sure we get the same loop boundaries, independent of const loops boundaries or not.
- [ ] Check third xstop value - which iirc was added for most-psyclone only. Either use one of the existing xstop values, or even remove it, and leave it to the most-psyclone to provide the required values.
- [ ] Check the handling of field property - atm I don't expect them to work (at least in the driver created by the ExtractNode).
- [ ] Consider command line options to trigger kernel extraction?
- [ ] Improve detection of which variables to store - loop boundaries, and temporary (scalar?) values can be ignored? We should give the user an option to add/remove variables to the automatic list.
- [ ] Create another example library, somewhat easier than the netcdf one?
- [ ] Verify the design of the PSyData API with a 'verify-read-only-accesses-are-read-only' library.

Not all of these todo items will be finished for the first pull request. All outstanding items at the time of the pull request should be converted into stand-alone issues to be handled later.

**Comment by hiker** [comment]
Updating this ticket to scope properly which will be done in the first pull request.

I've updated the documentation.Closing the 'simpler IO library' ... since I don't think writing (and reading!) an ASCII file is significantly easier than just using netcdf - imho this optional. Maybe we could add a different simple PSyData example (e.g. print field names and checksum before/after??), but since this is optional I am just closing this todo item.

Closed some todo items after reopening separate tickets for them, see #637, #638, #639, #640, #641, adeded [PSyData] to #199 and closed corresponding todo item.

This leaves two todo items (update all profiling libraries, and move driver generator likely into a gocean-specific node), before converting this into a pull request.

**Comment by hiker** [comment]
Created a separate project to keep track of PSyData related work (https://github.com/stfc/PSyclone/projects/16?add_cards_query=is%3Aopen).

**Comment by arporter** [comment]
#650 was merged! If I could figure out how to add party emojis then I would...

**Comment by hiker** [comment]
🎉  🍸 🍰 ✨ 🎁 🍹 🏆 🎈 
For a full list (though not much of party in there)
https://gist.github.com/rxaviers/7360908

Thanks a lot, Andy - highly appreciated. And I promise further PR will be smaller.
