### ISSUE TITLE
DataSymbols can have unknown interfaces that may be resolved later

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#584]
For instance in this case:
```
real a(n)
int n
```
When we parse `real a(n)`  we want to have the symbol `n` in the symbol table but we don't know it is a local symbol until we parse the next statement.

While in the cas:
```
use mod
real(kind=a) :: b
```
`a` has an unknown interface but we probably don't need to resolve it during PSyclone execution

**Comment by arporter** [comment]
@sergisiso are you happy if I take this one?

**Comment by sergisiso** [comment]
Sure :)

**Comment by arporter** [comment]
Rupert and I have just chatted about this and have agreed that this boils down to the concept of a Symbol being allowed to have a 'deferred' interface. As a first step we can then ensure that we don't generate declarations for any such Symbols (with the assumption being that they are covered by some use statement).

**Comment by arporter** [comment]
I've branched from the 544_resolve_deferred branch for now as Sergi has been doing some heavy re-structuring in there and it's not quite on master yet.

**Comment by rupertford** [comment]
#591 is now on master. Closing this issue.
