### ISSUE TITLE
[PSyIR] kind variables are declared

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#587]
If a kind variable is provided via a use statement then the Fortran that is output may (incorrectly) declare the variable. The one case where it does not do this is if the use statement specifies the kind variable in its only list and the use statement is in the same subroutine as the declaration - it can not be in the parent module.

**Comment by arporter** [comment]
This problem is demonstrated in dynamo example 13. (It's not actually a problem there because we don't compile the generated Kernel code.)

**Comment by arporter** [comment]
This problem will be solved by #591.

**Comment by arporter** [comment]
#591 is now merged and example 13 works as expected. @rupertford - can this issue be closed?

**Comment by rupertford** [comment]
I've just confirmed it works now, so yes we can close.
