### ISSUE TITLE
[PSyIR Fortran frontend] support REAL*8 declarations

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#588]
Attempting to process the `examples/nemo/code/tra_adv.F90` file with the fparser2 frontend fails because all of the `REAL` variables are declared as `REAL*8`. (In NEMO itself KIND parameters are used so this problem wouldn't occur but we want to be general purpose.)

**Comment by arporter** [comment]
I've had to fix the original problem (REAL*8 in tra_adv.F90) as part of #500 as it was causing the examples to fail. However, we should probably add support for this form of declaration at some point.

**Comment by rupertford** [comment]
I'll take this on as I need it for the tracer advection SIR example (nemo/eg4). the PSyIR and Fortran backend now has all the required support, we should just need to get the front-end to translate into PSyIR appropriately.

**Comment by rupertford** [comment]
Created branch 588_real8_support

**Comment by arporter** [comment]
#769 is merged.
