### ISSUE TITLE
x-failing tests too 'coarse'

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#593]
I realised that some x-failing tests are failing for the wrong reasons now. Example:
https://github.com/stfc/PSyclone/blob/97c3dbaf1192268d1c978674e342d1c73f57fdbe/src/psyclone/tests/nemo/transformations/loops/loop_test.py#L102
This x-failing test now fails because there is no gen_kernel() calls anymore, and because of the addition of schedules - but not for the original reason. This particular test should be fixed in https://github.com/stfc/PSyclone/blob/1e32f90fa9506eb38bdc82b95ad539a3d92d82c1/src/psyclone/tests/nemo/transformations/loops/loop_test.py#L108 (e.g. using coded_kernels(), and other fixes), but there could be other tests.

We should investigate if pytest.xfail("...") allows for better tests.

Obviously those problems will be detected later when the original reason for the x-fail is removed (and tests then still fail), but it means that we then need to go back to fix something that was potentially changed several months ago.

**Comment by hiker** [comment]
https://github.com/stfc/PSyclone/commit/6f48a94094a2ac25e04b00c061473a3b0bac2679 shows how xfail could be used for better tests.

My suggestion is that we document this as suggested way of using xfailing tests in the dev guide as part of the above branch, and then as usual get existing xfailing tests updated when they are touched.

**Comment by arporter** [comment]
I like your suggestion and don't see any reason not to go with it.

**Comment by rupertford** [comment]
I like the idea. However, at the moment, when an xfailing test is fixed, it changes from an "x" to an "X" (assuming the test is not broken in some other way as you point out) and you are alerted at the end of the tests.

If I'm not mistaken, with your suggestion the "x" changes to a "." when an xfailing test is fixed and the xfailing code would remain as part of the test without someone "grepping" for it and removing it. If I am right then it is not clear to me which is better.

**Comment by hiker** [comment]
Good point, seeing an 'X' is quite important. Having to fix a bug that went undetected for months (because of an X-failing test) is annoying. I verified my change by removing the x-fail, but then I  noticed that actual the failure is likely not the one it was supposed to be (and I could easily have missed it). Figuring out what was supposed to fail can be quite time consuming, and atm there is no clear indication what the right error should be.

One potential solution:
```
if something_does_not_work:
    pytest.xfail("still not working")
else:
    assert("X-failing test suddenly works")
```
But I admit that is pretty annoying having to write that :(

I am neutral, we can leave it the way it is, and just accept that when we fix x-failing tests we might have to go back to figure out what is happening. Or we can recommend to write a test like the one above. My original solution might be the worst 😁

**Comment by arporter** [comment]
I thought we had things configured so that an 'X' was actually reported as a test failure? If we don't then I think we should. Would pytest.xfail then raise an error?

**Comment by hiker** [comment]
We agreed on the telco to just leave it the way it is.
