### ISSUE TITLE
Transformations should not return anything.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#595]
Currently all Transformations return a tuple of `(Schedule, Memento)`. This has always been a bit odd because we pass a reference to the relevant bit of a Schedule to the transformation and it *transforms* it in place. There is therefore no need to return the Schedule and indeeed, in many tests we ignore the returned object. Worse than that, a transformation always returns the 'root' of the tree to which the nodes it has been passed belong. In the NEMO API this now means that we get back the root `Container` node describing the whole Fortran module. Although I could probably fix this by returning the `InvokeSchedule` instead, it seems to me that it would be better not to return a Schedule object at all. What do @rupertford, @sergisiso, @hiker and @TeranIvy think?

**Comment by hiker** [comment]
I was always wondering why we are getting a new schedule - so I am good with removing this.

**Comment by arporter** [comment]
@rupertford suggests (in reviewing #615) that we could remove the memento object that is also returned since we never use it. What do @sergisiso and @TeranIvy think? Once we have an agreed strategy this issue will morph in order to implement it (if necessary).

**Comment by TeranIvy** [comment]
If we are not using Memento then I vote for removing it. As for Schedule, as long as the transformed schedule is able to be transformed by another transformation in row (I presume that this is given) and  visible via `view` or a similar method I am fine with transformations not returning it as well.

**Comment by sergisiso** [comment]
I see no problem in removing `Memento`, the user can always make a copy in the script if needed (also the memento `deepcopy` is commented out anyways (?)). I am also ok with removing the returned `Schedule` as I agree it would be more clear that the transformations are in-place.

**Comment by arporter** [comment]
Now that that's agreed, I've changed this into a 'proper' issue.

**Comment by sergisiso** [comment]
In #1229 I remove most of the return values in front of the transformation callers: `schedule, _ = transformation.apply(...` -> `transformation.apply(...` , but I have not modified the Transformation interface (still returns something that gets ignored).

After #1229 is merged this issue will be much simpler to solve.
