### ISSUE TITLE
Can ancestor function return self?

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#597]
There is some code duplication in psyGen's _get_private_list and the Node.ancestor function, see
https://github.com/stfc/PSyclone/pull/559/files/1e32f90fa9506eb38bdc82b95ad539a3d92d82c1#r347838523

At the moment ancestor() does never return self, while the loop in _get_private_list needs to be able to get self as result.

Check if ancestor can be changed to return self. The test_node_ancestor in psyGen_test fails atm, but it is possible that nothing else breaks when changing the ancestor functions (in which case we only need to adjust the test).

**Comment by rupertford** [comment]
pr #602 is on master. Closing this issue.
