### ISSUE TITLE
Implement support for CMA-related kernels

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#6]

**Comment by arporter** [comment]
I have basic support for the three types of CMA-related operation now. Chris is in the process of testing this in Dynamo.
Next stage is to extend the kernel-stub generator to support the CMA operators.

**Comment by arporter** [comment]
Everything apart from the indirection dofmaps is now pulled out of the CMA type ahead of the kernel call. I'll add the indirection dofmaps to the `DynInvokeDofmaps` next.

**Comment by arporter** [comment]
Realised that I currently assume that a column-banded dofmap on any given Function Space is the same as that from another CMA operator on the same space. Am clarifying that with @christophermaynard and @eikehmueller.

**Comment by arporter** [comment]
Eike says:

"Those maps are necessary since the ordering of dofs in the CMAs is
different from what's chosen everywhere else in Dynamo (this reordering
necessary to represent the CMAs by banded matrices). It only depends on
the spaces, not on the particular CMA, so if you have two CMAs from
which map from space_A to space_B, then we only need the maps for
space_A and space_B once."

so my assumption is good.

**Comment by arporter** [comment]
Done. I've also added a test that we do the right thing (i.e. don't pass the same maps twice) when we have an apply kernel where the to- and from-spaces of the CMA operator are the same.

**Comment by arporter** [comment]
Branch now up-to-date with master. All tests still pass.
Need to check ordering of column-banded dofmaps matches what I've written in the docs.

**Comment by arporter** [comment]
Have changed the code so that the CMA indirection dofmaps are grouped with other function-space-related arguments. This required a few code changes so I need to review test coverage next. I also need to extend my testing of invokes containing multiple CMA operations.

**Comment by arporter** [comment]
I've extend the multi-kernel test. Have realised I also need to test with colouring and DM.

**Comment by arporter** [comment]
Given that CMA operators are built from LMA operators and we don't do halo swaps for the latter, I guess we don't do them for the former either. Similarly, we will also need to compute CMA operators redundantly out to the L1 halo as we do for the LMA operators.

**Comment by rupertford** [comment]
pull request #21 has been merged to master. Closing this issue.
