### ISSUE TITLE
[PSyIR] Reference node should reference a symbol

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#603]
At the moment a Reference node contains a string. It would be better if it contained the relevant symbol object. This solution was suggested by @arporter, so all glory or blame goes to him.

This issue came up when creating code using the create() methods (see #599 and #601). In this case it is possible to create lots of references without associated symbols and it is unclear how the symbols should subsequently be created. It would be better to ensure that a symbol has already been created.

**Comment by rupertford** [comment]
Created branch 603_reference_node_symbol

**Comment by arporter** [comment]
#665 is merged.
