### ISSUE TITLE
Rename LFRic (Dynamo) built-ins

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#61]
LFRic built-ins support was updated in Issue #16, and the new naming scheme proposed in [BuiltIns_Rules_v2.pdf](https://code.metoffice.gov.uk/trac/lfric/attachment/ticket/912/BuiltIns_Rules_v2.pdf) attached to [LFRic ticket #912](https://code.metoffice.gov.uk/trac/lfric/ticket/912). The overview of current LFRic and PSyclone built-ins names is in  [LFRic wiki page for ticket #912](https://code.metoffice.gov.uk/trac/lfric/wiki/ticket/912/PSycloneBuiltIns). Some additional required support is identified in [LFRic Design Discussion #1085](https://code.metoffice.gov.uk/trac/lfric/ticket/1085)
These references will be used for renaming built-ins and adding required support identitifed after closing Issue #16.

**Comment by arporter** [comment]
PR #71 merged to master. Closing Issue!
