### ISSUE TITLE
[SIR] use datatype of Literal node rather than assume it is float. 

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#612]
Currently the SIR backend assumes that any Literal nodes are of type `float`. #468/#600 has added the concept of datatype to the Literal node so this assumption can now be lifted.

**Comment by arporter** [comment]
See e.g. https://github.com/stfc/PSyclone/blob/216e5cae0322913810caccf726fb92d84172da4e/src/psyclone/psyir/backend/sir.py#L407

**Comment by rupertford** [comment]
Created branch 612_sir_literal_datatype

**Comment by arporter** [comment]
#614 is merged.
