### ISSUE TITLE
[PSyIR Fortran Backend] The literal visitor should not always produce node.value

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#616]
This is wrong at least with DataType.BOOLEAN where it produces `True`/`False` and it should produce `.True.`/`.False`

**Comment by arporter** [comment]
Related to this issue, I've just discovered that somewhere along the way, what was a Fortran double-precision literal (e.g. `1.0d0`) gets translated into a single-precision literal (`1.0e0`) after processing by PSyclone.

**Comment by arporter** [comment]
The boolean part of this had already been fixed in a previous issue. The loss of the `d0` was causing compilation failures in some of the NEMO examples in #1147 so I had to fix it there.
