### ISSUE TITLE
[nemo] Support 'independent' clause on OpenACC KERNELS directive

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#619]
PGI 19.9 is more robust in its dependency analysis and as a result refuses to parallelise a lot of NEMO loops that were previously OK. The suggested workaround for this is to add the `LOOP INDEPENDENT` clause to the KERNELS directive.

**Comment by rupertford** [comment]
Strictly we should only do this where we know that the loops are independent (via our dependency analysis). Perhaps we should disallow this by default and make the user override?

**Comment by arporter** [comment]
Yes, I'm merely going to implement support for having it as an option, not default behaviour.

**Comment by arporter** [comment]
I've looked into this and putting the 'independent' clause on a KERNELS directive only works when it is applied around a single loop (nest). This means it is really the equivalent of the OpenMP PARALLEL DO directive. If we weren't to do this we would need a PARALLEL region and then a separate LOOP directive on each loop nest. We already support the LOOP directive (for the NEMO API) but not PARALLEL. #423 exists to add support for the PRIVATE clause to the LOOP directive.

Therefore, I'm going to close this Issue and open a new one to add support for PARALLEL.
