### ISSUE TITLE
[nemo] Cannot add LOOP directive within KERNELS region

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#622]
Enclosing a loop nest within a KERNELS region and then attempting to add a LOOP INDEPENDENT directive to it results in everything going pear shaped:

    !$ACC KERNELS
    !$ACC LOOP INDEPENDENT
    !$ACC END KERNELS
    DO jl = 1, jpl
      DO jn = 1, ndim1d
        jid = MOD(tab_ind(jn) - 1, jpi) + 1
        jjd = (tab_ind(jn) - 1) / jpi + 1
        tab1d(jn, jl) = tab2d(jid, jjd, jl)
      END DO
    END DO

**Comment by rupertford** [comment]
PR #623 has been merged to master. Closing this issue.
