### ISSUE TITLE
[PSyData] Handling of builtins

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#637]
Investigate the handling of builtins. At this stage the dependency analysis seems not to handle read/write access in builtins at all.

E.g. the example in the psyke chapter of the user's guide:
```
      CALL psy_data%PreStart("unknown-module", "setval_c", 1, 3)
      CALL psy_data%PreDeclareVariable("f2", f2)
      CALL psy_data%PreDeclareVariable("cell_post", cell)
      CALL psy_data%PreDeclareVariable("df_post", df)
      CALL psy_data%PreDeclareVariable("f3_post", f3)
      CALL psy_data%PreEndDeclaration
      CALL psy_data%ProvideVariable("f2", f2)
      CALL psy_data%PreEnd
      !
      !$omp parallel do default(shared), private(df), schedule(static)
      DO df=1,undf_any_space_1_f2
        f2_proxy%data(df) = 0.0
      END DO
      !$omp end parallel do
      !$omp parallel do default(shared), private(cell), schedule(static)
      DO cell=1,f3_proxy%vspace%get_ncell()
        !
        CALL testkern_code_w2_only(nlayers, f3_proxy%data, f2_proxy%data, ndf_w2, undf_w2, map_w2(:,cell))
      END DO
      !$omp end parallel do
      CALL psy_data%PostStart
      CALL psy_data%ProvideVariable("cell_post", cell)
      CALL psy_data%ProvideVariable("df_post", df)
      CALL psy_data%ProvideVariable("f3_post", f3)
      CALL psy_data%PostEnd
```
The field f2 is considered an input (it is written before the kernel), but the setval builtin should mark this variable to be an output variable.

**Comment by arporter** [comment]
@hiker, I can't respond in-place to your comment (https://github.com/stfc/PSyclone/pull/825#discussion_r453388009) on #825 but I don't see a comment here about scalars?

**Comment by hiker** [comment]
Builtins are allowed to update scalars (e.g. gh_sum for a real). Add a test case for a written scalar in the dependency analysis to make sure it is detected properly as written (since atm this cannot be tested since scalars with write/update accessare not allowed in a kernel).

**Comment by hiker** [comment]
Sorry, I forgot to click on 'comment' ... it was still waiting in a tab. It's above here now.

**Comment by hiker** [comment]
I think 'all' that is needed is adding `reference_accesses` functions for the builtins. That shouldn't be too hard, as far as I can see each builtin creates an assignment. So we only need to execute the code for 'lower_to_language' for each node **without the `self.replace_with(assign)`**, and call `reference_accesses` for the created assignment statement. That should then report the accesses as expected, which means PSyData should create the right code then. Just a 'bit' of refactoring I guess :(
Is that urgent?

**Comment by hiker** [comment]
We ran into the same issue of not handling builtins. I've created 637_varinfo_lfric_builtins. This now produces:
```
    call invoke( name = 'Initialise fields',        &
                 setval_c( field1,     0.0_r_def ), &
                 setval_c( field2,     one       )  &
                 )
-->
...
      CALL extract_psy_data%PreEnd
      DO df=loop0_start,loop0_stop
        field1_proxy%data(df) = 0.0_r_def
      END DO
      DO df=loop1_start,loop1_stop
        field2_proxy%data(df) = one
      END DO
      CALL extract_psy_data%PostStart
      CALL extract_psy_data%ProvideVariable("df_post", df)
      CALL extract_psy_data%ProvideVariable("field1_post", field1)
      CALL extract_psy_data%ProvideVariable("field2_post", field2)
      CALL extract_psy_data%PostEnd
```
I.e. both `field1` and `field2` are now correctly considered output. I am just not sure if it's worth adding this (i.e. adding unit tests, looking at other data types, e.g. vector fields), since this is all 'old style', non-psyir style.

**Comment by arporter** [comment]
We can discuss. The Builtins themselves are now implemented in PSyIR.

**Comment by hiker** [comment]
@arporter , do I see it correctly that builtins only take scalar and fields as arguments (not field_vector)? Then the implementation would actually be complete.

I had a look at the psyir part - indeed `lower_to_language` creates a psyir, but I can't see an easy way of using this, since `lower_to_language` replaces 'self' (i.e. the builtin) with the psyir, and we don't really want to modify the tree for collecting the variable accessed. 

Please let me know what you want me to do: I can:
- leave it the way it is, but properly fix all tests), and then do a PR, which should be quite quick
- throw this away and wait till the LFRIc PSyIR has progressed enough
- use the existing,minimal psyir capability of builtins in a clever way that I am missing atm (this would actually be a great solution, since we can immediately get the expected results from it, while atm I have to re-implement the behaviour of the assignment statement: put any write accesses after all read accesses). I also notice that some builtins provide gen_code, others lower_to_language.

**Comment by hiker** [comment]
I've pushed my current version as https://github.com/stfc/PSyclone/pull/1804

**Comment by arporter** [comment]
#1804 has been merged. Can this be closed now?

**Comment by hiker** [comment]
Yes, thanks a lot!
