### ISSUE TITLE
[PSyData] Handling of grid properties

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#638]
Grid properties are not expected to work at this stage. This likely needs #363 to be fixed first (since at least in GOcean all grid properties are based on derived types).

- [x] Check that grid properties can be used in "ProvideVariable" as expected.
- [x] Improve the driver generation to handle derived types (since we likely want to avoid using the API specific data types, this means the grid properties need to be declared as simple variables).
- [x] Assuming that we just remove the 'derived type part' (i.e. ssh_fld%grid%subdomain%internal%xstop becomes just xstop in the driver), we need to make sure that these variables are unique (e.g. what if the program should have its own xstop variable).

**Comment by arporter** [comment]
Since GOcean doesn't (yet) make use of the PSyIR, hopefully the lack of support for derived types won't be an issue here - we'd generate the necessary extraction code in the same way as we generate the PSy layer. The driver code should be dealing with intrinsic types only so could (should?) be implemented using PSyIR rather than f2pygen.

**Comment by hiker** [comment]
The original code should probably be fine, though note that I am using the dependency analysis, which works on the PSyIR, which atm does not handle derived types properly, so I am not entirely sure what will happen. I _think_ I would just get a string like "field%internal..." back, which indeed should work fine for writing the data. Main issue is then actually the driver, since I can't use the field data type, so I need to create (unique) variable names, ideally based on the derived type's member, so that the code is easier to recognise. But no big deal indeed.

**Comment by arporter** [comment]
PR #708 is merged.
