### ISSUE TITLE
[PSyData] Command Line Options for Kernel Data Extraction

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#640]
Do we need command line option to allow kernel/invoke extraction to be applied automatically by PSyclone, without the usage of a transformation script?

**Comment by arporter** [comment]
I think this is a "nice to have" feature but not high priority. I suggest we wait until we have some users of this functionality and see what they think. (Where 'users' might be us but hopefully will be others too.)

**Comment by hiker** [comment]
I totally agree. I'll leave this open as a 'question', so that we can ask for feedback later.

**Comment by hiker** [comment]
This is replaced by #929 for a more general solution.
