### ISSUE TITLE
[fparser2 frontend] Fortran SAVE attributes are not supported

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#652]
e.g `integer, save  :: nit000, nitend, irecord`

Implementing support for the general case `SAVE` may be difficult, however, some symbols do not need any extra features to support the attribute as they are already implicitly saved. From the [Fortran specification](https://www.nag.co.uk/market/training/fortran-workshop/f2018_standard.pdf) 8.5.16.4:
> A variable, common block, or procedure pointer declared in the scoping unit of a main program, module, or submodule implicitly has the SAVE attribute, which may be confirmed by explicit specification.

In this cases we can ignore the attribute and the result will be the same.

**Comment by arporter** [comment]
#671 has been merged, closing issue.
