### ISSUE TITLE
[PSyData] Transformation refactoring

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#655]
Somehow I ended up with quite a bit of code duplication (extract_trans and profile_trans are not based on psy_data_trans) _ I suspect that this happened when manually resolving the various conflicts, or maybe some non-conflicting parts of the merge request recreated things that I had moved into a common base class ... no idea :angry: Anyway, I need to refactor this :(

**Comment by hiker** [comment]
I also noticed that there is a lot of code duplication in our transformations re the handling of the node or node_list parameter (e.g. if it;'s a single node, convert this to a list, if it's a schedule, get a list of the child nodes). I am refactoring this as well.

**Comment by hiker** [comment]
A side effect of removing duplicated tests, the error messages are somewhat more generic (e.g. instead of mentioning the "ProfileNode" in an error message, the message now only mentions "PSyDataNode". This will be improved when implementing #415 - when we have a class name, we can improve the error messages back to indicate the actual node type, e.g. "PSyDataNode(Profile)" or so.

**Comment by arporter** [comment]
#684 is merged.
