### ISSUE TITLE
[PSyIR] determine the type of nodes

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#658]
At the moment it is difficult to determine the type of nodes - unless they have an explicit type associated with them i.e. Literal or Reference. This would be very useful for checking correctness when creating or modifying PSyIR and possibly for backends as well. After discussion with @arporter and @sergisiso it is suggested that all nodes have a get_type() method (or similar) which will work out what type the node is, or returns.

**Comment by arporter** [comment]
This is needed when attempting to determine whether an array access is to a range or not. e.g.

    my_array(my_func(a(:))) = 1.0

could be an assignment to a single element of `my_array` or it could be an assignment to a slice. To know this we need to know what `my_func` returns. We have the same problem with Operators but that is temporarily solved by keeping a list of those Operators that perform a reduction (currently just the unary, binary and nary forms of SUM).

**Comment by arporter** [comment]
All nodes (apart from Calls) now have a `datatype` method so this issue can be closed.
