### ISSUE TITLE
KernelGlobalsToArguments does not set kernel.modified=True

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#663]
The `apply` method needs to set the `modified` property of the transformed kernel to True. This then facilitates validation checks in other transformations and also ensures that a re-named version of the kernel is written to file. Currently the transformed kernel is not re-named.

**Comment by arporter** [comment]
`CodedKern.gen_code()` calls `self.rename_and_write()` which does what it says. It also updates the kernel PSyIR with the new name.

**Comment by arporter** [comment]
Now that the test-compilation system supports the specification of additional dependencies we can add compilation testing to the tests for this transformation. However, this reveals a couple of problems:

  1. `psy.gen` must be called before the compilation test is performed as it is only at the code-generation stage that we rename the transformed kernels.
  2. Compilation fails because 'wildcard' use statements from the kernel module are currently discarded. This is fixed by #615.

**Comment by sergisiso** [comment]
Fixed by #951
