### ISSUE TITLE
[PSyData] Do we need a init and finalise function for PSyData libraries?

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#668]
For profiling we have added ``ProfileInit`` and ``ProfileEnd`` functions, and I would guess we should add the same for the PSyData API. This would also require a rewrite of more of the profile documentation.

**Comment by hiker** [comment]
I am adding this, since visualisation needs this as well, and it removes the special functions ProfileInit and ProfileFinalise from the profiling api, making it fully _PSyData complient_ 😁

**Comment by arporter** [comment]
#731 is merged.
