### ISSUE TITLE
Crash when printing Invoke class

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#67]
A minor issue: while adding some debug prints to study some code, I caused a crash when printing an instance of psygen::Invoke().
Reason is that ``__str__`` is:
```
    def __str__(self):
        return self._name+"("+str(self.unique_args)+")"
```
And ``self.unique_args`` is not defined. And while I have a test case and fix ready for this, I realised that ``self.unique_args`` is never used or set anywhere in PSyclone - looks like a left over. Unfortunately I am not sure what should be used. Maybe just return ``self._name`` in ``__str__()`` (but even then it needs a minor fix in case that ``Invoke(None, None, None)`` is used since ``self._name`` is then still undefined ... set``self._name`` to "Undefined" perhaps in this special case??).

**Comment by arporter** [comment]
I think we should be using `self._alg_unique_args`. I also see your point about `self._name` being undefined in certain cases. This highlights the fact that our test coverage of psyGen.py is [not great](https://coveralls.io/builds/12718183/source?filename=%2Fhome%2Ftravis%2Fvirtualenv%2Fpython2.7.9%2Flib%2Fpython2.7%2Fsite-packages%2Fpsyclone%2FpsyGen.py).
My preferred solution would be to set `self._name = "invoke"` at line 390 to cover the early exit from `__init__`.

**Comment by arporter** [comment]
I've added a comment to the commit - basically we would mess with internal state by setting `._name` directly rather than adding a setter to the source code (since that is only required for testing). Apart from that it all looks good!
