### ISSUE TITLE
[PSyIR] Make loop node use a symbol rather than a string for its loop variable.

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#679]

**Comment by rupertford** [comment]
For historical reasons the PSyIR loop node keeps its loop variable name as a string. This should be changed to a reference as that is what the rest of the PSyIR uses.

**Comment by rupertford** [comment]
Created branch 679_loop_node_var_use_symbol

**Comment by sergisiso** [comment]
Loop node uses a symbol now. Closing this issue.
