### ISSUE TITLE
Failing tests on master branch

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#69]
Running `py.test` in `src/psyclone/tests` on master branch results in 3 failing tests in `dynamo0p3_test.py`: 
- `test_kernel_stub_usage`
- `test_kernel_stub_gen_cmd_line`
- `test_vn_generation`
All failures are related to missing files, e.g. `E           OSError: [Errno 2] No such file or directory`.
The full error report is attached ([Master_test_errors.txt](https://github.com/stfc/PSyclone/files/1230574/Master_test_errors.txt)).

**Comment by arporter** [comment]
Hi @TeranIvy, the tests all work for me (modulo a problem with the graphviz version I have). They also all pass on [travis](https://travis-ci.org/stfc/PSyclone/branches). Have you installed PSyclone before running the tests?

**Comment by TeranIvy** [comment]
Hi @arporter. I am running the tests with the current 1.4.1. PSyclone release we use in LFRic. I will try to use environment from the current master or my branch and let you know.

**Comment by TeranIvy** [comment]
Update @arporter: I ran tests with PSyclone installed from the current master and I still get failing `test_vn_generation` (same error as in the attached file).

**Comment by arporter** [comment]
Hi @TeranIvy, could you supply the full error you get with the `test_vn_generation` test - the attached file has chopped-off some of the output. It seems to be failing when attempting to import the `setup` module which would indicate either a syntax error in that file or that monkey-patching the system path hasn't worked and thus python cannot find the module.

**Comment by TeranIvy** [comment]
Hi @arporter, the full error is below.
```
=================================== FAILURES ===================================
______________________________ test_vn_generation ______________________________
[gw3] linux2 -- Python 2.7.6 /usr/local/sci/bin/python
monkeypatch = <_pytest.monkeypatch.MonkeyPatch instance at 0x35d0830>
tmpdir = local('/var/tmp/pytest-of-ikavcic/pytest-87/popen-gw3/test_vn_generation0')

    def test_vn_generation(monkeypatch, tmpdir):
        ''' Check that running setup.py generates the expected Python
        module file containing the current version of PSyclone '''
        import sys
        sys_path = sys.path
        # BASE_PATH points to some_path/PSyclone/src/psyclone/tests and we
        # need some_path/PSyclone
        tail = ""
        head = BASE_PATH
        while tail != "src":
            head, tail = os.path.split(head)
        # Monkeypatch sys.path so that it includes the locations of setup.py
        # and our scratch directory
        monkeypatch.setattr(sys, "path", value=sys_path + [head, str(tmpdir)])
        # Now import the setup module and call the write_version_py() routine
        # to generate a new module containing the version number.
>       import setup

setup_test.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/data/users/lfric/modules/packages/python/2.7/lib/python2.7/site-packages/pytest-3.0.7-py2.7.egg/_pytest/assertion/rewrite.py:216: in load_module
    py.builtin.exec_(co, mod.__dict__)
../../../setup.py:41: in <module>
    PACKAGES = find_packages(where="src")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

where = 'src', exclude = ()

>   ???
E   OSError: [Errno 2] No such file or directory: 'src'

build/bdist.linux-x86_64/egg/setuptools/__init__.py:43: OSError
============== 1 failed, 792 passed, 13 xfailed in 52.08 seconds ===============
```

**Comment by arporter** [comment]
Aha, thanks. Could you give me the full path to the directory where you're running the tests? Also, please could you try adding `print sys.path` immediately before the the `import setup` line in that test and let me know what it gives?

**Comment by TeranIvy** [comment]
Full path: `/data/local/ikavcic/PSyclone_Projects/PSyclone/src/psyclone/tests`

Running `py.test -n 4` after adding `print sys.path` immediately before `import setup` this time returns: 
```

============== ERRORS =================
____________ ERROR collecting src/psyclone/tests/setup_test.py ________________________
setup_test.py:38: in <module>
    print sys.path
E   NameError: name 'sys' is not defined
====== 792 passed, 13 xfailed, 1 error in 52.10 seconds =====================
```

**Comment by arporter** [comment]
Hmm. Are you sure you added it before `import setup` (line 60 of setup_test.py)?

**Comment by TeranIvy** [comment]
Doh!!! Sorry, the correct output is now in the attached file. I also put in results of $PATH and $PYTHONPATH enquiries if that helps.
[test_vn_generation_error.txt](https://github.com/stfc/PSyclone/files/1248424/test_vn_generation_error.txt)

**Comment by TeranIvy** [comment]
A moment of brightness: when I run tests from main PSyclone directory everything works (I gess it knows where `src` is).

```
[ikavcic@eld470 PSyclone]$ pwd
/data/local/ikavcic/PSyclone_Projects/PSyclone
[ikavcic@eld470 PSyclone]$ py.test -n 4 src/psyclone/tests/
============ test session starts ==========
platform linux2 -- Python 2.7.6, pytest-3.0.7, py-1.4.31, pluggy-0.4.0
rootdir: /data/local/ikavcic/PSyclone_Projects/PSyclone, inifile:
plugins: cov-2.5.0, flakes-1.0.1, pep257-0.0.5, xdist-1.16.0
gw0 [806] / gw1 [806] / gw2 [806] / gw3 [806]
scheduling tests via LoadScheduling
..............x..................xx.........................................x......................x...............................................
.......................................................................................................................................................
....................................................................x.................................................................................
......................x..x...........................................................................x.x............................................
................................................................x.....................................................................................
..................................x...x.....................
=========== 793 passed, 13 xfailed in 52.58 seconds =======
```

**Comment by arporter** [comment]
For my reference, the patch to setup.py required to fix setup_test is:

    diff --git a/setup.py b/setup.py
    index 306a864..12922fd 100644
    --- a/setup.py
    +++ b/setup.py
    @@ -37,8 +37,11 @@
     """Setup script. Used by easy_install and pip."""
     
     from setuptools import setup, find_packages
    +import os
 
    -PACKAGES = find_packages(where="src")
    +BASE_PATH = os.path.dirname(os.path.abspath(__file__))
    +SRC_PATH = os.path.join(BASE_PATH, "src")
    +PACKAGES = find_packages(where=SRC_PATH)
 
     NAME = 'PSyclone'

At this point I don't know why this patch is required.

**Comment by arporter** [comment]
Hi @TeranIvy, I think this issue is pretty much sorted (or will be once you've upgraded the MO python installations). Please could you create a pull request for the change to `setup.py`. @rupertford will have to review it as I wrote it and you implemented it :-)

**Comment by TeranIvy** [comment]
Hi @arporter. Ok, I'll do that. Next time I won't implement your solutions so I can get a chance to do a review as well :-)

**Comment by rupertford** [comment]
Pull request #73 has been merged to master. Closing this issue.
