### ISSUE TITLE
Profiling improvement

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#694]
At this stage the only executable test for profiling libraries is with the dummy 'template' library. Extend this testcase to cover as many wrapper libraries as possible, and also add a short description of the wrapper libraries to the documentation.

**Comment by hiker** [comment]
Mostly done in https://github.com/stfc/PSyclone/tree/improved_profiling_example, but it needs #650 to be merged first.

**Comment by arporter** [comment]
@hiker, can this be closed now?

**Comment by hiker** [comment]
Yes, thanks for merging!
