### ISSUE TITLE
Left over files in /tmp

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#695]
My /tmp just filled up, and I had over 3000 left-over temporary PSyclone Fortran files in there, e.g. containing ``module kernel_scalar_float``. To reproduce:
```
pytest  -k test_goloop_partially   ./dependency_test.py 
```
This will create a file of size 4493 bytes in /tmp.

Any idea where this might be coming from (so far I think from parsing the file). There are other files in /tmp created by psyclone, but most of them are correctly removed before PSyclone/pytest exits, but several are not.

**Comment by arporter** [comment]
Looking at https://docs.pytest.org/en/latest/tmpdir.html, it says that:

    Temporary directories are by default created as sub-directories of the system temporary directory. 
    The base name will be pytest-NUM where NUM will be incremented with each test run. Moreover, 
    entries older than 3 temporary directories will be removed.

If I look at my tmpdir situation I have a lot of data because we don't clean-up after our compilation tests (so we have a lot of object and module files). If quantity of data is a problem (rather than number of files), then we could update the compilation testing to remove the resulting files.

**Comment by hiker** [comment]
To clarify that: the files are not in ``/tmp/pytest-of-$USER/pytest-NUM...``, but directly in ``/tmp``. The pytest directory is indeed cleaned up, but /tmp is not (which apparently caused my bash filename completion (tab key) to fail, because it couldn't create files in /tmp anymore). Maybe it's something special with my setup, I will chase it down. I get this with tests without compilation.

**Comment by arporter** [comment]
Ah, I see. I've just checked (without compilation) and I don't get any files left in /tmp.

**Comment by arporter** [comment]
Did you ever get to the bottom of this one @hiker ?

**Comment by hiker** [comment]
I checked in a bit more details - I can't reproduce this with the example I quoted before anymore. But looking at the files, I realised that they are fparser files, which I could confirm, see https://github.com/stfc/fparser/issues/454
