### ISSUE TITLE
Compilation testing can pick-up previously-compiled FortCL files - update to latest dl_esm_inf.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#699]
HEAD of master has 59 test failures which compilation-testing is enabled. I think this is what hit @hiker in #650.

**Comment by arporter** [comment]
Problem seems to be that the test compilation was picking up existing files compiled with a different compiler:

    gfortran  -I/me/PSyclone/external/dl_esm_inf/finite_difference/src/../../external/FortCL/src -c /me/PSyclone/external/dl_esm_inf/finite_difference/src//field_mod.f90
    /me/PSyclone/external/dl_esm_inf/finite_difference/src//field_mod.f90:305:8:

      305 |     use FortCL, only: read_buffer
          |        1
    Fatal Error: File \xe2\x80\x98fortcl.mod\xe2\x80\x99 opened at (1) is not a GNU Fortran module file
    compilation terminated.
    make: *** [field_mod.o] Error 1

If I go into `/me/PSyclone/external/dl_esm_inf/finite_difference` and do a `make allclean` first, then all of the tests pass.

**Comment by arporter** [comment]
Problem is the `-I/me/PSyclone/external/dl_esm_inf/finite_difference/src/../../external/FortCL/src` flag. It should be using the CWD, not the `src` directory in the repo.

**Comment by arporter** [comment]
The problem is in `dl_esm_inf/finite_difference/src/Makefile`:

    ${API_LIB}: fortcl ${MODULES}
        ${AR} ${ARFLAGS} ${API_LIB} ${FORTCL_DIR}/*.o ${MODULES}
        ${AR} d ${API_LIB} clfortran.o

    fortcl:
        ${MAKE} -C ${FORTCL_DIR} F90=${F90} ${FORTCL_TARGET}

I've created https://github.com/stfc/dl_esm_inf/pull/35 for this.

**Comment by arporter** [comment]
Since this will require us to update the version of dl_esm_inf, I'll take the opportunity to do #697 as well.

**Comment by arporter** [comment]
I've extended `check_examples` (see last commit) so that a user can request that compilation be performed. Currently this only affects gocean/eg2 but it can easily be extended to other examples. This potentially gives us a lighter-weight way of checking compilation on Travis (rather than enabling it for the whole test suite).
@rupertford and @hiker - before I go ahead and document this new feature, do you think it is a good idea?

**Comment by rupertford** [comment]
PR #704 is on master. Closing this issue.
