### ISSUE TITLE
PSYKE: PSyclone Kernel extractor

### ISSUE THREAD

**Issue by christophermaynard** [stfc/PSyclone#7]
Build a PSy layer which when the transformation ``KernelDumpTrans`` is applied to a ``Kern`` object it calls ``proflib_io`` to write out all the scalars and arrays necessary to call the kernel. Moreover it generates a driver code which reads the dump with ``proflib_io`` and calls the kernel.

**Comment by christophermaynard** [comment]
Branch name is [r8623_kernel_extraction2](https://github.com/stfc/PSyclone/tree/r8623_kernel_extraction2)

**Comment by arporter** [comment]
@TeranIvy - has #139 replaced this issue?

**Comment by TeranIvy** [comment]
Yes, it has. I will close this.

**Comment by TeranIvy** [comment]
Replaced by #139 so closing.
