### ISSUE TITLE
Kernel stub generator in the bin directory

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#70]
Ben Shipway asked for kernel stub generator to be available in the `bin` directory for the purpose of adding UM Physics parameterisations to LFRic (see e.g. [LFRic ticket 870](https://code.metoffice.gov.uk/trac/lfric/ticket/870)).

**Comment by arporter** [comment]
Hi @TeranIvy, the `setup.py` of PSyclone is configured to install both `psyclone` and `genkernelstub` to the `bin` directory. This works OK for me when using pip but I realise that you don't use that. Where does `psyclone` end up after your installation?

**Comment by TeranIvy** [comment]
Hi @arporter, as just mentioned I installed PSyclone from the current master branch and everything is where it should be :) Also, kernel stub generator tests now work (issue #69) Thank you for a quick response!

Closing issue.
