### ISSUE TITLE
Use Make to execute the examples

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#713]
Currently the examples are run using the `check_examples` bash script. However, the number of examples and the cost of running them means that we could do with something a bit more sophisticated.

Replacing `check_examples` with a Makefile has several advantages:

1. Different targets can be used to just run the examples associated with a particular API;
2. Ease of control of whether or not to do actual code compilation;
3. Run examples in parallel (when just testing that they work).

**Comment by arporter** [comment]
@hiker has also suggested the following improvement:

Redirect the output of all scripts we call to stderr? Then we can print a short summary to stdout (git branch, psyclone version(?), config file used).

**Comment by arporter** [comment]
@hiker @rupertford re. the re-directing of output. I'm not sure of the best approach. Is the aim to simply cut down on the amount of output when running all of the examples together? It doesn't feel right to re-direct legitimate, correct output to stderr. Also, if an example fails, we'll want the stderr from it. I could leave the scripts as they are and, in the Makefile, redirect stdout from each cmd to its own log file. That way we'll only see stderr when running with Make. This could be made configurable via a variable, e.g. `make VERBOSE=1` might not redirect stdout to file. I guess the quantity of output is only really a problem on Travis since, one of the advantages of moving to Make, is that it becomes straightforward to just run a sub-set of the examples?

Another point to consider is that a lot of the terminal output is of schedules (via e.g. `schedule.view()`). Currently, the `view()` method *always* writes to stdout - this is something we should probably make configurable.

**Comment by rupertford** [comment]
I agree that redirecting to a log file or /dev/null seems to make more sense than moving valid output to stderr. As you say, the script is really only to check that things work. Presumably the files would be deleted on success?

**Comment by arporter** [comment]
GOcean examples all now work with Make.

**Comment by arporter** [comment]
All NEMO examples now work with Make.

**Comment by arporter** [comment]
Discovered that LFRic eg14 part 3 is broken because of #450. Added a note to the Makefile and the README.

**Comment by arporter** [comment]
LFRic eg15 wasn't being exercised by the `check_examples` script and was broken. I've fixed it and added a Makefile. All LFRic examples now run with make.

**Comment by rupertford** [comment]
Yes I found that last night too. I think the reason it was not added is because it purposefully aborts PSyclone in order to output the changes to the matvec kernel code.
