### ISSUE TITLE
[PSyIR] Support array declarations with specified lower/upper bounds and expressions

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#714]
In #336 we record that we do not yet support declarations containing e.g. `DIMENSION(0:N)` attribute (with non default lower/upper bounds). With the change in #500 to constructing SymbolTables for the nemo domain, this then means that at least two of the examples in `nemo/eg4` no longer work (`copy_stencil.f90` has `DIMENSION(n+1)` and `hori_diff.f90` has `DIMENSION(0 : n + 1, 0 : n + 1, 0 : n + 1)`).

**Comment by arporter** [comment]
Currently, the members of the `shape` list of a symbol must be one of: `DataSymbol`, `int` or `DataSymbol.Extent`. To be consistent, `int` should really be a PSyIR `Literal` with integer type, `DataSymbol` could in fact be any PSyIR expression and we should allow members of type `Range`. In fact, we could mandate that all members of the list be of type `Range` and default (in Fortran) to having the lower bound of each one be unity unless specified in the parsed code.

What do @sergisiso and @rupertford think - is mandating that each element of the `shape` list be a `Range` too heavyweight (for all the cases where it's just one number) or is the consistency worth this overhead?

**Comment by arporter** [comment]
@rupertford, @sergisiso - this is the issue I was thinking of before I rushed off. Do other languages even have support for specifying the start bound of an array?

**Comment by sergisiso** [comment]
I don't think any of the current C/C++ containers have support for a different lower bound. However this can be implemented in the array accessor adding the appropriate offset to each index (which we may have to do anyway for the 1 -> 0 indexing?).

**Comment by arporter** [comment]
Although changing shape to use Range() feels good, the issue of having previously unseen Symbols in the shape specification actually means I need the functionality that I'm adding in #500. This is then a catch-22 since I paused #500 to do this.

**Comment by rupertford** [comment]
It seems that the examples in nemo/eg4 now work.

**Comment by arporter** [comment]
So they do. Closing this issue.
