### ISSUE TITLE
[PSyIR] Transformation to convert initial_values to schedule assignments

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#715]
Attempting to process the following:

    integer, parameter :: n=10
    integer, parameter :: np1= n + 1

Results in a "symbol 'n' not found" error from `Node.find_or_create_symbol()`.

**Comment by arporter** [comment]
The FE also only permits initialisation within parameter declarations - i.e. not for normal variables. This limitation is a problem for NEMO.

**Comment by arporter** [comment]
Note that a *variable* that is initialised implicitly has the `SAVE` attribute also. This is another concept that the PSyIR does not yet have.

**Comment by rupertford** [comment]
@arporter. Now that #773 is on master can this issue be closed? I understand that initialising variables is not supported yet but I think that is a separate issue to this one (initialisation referring to another symbol) - unless you want to re-purpose this issue?

**Comment by arporter** [comment]
I was intending to repurpose this issue to fix both simultaneously so let's keep it open.

**Comment by sergisiso** [comment]
I repurposed this issue as suggested by the last comment. This is also mentioned in #1419 and is blocking other issues like #2137 

There are two options to fix this:
- Adding the RHSs as assignments at the beginning of the schedule.
- Repurpose the constat_value as a init_value (and then make the constant/parameter just a bool on the symbol or the type?)

The problem of the assignment solution are that initialisations in module-level and SAVE attributes are not as easy those placed in subroutines.

The problem with the init_value is that we leave this expressions outside the may tree, and:
- array assignments would be useful to transform to to explicit_loops and offload to gpu.
- the dependency analysis must be aware of the initializations expression and be part of the use-chains, which we currently ignore.

**Comment by sergisiso** [comment]
@arporter @rupertford Looking at the pros and cons above, I changed my mind and I now think that the constant_value repurpose to init_value that @arporter proposed is the way to go to provide support everywhere, as there is no easy way to do module and SAVE inits with assignments.

But then we could have a init_value to assignment transformation that we can apply when:
- Need to offload to GPU (part of the code normalisation set of transformation we already do in NEMO)
- Need to fix dependency ordering initialisation statements for a specific compiler.
- Need the complete use-chain of a symbol.

Do you think this is the right approach? I am missing something that we could not do with the proposed implementation?

**Comment by arporter** [comment]
Yes, I think this is a duplicate of #1419. I agree with your proposal as I can't think of a solution to module variables with initial values and supporting a subsequent transformation that we can apply to variables declared within routines seems to support all other use cases. (The alternative would be to automate this process as part of the front end but it is probably more robust to provide a Transformation instead.) I've just brought my #1419 branch up-to-date with master: https://github.com/stfc/PSyclone/compare/1419_loop_var_unknowntype?expand=1 Would you like me to finish this off?

**Comment by sergisiso** [comment]
Oh so this is already half done, even better :)

Yes please finish that one. Should then I repurpose this one once again to be about the transformation to assingments? So we don't have duplicates.

**Comment by arporter** [comment]
> Yes please finish that one. Should then I repurpose this one once again to be about the transformation to assingments? So we don't have duplicates.

Yes, let's do that.

**Comment by LonelyCat124** [comment]
Is the transformation to assignments correct? Since something like `integer :: b = 1` is equivalent to `integer, save :: b = 1` transforming the initialisation to an assignment requires some special tracking, notably these are not the same:
```
Subroutine a()
    integer :: b = 1

    b = b + 1
    print *, b
end subroutine

Subroutine c()
    integer, save :: b
    b = 1
    b = b + 1
    print *, b
end subroutine

Program hello
    Call a()
    Call a()
    Call c()
    Call c()
End Program hello
```
This outputs
```
2
3
2
2
```

I'm not sure there is a good workaround to this problem that I can think of either, unless newer Fortran offers a way to check if a save variable has been initialised?

**Comment by sergisiso** [comment]
I confirm that solving #1419 has also fixed the original comment at the top.

This issue title solution has been discarded in favor of keeping the init expressions in a symbol attribute

And now Fortran initial value properly set the symbols to StaticInterface

So I close this issue.
