### ISSUE TITLE
[LFRic] Reference element stub generation and additional support

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#716]
The main requirements for supporting reference element information in LFRic kernels were added through pull requests related to the issue #150. Whilst testing #701 I noticed that there are still some outstanding requirements and functionality to complete the reference element support. These are:
- Support for all `normals_to_faces` and `outward_normals_to_faces` (see e.g. LFRic kernel [compute_trace_operator_kernel_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/kernel/compute_trace_operator_kernel_mod.F90),
- Stub generation support (it is added for quadrature in #701 togeher with the PSy-layer code generation).

**Comment by TeranIvy** [comment]
I will take this on as @arporter  is quite busy with quadratures, mesh info, i-first and other things.

**Comment by arporter** [comment]
Thanks @TeranIvy, much appreciated. Unless you (or others at the MO) have a burning desire to have the stub-generator functionality working, I would leave that bit for now.

**Comment by TeranIvy** [comment]
Hi @arporter, I am happy to add the stub generation as well as it will be useful when rearranging boundary-layer kernels to be psycloned.
