### ISSUE TITLE
Where statement array syntax is limited

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#717]
Array syntax in Fortran where statements must be for the full extent i.e. the dimension must only contain a `:`. If it is for a subset of the data in the dimension e.g. `2:4` then the PSyIR front-end raises an exception.
We also do not currently support use of 'bare' arrays, e.g. `WHERE(some_array < 0)` because we rely on array notation to identify array accesses. Once #500 is complete we will have the necessary functionality to look-up the shape of such arrays.

**Comment by arporter** [comment]
While tackling reviewer comments on #1518, it was suggested that the `_array_notation_rank` method in the frontend ought really to be associated with a PSyIR node. I started to do this but it got quite big and then started to touch code that is related to this issue so I've created `717_lift_where_restrictions` (branched off `1506_where_dtyptes`) and put my changes onto that.

**Comment by arporter** [comment]
Have now added `rank_of_subsection` to most nodes that need it. However, I need to check that I've not lost fixes that were added to the old _array_notation_rank() method in fparser2.py. I also need to think about whether this routine needs extending to cope with subsections that are not for the full extent of a given dimension.

**Comment by arporter** [comment]
It would also be good to handle the case where a WHERE contains references to arrays without any subscripting.

**Comment by sergisiso** [comment]
I believe tacking #1858 first will allow to solve this issue without having to duplicate logic from Reference2Array and ArrayAssignment2Loop, as they all need the same.
