### ISSUE TITLE
Migrate org level Project to repository

### ISSUE THREAD

**Issue by tofu-rocketry** [stfc/PSyclone#72]
For some reason, repository level GitHub Projects were disabled. I've enabled them, so could you please migrate your Project (https://github.com/orgs/stfc/projects/1) to a repository of yours.

Thanks.

**Comment by arporter** [comment]
Done. I hadn't realised I'd attempted to create an organisation-level project. Thanks for enabling them on a repo level.

**Comment by tofu-rocketry** [comment]
It was the only option you would have had. I've disabled the org level ones now as I can't currently see a use case for them with all these disparate repositories.
