### ISSUE TITLE
Generalise the intrinsic translation transformations

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#725]
NemoAbsTrans, NemoMinTrans, and NemoSignTrans were originally NEMO specific because they required a symbol table to be passed in. This requirement has been removed (#500) and so these transformations can be renamed and made applicable to all APIs.

**Comment by rupertford** [comment]
Created branch 725_generalise_intrinsic_trans

**Comment by arporter** [comment]
#762 has been merged.
