### ISSUE TITLE
Going from generic PSyIR to Domain-Specific PSyIR

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#737]
In #596 the process of creating PSyIR for the NEMO API has been brought into line with the way Kernel PSyIR is created. While discussing that PR @rupertford suggested that the PSyIR frontend be purely responsible for creating the 'lowest level' PSyIR of the source code being processed. This PSyIR could then be processed to 'raise' the level of abstraction. e.g. in the NEMO API we could convert recognised Fortran Do Loops into instances of `NemoLoop`, the bodies of such loops into instances of `NemoCodedKernel` and ultimately, subroutine calls that are halo swaps into instances of `NemoHaloExchage` or similar.
This is in contrast to what we do at the minute which is to have NEMO-specific handlers in the PSyIR frontend that create Nemo-specific objects in response to certain elements in the fparser2 parse tree.
As an aside: a domain-specific PSyIR could be DPSyir, "d-sire" :-)

**Comment by sergisiso** [comment]
I will copy here part of what I said at #596.

I think the bit that I wrongly placed into the generic front-end reader is that `generate_schedule` generates a KernelSchedule. I think there should be a more generic concept of Subroutine (or similar) for and when this generate_subroutine is called we know what are we expecting (we don't need a complex pattern matching pass) and we can to the necessary preparations to generate the kernelSchedule, InvokeSchedule or Algorithm.

There is probably some minor renaming of a few classes/methods needed.

@rupertford @arporter Does it make sense?

**Comment by arporter** [comment]
I think what you said above @sergisiso does make sense - I'm looking at this because of #430. Shall I introduce a new `Routine` node? @rupertford, how is a 'standard' Kernel represented in the PSyIR? Obviously we get the subroutine statement and associated declarations when we use the backend there...

**Comment by arporter** [comment]
OK, so I've answered my own question: we create a `Container` for a module and this has `KernelSchedule` nodes as children, each of which represents a routine. I agree with Sergi that this is a bit misleading and it would be better if we had generic `Routine` nodes instead.

**Comment by rupertford** [comment]
Yes, I agree with you both. When we introduced the concept of a call into the PSyIR, the plan was to introduce the concept of a Routine that a call calls and this was discussed in #786 but no issue was added (and we hadn't agreed on a name at the time). PR #787 added a RoutineSymbol which should be used when adding a Routine Node.

**Comment by arporter** [comment]
I'm going to take this on, at least in part, because I need to improve the way the NEMO API constructs the PSyIR (so that we can use the backed properly for #435).

**Comment by arporter** [comment]
Actually, I'm going to wait and see what Rupert does in #1104 in case it does what I need.

**Comment by arporter** [comment]
Closing this as we do now create language-level PSyIR and then raise it via transformations.
