### ISSUE TITLE
gocean1p0 pylint iterator errors

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#74]
When running pylint on gocean1p0.py I get the following errors.

E:990,23: Non-iterable value self.arg_descriptors is used in an iterating context (not-an-iterable)
E:1008,19: Non-iterable value self.arg_descriptors is used in an iterating context (not-an-iterable)

This should be checked out.

**Comment by arporter** [comment]
These errors are no longer present on master so closing issue.
