### ISSUE TITLE
Make Wchi function space read-only

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#749]
PR #734 adds support for `Wchi` function space that holds coordinate fields in LFRic. The peculiarity of this function space is that the fields on it are read-only when it comes to PSy layer. Coordinate fields are created during the LFRic model setup and not updated afterwards. Consequently, LFRic does not perform halo exchanges on them.
This issue builds on #734 by introducing checks on `Wchi` access metadata (only allowing `GH_READ`) and making sure there is no generated code for halo exchanges on `Wchi` space.
The LFRic ticket [2176](https://code.metoffice.gov.uk/trac/lfric/ticket/2176) will explicitly make these fields read-only in LFRic.

**Comment by rupertford** [comment]
Whilst reviewing #734 it occurred to me that it might make sense for LFRic read-only fields to have their own (read_only) list separate from the ``continuous`` and ``discontinuous`` lists. The reason for this is that it does not matter if read-only fields are continuous or not from PSyclone's perspective and we will need to do different things to them cf other fields (ensure that the dirty flag is always false and ensure that they are never written to in kernels called by PSyclone). I think this would be better than having hardcoded Wchi lookups, particularly because hardcoded lookups is something we've been moving away from.

**Comment by TeranIvy** [comment]
Yes, I think you're right. I'll move `Wchi` to this `READONLY_FUNCTION_SPACE` list in this issue (please feel free to suggest another name). I won't put the new list in the configuration file, though, as this is a larger job for which we're only setting a strategy (#742) now.

**Comment by rupertford** [comment]
@TeranIvy and I have agreed that I will take this on.

**Comment by rupertford** [comment]
Created branch 749_chi_readonly

**Comment by rupertford** [comment]
We need to 
1) make a new read_only function space list
2) check that any fields with a read_only fs are not written to
3) check that a halo exchange is never called for a field with a read_only fs

**Comment by rupertford** [comment]
So 1) is very simple (ignoring tests!). However, I was thinking that we could simply check statically for wchi being readonly in metadata. Clearly we can do this and should raise an error. However, a wchi field could be passed into a kernel that specifies any_space so we also need a run-time check on field types that are written to when their space is not known statically by the metadata (any*space). This moves us into the realm of general correctness checking (that fields match what the metadata specifies).

**Comment by rupertford** [comment]
I've added code which raises an exception if an LFRic kernel's metadata is written such that a field argument is on a read only function space but is specified as modifying it. I've also written an associated test.
It is not yet possible to statically determine the type of an algorithm data object and then check that it is consistent with kernel metadata. In relation to this PR we would want to check that a field on a read only function space is not modified. I've created issue #753 (and there is already issue #79) which would support static checks

**Comment by rupertford** [comment]
Next is run-time checks. I will need to add PSy-layer code that checks whether fields that have a read-only function space are not passed into kernels that modify them. I might as well do full blown correctness checks i.e. check field function spaces are consistent with kernel metadata (and I could have a switch to do the checks or not).

**Comment by rupertford** [comment]
So the code for the above run-time checking would be best added at the start of the PSy-layer routine i.e. in ```DynInvoke``` before the kernels are called. For each field for which the function space can not be worked out (we might be able to discount some by analysing the algorithm layer) the code could look something like ...

```
if field.fs == "rofs" then
    ! this field_is_modified in kernels x,y,z
    call abort(...)
end if
```
The test for field.fs would need to be repeated for each read-only function space (although there is currently only one).
We would need to look up to see whether the field was modified in any of the kernels and only generate the code if so.

The above approach could be used to check that the halos were clean i.e.
```
if field.fs == "rofs" and field_has_any_dirty_halos then
    call abort(...)
end if
```

Alternatively, the read-only test could be done before each halo exchange was about to be called which would reduce the amount of testing as there are fewer halo exchange calls than invokes (at least I believe that is the case).

**Comment by TeranIvy** [comment]
Mike's infrastructure ticket is https://code.metoffice.gov.uk/trac/lfric/ticket/2176.

**Comment by arporter** [comment]
#756 is merged. Can this be closed now?

**Comment by rupertford** [comment]
Yes, I think so. Wchi is now part of a read-only list in LFRic-PSyclone and we have added static and run-time checks to make sure that fields on read-only function spaces are not modified.
