### ISSUE TITLE
Mixed-precision PSylayer

### ISSUE THREAD

**Issue by christophermaynard** [stfc/PSyclone#757]
This may involve several tickets.
Recognise  declaration of different `fileld_type`s in algorithm the layer, and extract _kind_ information.
Generate PSylayer with those kinds

**Comment by christophermaynard** [comment]
Examples of LFRic design can be found [here](https://code.metoffice.gov.uk/trac/lfric/wiki/LFRicInfrastructure/FieldEnhancements/MixedPrecisionInfrastructure) and LFric tickets #2196 and #2197

**Comment by rupertford** [comment]
The algorithm example given in the link provided by Chris above is:
```
program mixed_precision
  use constants_mod, only : r_def, i_def, r_solver
  use field_mod, only : field_type, r_solver_field_type
  implicit none

  type(field_type) :: f1
  type(r_solver_field_type) :: f2
  
  write(*,*) "Hello, World"

  call invoke(mix_prec_kernel_type(f1), mix_prec_kernel_type(f2) )
 
end program mixed_precision
```

The first job therefore is to add the concept of precision to a PSyclone field object and populate that with the type of the field in question as specified in the algorithm layer. The main complications will occur when fields are part of larger types, arrays, or are potentially computed. We should raise an exception if we are not able to find the information and can then gradually work through the failures, either making rules about code structure or adding support in PSyclone.

**Comment by rupertford** [comment]
One question that springs to mind is whether we need/should do this for all kernels, or whether we will have metadata saying that a particular kernel is a mixed precision kernel, as opposed to a "standard" kernel, and therefore limit this information to these particular kernels. @christophermaynard, could you advise.

**Comment by christophermaynard** [comment]
Hi @rupertford A minority of kernels will be written as mixed or multi-precision. We are planning on using Fortran run-time overloading, so we (LFRic devs) write a kernel with a 64bit interface, 32bit interface, even a mixed-prec interface. Fortran run-time maps `r_def`, `r_solver`, etc to those interfaces. For this to work, no metadata is required. However, we could create metadata for PSyclone to read?

**Comment by rupertford** [comment]
Presumably you would be still be referencing these kernels from algorithm invokes? If so, the kernels would need kernel metadata in order for us to generate a call to the generic interface from the PSy-layer. Or have I misunderstood? Assuming I'm right, we would presumably just use the type of the fields in the PSy-layer as you have previously proposed and everything is hunky dory?

**Comment by christophermaynard** [comment]
Yes we will reference the kernels from the invokes. The kernel won't have extra metadata as it has two (or more) interfaces. One for 32-bit, one for 64-bit. Fortran run-time picks which one. PSyclone needs to know from the algorithm layer, what is the kind of the field, `r_solver`, `r_def`, etc but doesn't know what that maps to, it gets resolved at run-time. The metadata is the field_type in the algorithm layer.

**Comment by christophermaynard** [comment]
Created a branch (https://github.com/stfc/PSyclone/tree/757_mixed_precision)[757_mixed_precision].

**Comment by christophermaynard** [comment]
I am updating my example code to be more like actual LFRic code, PSyclone will now parse it but falls over as it doesn't know about the interface statement and cannot find the actual subroutines. Don't believe this is a major problem and it gets me looking at the right bit of psyclone code!

**Comment by christophermaynard** [comment]
@rupertford and @arporter I have discovered something of a contradiction which is going to cause a problem. All are kernel types have the type bound procedure, but this is called as a module scope subroutine from the PSylayer. I cannot overload a type-bound procedure with a F90 style overloading using an interface. I can write the fortran code to use F2K3 OO over-loading of functions, but PSyclone still wants to generate the call as a pure module scope subroutine. This is a bit confused and is quite a non-trivial amount of fixing. Hmm ...

**Comment by christophermaynard** [comment]
I have updated my example code to include a PSylayer that was generate by PSyclone which I have then modified. The main program is `mp_alg_mod.F90`. See [mix_prec_exmple](https://github.com/christophermaynard/mix_prec_exmple)

**Comment by christophermaynard** [comment]
@rupertford @arporter I have made function with returns the name of an explicit interface that has module procedures. If the kernel parser cannot find a TBP it now calls the interface function - which returns the interface name. If there is no interface, the interface is implicit or it has no module procedures it returns None and then kernel parse says cannot find TBP or explicit interface. We don't need to check the module procedure names against actual subroutines because Fortran does this and its user code, not generated code, so produces an Fortran error compiling user Fortran code.

**Comment by rupertford** [comment]
Great. Probably enough for a PR.

**Comment by christophermaynard** [comment]
OK @rupertford I'll do the kernel and alg parsing as separate PRs. In terms of your working practices, do they form a separate issue or can there (should there) be multiple pull requires per issue?

**Comment by christophermaynard** [comment]
Oops. Trying again with names for branches ...
Created a branch [757_mixed_prec_kernel_proc](https://github.com/stfc/PSyclone/tree/757_mixed_prec_kernel_proc)

**Comment by christophermaynard** [comment]
@rupertford and @arporter. Two questions. I can make the tests work for kernels if I supply another kernel header. Q1. How do I make the test loop through two versions on the kernels. 
Two of the tests will need to be different for each kernel version (i.e one with TBP and one with interface). The first test that will need modification I can probably manage, the second is harder. 
`KernelProcedure` returns 
`subroutine name 
end subroutine name` It would be hard to make the interface versions return the same. Q2 why does it return this as it is apparently not used so what is the test for? Thanks.

**Comment by arporter** [comment]
I'm sorry Chris but you're going to have to give us more information for 2. As for 1, it's up to you. If it's purely a matter of meta-data parsing (and I think it should be for your first PR) then it's best to just have the meta-data as a string in the test file. You can then manipulate this to your heart's content or, have a second string containing the other version of the kernel. Have a look at the tests in `tests/parse/kernel_test.py`.

**Comment by christophermaynard** [comment]
Hi @arporter, thanks. I am looking at the test file. With other tests one can specify which file to test on, in this case, it has a text block containing some Fortran code, then each test runs on the defined variable called CODE. I need to make most of the tests use two versions. The file only contains functions starting with test so how do I run the same test twice with different inputs is Q1

**Comment by christophermaynard** [comment]
Q2 is a bit more involved. As I can tell, `kernelProcedure` in `src/parse/kernel.py` returns the following:
`subroutine tbp_name

end subroutine tbp_name`
Again, as far as I can tell, this is not used during the code generation. I state this because currently the interface version returns ...
`INTERFACE test_code
    MODULE PROCEDURE sub_code
 END INTERFACE test_code`
with the correct code generation, so this is why I claim it is not used. 
The test assumes it is the former. I could fix the test but that is difficult to have one test with two different inputs. So the question is what is the desired behaviour I should test for as the only place the result is used is the test. Clear as mud?

**Comment by arporter** [comment]
For Q1 you have two options, setup SOME_CODE1 and SOME_CODE2 strings with the content you want to parse. Loop over those two things in your test. Or, if they are quite closely related and the actual amount of test code is small you can just modify SOME_CODE1 c.f. what is done here: https://github.com/stfc/PSyclone/blob/e658c8287bd875783429b8637ecd4c354fd5de2c/src/psyclone/tests/parse/kernel_test.py#L377. Alternatively, if you're really testing two different things then use two tests.

**Comment by arporter** [comment]
`KernelProcedure` is a class: https://psyclone-ref.readthedocs.io/en/latest/_static/html/classpsyclone_1_1parse_1_1kernel_1_1KernelProcedure.html. It contains both the parse tree and the name of the procedure. Does that clarify things?

**Comment by christophermaynard** [comment]
Hi @arporter, OK, lets consider Q1 answered. Thanks.
Q2. In the test, the __init__ call is the function which is returning the Fortran code block. My point is, for to run PSyclone, it works fine whether it returns a subroutine code block or a Fortran interface code block instead. So, what behaviour is the test actually testing?

**Comment by arporter** [comment]
@AdamVoysey Is this to be replaced by more targeted issues?

**Comment by AdamVoysey** [comment]
Yes, I think that was the plan - particularly as we are dividing the work between people. Perhaps this issue should be renamed to make that clearer.
