### ISSUE TITLE
Support for the new quadrature API

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#76]
@ss421 has provided SRS issue 763 (https://code.metoffice.gov.uk/trac/lfric/ticket/763) which describes the changes required to PSyclone's existing support for kernels requiring quadrature. The implementation of this will be tackled in this issue.

**Comment by arporter** [comment]
Although PSyclone currently recognises "gh_shape = quadrature_xyoz", this is just a re-naming of the original quadrature functionality. The generated PSy layer needs to be changed to match the new API.
In addition, we need to add support for quadrature_xyz and quadrature_xoyoz shapes.

**Comment by arporter** [comment]
Have created new `multi_quadrature` branch. I've moved a couple of the explicit quadrature tests into a new module (to try and shrink the behemoth that is dynamo0p3_test.py) and modified them to match the new XYoZ interface described in SRS 763.

**Comment by rupertford** [comment]
pull request #89 is now on master so closing this issue.
