### ISSUE TITLE
Operator ordering broken in PSyiR Fortran back-end

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#766]
The Fortran back-end will write out `a*(b+c)` as a*b+c. As suggested by @sergisiso, the simplest solution would be to add brackets around all unary, binary and nary operators. This is what he already does in the C backend.

**Comment by rupertford** [comment]
Created branch 766_operator_ordering

**Comment by sergisiso** [comment]
Bug fixed by PR #770
