### ISSUE TITLE
PSyclone fails to understand literal precision in parameter initialization expressions

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#772]
I tried to psyclone-generate the OpenCL version of NemoLite2D with PSyclone master and I got the following error:
```psyclone.errors.InternalError: PSyclone internal error: Failed to find a symbol table to which to add the kind symbol 'go_wp'.```

This occurs while importing external global variables declarations from a module, specifically in the expression:
```REAL(go_wp), PARAMETER :: pi    = 3.1415926535897932_go_wp```
if I remove the "_go_wp" it fails in the following line:
```REAL(go_wp), PARAMETER :: d2r   = pi / 180```
with the error:
```psyclone.psyir.symbols.symbol.SymbolError: PSyclone SymbolTable error: No Symbol found for name 'pi'.```

If I replace `pi` with its value then it works fine again.

I think the problem is that `literal_precision` tries to find the symbol_table of its parent, but parameters use a dummy node to evaluate the initialisation expression.

**Comment by arporter** [comment]
I think this is part of #715 - any reference to a symbol on the RHS of a declaration is going to cause us trouble.

**Comment by sergisiso** [comment]
I think if the dummy node is a temporary child in the current scope instead of a hanging one it may solve part of it (not all as Fortran can have out of order declarations). I will give it a try.

**Comment by sergisiso** [comment]
I don't know where my out-of-order idea comes from but it doesn't seem to be the case. Then this would be a duplicate of #715

**Comment by arporter** [comment]
I think out-of-order is permitted but maybe not for parameters. e.g. you can declare an array argument with extent `n` before you declare that `n` is an integer. The Intel compiler doesn't like this but other compilers are happy.
