### ISSUE TITLE
matmul2code transformation bug

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#775]
The matmul2code transformation gives the incorrect upper bound for one of the created loops. This wasn't picked up as the values for each dimension in the tests were the same - doh! Note that LFRic eg15 is also broken due to an incorrect import in the transformation script so this might as well be fixed too.

**Comment by rupertford** [comment]
The transformation produces the following transformed matrix vector code ...
```
    do i = 1, ndf2, 1
      lhs_e(i)=0.0
      do j = 1, ndf2, 1
        lhs_e(i)=lhs_e(i) + matrix(i,j,ik) * x_e(j)
      enddo
    enddo
```
Notice that the loop `i` is over `ndf2` but should be `ndf1`

**Comment by rupertford** [comment]
Created branch 775_matmul2code_bug

**Comment by arporter** [comment]
#776 is merged.
