### ISSUE TITLE
FunctionSpace refactoring

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#780]
While studying the implementation of function spaces in dynamo0p3.py, I noticed that it could to with a bit of refactoring. This issue is created for some discussions about this.

**Comment by hiker** [comment]
I've created a small branch e2e8752ee0a9aaf0b88ccbc1c338df53c928af28, which can be used for some discussion. The idea of this branch is to start small refactoring, which hopefully can be merged in quickly, without conflicting with too many other branches. Questions:
1) Where do we put the new `function_space.py` file? I have put it in `domain/lfric`, but I have the feeling that you prefer another subdirectory :)
2) I would also suggest to move the global variables (constants) into the `FunctionSpace` class. I've done this for `VECTOR_DIFF_BASIS_SPACE_NAMES` as an example. Is that ok?
3) If we agree on 2), then how do we access those values? I see three options:
    1) The way it is with `VECTOR_DIFF_BASIS_SPACE_NAMES` - just access the variable directly.
    2) Use a property to access this value - which would make it much easier to support a config file in the future (see #742). But then we would need a `FunctionSpace` instance in order to access this value.
    3) Use a class method to access this value - which would make it much easier to support a config file in the future (see #742). But then we have to use '()', since it's not a property - and I know you all prefer not to use '()' in a case like this.
    4) Use a static property - which avoids the disadvantages of ii) and iii) ... but  that concept appears not to exist in Python :cry: (https://stackoverflow.com/questions/1697501/staticmethod-with-property - not sure if we want to try implementing our own @classproperty ... well, tbh I copy&pasted the code, but couldn't get it to work)
4) I have also started to convert some global functions into methods of `FunctionSpace` (done for `get_fs_map_name`), which I think should be a fairly obvious change.

I am happy to finish this work, if you are interested and provide answers for my question above :)

**Comment by TeranIvy** [comment]
I like the idea of moving all function space properties in one class instead of having them scattered over lists. A dictionary of properties, similar to what Matthew has suggested in his [comment in #742](https://github.com/stfc/PSyclone/issues/742#issuecomment-610888030) looks good to me.
