### ISSUE TITLE
[LFRic] Add support for additional Stencil dofmap types for use in LAMs

### ISSUE THREAD

**Issue by andrewcoughtrie** [stfc/PSyclone#781]
LFRic tickets [2170](https://code.metoffice.gov.uk/trac/lfric/ticket/2170) and [2055](https://code.metoffice.gov.uk/trac/lfric/ticket/2055) implement a new "2D" stencil type which requires slightly different array dimensions to the current "1D" stencils as well as incorporating the get_stencil_sizes function described in #194. This requires some changes to the PSylayer code being generated. This will likely also allow #486 to work though would require some other small changes.

**Comment by TeranIvy** [comment]
Possible related issues: #486 (variable stencil depth) and #194 (support for region stencils).

**Comment by andrewcoughtrie** [comment]
The region stencils are 1D and will remain so, their use currently doesn't require directional information. If we ever do need directionally informed region stencils it will be difficult to implement because the number of directions from the centre cell increases with the depth of the stencil, a different method of describing the direction would be needed.

**Comment by arporter** [comment]
What is the metadata change for these new stencil type? Is there an example somewhere that you can point me to? Also, please could you point me to the PSyKALite code for this new stencil type (so I can see what it is that PSyclone must generate).

**Comment by andrewcoughtrie** [comment]
@arporter the information on the 2D stencils and as well as example PSyKALite code can be found [here](https://code.metoffice.gov.uk/trac/lfric/wiki/LFRicInfrastructure/StencilDOFMapDesign). I was planning to do the changes my self to get a better understanding of the mechanics of PSyclone, likely asking @TeranIvy lots of questions while I do so.

**Comment by arporter** [comment]
Ooh, exciting. I shall let you get on with it then. Do feel free to ask us questions too. We can add you to the PSyclone team on MS Teams if that would help.

**Comment by andrewcoughtrie** [comment]
That would be useful thanks Andy, do you need anything from me for Teams?

**Comment by arporter** [comment]
Can this be closed now that #912 is merged?

**Comment by andrewcoughtrie** [comment]
Now that #912 is on master this can be closed.
