### ISSUE TITLE
find the nearest ancestor with a symbol table

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#793]
We need a nice way to find the closest ancestor with a symbol table. As both a schedule and a container may have a symbol table it would be good to have a simple interface. It has been suggested by @sergisiso that the `scope` property be added to a node and this would return the closest ancestor with a symbol table. Scope makes sense as it provides the scope in which this node exists. The closest symbol table could then be accessed by `node.scope.symbol_table`. It has also been suggested that a `symbol_table` property be added to node which returns `node.scope.symbol_table`.

This work is a precursor to addressing #630.

**Comment by rupertford** [comment]
Created branch 793_find_symbol_table

**Comment by rupertford** [comment]
The existing `find_symbol_table()` method was doing a similar job to the new `scope` property so I've replaced the former with `scope.symbol_table`. I didn't add in a `symbol_table` property to `Node` as I prefer the idea that certain nodes have a symbol table and you have to find the appropriate node first cf. all nodes appear to have a symbol table (as you would be able to call symbol_table from any node).

**Comment by sergisiso** [comment]
Closing this issue. Node has a scope property which returns nearest ancestor with a symbol table.
