### ISSUE TITLE
"write_args" in "unique_declns_by_intent" do not check all "read" first accesses

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#801]
Whilst working on PR #792 it became apparent that that the logic for `write_args` Fortran intent in `    `Invoke.unique_declns_by_intent` is not quite correct. We have
```
        # sum_args behave as if they are write_args from
        # the PSy-layer's perspective.
        write_args += sum_args
        # readwrite_args behave in the same way as inc_args
        # from the perspective of first access and intents
        inc_args += readwrite_args
```
and then there are first checks for "inc" and "readwrite" args 
```
        for arg in inc_args:
            ...
            first_arg = self.first_access(arg.declaration_name)
            if first_arg.access != AccessType.WRITE:
                if arg not in declns["inout"]:
                    declns["inout"].append(arg)
            else:
                if arg not in declns["out"]:
                    declns["out"].append(arg)
```
and after that for "pure" writers
```
        for arg in write_args:
            # For every argument that is written to by at least one kernel,
            # identify the type of the first access - if it is read
            # or inc'd before it is written then it must have intent(inout).
            # However, we deal with inc and readwrite args separately so we
            # do not consider those here.
            first_arg = self.first_access(arg.declaration_name)
            if first_arg.access == AccessType.READ:
                if arg not in declns["inout"]:
                    declns["inout"].append(arg)
            else:
                if arg not in declns["out"]:
                    declns["out"].append(arg)
```
However, **there is a possibility that a "write" arg can have a  "read"-like first access access other than `AccessType.READ`** so the check should be something like
```
        for arg in write_args:
            ...
            first_arg = self.first_access(arg.declaration_name)
            if first_arg.access in (AccessType.READ, AccessType.READWRITE, AccessType.INC):
                if arg not in declns["inout"]:
                    declns["inout"].append(arg)
            else:
                if arg not in declns["out"]:
                    declns["out"].append(arg)
```
This would prevent having an Invoke argument with an incorrect `intent(out)` instead of the correct `intent(inout)` if previously it had a "read" access.

**Comment by rupertford** [comment]
Hi Iva, I am not sure there is a bug here, but please forgive me if I am wrong.

Looking at master, the existing comment above the one you added does hint at what is going on ...
```
            # For every argument that is written to by at least one kernel,
            # identify the type of the first access - if it is read
            # or inc'd before it is written then it must have intent(inout).
            # However, we deal with inc and readwrite args separately so we
            # do not consider those here.
            # TODO #801: The first access check should be for all "read"-like
            # accesses (e.g. "READWRITE", "INC") and not only for "READ".
```

The point is that inc and readwrite args are treated separately so there is no need to check.

As a simple illustration. Consider field `A` which first has a `gh_inc` access, then a `gh_write` access.

Therefore both the `inc_args` and `write_args` variables will contain field `A`.

However after the following code ...

```
        for arg in write_args[:]:
            if arg in inc_args:
                write_args.remove(arg)
```

field `A` is removed from `write_args` and only exists in `inc_args`.
Therefore field `A` is treated under the "inc_args" logic and will return `inout`.

Similarly a `gh_readwrite` followed by a `gh_write` will obey the same logic as `gh_readwrite` is treated in the same way as `gh_inc`.

Have I missed something?

**Comment by arporter** [comment]
It's possible we are all confused :-) but in #792 we found that a particular argument is being returned in two lists https://github.com/stfc/PSyclone/pull/792#discussion_r441653327 - both those with intent(in) and those with intent(out). My reading of the associated routine docstring was that `unique_declarations_by_intent` is dealing with a whole invoke and therefore a given variable cannot have more than one intent. Either the docstring needs updating or we have a bug but I'm not sure which...

**Comment by rupertford** [comment]
Ah, OK. Thanks @arporter. Yes, `unique_declarations_by_intent` is meant to deal with an invoke. It's obviously could be coded more simply irrespective of bug or not.

So for clarity, the issue is demonstrated in the following case (originally described in #792):

In the test example `20.5_multi_cma_invoke.f90`, `cma_op1` is a "read" arg in the`columnwise_op_app_kernel_type` call and a "write" arg in the `columnwise_op_mul_kernel_type` call. This results in cma_op1 being declared as both `intent(in)` and `intent(out)`.

I'll take a look.

**Comment by rupertford** [comment]
OK, I can confirm that `unique_declarations_by_intent` is not working as expected. The reason we don't see this in the resultant code is that it is not actually used for any declarations, other than lfric scalar arguments in the PSy-layer. In all other cases where there might be multiple accesses `intent(in)` is explicitly used - I guess because it was decided that all psy-layer objects should be intent(in) even if their content is modified?
So I guess the simplest thing to do is just fix this routine and add tests to make sure it behaves as expected for, at least, scalars.

**Comment by TeranIvy** [comment]
> 
> 
> OK, I can confirm that `unique_declarations_by_intent` is not working as expected. The reason we don't see this in the resultant code is that it is not actually used for any declarations, other than lfric scalar arguments in the PSy-layer. In all other cases where there might be multiple accesses `intent(in)` is explicitly used - I guess because it was decided that all psy-layer objects should be intent(in) even if their content is modified?

Yes, @rupertford, the behaviour is masked by `intent(in)` for field and operator arguments in PSy layer. 

Regarding the `20.5_multi_cma_invoke.f90` test example in question, `cma_op1` is `write` arg in `columnwise_op_asm_field_kernel_type` call, then `read` arg in `columnwise_op_app_kernel_type` call and finally `readwrite` arg in `columnwise_op_mul_kernel_type`. From the logic in `inc_args += readwrite_args` I think `cma_op1` should get picked up by `unique_declarations` for all three accesses and then excluded from `write_args` and `read_args` list as it is in `inc_args += readwrite_args`, which would then make its intent `inout`. Is this the expected behaviour?

**Comment by rupertford** [comment]
Hi @TeranIvy, I've rewritten the method in a - hopefully - simpler and more readable way. The logic I am using is:
for each unique field. If its first access is a write or sum then it is intent out, else if all of its accesses are reads then it is intent in else it is intent inout.
There should be a PR on this appearing later today or tomorrow as I have the new implementation working.
