### ISSUE TITLE
DAG visualisation not working on Binder

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#803]
Visualisation of the DAG in example three is not working on Binder:

![image](https://user-images.githubusercontent.com/17409212/85146128-6712e300-b245-11ea-8bf2-315abaf01a61.png)

This seems to be because the graphviz python bindings have not been installed.

**Comment by arporter** [comment]
Having read https://mybinder.readthedocs.io/en/latest/config_files.html#pipfile-and-or-pipfile-lock-install-a-python-environment I've added a `requirements.txt` file that requests that graphviz and termcolor be installed. I've done this directly on master since it doesn't affect anything else and it's then immediately available to test.
Would @rupertford or @sergisiso mind trying Binder for themselves just to confirm that it now works?

**Comment by sergisiso** [comment]
It works now @arporter
