### ISSUE TITLE
[NEMO] Cannot process Fortran containing long (continued) lines

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#809]
When parsing standards-compliant Fortran containing a very long continued line we have a problem. fparser removes all of the continuation symbols which means that PSyclone sees a line that is not standards compliant. If we request line-length limiting then rather than just limit the output, PSyclone will also reject incoming code that it sees as having lines that are too long.

Since the PGI compiler strictly enforces the line-length limit and has no 'override' flag, we can't then process code (that has very long continued lines) with PSyclone and compile it with PGI.

**Comment by arporter** [comment]
The problem seems to be that we have chosen to pass the 'limit-line-length' flag down to the parsing code:

https://github.com/stfc/PSyclone/blob/ec8196c5418b145934db211a3e80e1d261c27e07/src/psyclone/generator.py#L367-L373

If we didn't do this then (presumably) we wouldn't check the supplied source code.

**Comment by arporter** [comment]
To summarise:

If the `--limit` flag is specified to PSyclone then we check the lengths of the lines in the incoming source, as well as limiting the lengths in the output. Unfortunately, once the code has been parsed by fparser, any line-continuation symbols are stripped out. This means that perfectly legal Fortran (presented to the parser) containing a long line continued over several source lines now appears to be a single line of illegal length and PSyclone rejects it. Given that I don't think it's reasonable to expect fparser to retain information on line-continuation characters, it then seems wrong that we are checking the line lengths coming from it.

**Comment by rupertford** [comment]
I'm sure I'm wrong but I've just had a look at the implementation of line length and it seems right to me, at least in the context of unmodified kernel code. For algorithm and psy-layer code we limit the line length of the processed code and for kernels we check the line length of the original non-processed code.

**Comment by arporter** [comment]
I haven't looked in detail but I know that if I simply set `line_length` to False in the call to generate() then all is well. If I don't then PSyclone refuses to process the code. When you say "we check the line length of the original non-processed code" does that mean we read in the file and look at the length of each line (i.e. not using fparser)? As soon as we use fparser then all bets are off...

**Comment by rupertford** [comment]
Yes, we read the original kernel file and look at its line lengths - see utils.py check_line_lenth().

**Comment by rupertford** [comment]
The logic for this is that we would be letting through unmodified kernel code that breaks the line-length limit that we have imposed on the generated and modified code.

**Comment by arporter** [comment]
I've done a bit of digging and realised I was wrong in identifying continued lines as the source of the problem - it's actually in-line comments. The line-length check doesn't allow for them:

https://github.com/stfc/PSyclone/blob/c9caa3028924bbb66912ba09f30e9afcb517053c/src/psyclone/line_length.py#L58-L64

My reading of the standard is that comments are included in the line-length limit of 132 chars and therefore the code causing us this problem is non-standard. However, we still need to support it in some way. We could manually check for comments but that's difficult because of allowing for '!' chars within character strings. We could use some preprocessor to strip comments but then we have a dependency on a compiler. (In the general case we of course need a compiler anyway but for things like testing and Jupyter examples we want to minimise dependencies.)

**Comment by arporter** [comment]
I think the best solution is to add a new command-line flag that disables the line-length checks for incoming code. That way, we can still limit the line lengths in output code while not falling over if the input code doesn't conform. Do you agree @rupertford?

**Comment by rupertford** [comment]
That's fine by me. I think it makes sense to have line length checks switched on by default though as in general I think we want to avoid PSyclone being blamed for outputting code that is not compliant, when the fault is in the original kernel code.

**Comment by arporter** [comment]
I've altered the existing `-l/--limit` flag so that it takes a value as I felt that was the nicest approach:
 
    -l {off,all,output}, --limit {off,all,output}
                        limit the Fortran line length to 132 characters
                        (default 'off'). Use 'on' to apply limit to both input
                        and output Fortran. Use 'output' to apply line-length
                        limit to output Fortran only.

 However, it means this change is not backwards compatible so if we think that's an issue (@TeranIvy, @rupertford) I can make a new flag instead (maybe `--limit-output-only` or somesuch).

**Comment by arporter** [comment]
(Note that line-length limiting is currently switched off by default.)

**Comment by arporter** [comment]
Travis fails because a number of the examples use the `-l` flag and I haven't updated them yet. I'll hold off doing this until we've agreed on the command-line interface :-)

**Comment by rupertford** [comment]
I think your proposed solution looks nice and I have no problem with the change. However, the Met Office use it I believe so @TeranIvy might have a different perspective. Presumably it is not possible to have the extra value being optional?

**Comment by arporter** [comment]
> 
> 
> I think your proposed solution looks nice and I have no problem with the change. However, the Met Office use it I believe so @TeranIvy might have a different perspective. Presumably it is not possible to have the extra value being optional?

Sadly not, no :-(
