### ISSUE TITLE
[examples] make compile for the examples fails if dl_esm_inf has not already been built

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#810]
@TeranIvy has found that we've neglected to ensure that those examples that require the dl_esm_inf library actually build it - compilation simply fails saying it can't find one of the `.mod` files.

I think we have two choices:

 1. Choose to leave it this way and document the fact that a user must build dl_esm_inf first.
 2. Alter the make system so that it builds the library if it is required.

I favour option 2 (especially since @hiker and I both thought that this was what happened already ;-) ) but thought I would discuss it here to make sure we've considered all use cases. (Obviously, when running compilation tests in the test suite we already do compile dl_esm_inf but we do that in a temporary, test-specific location.)

**Comment by hiker** [comment]
Considering that eg2 already compiles dl_esm_inf, I don't think we need to discuss this, I'll just fix the other examples.

**Comment by arporter** [comment]
Oh yes, so it does!

**Comment by arporter** [comment]
#816 merged.
