### ISSUE TITLE
Support transforming ranges to explicit loops when the ranges differ

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#814]
Using Fortran syntax ... we may have the following situation ...

`a(:) = b(::2)`

This would require the index of one of the arrays to be computed. For example:

```
do i=lbound(a,1),ubound(a,2):1
  a(i)= b(2*(i-1)+1)
end do
```

At the moment the transformation ArrayBound2LoopTrans will raise an exception if the above case is found.

In the general case ...

`a(fn1(..),fn2(..),fn3(..)) = b(fn4(..),fn5(..),fn6(..))`

there are a number of solutions. The simplest is probably the following ...

```
do i=fn1(..),fn2(..),fn3(..)
  a(i)= b(fn6(..)*(i-fn1(..)+fn4(..)-1)+1)
end do
```

**Comment by sergisiso** [comment]
When ranges differ an offset is added. This is not an issue anymore.
