### ISSUE TITLE
remove nemoimplicitloop

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#827]
The nemo api currently creates a nemo-api-specific node when it finds Fortran array notation. This is not a nemo-specific concept so should either be supported directly in the PSyIR or removed. As the PSyIR now supports array notation (using the Range node) it has been agreed to remove nemoimplicitloop. A generic PSyIR ImplicitLoop Node could be re-introduced if it turns out that Range nodes in array references are a pain to transform.

The removal of NemoImplicitLoop should not affect work using the NEMO api as no transformations currently make use of this node, but of course it will need to be tested with the existing nemo transformation scripts to make sure there are no unforeseen issues.

**Comment by rupertford** [comment]
Created branch 827_remove_nemoimplicitloop

**Comment by arporter** [comment]
#829 is merged.
