### ISSUE TITLE
[PSyIR FE] MAXVAL and MINVAL intrinsic functions not supported

### ISSUE THREAD

**Issue by deardenchris** [stfc/PSyclone#840]
I found some NEMO code that uses the MAXVAL intrinsic within stpctl.F90. Use of MAXVAL (and MINVAL) also occurs within lib_fortran.F90. When processed with PSyclone, these lines of code are not included within an ACC KERNELS region automatically.

**Comment by arporter** [comment]
@rupertford, this is another one that has quite a big effect in the NEMO work. It's complicated a bit by the fact that both of these intrinsics accept a `mask` argument which is used a fair bit in NEMO.

**Comment by rupertford** [comment]
@arporter or @deardenchrisl, could you please paste some examples of lines of Fortran code from nemo (or equivalent code) that uses maxval and minval with and without masks so I can create relevant tests. Many thanks.

**Comment by rupertford** [comment]
One more question (which you would answer with examples anyway :-)). Does nemo make use of the `dim` option, or is it just `mask`?

**Comment by arporter** [comment]
Here you go:

    ze1max = MAXVAL(e1t(:, :), mask = tmask_i(:, :) == 1._wp)
    zmax(3) = MAXVAL(- tsn(:, :, :, jp_sal), mask = tmask(:, :, :) == 1._wp)
    zrnfcl(:, :, 1) = MAXVAL(zrnfcl(:, :, :), DIM = 3)

**Comment by arporter** [comment]
and...

    ze1min = MINVAL(e1t(:, :), mask = tmask_i(:, :) == 1._wp)

so I think we do want `dim` too.

**Comment by sergisiso** [comment]
Oh that's an interesting test for implicit loops:
`ze1min = MINVAL(e1t(:, :), mask = tmask_i(:, :) == 1._wp)`
The right one is, the left one isn't.

@rupertford asked me if I thought this should be an Operator or the implementation with PSyIR constructs. Which I said an Operator, but I see now that there is a possible optimization to avoid the temporary mask if we have the implementation and the implicit loop figured out properly.

I would still go for the simpler implementation. But I am just wondering if Fortran compilers do the smart thing latter on or is it something that PSyclone could attempt.

In fact in `zmax(3) = MAXVAL(- tsn(:, :, :, jp_sal), mask = tmask(:, :, :) == 1._wp)` the left one also has an implicit loop applying the minus operator to the whole tsn array. Again it would be good to check if the Fortran compiler creates a temporary or is smart enough to bring the element operation inside the MAXVAL implementation loop.

**Comment by arporter** [comment]
Related to this, Simon has also reported that `SUM` with a `dim=xx` argument ends up in a CodeBlock. We need to handle the `dim=xx` form.

**Comment by arporter** [comment]
Can @rupertford or @sergisiso remind me where we're up to with this?

**Comment by arporter** [comment]
Note to self: this is one of the issues that results in us requiring manual tweaks to the NEMO source.

**Comment by sergisiso** [comment]
> Can @rupertford or @sergisiso remind me where we're up to with this?

I don't think there has been any progress on this

**Comment by rupertford** [comment]
No progress on this from me apart from getting `sum` working along with a sum-to-code transformation

**Comment by rupertford** [comment]
The requirements for these two intrinsics look very similar to the sum2code transformation I implemented previously so I'll take this on.

**Comment by rupertford** [comment]
Created branch [840_max_min_val](https://github.com/stfc/PSyclone/tree/840_max_min_val)
