### ISSUE TITLE
Create a NEMO API version of ArrayRange2LoopTrans transformation

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#843]
The ArrayRange2LoopTrans transformation converts an array range to a loop in the PSyIR. For the NEMO API we want to be able to return a NemoLoop rather than a Loop with its loop type set to the expected value based on the index of the array that is being modified. We also want to place the computation captured in the array range in a NEMOKern node (once all ranges have been transformed). This will mean that the new explicit loops will have the same structure as the existing loops.

**Comment by arporter** [comment]
This would then allow us to correctly capture code such as (taken from the tra_adv mini-app):

      DO jk = 2, jpk - 1
        zwx(:, :, jk) = tmask(:, :, jk) * (mydomain(:, :, jk - 1) - mydomain(:, :, jk))
      END DO

Currently the assignment is not captured as a NEMOKern and therefore transformations that are looking for loops containing kernels will miss it.

**Comment by rupertford** [comment]
Is this something for the tutorial @arporter?

**Comment by arporter** [comment]
Yes, but it's not essential and I figure we've got enough to do. At least it doesn't result in incorrect code, unlike some of the other things I'm discovering :-(

**Comment by rupertford** [comment]
Oh dear! I can probably commit to doing this so if you want it, feel free to add the tutorial label to it - it is something I need to do for ESiWACE2 anyway.

**Comment by arporter** [comment]
I'll see how many issues I've generated by the end of the tutorial and then decide :-)

**Comment by rupertford** [comment]
Created branch [843_nemo_arrayrange_to_loop](https://github.com/stfc/PSyclone/tree/843_nemo_arrayrange_to_loop)
