### ISSUE TITLE
jupyter nemo tutorial

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#848]
We are providing a self learning jupyter tutorial for the ESiWACE2 summer school so need to create it.

**Comment by rupertford** [comment]
Created branch [848_jupyter_tutorial](https://github.com/stfc/PSyclone/tree/848_jupyter_tutorial)

**Comment by rupertford** [comment]
I'll limit this to the NEMO API (and an intro) to start off with in case people disagree with what I've done. Therefore the tutorial for LFRic will be a separate issue.

**Comment by arporter** [comment]
This too is on master now.
