### ISSUE TITLE
Move Rules For Intergrid Kernels documentation to correct place

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#85]
The dynamo0p3 api section has an Intergrid Kernels subsection which is in the wrong place as it splits the subsection describing CMA (the CMA subsubsections are now after the Intergrid Kernels subsection). This needs to be moved.

**Comment by rupertford** [comment]
As can be seen above I've already created a branch ... move_docs_section

**Comment by arporter** [comment]
#86 has been merged to master. Closing issue.
