### ISSUE TITLE
Bug in Dynamo0p3RedundantComputationTrans (field.call in dynamo0p3.halo_check_arg returns DynHaloExchange)

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#867]
When trying to group built-in and kernel calls in a single invoke in a newly added LFRic algorithm ([LFRic ticket #2185](https://code.metoffice.gov.uk/trac/lfric/ticket/2185#comment:47))
```
 call invoke( name = "initialise vertical_departures", &
    setval_c(dep_pts_z, 0.0_r_def), &
    setval_c(dep_wind_n, 0.0_r_def), &
    setval_c(dep_wind_np1, 0.0_r_def), &
    calc_departure_wind_kernel_type(dep_wind_n, wind, chi), &
    setval_X(dep_wind_np1, dep_wind_n), &
    vertical_trapezoidal_kernel_type(dep_pts_z, dep_wind_n, dep_wind_np1))
```
the `Dynamo0p3RedundantComputationTrans` in the LFRic optimisation script [global.py](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/optimisation/meto-spice/global.py) returns the following error:
```
Generation Error: Generator: script file '/data/users/ikavcic/r24358_split_scheme/gungho/optimisation/meto-spice/global.py'
raised the following exception during execution ...
{
      File "/data/users/ikavcic/r24358_split_scheme/gungho/optimisation/meto-spice/global.py", line 67, in trans
    schedule, _ = rtrans.apply(loop, options={"depth": 1})
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/transformations.py", line 2406, in apply
    loop.update_halo_exchanges()
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 7160, in update_halo_exchanges
    self.create_halo_exchanges()
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 7198, in create_halo_exchanges
    self._add_halo_exchange(halo_field)
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 7151, in _add_halo_exchange
    self._add_halo_exchange_code(halo_field)
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 7130, in _add_halo_exchange_code
    required, _ = exchange.required()
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 5921, in required
    required_clean_info = self._compute_halo_read_depth_info()
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 5839, in _compute_halo_read_depth_info
    halo_info_list = self._compute_halo_read_info()
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 5859, in _compute_halo_read_info
    in read_dependencies]
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 5858, in <listcomp>
    return [HaloReadAccess(read_dependency) for read_dependency
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 6543, in __init__
    self._compute_from_field(field)
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 6588, in _compute_from_field
    call = halo_check_arg(field, AccessType.all_read_accesses())
      File "/data/users/lfric/modules/packages.rhel7/psyclone/1.9.0/lib/python3.6/site-packages/psyclone/dynamo0p3.py", line 6445, in halo_check_arg
    "found {1}".format(field.name, type(call)))
    psyclone.errors.GenerationError: Generation Error: In HaloInfo class, field 'dep_wind_n' should be from a call but found <class 'psyclone.dynamo0p3.DynHaloExchange'>
```

The problematic combination of calls can be narrowed down to two last calls
```
 call invoke( name = "initialise vertical_departures", &
    setval_X(dep_wind_np1, dep_wind_n), &
    vertical_trapezoidal_kernel_type(dep_pts_z, dep_wind_n, dep_wind_np1))
```

The  `Dynamo0p3RedundantComputationTrans` is applied to `setval_c` and `setval_X` built-in calls to the depth of 1, as can be seen from the optimisation script code:
```
        for loop in schedule.loops():
            if loop.iteration_space == "dofs":
                if len(loop.kernels()) != 1:
                    raise Exception(
                        "Expecting loop to contain 1 call but found '{0}'".
                        format(len(loop.kernels())))
                if loop.kernels()[0].name in ["setval_c", "setval_x"]:
                    setval_count += 1
                    schedule, _ = rtrans.apply(loop, options={"depth": 1})
``` 

Printing the type of `loop.kernels()[0]`, its arguments and the calls of these arguments in the `global.py` optimisation script returns `<class 'psyclone.dynamo0p3_builtins.DynSetvalXKern'>`, `dep_wind_np1`, `dep_wind_n`  and `<class 'psyclone.dynamo0p3_builtins.DynSetvalXKern'>`. Therefore, it is not quite clear how `field.call` manages to become `<class 'psyclone.dynamo0p3.DynHaloExchange'>` by the time the argument call is checked in `dynamo0p3.halo_check_arg` support function.

Interestingly enough, this failure does not happen when the `setval_X` built-in call is placed **after** the `vertical_trapezoidal_kernel_type` call in the invoke (including the previous `setval_c` and `calc_departure_wind_kernel_type` calls not shown below)
```
 call invoke( name = "initialise vertical_departures", &
    vertical_trapezoidal_kernel_type(dep_pts_z, dep_wind_n, dep_wind_np1), &
    setval_X(dep_wind_np1, dep_wind_n) )
```
Also, when the last call to `vertical_trapezoidal_kernel_type` is in a separate invoke
```
 call invoke( name = "initialise vertical_departures", &
    setval_c(dep_pts_z, 0.0_r_def), &
    setval_c(dep_wind_n, 0.0_r_def), &
    setval_c(dep_wind_np1, 0.0_r_def), &
    calc_departure_wind_kernel_type(dep_wind_n, wind, chi), &
    setval_X(dep_wind_np1, dep_wind_n) )
 call invoke( vertical_trapezoidal_kernel_type(dep_pts_z, dep_wind_n, dep_wind_np1) )
```
everything works normally.

The algorithm and kernel files can be found at these links (algorithm is new in the branch from the ticket, kernels already exist in LFRic trunk):
- [calc_vertical_departure_alg_mod.x90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/mohamedzerroukat/r24358_split_scheme/gungho/source/algorithm/calc_vertical_departure_alg_mod.x90?rev=24583)
- [calc_departure_wind_kernel_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/mohamedzerroukat/r24358_split_scheme/gungho/source/kernel/calc_departure_wind_kernel_mod.F90?rev=24518)
- [vertical_trapezoidal_kernel_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/branches/dev/mohamedzerroukat/r24358_split_scheme/gungho/source/kernel/vertical_trapezoidal_kernel_mod.F90?rev=24518)

**Comment by arporter** [comment]
Thanks for investigating this @TeranIvy. The `HaloExch` nodes are inserted into the `Schedule` dynamically so it is probably not that a kernel call has turned into a halo exchange, simply that the `halo_check_arg` (https://github.com/stfc/PSyclone/blob/355d0b05bb7a9d6fb83462865380eeb445245016/src/psyclone/dynamo0p3.py#L5739) method is being called for the wrong object.

**Comment by TeranIvy** [comment]
> 
> 
> Thanks for investigating this @TeranIvy. The `HaloExch` nodes are inserted into the `Schedule` dynamically so it is probably not that a kernel call has turned into a halo exchange, simply that the `halo_check_arg` (
> 
> https://github.com/stfc/PSyclone/blob/355d0b05bb7a9d6fb83462865380eeb445245016/src/psyclone/dynamo0p3.py#L5739
> ) method is being called for the wrong object.

It's interesting that this doesn't happen when the calls are re-ordered. This probably requires looking into every step of the dynamical insertion of halo exchanges.

**Comment by arporter** [comment]
In your minimal reproducer, if `setval_X` is replaced by `setval_c(dep_wind_np1, 0.0)` does the same error happen?

**Comment by TeranIvy** [comment]
Nope, it doesn't happen when `setval_X` is replaced by either `setval_c(dep_wind_np1, 0.0)` or `setval_c(dep_wind_n, 0.0)` (the error report above is for halo exchange on `dep_wind_n`) or when both are present. All of them are fine.

Also, when  `setval_X(dep_wind_np1, dep_wind_n)` arguments are re-ordered as `setval_X(dep_wind_n. dep_wind_np1)` the error happens but this time for `dep_wind_np1`. Both `dep_wind_np1` and `dep_wind_n` have `GH_READ` access in `vertical_trapezoidal_kernel_mod` so the script breaks for the argument that also has `GH_READ` access in `setval_X` (the second one).

**Comment by TeranIvy** [comment]
If it helps, the schedule before the transformations looks like this
```
InvokeSchedule[invoke='invoke_initialise_vertical_departures', dm=True]
    0: Loop[type='dofs', field_space='any_space_1', it_space='dofs', upper_bound='nannexed']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: BuiltIn setval_c(dep_pts_z,0.0_r_def)
    1: Loop[type='dofs', field_space='any_space_1', it_space='dofs', upper_bound='nannexed']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: BuiltIn setval_c(dep_wind_n,0.0_r_def)
    2: Loop[type='dofs', field_space='any_space_1', it_space='dofs', upper_bound='nannexed']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: BuiltIn setval_c(dep_wind_np1,0.0_r_def)
    3: HaloExchange[field='wind', type='region', depth=1, check_dirty=True]
    4: HaloExchange[field='chi(1)', type='region', depth=1, check_dirty=True]
    5: HaloExchange[field='chi(2)', type='region', depth=1, check_dirty=True]
    6: HaloExchange[field='chi(3)', type='region', depth=1, check_dirty=True]
    7: Loop[type='', field_space='w2', it_space='cells', upper_bound='cell_halo(1)']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: CodedKern calc_departure_wind_code(dep_wind_n,wind,chi) [module_inline=False]
    8: Loop[type='dofs', field_space='any_space_1', it_space='dofs', upper_bound='nannexed']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: BuiltIn setval_x(dep_wind_np1,dep_wind_n)
    9: HaloExchange[field='dep_wind_n', type='region', depth=1, check_dirty=False]
    10: HaloExchange[field='dep_wind_np1', type='region', depth=1, check_dirty=False]
    11: Loop[type='', field_space='w2', it_space='cells', upper_bound='cell_halo(1)']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: CodedKern vertical_trapezoidal_code(dep_pts_z,dep_wind_n,dep_wind_np1) [module_inline=False]
```

**Comment by arporter** [comment]
I've used your reproducer to create a (failing) test. How urgent is this? The reason I ask is that @rupertford is probably best placed to investigate since he wrote this section but he's on leave until next week.

**Comment by arporter** [comment]
The problem seems to be to do with the dependence analysis for the halo exchange introduced before the built-in call once it is transformed to perform redundant computation (prior to this it didn't need one because computation over annexed-dofs is enabled). Field `f1` is listed as having two read dependencies, the first is OK (it's `psyclone.dynamo0p3_builtins.DynSetvalXKern`) but the second is a `DynHaloExchange`. Presumably it is there because we're in the process of updating the halo exchanges (the stack trace goes back up to `loop.update_halo_exchanges`) and it was originally needed because the user-supplied kernel reads from it and it's on a continuous function space.

**Comment by arporter** [comment]
The Schedule for the failing test *before* the transformation for redundant computation looks like:

    InvokeSchedule[invoke='invoke_0', dm=True]
    0: Loop[type='dofs', field_space='any_space_1', it_space='dofs', upper_bound='nannexed']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: BuiltIn setval_x(f2,f1)
    1: HaloExchange[field='f1', type='region', depth=1, check_dirty=True]
    2: HaloExchange[field='f3', type='region', depth=1, check_dirty=True]
    3: HaloExchange[field='f4', type='region', depth=1, check_dirty=True]
    4: Loop[type='', field_space='w1', it_space='cells', upper_bound='cell_halo(1)']
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]
        Literal[value:'1', Scalar<INTEGER, UNDEFINED>]
        Schedule[]
            0: CodedKern testkern_code(aval,f2,f1,f3,f4) [module_inline=False]

Presumably the `HaloExch` for `f1` is required because we are looping out to the depth-1 halo in order to ensure that the annexed dofs for `f2` (written to by `testkern_code`) are clean?

**Comment by arporter** [comment]
I need to check how the `loop.update_halo_exchanges()` is supposed to handle pre-existing halo exchanges. Obviously it must do (in theory) because the whole point of adding redundant computation is to remove them.

**Comment by TeranIvy** [comment]
> 
> 
> I've used your reproducer to create a (failing) test. How urgent is this? The reason I ask is that @rupertford is probably best placed to investigate since he wrote this section but he's on leave until next week.

@arporter, it is not urgent as we can work around this by not having all calls in one invoke - perhaps not optimal for performance but it will get us to the next release. We have a practice of referencing PSyclone issues in LFRic code to add the PSyclone support as it become available in releases, so I will ask the developer to reference this issue.

**Comment by TeranIvy** [comment]
Also, I am changing built-in accesses from `INC` to `READWRITE` (and potentially halo exchanges) in #823 so that may influence this problem as well. I will try installing PSyclone from that branch and see what happens with this code.
