### ISSUE TITLE
Missing halo exchange before call to Builtin with RW access.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#885]
In #823 it was discovered that changing the access from 'inc' to 'readwrite' of a field argument to a builtin doing redundant computation meant that a (required) halo exchange for that field was removed.

**Comment by arporter** [comment]
The Schedule before and after the transformation to perform redundant computation looks like:
![sched](https://user-images.githubusercontent.com/17409212/92399779-c389ee00-f122-11ea-9d3f-55999f2e7130.png)
Note that 'computation on annexed dofs' is 'on'. This is taken from `test_rc_dofs_depth` in `tests/domain/lfric/transformations/dynamo0p3_transformations_test.py`.

**Comment by rupertford** [comment]
Created [885_halo_exchange_bug](https://github.com/stfc/PSyclone/tree/885_halo_exchange_bug)
