### ISSUE TITLE
-v command-line flag does not work unless a filename is supplied.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#888]
Because we use `argparse.ArgumentParser` to handle command-line flags we automatically get an error if the user omits the (mandatory) filename argument. Unfortunately this means that simply running `psyclone -v` to get the version number fails.
I *think* what needs to be done is check for a solitary `-v` flag *before* we call `parse_args` in the `main()` routine in the generator.py file.

**Comment by hiker** [comment]
I believe we discussed this when I added the -v flag 😄 I couldn't find an easy way of handling optional arguments (and still getting help at that time iirc). Googling now shows https://stackoverflow.com/questions/4480075/argparse-optional-positional-arguments - that would make the filename optional, but then we would have to check ourselves that filename is specified if no -v is given.

**Comment by hiker** [comment]
Here it is: #175.

**Comment by arporter** [comment]
Oh yes, thanks @hiker - I'd forgotten that!

**Comment by arporter** [comment]
I've just found that `argparse` does know about 'version' (like 'help') and can take special action for it. See https://docs.python.org/3/library/argparse.html#action
