### ISSUE TITLE
Update Coding Style in Dev guide with details on raising exceptions

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#897]
1. We are currently inconsistent in whether we give the name of the current routine when creating an exception.
2. We also do not consistently use 'raise from' when re-raising an exception.
3. It would be nice to agree on the tense to use in exception messages (e.g. "expected ..." versus "expecting ...")

We need to agree on the rule for 1. and then document all of these things in the Coding Style of the Dev guide.

I favour not specifying the name of the raising routine since that is available in the Python stacktrace. What do @TeranIvy, @sergisiso, @rupertford and @hiker think?

**Comment by arporter** [comment]
Once we've agreed the rules this might make a nice PR for @drewsilcock come Hactoberfest :-)

**Comment by hiker** [comment]
I agree with not specifying the name (besides duplicating information available elsewhere, it also means more work when renaming something). I have no real preferences regarding the tense - to me 'expected' sounds more natural, but that doesn't mean a lot coming from a non-native speaker 😏

**Comment by TeranIvy** [comment]
> 
> 
> I agree with not specifying the name (besides duplicating information available elsewhere, it also means more work when renaming something). I have no real preferences regarding the tense - to me 'expected' sounds more natural, but that doesn't mean a lot coming from a non-native speaker 😏

+1 for all
