### ISSUE TITLE
Support for read-only integer scalar arguments

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#90]
During work on renaming `dynamo0p3` built-ins (issue #61, PR #71), it became clear that it was not possible to add the planned built-in `inc_X_powint_n` (raising a field to an integer power) due to limitation for only `gh_field` and `gh_real` arguments. 

Simply adding `gh_integer` to `dynamo0p3_builtins.py` raises other errors (e.g. `Generation Error: Integer reductions are not currently supported by the LFRic infrastructure in psyGen`). The full error report is in [Powint_generation_error.txt](https://github.com/stfc/PSyclone/files/1239349/Powint_generation_error.txt)

This issue is opened to add the support for read-only integer scalar arguments to built-ins (and `inc_X_powint_n` built-in as well).

**Comment by arporter** [comment]
Closing issue as #102 now merged to master.
