### ISSUE TITLE
[LFRic] Make module-level USE statements flexible

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#908]
Issue #817 introduces support for fields of different primitive types by specifying data type for the existing `real` fields and introducing `integer` fields. The LFRic infrastructure initially only had `field_type` as all fields had `real` data. Now it has `field_type` for `real`-valued fields (in [field_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/field/field_mod.F90)) and `integer_field_type` for `integer`-valued fields (in [integer_field_mod.F90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/field/integer_field_mod.F90)). These classes are subclasses of the `field_parent_type` defined in [field_parent_mod.f90](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/field/field_parent_mod.f90).

From the PSyclone LFRic API point, this means that we need to generate `use integer_field_mod, only: integer_field_type, integer_field_proxy_type` to support integer fields.

The generation of `use` statements for LFRic fields and operator classes is currently fixed in [class DynamoPSy(PSy)](https://github.com/stfc/PSyclone/blob/master/src/psyclone/dynamo0p3.py#L1001) to always contain `use` statements for fields, LMA operators and CMA operators whether or not the generated PSy module uses them. We can go down this route for integer fields as well but I think this would not be wise as there will be more different field and potentially operator types with the addition of multi-data fields, 2D fields, different precisions etc.

I suggest making this generation dependent on what objects are required in the Invoke list generated for the PSy module. That means that the `use` statements for a specific object type (and its proxy type) would only be added if these objects are found in Invokes. From the technical point of view this means that the `class DynamoInvoke` that has access to the objects would inform `class DynamoInvokes` what objects are used and then `DynamoInvokes` could update the list of objects to add to `use` statements or generate the `use` statements for in `DynamoPSy`.

**Comment by arporter** [comment]
I know I'm a bit late to the party here but unless this is a trivial amount of work then I wouldn't bother. The existing solution works OK, even though it's not ideal and, as Rupert said, this code-generation will all be replaced with the move to PSyIR. We have a lot of work on and don't need to give ourselves more :-)

**Comment by TeranIvy** [comment]
@arporter, it's not so much work and it prevents generating redundant code. We will have more than one field and two operator types way before we have full application of PSyIR so we need a way to handle them.
