### ISSUE TITLE
Warnings when building Reference Guide

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#916]
When building the Reference guide we get a lot (25) of warnings about incorrectly formatted docstrings.

**Comment by arporter** [comment]
I've managed to fix all warnings except for those related to a couple of module variables (e.g. `node.SCHEDULE_COLOUR_MAP`). It seems that autodoc is generating incorrectly-formatted sphinx 'code' for those and I can't find a way of fixing it:

    /home/me/Projects/PSyclone/src/psyclone/psyir/nodes/__init__.py:docstring of psyclone.psyir.nodes.SCHEDULE_COLOUR_MAP:3: WARNING: Unexpected indentation.
    /home/me/Projects/PSyclone/src/psyclone/psyir/nodes/__init__.py:docstring of psyclone.psyir.nodes.SCHEDULE_COLOUR_MAP:4: WARNING: Block quote ends without a blank line; unexpected unindent.
    /home/me/Projects/PSyclone/src/psyclone/psyir/nodes/__init__.py:docstring of psyclone.psyir.nodes.SCHEDULE_COLOUR_MAP:7: WARNING: Unexpected indentation.
    /home/me/Projects/PSyclone/src/psyclone/psyir/nodes/__init__.py:docstring of psyclone.psyir.nodes.SCHEDULE_COLOUR_MAP:9: WARNING: Inline strong start-string without end-string.

I thought perhaps I could override the autodoc-generated documentation by explicitly documenting the `SCHEDULE_COLOUR_MAP` property but I can't get that to work either.

**Comment by arporter** [comment]
I think this problem is because those module variables are dicts and Sphinx is pulling in the docstring for dict. I *hope* that means that https://github.com/sphinx-doc/sphinx/issues/7805 fixes this problem.

**Comment by arporter** [comment]
Nope, I've updated to Sphinx 3.2.1 which was released on 14th of August and the warnings remain. Oh well, I think I've done all I can.

**Comment by rupertford** [comment]
Keeping this issue open while @arporter looks to see if there is a solution to the warnings produced by external docstrings. If the answer is no then this issue can be closed.

**Comment by arporter** [comment]
I pursued this on the relevant forum but was unable to find a solution so closing for now.
