### ISSUE TITLE
test_lookup_2 test fails with AssertionError

### ISSUE THREAD

**Issue by AdamVoysey** [stfc/PSyclone#937]
The `test_lookup_2` unit test fails with the error:

`E       assert "'var2' exists in the Symbol Table but has visibility 'PRIVATE' which does not" in '<ExceptionInfo SymbolError tblen=2>'`
`E        +  where '<ExceptionInfo SymbolError tblen=2>' = str(<ExceptionInfo SymbolError tblen=2>)`

**Comment by rupertford** [comment]
Hi @AdamVoysey. I presume this is the test in `tests/psyir/symbols/symboltable_test.py`? Is this failing for you on master as all tests must pass in order for code to go on master (as checked by travis) so do work, at least in the environment we test them in :-)

**Comment by AdamVoysey** [comment]
Yes, its failing on master (but only for python 3). I think I have a fix - its pretty trivial.

**Comment by arporter** [comment]
I think the real question then is, how do we get the problem to show itself on Travis? Do we need (want) to add another Python version to the matrix?

**Comment by rupertford** [comment]
Great. It must be the particular version of Python 3 you are using as it works for the version travis uses and for the versions the rest of the developers currently use - although @andrewcoughtrie did mention something about failing tests with a certain version of Python3, so perhaps it is related? We don't appear to have a record of this problem so as @arporter says it would be good to narrow it down to a version so we can reproduce the problem outside of your environment.

**Comment by AdamVoysey** [comment]
Created branch [937_test_lookup_2_fix](/stfc/PSyclone/tree/937_test_lookup_2_fix)

**Comment by AdamVoysey** [comment]
We are testing against Python 3.6.8 (with pytest-5.2.1)

**Comment by rupertford** [comment]
That is indeed an error in the tests. I thought we'd picked up all of the `error -> error.value` changes. Well found.

**Comment by AdamVoysey** [comment]
OK, I think I have done the right thing here to get this fixed. (?) My github experience/wisdom is poor, so forgive me if I have done this is totally wrong! I think I now need a reviewer?

**Comment by rupertford** [comment]
You've done the right thing. You just need to wait until travis has completed its tests then add the label "ready for review", add yourself as the assignee and, if you want, request andy or I to review explicitly - all in the pull request #938.

**Comment by rupertford** [comment]
You might want to sign yourself up to hacktoberfest?
