### ISSUE TITLE
PSyIR arrays dimensions correctness checking

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#948]
If a PSyIR array dimension is declared with a data symbol then the data symbol should not be a local symbol unless it is a constant as otherwise it will not have a valid value. The code to test this was added in pr #947 (see datatypes.py), however it causes quite a few errors in existing tests so the code was commented out and this issue created instead.

Also, it would be good to ensure that integers and literals values are > 0.

**Comment by arporter** [comment]
The one test that was tagged as xfailing and referenced this issue was failing for a different reason. Once corrected it passes so I'm closing this issue. There are no other references to this issue in the code base.
