### ISSUE TITLE
[LFRic] Forbid white space in Invoke names.

### ISSUE THREAD

**Issue by rupertford** [stfc/PSyclone#95]
As reported by Chris Maynard ... PSyclone sees strings with "_" as being the same as strings with " ". These are different so need to be identified as being different. We might like to raise an exception if white space is used. This should be raised this with the lfric folk before implementing a solution to this bug.

```
module alg
  use field_mod, only: field_type
  implicit none
  subroutine mini_alg
    implicit none
    type(field_type) :: f1, f2, f3
    call invoke( name = "x times y", &
                 X_times_Y(f1, f2, f3)  &
                  )
    call invoke( name = "x_times_y", &
                 X_times_Y(f2, f3, f1)  &
                  )
  end subroutine mini_alg
end module alg
```

If he runs psyclone over this he gets …

`Parse Error: Found multiple named invoke()'s with the same name: ''"`

**Comment by TeranIvy** [comment]
Hi @arporter! I do not think there is a problem with allowing spaces, as long as PSyclone can go through the list of generated names after replacing " " with "_" and check whether there are duplicates (of course, it should raise an exception).

**Comment by stevemullerworth** [comment]
I recall that we had a discussion at an LFRic meeting, and decided that we would not allow whitespace.

So in essence we can provide a simple explanation to a user that the generated subroutine name will be formed by prefixing the given name with "invoke_" and suffixing it with a number (if the name is a duplicate).

**Comment by TeranIvy** [comment]
Hi @arporter, is this still active?

**Comment by TeranIvy** [comment]
Are there more updates on status of this issue? Can it be closed?

**Comment by stevemullerworth** [comment]
The LFRic coding standards mandate that the name should meet rules for naming subroutines. It would be nice to enforce this as it makes it easier to explain the link between the name and the name of the invoke subroutine. For this reason it would be nice to enforce the no-white-space rule.

**Comment by arporter** [comment]
I was thinking of taking this on but that will involve messing with the `Alg` class in `alg_gen.py`. The question for @rupertford is, is this one of the files that you are going to re-write in the near future?

**Comment by rupertford** [comment]
Is it still a problem? It's not been raised by the Met Office for a number of years. Assuming it is, Alg and alg_gen will be replaced and at the moment there should be an equivalent bit of code in the new implementation that does the same thing, so it will be in two places. We can remove this code when the new algorithm generation is fully working but given that the code will be slower we should probably wait until the new metadata can also be used to generate the psy-layer. I've started working on this but it will be a while. So, to cut short a long story I would say to go ahead and make the changes in the existing code if it is a pressing issue but please also look at the new implementation and add any required changes there too.

**Comment by arporter** [comment]
OK, I will take this on.

@stevemullerworth in #994 @hiker suggested that we don't automatically prepend "invoke_" to a supplied name. Is that change OK with you or will it break things in LFRic?

**Comment by stevemullerworth** [comment]
If I understand the point @hiker is making, it relates to writing transformation scripts that apply to specific invokes. If so, it makes complete sense for the script to be able to use the exact same string. And maybe enforcing lower case removes all uncertainty?

It is helpful, when debugging, to be able to distinguish PSy-layer calls from alg calls by searching for "call invoke". But I don't have a strong opinion, and once the subroutine name is identical to the name string searching for the transformed call line will be easier anyway.

I created the following LFRic ticket to fix existing names (password protected link)

https://code.metoffice.gov.uk/trac/lfric/ticket/3848

**Comment by arporter** [comment]
Great, thanks Steve. I'll proceed to follow @hiker's suggestions then.

**Comment by arporter** [comment]
`Call` has an almost identical `_validate_name` method.

**Comment by arporter** [comment]
`Config` defines the `valid_name` regex.

**Comment by arporter** [comment]
Upon reflection, it seems odd that `Config` has this property. I shall therefore (also) implement something in `psyclone.utils` and investigate what `Config.valid_name` is used for.

**Comment by hiker** [comment]
The leading underscore was likely my fault - I have to admit I only learned recently that Fortran does not allow leading underscores. I added the original name to verify that the PSyData prefix (i.e. if the prefix (like `extract_`) is a valid Fortran name when added to `psydata`. That is afaik the only use of this, and obviously if we need similar tests, it should go elsewhere :)
