### ISSUE TITLE
[LFRic] Remove orientation support

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#960]
Up to now we have kept the existing support for 'orientation' in PSyclone, even though it is not actively used in LFRic. However, it now turns out that because of this, some of the compilation tests require that `get_cell_orientation` exist in the LFRic infrastructure. Joerg's work to bring in a full but hacked version of the infrastructure has highlighted this problem - we clearly shouldn't have to modify that infrastructure to introduce a routine that has been removed.

Therefore, we should probably remove orientation support from the LFRic API.

**Comment by TeranIvy** [comment]
I grepped the LFRic code for `get_cell_orientation` and it comes back with a function in `gungho/source/algorithm/runtime_constants_mod.x90` which is definitely not part of the LFRic infrastructure. Another thing is the metadata support for `GH_ORIENTATION` that is only mentioned in `infrastructure/source/field/argument_mod.F90` and nowhere else in LFRic. My guess is that this support is no longer needed. @thomasmelvin, what is your view on this?

**Comment by thomasmelvin** [comment]
I think these are two versions of cell orientation, the one used in `runtime_constants_mod.x90' is just a field used to store the orientation (and is used for cosmic)

I think there was an older implementation (of something subtly different) that was part of the infrastructure and the psyclone support and metadata `GH_ORIENTATION` refers to this.

We need to the keep the  `get_cell_orientation` function and fields that this points to, but these will not impact psyclone as they are just fields passed from the algorithm layer. We can get rid of the metadata in `argument_mod.F90` and any specific psyclone support for it
