### ISSUE TITLE
Find a better name for NAN test

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#992]
As @arporter correctly commented: "It may be better to call this 'nan_check' rather than 'nan_test' as the latter sounds like it relates to a testing framework."

A different name might be even better, considering that we want to also support additional validation checks, like to guarantee that each value is within a certain range. Maybe ``RangeValidationCheck`` or so???

**Comment by hiker** [comment]
- [ ] Once this is added to the documentation, the tutorial ``LFRic/building_code`` README needs to be updated to contain a link to the new documentation area.

**Comment by hiker** [comment]
The NAN section is already there, just not on readthedocs. I've added the links to the tutorial so that it should work once readthedocs is updated.

**Comment by arporter** [comment]
RTD is currently not working because of a pip bug. That bug has been fixed but RTD need to update the version of pip that they use.

**Comment by hiker** [comment]
RTD seems to be fixed, and the link works. Closing this now.
