### ISSUE TITLE
Invoke names don't work as documented

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#994]
user_guide/algorithm_layer.rst states:

    Note that, in keeping with the Fortran language, labels are not case sensitive and, after having any
    spaces replaced by underscores, must be valid Fortran names 

This is not the case, if I give a name with capital letters:
```
     call invoke( name = "Propagate perturbation",  &
```
and I try to use a lower case name, I get:
```
    RuntimeError: Cannot find an invoke named 'invoke_Propagate_perturbation' in dict_keys(['invoke_initialise_perturbation', 'invoke_propagate_perturbation'])
```
Note capital 'P' in my request, same as the invoke name (plus ``invoke_`` as prefix), but ``get`` only has lower case names.

**Comment by hiker** [comment]
While an immediate bug fix is simple:
```
diff --git a/src/psyclone/psyGen.py b/src/psyclone/psyGen.py
index fb87f9be2..e3927e7fe 100644
--- a/src/psyclone/psyGen.py
+++ b/src/psyclone/psyGen.py
@@ -351,7 +351,7 @@ class Invokes(object):
     def get(self, invoke_name):
         # add a try here for keyerror
         try:
-            return self.invoke_map[invoke_name]
+            return self.invoke_map[invoke_name.lower()]
         except KeyError:
             raise RuntimeError("Cannot find an invoke named '{0}' in {1}".
                                format(invoke_name,
```
we also need to support the other changes that are done to an invoke name (at least convert spaces to _, maybe more??).

**Comment by hiker** [comment]
And imho we should not make the user specify the "invoke_" in front. If a name is given, that exact name should be useable in a transformation. I'd suggest if the (transformed) name is not in the dict, to then search for ``"invoke_"+name``.

**Comment by arporter** [comment]
I suggest that this should be done as part of #95.

**Comment by arporter** [comment]
Closing this as #95 is fixing the immediate bug and whether or not to prepend "invoke" to the name is something nobody feels strongly about one way or the other :-)
