### ISSUE TITLE
PSyData with intel compiler

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#999]
At least the intel compiler 17 on Cray's doesn't like the generic interface used in PSyData. It needs to be investigated if this is a compiler issue, or if the code needs to be changed.

**Comment by hiker** [comment]
Intel and old gfortran complain about the ``stop`` statement as well.

For intel: Apparently the generic interface used in psydata needs to be declared in the base classes as well (and the derived classes then use the same interface, but only add the new functions) ... under investigation.

**Comment by hiker** [comment]
It turns out that I didn't use the generic interface properly (though gfortran accepted it). According to the [Fortran standard](https://j3-fortran.org/doc/year/18/18-007r1.pdf), rule 773:
   
>  A binding-name in a type-bound GENERIC statement shall not specify a specific binding that was inherited or specified previously for the same generic identifier in that derived type definition.

Or as [this stackoverflow](https://stackoverflow.com/questions/25410476/understanding-fortran-extends-types-and-override) questions states:

> You can [...] define a generic already in the base type and extend it in its derived types.

Important is that you can only extend it, not replace an existing binding to a set of argument types. This means that:
- ``psy_data_base.jinja`` needs to declare a generic interface for the variable **declaration** for (say) read-only-test (since neither the read-only base class nor the API-specific read-only class provide declaration). 
-  ``read_only_base.jinja`` needs to declare the generic interface for **providing** variables of standard Fortran types.
- the API-specific read-only implementations extend the generic interface for **providing+declaring** variable for the **API-specific types** (e.g. field types).

To make things more complicated, in e.g. the case of kernel extraction, the generic interface for variable declaration must be provided by the netcdf-base class, the ``psy_data_base`` class must NOT declare them in this case (since only one class in the inheritance tree can declare a generic interface for a certain set of argument types). The netcdf-base class will of course use the methods provided by the ``psy_data_base`` class using the inheritance functionality.

This requires a bit of refactoring - luckily the design that each API-specific library processes its own copy of all jinja files helps a lot, since e.g. for read-only we can process the ``psy_data_base`` class to include generic interface for variable declaration, while for extraction we process the ``psy_data_base`` class not to include this (I am really happy that this design decision pays off now 😄 ).

The additional advantage is that now that the API-specific classes do not need to declare the full generic interface for all Fortran base types (which is now done in one of the base classes), but only extends this generic interface by the API-specific data types - we don't need to use jinja in any API-specific library anymore.

This then seems to compile fine with Intel (2020.2.254 at least, earlier versions will be tested later), and gfortran.

**Comment by arporter** [comment]
Hi @hiker, can this be closed now?
